### ISSUE TITLE
[Android] Unable to Trigger Map onPress over a Polygon  Area

### ISSUE THREAD

**Issue by symmetriccurve** [react-native-community/react-native-maps#1002]
Hello,

I'm trying to get a Coordinates of the point  when a user presses on the Map inside a polygon Area. This works Perfectly on iOS and does not work on Android.

I tried to add Polygon OnPress and tried to extract coordinates from onPress native Event, but this gives first coordinate object of the Polygon array.

**Comment by senthil5053** [comment]
Hi symmetriccurve,
I'm also having the same issue. Did you find any solution for this ?

**Comment by symmetriccurve** [comment]
Not yet ! We got an Android Expert working on this. Hoping to hear from him.

**Comment by senthil5053** [comment]
It worked for me with changing setClickable boolean to false in AirMapPolygon.java file

**Comment by ericapply** [comment]
Anyone have a workaround without setting setClickable boolean to false ?

**Comment by zolrath** [comment]
Has anyone been able to fix this issue? I've got a polygon covering the active area of my map and this is preventing the Maps OnPress from firing.

**Comment by bosung90** [comment]
@zolrath For me, because I never have to detect polygon onPress, I just simply disabled it

**Comment by MarcJohansenITM** [comment]
Any news on this issue?

**Comment by phehaz** [comment]
Any news on this issue? :)

**Comment by aidanw** [comment]
The pull request above seems like it would fix the issue. 

The latest version (0.21.0) Is older than when the pull request was merged, are we expecting a release soonish?

**Comment by rborn** [comment]
@aidanw please use the git version for now

**Comment by vkumarNobul** [comment]
Any solution on this? I have used react-native-maps direct from github, still facing the same issue. Please update the status on this issue.

**Comment by antonioreyna** [comment]
i have the same issue
