### ISSUE TITLE
[Android] TouchableNativeFeedback with borderless ripple renders under map.

### ISSUE THREAD

**Issue by BKova** [react-native-community/react-native-maps#1007]
Hello, I want to implement button like one on the second image and I want it to display borderless ripple
onPress, but when I set background ripple as borderless in TouchableNativeFeedback, I get result seen in the first picture, with half of the ripple covered by map. How can I add borderless ripple round button on top of map?
Code: 
```
<View style ={JobsDetailsStyle.Container}>
            <MapView
                style={JobsDetailsStyle.GoogleMaps}
                region={{
                latitude: 43.514508,
                longitude: 16.450262,
                latitudeDelta: 0.01,
                longitudeDelta: (width / height)*0.01,
                }}>
                    <MapView.Marker title="OK" coordinate={{latitude: 43.514508,  longitude: 16.450262}}>
                        <View style={JobsDetailsStyle.MarkerOuterCircle}>
                            <View style={JobsDetailsStyle.MarkerInnerCircle}>
                            </View>
                        </View>
                    </MapView.Marker>
            </MapView>
            <TouchableNativeFeedback
                            background={TouchableNativeFeedback.Ripple('grey',true)}
                            onPress={() => {
                            }}>
                <View style={JobsDetailsStyle.MapsAppButtonCircle}>
                    <Icon name="directions" size={width*0.08} color="white" />
                </View>
            </TouchableNativeFeedback>
        </View>
```
Where 'JobsDetailsStyle' is this:
```
import { StyleSheet, Dimensions } from 'react-native';

const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
    GoogleMaps:{
        ...StyleSheet.absoluteFillObject,
    },
    Container:{
        ...StyleSheet.absoluteFillObject,
        height: height*0.324,
        width: width,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    MarkerOuterCircle:{
        height: width*0.06, 
        width: width*0.06, 
        backgroundColor:'#57B9F6',
        borderRadius: width*0.03,
        justifyContent: 'center',
        alignItems: 'center'
    },
    MarkerInnerCircle:{
        height: width*0.015, 
        width: width*0.015, 
        backgroundColor:'#0195F3',
        borderRadius: width*0.0075
    },
    MapsAppButtonCircle: {
        height: width*0.14,
        width: width*0.14,
        backgroundColor: '#0195F3',
        alignSelf: 'flex-end',
        marginRight: width*0.08,
        marginBottom: -width*0.07,
        borderRadius: width*0.07,
        justifyContent: 'center',
        alignItems: 'center'
    }
    });
```
It renders the button like this
![capture](https://cloud.githubusercontent.com/assets/11560414/22517907/02291f52-e8ab-11e6-9828-6cbc27c18323.PNG)

And when I change from borderless 'true' to 'false' it renders normally, but it is not borderless:
![capture](https://cloud.githubusercontent.com/assets/11560414/22518003/50891eae-e8ab-11e6-8f1d-edc147c53099.PNG)

**Comment by BKova** [comment]
Until I find solution to this I will use customized ToogleButton from react-native-material-ui : https://medium.com/react-native-motion/ripple-effect-in-react-native-1cb0ad568e91#.68u6ze8r0

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
