### ISSUE TITLE
Rotation attribute (Marker) not work on iOS (Google Maps)

### ISSUE THREAD

**Issue by alexsbobylev** [react-native-community/react-native-maps#1016]
Hi, thanks for you work!

Rotation attribute (MapView.Marker) not work on iOS (Google Maps), but on Android is work fine.
Help please!

React Native 0.37
React-native-maps 0.12.4

**Comment by unboundfire** [comment]
@alexbelyeu  I have rotation working on all platforms by using a View inside of the marker here is some example code

```
const style = {
    width: 50,
    height: 52,
    transform: [
      { rotate: `${this.props.heading}deg` }
    ]
}

<MapView.Marker
      key='aircraft-marker'
      anchor={{ x: 0.5, y: 0.5 }}
      zIndex={this.props.zIndex}
      coordinate={this.props.coordinate}>
        <Animated.Image ref='image' style={style} source={aircraftImg} />
</MapView.Marker>
```

**Comment by fmelp** [comment]
@unboundfire Just a quick question, how do you figure out the heading? Could you post some example code. Thank you!!

**Comment by Norchene** [comment]
I have the same problem.
@unboundfire : you are using the "rotate" prop style, not the "rotation" marker prop (of which @alexsbobylev is speaking)

**Comment by sarmad1995** [comment]
but when we will rotate the map it would not rotate the marker with it....any solution? as flat prop doesn't work on ios
