### ISSUE TITLE
Animation of region change not working

### ISSUE THREAD

**Issue by SjoerdvGestel** [react-native-community/react-native-maps#1027]
When using the map component MapView.Animated and setting the region with an MapView.AnimatedRegion wil not result in a panning camera action as expected when changing the region. 

is there more needed for animation to occur when changing the region of them map? 
(tested on android and ios)

**Comment by zheng-liu-seattle** [comment]
+1

**Comment by wbattel4607** [comment]
+1

**Comment by engineforce** [comment]
Assuming region is AnimatedRegion, you can use timing().

```js
region.
  .timing({
    latitude: currentPosition.latitude,
    longitude: currentPosition.longitude,
    duration: 1000,
  })
  .start();
```

**Comment by rborn** [comment]
The lastest versions have camera* methods  implemented. Closing.
