### ISSUE TITLE
iOS: Have to select a marker before I can press again drag it

### ISSUE THREAD

**Issue by kcfgl** [react-native-community/react-native-maps#1050]
I've got an app for both iOS and Android using a pretty standard draggable marker with a custom image.

On Android, I can press and start dragging the pins immediately.  On iOS I need to select the pin I want to drag before I can press and drag it.  

Is this a known issue and I just missed it?  Is there a workaround?

Thanks.

**Comment by kcfgl** [comment]
Any thoughts on this one?  Am I just doing something wrong? Thx!

**Comment by freshnewegg** [comment]
It's a matter of the marker not being selected by default on IOS. I made an adjustment here. 

https://github.com/freshnewegg/react-native-maps/commit/a0965efe97844317e81aee027bfe519914437be2

**Comment by kcfgl** [comment]
@freshnewegg Had to take a break from my project for a bit for another one. Just getting back to this and will try your adjustment tonight.  Thanks!
