### ISSUE TITLE
Pass reference of the map to another component from a MapView.Marker

### ISSUE THREAD

**Issue by amaurymartiny** [react-native-community/react-native-maps#1071]
Hey, I have a problem I'm trying to solve with react-native-maps.

Let's say I have two pages, a first page with the Map and some markers, and when I press on the callout of any marker, it will show the second page with some detailed info about the marker. And in this second page, I wish to take a snapshot of the map at its current state.

So here's how I tried to do that:
- In the `render()` function on the first page, in the relevant part, I have:

        <MapView
          ref="map"
          //... other props
        >
          {this.props.markers.map(marker => (
            <MapView.Marker
              key={marker.id}
              //... other props
              onCalloutPress={() => this.props.navigation.navigate('SecondPage', { markerId: marker.id, mapView: this.refs.map })}
            />
          ))}
        </MapView>

- In the second page, I would just call `this.props.navigation.state.params.mapView.takeSnapshot()` and the trick is done (using `react-navigation` for navigation).

The problem is, I have the following error: `TypeError: Converting circular structure to JSON`, which is understandable since I'm calling the map reference from inside the MapView.Marker.

Any idea how I can pass this reference to the second page? Thanks.

**Comment by grundmanise** [comment]
1) You can take a snapshot of the map __before__ the `push` and pass that snapshot data to the `pushed` screen (as you do with `markerId`). 

or

2) You can use Google's [static maps](https://developers.google.com/maps/documentation/static-maps/).

I don't know which option is more performant.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
