### ISSUE TITLE
TestID's for e2e automation

### ISSUE THREAD

**Issue by nischayv** [react-native-community/react-native-maps#1104]
I am trying to add testID's to the map components, similar to Views in react native. The goal is to make react-native-maps testable using automation tools like Appium. This would allow end to end testing in react-native-maps. I started off with the Google Maps MapMarker. But I am running into challenges and Appium is still not able to find the marker. Here is my change - https://github.com/nischayv/react-native-maps/commit/c37548d18b25fbe1521e8263ff63577931b00215

Any help would be appreciated! 

cc: @unboundfire  @lelandrichardson

**Comment by kidmillions** [comment]
+1 to this. Blocking automation efforts for us...we'd love to be able to automate map interactions with Appium and XCUITest.

**Comment by lelandrichardson** [comment]
@nischayv this looks great. I would love it if you opened this up as a PR and we can discuss it there?

**Comment by tiagofs** [comment]
Hi,
Have you managed to find a map marker with Appium?
