### ISSUE TITLE
toolbarEnabled={false} not working on litemode

### ISSUE THREAD

**Issue by alexprice1** [react-native-community/react-native-maps#1111]
I can't get `toolbarEnabled={false}` to work on litemode. Any advice?

Code:
```
        <MapView
          customMapStyle={customMapStyle}
          liteMode={true}
          region={region}
          scrollEnabled={false}
          showsPointsOfInterest={false}
          style={{flex: 1}}
          toolbarEnabled={false}
        >
          <Marker
            coordinate={{
              latitude,
              longitude,
            }}
            key={0}
          />
        </MapView>
```

![screen shot 2017-03-11 at 11 02 55 am](https://cloud.githubusercontent.com/assets/4140149/23825172/50b67824-064a-11e7-80dd-9a4e5573b29f.png)

**Comment by mtimofiiv** [comment]
I have a similar issue, but for me, it works on the initial render of the component. Then if the mapview is resized, it shows it again.
