### ISSUE TITLE
Double tap zooms even if zoomEnabled is false

### ISSUE THREAD

**Issue by ahstro** [react-native-community/react-native-maps#1133]
Not sure if this is intended or a bug, but when `zoomEnabled` is set to `false`, it's still possible to zoom in by double tapping the map. I couldn't finh any option to turn this off, and since there's no way (that I could find) to zoom out after this, I'm fairly certain it's not intended.

**Comment by lelandrichardson** [comment]
@ahstro is this ios or android or both?

**Comment by ahstro** [comment]
I've only tried it on Android, unable to test it on iOS.

**Comment by danielreuterwall** [comment]
Same goes for when scollEnable is set to false. Double tap takes the map to the tapped position on the map. My idea was to have scollEnable set to false to ensure the center location is always the same. Can probably work around it by controlling the region but I think we would like to controll the double tap anyhow. Tried on ios.
