### ISSUE TITLE
Markers are not included in Snapshots when <Image> child is used

### ISSUE THREAD

**Issue by amaurymartiny** [react-native-community/react-native-maps#1163]
Hello,

Taking snapshot works good when I use `<MapView.Marker>` without custom image (so a pin) or with the `image={...}` prop, but not when I use a custom `<Image />` as its child. I only see the map without any markers at all.

Is this a feature or a bug?

**Comment by lelandrichardson** [comment]
@amaurymartiny is this on ios or android?

**Comment by amaurymartiny** [comment]
I only tried on ios.

**Comment by caseyt** [comment]
This is still a problem. I have tried both Marker and Circle and neither one shows up on the snapshot image.

**Comment by navneet7723** [comment]
can any one tell me how to show screenshot
