### ISSUE TITLE
MapView makes background transparent before load on Android

### ISSUE THREAD

**Issue by maxhawkins** [react-native-community/react-native-maps#1202]
I'm using the React Native Navigator and react-native-maps v0.13.1.

I have a page with a full-screen map that I'm `navigator.push()`-ing to from the main page. There is an issue with this map on Android.

Before the map tiles have loaded the background of the map area is transparent even though the background of the page it's in is opaque. This shows the previous page I'm transitioning from, which is confusing.

How do I make the MapView's background opaque before the map has loaded?

<img src="https://cloud.githubusercontent.com/assets/28565/24764469/4b4459ba-1aa9-11e7-8732-7fa2dccd6b6d.gif" width=300>

**Comment by darleikroth** [comment]
For me, this goes beyond.
I'm using the [React Navitagion](https://reactnavigation.org/). When go back to previous screen (from screen with MapView component), it causes a bug in app screen, leting half screen or more, locked.
This is a bug on the screen of device. When hide the app and open it again, it comes back to normal.
This happens just in real Android devices.

MapScreen `render()`:
```js
render()
{
  return (
    <MapView
      ref={map => this._map = map}
      style={styles.map}
      region={this.state.region}
      onRegionChange={region => this.setState({ region })}
      loadingEnabled
    >
      {this.state.markers.map(marker => (
        <MapView.Marker
          key={marker.id}
          coordinate={{
            latitude: marker.latitude,
            longitude: marker.longitude
          }}
          title={marker.title}
          description={marker.description}
        />
      ))}
    </MapView>
  )
}
````

react@16.0.0-alpha.6
react-native@0.43.3
react-native-maps@0.13.1
react-navigation@1.0.0-beta.7

**Comment by AlpZero** [comment]
having same issue here

**Comment by jonesdar** [comment]
Seems to be caused by the changes in https://github.com/airbnb/react-native-maps/pull/1150
If I change the AirMapView constructor to use the current activity again
`super(reactContext.getCurrentActivity(), googleMapOptions);`
it fixes this transparency problem.

**Comment by boudellaredouane** [comment]
I'm having the same issue, had to go back all the way to 0.10 to get rid of that issue.

Is there any plans for this ticket ?

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
