### ISSUE TITLE
Custom callout arrow position

### ISSUE THREAD

**Issue by axelander** [react-native-community/react-native-maps#1207]
I am implementing a custom callout but I am struggling on how to position a custom downward pointing arrow. When a marker is rendered at the center of the screen I can easily position the arrow at the middle of my callout. When a callout is rendered close to the screens edge there is an auto-adjusting behaviour of the callout (which is very nice) but then the arrow can't be positioned at the center.

Also, is it possible to change the default padding of the callout? The padding pushes the callout too far from the edge.

**Marker center of screen:**
<img width="637" alt="screen shot 2017-04-07 at 09 38 11" src="https://cloud.githubusercontent.com/assets/3784741/24790080/fca49f7c-1b75-11e7-9b87-d6ffadd119df.png">

**Marker close to edge of screen:**
<img width="652" alt="screen shot 2017-04-07 at 09 38 24" src="https://cloud.githubusercontent.com/assets/3784741/24790081/fca587a2-1b75-11e7-840e-95812f738fae.png">

**Padding issue**
<img width="338" alt="screen shot 2017-04-07 at 09 41 45" src="https://cloud.githubusercontent.com/assets/3784741/24790175/6f90029c-1b76-11e7-835e-9cfb7bca9ae3.png">

**Comment by cyakimov** [comment]
I'm facing this problem as well. Did you find a good solution?

**Comment by cyakimov** [comment]
Worth mentioning that `onSelect` & `onPress` events does not provide `position:Point` as stated in [docs](https://github.com/airbnb/react-native-maps/blob/master/docs/marker.md#events) making it almost impossible to dynamically reposition the arrow.

**Comment by axelander** [comment]
@cyakimov No I have not found a solution for this :(

**Comment by cyakimov** [comment]
Neither I. I forked the project and made the required style changes I needed right in the Objective-C classes.

**Comment by ssuchanowski** [comment]
Anything new here?

**Comment by cyakimov** [comment]
@ssuchanowski Sadly, no. In my case I just needed to change the bubble background color.

**Comment by ssuchanowski** [comment]
What I found at the time I was playing with this is lib is using default callout (which has this auto-positioning feature) and create inside custom one. Creating a proper nice custom callout is something that I might be looking in the future but not at the moment.

**Comment by cyakimov** [comment]
That's what I did at first but then things went to hell as soon I changed the background of the inner view. The bubble background is defaulted to `white`. Naturally anything you put in it will have this white frame around :(

**Comment by cohendl** [comment]
+1 on this issue. Frustrating to be unable to access the offset to know where to put the arrow on a custom callout.

**Comment by alvelig** [comment]
@cyakimov, compadre, could you provide some code to reproduce and lets find out how to solve this problem.

**Comment by danikane** [comment]
Guys, I had the same issue, upgraded to latest release and looks like it's solved. :)

**Comment by mafiusu** [comment]
@cyakimov could you provide some more details of how you solved that problem? Which exactly objective c classes did you changed?
