### ISSUE TITLE
Markers not rendering on Map (Only when using default iOS maps?)

### ISSUE THREAD

**Issue by cruz02148** [react-native-community/react-native-maps#1365]
Hello,

I've struggling with debugging why my map markers are not rendering on the map. I centered my initial region in Boston, MA and I should have 2 markers appear on the map. They are not there. I actually ended up scrolling out and I saw 1 marker somewhere over Spain. After trying out a few things, I figured out that I can use Google Maps instead of Apple Maps so I added the `provider="google"` prop to the MapView and everything worked just as expected.

Expo: SDK 17.0.0
RN: 0.44
React: 16.0.0-alpha.6

Here is the relevant code I was using:
```
<View style={styles.mapContainer}>
  <MapView
    provider="google"
    onRegionChangeComplete={this.onRegionChangeComplete}
    region={this.state.region}
    style={{ flex: 1 }}
   >
     {this.renderMapMarkers()}
   </MapView>
 </View>

  renderMapMarkers = () => {
    const { jobsList } = this.props;

    return jobsList.map(job => (
      <MapView.Marker
        key={job.id}
        coordinate={{
          latitude: job.lat,
          longitude: job.lng,
        }}
      />
    ));
  }
```

Also note that did try just directly rendering a Market inside the MapView itself with hard-coded coordinates like so:

```
<MapView ...>
  <MapView.Marker coordinate={{ latitude: 42, longitude: -71 }}/>
</MapView>
```
but i ran into the same issue as above...

**Comment by ararog** [comment]
I'm having very similar issue, markers not rendering after region change.

**Comment by Velissel** [comment]
I had the same issue, for me, the reason is coordinate of a marker is updated but job.id is not so that that marker is not re-rendered to new position

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
