### ISSUE TITLE
Cannot add property 0, object is not extensible

### ISSUE THREAD

**Issue by rexlow** [react-native-community/react-native-maps#1371]
In my project, I'm trying to draw multiple polyline path by pushing an empty array every time user press the button.

Basically, I'm working with 2D array and trying to push latest GPS data into the last child of the array

```
constructor(props) {
    super(props);
    this.moundted = false;
    this.state = {
      latestRegion: new MapView.AnimatedRegion({
        latitude: 0,
        longitude: 0,
        latitudeDelta: LAT_DELTA,
        longitudeDelta: LONG_DELTA
      }),
      routeCoordinates: [],
      routeCount: -1,
      markerArray: [],
      prevLatLang: {},
      distanceTravelled: 0,
      running: false
    }
  }
```

```
onButtonPressed = () => {
    const { running, routeCount } = this.state
    const latestLatLong = pick(this.state.latestRegion, ['latitude', 'longitude'])

    let marker = {
      title: (running ? 'End Point' : 'Starting Point'),
      description: (running ? 'You finished here' : "You Started here"),
      coordinate: latestLatLong
    }

    this.setState({
      running: !this.state.running,
      markerArray: [...this.state.markerArray, marker]
    })

    if (!running) {
      this.setState({
        routeCoordinates: this.state.routeCoordinates.concat([[]]), //add array
        routeCount: this.state.routeCount + 1
      })

      this.followWatchCoords()
    } else {
      this.stopFollowing()
    }
  }
```

Then I would call the watchPosition polyfills and calculateDistance to find out the distance between each marker
```
calculateDistance = (coords) => {
    const { latitude, longitude } = coords
    const { routeCoordinates, routeCount, distanceTravelled } = this.state

    const prevLatLang = {
      latitude: parseFloat(latitude),
      longitude: parseFloat(longitude)
    }
    const positionLatLong = pick(coords, ['latitude', 'longitude'])

    let newArr = [...routeCoordinates]
    newArr[routeCount].push(positionLatLong)    // error occurs here

    this.setState({
      routeCoordinates: newArr,
      distanceTravelled: distanceTravelled + this.calcHaversineDistance(prevLatLang),
      prevLatLang
    })
  }
```

This is how I render my polylines
```
{this.state.routeCoordinates.map((coordinates, index) => (
            <MapView.Polyline
              key={index}
              coordinates={coordinates}
              strokeColor="#19B5FE"
              strokeWidth={5} />
          ))}
```

I checked my state before rendering and its all matched with how its suppose to be

**Comment by james2406** [comment]
I'm not sure if I'm reading this right, but you shouldn't need to map over the `<MapView.Polyline/>` Component

Simply:

```
<MapView.Polyline
    key={index}
    coordinates={this.state.routeCoordinates}
    strokeColor="#19B5FE"
     strokeWidth={5}
/>
```

Unless you want multiple, separate Polylines on the screen?

**Comment by rexlow** [comment]
Yes you are right, I'm trying to draw multiple lines

**Comment by james2406** [comment]
Okay, but I'm assuming this is a running application? So you're not showing different paths, just different segments of one path, right?

What is the reason for doing that? Is it for an undo feature? (My app has similar functionality, but I've gone about it a different way)

**Comment by rexlow** [comment]
Ah I see. For my app I'm trying to show a different path. For instance, user press start button and the app would start collecting GPS data until the button is pressed again (to stop). All data will be pushed into one array to show the polyline lo. Please note that the array is a child of a parent. When the button is pressed again (to start), then a child array would be created and all incoming data will be stored in that child.

**Comment by james2406** [comment]
Okay. The structure you're using makes sense then. Could you console.log a snippet of `this.state.routeCoordinates`?

**Comment by rexlow** [comment]
With the approach that I'm using, I can always get 
[
    [ 
        { lat: ?num, long: ?num } ,
        { lat: ?num, long: ?num } ,
    ],
   [ 
        { lat: ?num, long: ?num } ,
        { lat: ?num, long: ?num } ,
    ]
]

But I believe is the problem is with the mutation of the array. I've tried concat and other methods and no luck :(

**Comment by james2406** [comment]
Okay, well the object you need to give Polyline is:

```
{
    latitude: Number,
    longitude: Number,
}
```

**Comment by rexlow** [comment]
Sure. I have confirmed that the object I'm passing in is correct.
Now I try to do it this way and the error is gone but it is mutating my array the second time start button is pressed.
```
this.setState({
      routeCoordinates: [routeCoordinates[routeCount].concat(positionLatLong)],
      // routeCoordinates: [...this.state.routeCoordinates, routeCoordinates[routeCount].concat(positionLatLong)], //this wont wory
      distanceTravelled: distanceTravelled + this.calcHaversineDistance(prevLatLang),
      prevLatLang
    })
```

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
