### ISSUE TITLE
onRegionChangeComplete will not always fire on android

### ISSUE THREAD

**Issue by avdept** [react-native-community/react-native-maps#1379]
```
<MapView loadingEnabled
                     showsMyLocationButton={false}
                     toolbarEnabled={false}
                     provider="google"
                     showsUserLocation
                     ref={ref => { this.map = ref; }}
                     style={[styles.map]}
                     initialRegion={this.state.coords.usingCoordinates}
                     onRegionChangeComplete={region => this.onRegionChangeComplete(region)}
                     onRegionChange={region => this.onRegionChange(region)}
                >


onRegionChangeComplete(region) {
        console.log("REGION HAS CHANGED:");
        if (Platform.OS == 'android' && region.latitude == 0 && region.longitude == 0) {
            return true; // This is fix for strange bug, when android throws 0 lat and 0 lng coordinates when initializing map
        }
    }
```

I didn't find any reason of why sometimes callback fires and sometimes not.

**Comment by chapeljuice** [comment]
Just curious do you get any errors when you run `react-native log-android` or `adb logcat`?

**Comment by Radu-Filip** [comment]
I'm seeing this issue when zooming. 
onRegionChange fires properly while onRegionChangeComplete doesn't ever fire when finishing zoom. 
Dragging the map seems to work as expected.

No errors or warnings in the adb logcat

**Comment by Radu-Filip** [comment]
I was looking that for Android GoogleMap.OnCameraChangeListener is deprecated. 
Maybe is worth looking into adapting the implementation using GoogleMap.OnCameraMoveListener  and GoogleMap.OnCameraIdleListener?

**Comment by sandropoluan** [comment]
+1

**Comment by chadzheng** [comment]
+1

**Comment by vinceyuan** [comment]
Same problem here.

**Comment by cbartondock** [comment]
Same problem. Any fix for this without editing the native code? Seems like it should be fixed within react-native-maps

**Comment by cbartondock** [comment]
Speaking of, I get the same issue on ios. onRegionChangeCompleted does not fire when zoom out finishes

**Comment by chadzheng** [comment]
My solution to zoom did not fire onRegionChangeComplete is to use onRegionChange instead, and calculate zoom level by yourself by using this **** Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2) ****   and fire the onChange function when zoom level changed. and onRegionChangeComplete is fired only when the previous region is not the same as current region. **** JSON.stringify(this.state.previousRegion) !== JSON.stringify(region) **** and also fired the onChange function to make some action towards the map. Hope this would help.

**Comment by cbartondock** [comment]
@chadzeng to be clear though this code will fire mid zoom out also? It doesn't fire only once the zoom out/in is finished.

**Comment by sandropoluan** [comment]
Here is my solution. I use onRegionChange instead. This will fired only when user user is done moving the map, or after zooming in/out is finished.

`onRegionChange={(region)=>{
	
	 clearTimeout(this.timerForMap);
	 this.timerForMap=setTimeout(()=>{

	 console.log(region) 

	 },500);		          	 

}}`

**Comment by chadzheng** [comment]
@cbartondock Hi, this method get fired when zoom level changed, which zoom level is calculated by the equation "Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2)" that I mentioned above.

**Comment by chadzheng** [comment]
@cbartondock The react native map onRegionChangeCompleted method seems can't response to zoom action and only get fired when the map center change completed according to my understanding, and the onRegionChange, on the other hand, get fired at any changes on the map (both zoom and region). So I use onRegionChange instead.

**Comment by cbartondock** [comment]
Fair enough! I ended up combining onRegionChange with underscores "debounce" method to produce the desired result.

**Comment by pedrolopes10** [comment]
+1

**Comment by paulsc** [comment]
+1

**Comment by whs465** [comment]
+1

**Comment by juergengunz** [comment]
+1

**Comment by AlexandreRoba** [comment]
+1

**Comment by IjzerenHein** [comment]
Guys, please try PR #1710, it fixes the hacky region-change code for Android

**Comment by carsonwah** [comment]
Facing the same problem.  
Sometimes it just works fine. Cannot guess any pattern from it.

**Comment by tsangwailam** [comment]
I found that when you zoom to max. The region from onRegionChangeComplete will be continue changing. The change is so small and about 15/16 significant decimal digits. Is it related to the permission?

**Comment by rborn** [comment]
Old issue.Closing.
