### ISSUE TITLE
Change User Location Dot Color?

### ISSUE THREAD

**Issue by Nsingh13** [react-native-community/react-native-maps#1429]
Is there any support for changing the default blue color for the dot to a different color?

**Comment by christopherdro** [comment]
It appears you can set the tintColor on mapView for this but that API is not exposed through this library.

Should be a pretty simple addition. Care to give it a shot?

**Comment by pavelpark** [comment]
How did it work out for you?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by IjzerenHein** [comment]
One solution is to set the tint-color on the MapKit MapView appearance proxy.

```
// AppDelegate.m
@import MapKit;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  // Set the tint-color for the MapKit map-view
  [[MKMapView appearance] setTintColor:[UIColor colorWithRed:0.08 green:0.55 blue:0.77 alpha:1.0]];
  // color = #158CC5 - https://www.uicolor.xyz/#/hex-to-ui
 ...
}
```

**Comment by maitrungduc1410** [comment]
> One solution is to set the tint-color on the MapKit MapView appearance proxy.
> 
> ```
> // AppDelegate.m
> @import MapKit;
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   ...
>   // Set the tint-color for the MapKit map-view
>   [[MKMapView appearance] setTintColor:[UIColor colorWithRed:0.08 green:0.55 blue:0.77 alpha:1.0]];
>   // color = #158CC5 - https://www.uicolor.xyz/#/hex-to-ui
>  ...
> }
> ```
Works perfectly on iOS, thank you

**Comment by ziyaddin** [comment]
> One solution is to set the tint-color on the MapKit MapView appearance proxy.

@IjzerenHein thank you. Is there any known way of doing this on Android?
