### ISSUE TITLE
Tilt react-native-maps google map

### ISSUE THREAD

**Issue by francescafasullo** [react-native-community/react-native-maps#1446]
Hi! I (finally) got a google map to display on my iPhone using react-native-maps. I currently have a showsBuidings prop in my MapView component and I would like to be able to set the map tilt so that when a user opens it, they can see the 3d rendering of the buildings around them. This is the code I have so far, but the custom style that is supposed to tilt the map is definitely not working. Has anyone gotten this to work? here is some of my code for reference:

`const mapStyle = {
    transform: [
        { rotateY: '180deg'},
    ]
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          provider={PROVIDER_GOOGLE}
          customMapStyle={mapStyle}
          style={styles.map}
          initialRegion={{
            latitude: this.state.latitude || 40.7050758,
            longitude: this.state.longitude || -74.00916039999998,
            latitudeDelta: 0.005,
            longitudeDelta: 0.005
          }}
          showsBuildings
        >
        { Object.keys(this.state.keys).length > 0 ? Object.keys(this.state.keys).map((key) => {
          return (
            <Marker
              location={this.state.keys[key].location}
            />
          )
        }) : null
        }
        </MapView>
      </View>
    )
  }`

**Comment by francescafasullo** [comment]
<img width="801" alt="screen shot 2017-07-01 at 3 22 42 pm" src="https://user-images.githubusercontent.com/26489321/27764833-64f6f456-5e71-11e7-9fbc-551c4ba979a5.png">
<img width="255" alt="screen shot 2017-07-01 at 3 22 51 pm" src="https://user-images.githubusercontent.com/26489321/27764834-64fa9462-5e71-11e7-8ed6-d6293465aa5d.png">

**Comment by Farzad7** [comment]
Hi
Did you have any luck on this?
Thx

**Comment by aaronbuchanan** [comment]
I've also been looking for a way to force tilt, I can only get tilt after using guestures

**Comment by francescafasullo** [comment]
Hi Farzad & Aaron,

I was able to solve this by editing the AIRGoogleMap.m file in XCode. I've
attached a screenshot of the last few lines of that file. The line with
viewingAngle:65 is what tilted the map.

**Comment by francescafasullo** [comment]
<img width="840" alt="screen shot 2017-07-12 at 10 58 31 am" src="https://user-images.githubusercontent.com/26489321/28124390-86907c94-66f1-11e7-9c3e-fc5022589872.png">

**Comment by jonathanmauer** [comment]
Hi francescafasullo,

Is there a way to do this works in android?

**Comment by aaronbuchanan** [comment]
Thanks! @francescafasullo curious if you managed to do the same for android?

**Comment by sandinosaso** [comment]
Hi, I ended here looking for some folks talking about changing the camera on the Map.
I worked on this PR that aims to give support to animateToViewAngle and animateToBearing https://github.com/airbnb/react-native-maps/pull/1544

**Comment by resson-ntranquilla** [comment]
@Farzad7 , @aaronbuchanan , and @francescafasullo , you should be able to accomplish the tilt with `animateToViewingAngle` once you have a handle on  the map ref. See [latest master: MapView.js](https://github.com/airbnb/react-native-maps/blob/master/lib/components/MapView.js)
