### ISSUE TITLE
[iOS] Markers not showing on re-renders

### ISSUE THREAD

**Issue by sorodrigo** [react-native-community/react-native-maps#1465]
Hello, I have an issue with the markers rendering. What happens is the following:
    1. Initial render of the map: markers.length = 1; (The map renders one marker)
    2. onRegionChangeComplete => markers.length = 2; (The marker renders only one marker in the new position)
    3. Any change in the map that makes the markers state change, results in rendering one of the total markers in a new position.

This is basically how we are setting the markers on the map:
```jsx
<View style={styles.container}>
  <MapView
    ref={(ref) => { this.map = ref; }}
    style={styles.map}
    provider={MapView.PROVIDER_GOOGLE}
    mapType="none"
    minZoomLevel={2}
    maxZoomLevel={18}
    rotateEnabled={false}
    initialRegion={this.state.region}
    onRegionChangeComplete={this.updateRegion}
    onLayout={this.onLayout}
    moveOnMarkerPress={false}
    onPress={e => this.mapPress(e.nativeEvent.coordinate)}
  >
    {this.props.markers.map((marker, index) => {
      const coordinates = {
        latitude: marker.geometry.coordinates[1],
        longitude: marker.geometry.coordinates[0]
      };
      return (
        <MapView.Marker
          key={`Alert-marker-${index}`}
          coordinate={coordinates}
          anchor={{ x: 0.5, y: 0.5 }}
          onPress={() => this.props.selectAlert(coordinates)}
          zIndex={1}
          draggable={false}
        >
          <View
            style={[
              styles.markerIcon,
              this.props.type === 'primary' ? styles.primary : styles.secondary
            ]}
          />
        </MapView.Marker>
      );
    })}
  </MapView>
</View>
```
I've debug the rendering, so I can confirm that markers is receiving more elements than the ones that the map is displaying.

Any help would be much appreciated, this issue is currently blocking me and my colleagues. Even if it isn't a complete solution, pointing in the right direction would be awesome. Thanks 😄 !

**Comment by christopherdro** [comment]
You can try using `forceUpdate()` as a temp working to see if that changes things.

**Comment by sorodrigo** [comment]
@christopherdro do you mean using `forceUpdate()` on my component or on the map instance?

**Comment by christopherdro** [comment]
The component that has the map view has a child.

**Comment by sorodrigo** [comment]
Thanks for the help! The solution you suggested didn't work. I'm sharing our workaround for anyone else that might run into this issue again. In the `MapView` component to forceUpdate it when the markers changed we added a prop `key={markers.length}` this way any time the markers changed the map re-rendered. This is not a complete solution because if the marker changed and the length if the same the map will not re-render. A solution for this is prefixing/suffixing the markers.length with some id or something else that will only change when you want the map to re-render.

**Heads up:** Don't prefix/suffix with a value that always changes (i.e. `Date.now()`) because this will cause an infinite render loop.

**Comment by alvelig** [comment]
Actually I had that problem and tried to PR #1845. That was not a complete solution for marker and callout problems, that's why I closed it for now. @sorodrigo But if you could try using that commit to test if it works?

**Comment by Germanaz0** [comment]
@sorodrigo thanks for the quick fix, it happened to me, on IOS I was having the same issues but not on android.

**Comment by sorodrigo** [comment]
I came up with this issue on some other non-related libs. What I learned is that this is usually caused by creating inner config/state from props and not adding a `componentWillReceiveProps` to handle the re-update. I don't have time to dig into the issue but if someone else has the time maybe the issue will revolve around this.

Also @alvelig thanks for your solution candidate I'm sorry, I can't test it right now.

**Comment by alvelig** [comment]
@sorodrigo you can test it from master now. It is merged (in #https://github.com/react-community/react-native-maps/commit/921fffb8c4ea0cb1760b7389af254715aaeb3076).

**Comment by leminhtuan2015** [comment]
I have the same problem, I already test (in #921fffb). but it still NOT work.

**Comment by sebackend** [comment]
Hi, i'm facing this problem too...the Markers are only displayed on Android but not in iOS (the coordinates comes from redux).

I'm using the 0.22  version, any suggestion?

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.

**Comment by sebackend** [comment]
Still can't figure it out how to fix it or what is causing it.
Please if you have any idea, i will appreciate your help.

In android this is working fine, loading the markers from remote API call, and re-rendered with 'onRegionChangeComplete'

**Comment by Narcis11** [comment]
> Thanks for the help! The solution you suggested didn't work. I'm sharing our workaround for anyone else that might run into this issue again. In the `MapView` component to forceUpdate it when the markers changed we added a prop `key={markers.length}` this way any time the markers changed the map re-rendered. This is not a complete solution because if the marker changed and the length if the same the map will not re-render. A solution for this is prefixing/suffixing the markers.length with some id or something else that will only change when you want the map to re-render.
> 
> **Heads up:** Don't prefix/suffix with a value that always changes (i.e. `Date.now()`) because this will cause an infinite render loop.

This worked for me (using react-native-maps 0.25.0 and RN 0.60.4) Thanks a lot for the solution!

**Comment by sebackend** [comment]
I found the problem, i was rendering all markers inside the MapView with a <View></View> component, i don't know why this was working perfectly on Android, so i tried to remove this View and finally the markers were showed on the iOS device :D

Please close.

**Comment by AngelTrinidad** [comment]
If for anyone help this, I was solve it my issue by removing the React.useMemo (or PureComponent) on my custom Marker

**Comment by richardwu** [comment]
FWIW, my markers weren't rendering on the initial rendering of the map (only on iOS), even though the data + rendering of the Markers was working.

I fixed this by keeping around an `initialLoad: boolean` state that I would update `onMapReady` with a short delay (e.g., 1000ms), and including the `initialLoad` boolean in the key of the marker.

**Comment by 92206** [comment]
> Thanks for the help! The solution you suggested didn't work. I'm sharing our workaround for anyone else that might run into this issue again. In the `MapView` component to forceUpdate it when the markers changed we added a prop `key={markers.length}` this way any time the markers changed the map re-rendered. This is not a complete solution because if the marker changed and the length if the same the map will not re-render. A solution for this is prefixing/suffixing the markers.length with some id or something else that will only change when you want the map to re-render.
> 
> **Heads up:** Don't prefix/suffix with a value that always changes (i.e. `Date.now()`) because this will cause an infinite render loop.

i have the same problem where initially the markers are loaded but not on state changes they dont update  (only IOS ) .  
A similar workaround was to give markers unique keys that would change in sync with state update

**Comment by cjones26** [comment]
Definitely still an issue, I really hate the key workaround but I guess it works...

**Comment by shaktitechno** [comment]
in ios remove trackViewChange={false}

**Comment by cjones26** [comment]
> Years go by and every now and then I get notified from an issue I created as a junior 🥲. Nostalgia.

Yeah we gave up on this library and implemented our own.

**Comment by irg1008** [comment]
Still happening, mind blowing
