### ISSUE TITLE
Ask geo permission only when the map is mounted/rendered

### ISSUE THREAD

**Issue by mtt87** [react-native-community/react-native-maps#1489]
RN 0.46.4, react-native-maps 0.15.3

As soon as I open the app it's asking for geo permission, is there a way to show it only when the component with the map is being mounted/rendered for the first time?

Thanks 😄

**Comment by mtt87** [comment]
Any hint on this? 😄

**Comment by kennyfox7** [comment]
I need this too :(

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by mtt87** [comment]
@alvelig why did you close this?
Your comment is about "showing the user location" which is different than the subject of this issue.

This issue is about asking the geo permission popup on request rather than automatically when the app is loadded and/or the map is mounted.

I'm talking about this, if it's not clear:
<img src="https://i.stack.imgur.com/XhAsU.png" />

**Comment by sonaye** [comment]
Removing `showsUserLocation` prop did it for me, it asks for location permissions immediately it seems.
