### ISSUE TITLE
Error when marker is pressed on IOS

### ISSUE THREAD

**Issue by neilakoh** [react-native-community/react-native-maps#1499]
I have my map set up like this:

```
        <MapView.Animated style={styles.map}
          region={region}
          loadingEnabled={true}
          zoomEnabled={false}
          rotateEnabled={true}
          provider={PROVIDER_GOOGLE}
          moveOnMarkerPress={false}
          scrollEnabled={false}
          onPress={(e)=>{this.getCoords(e.nativeEvent)}}
          customMapStyle={MapTheme.battleofcoin()}
        >
                  <MapView.Marker.Animated
                     coordinate={region}
                     onPress={this.triggerCurrentUser}
                 >
                 </MapView.Marker.Animated>
        </MapView.Marker.Animated>
```

Whenever I click the marker it gives me an error saying 

> "Cannot read property 'latitude' of undefined

 I believe this is due to I added event onPress on the map but I need it to get map coordinates through map press. Is there a way to sort this out or is this a bug? Please advise. Thanks a lot.

---------------

By the way it happen only in IOS not on android

**Comment by rayzor65** [comment]
I believe I am having a similar issue
`<MapView.Marker key={place.placeId} coordinate={place.latLng} title={place.title} description={place.address} onPress={this.animateToCoordinate} > <MapView.Callout> <PlaceCallout {...place} /> </MapView.Callout> </MapView.Marker>`
And then I try to print out coordinate
`animateToCoordinate(e) { 
console.log(e); 
console.log(e.nativeEvent); 
console.log(e.nativeEvent.coordinate); 
}`

**Comment by jakeols** [comment]
+1, experiencing a similar issue. My onPress method returns the following, even when I'm explicitly setting the ID.

```
Object {
  "action": "marker-press",
  "id": "unknown",
  "target": 145,
}
```

**Comment by neilakoh** [comment]
@rayzor65 - I believe if you do it like this `onPress={(e)=>{this.animateToCoordinate(e.nativeEvent)}}` you should be able to get the event data on press on android but not on IOS.

**Comment by rayzor65** [comment]
@neilakoh thanks for the tip but I really need this working for iOS.
On iOS when logging currently it gets
```
{
    action:"marker-press"
    id:"unknown"
    target:307
}
```

**Comment by neilakoh** [comment]
@rayzor65 on your MapView did you add `provider={PROVIDER_GOOGLE}` ? In my end I removed the provider={PROVIDER_GOOGLE} and it worked fine now; however, the problem is I can no longer add custom map design . . try to remove the provider={PROVIDER_GOOGLE} if you added it and see it will work in your end.

**Comment by rayzor65** [comment]
@neilakoh yes that is the problem. My requirements is I need to use a google map and it appears when I do you lose the coordinate information. I can confirm it works for the Apple map.

**Comment by chiphan2008** [comment]
<MapView
            region={this.state.region}
            onPress={ (event) =>{
              const {latitude,longitude} = (event.nativeEvent.coordinate || this.state.region);
              ...
            }}

**Comment by ng-hai** [comment]
Try this

```js
onMarkerPress = coordinate => event => {
  this.map.animateToCoordinate(coordinate, 200)
}

getMapReference = ref => {
  this.map = ref
}

render () {
  return (
    <MapView ref={this.getMapReference}>
        // if you already have a determinded coordinate
        <Marker 
          coordinate={this.state.coordinate}
          onPress={this.onMarkerPress(this.state.coordinate)} 
        />

        // if you get dynamic coordinate by mapping array
        {locations.map(({ latidude, longtitude }) => {
          const coordinate = { latidude, longtitude }
          return <Marker coordinate={coordinate} onPress={this.onMarkerPress(coordinate)} />
        })}
    </MapView>
  )
}
```

**Comment by rborn** [comment]
Closing, old issue. Please open a new one if you still have the problem.
