### ISSUE TITLE
Want to animate the polyline likewise in uber

### ISSUE THREAD

**Issue by thayanithik** [react-native-community/react-native-maps#1566]
Hi,

I want to animate the polyline of the mapview likewise in UBER app's map.

Please implement this feature, for better polyline view.

**Comment by rishabhmathur1693** [comment]
Does anyone have a solution for this thing? I also need to implement this thing in my project and I haven't found anything anything in the document regarding Polyline animation.

**Comment by davidwu220** [comment]
I am too looking for this feature. I found a [post](https://forums.raywenderlich.com/t/how-do-i-add-animation-to-drawn-route-in-ios-map-like-uber-application-doing-now-days/26719) that mentions usage of `rendererForOverlay` in swift could possibly be used to achieve this. But that may not be the best solution we have here.
