### ISSUE TITLE
cacheEnabled google maps

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-community/react-native-maps#1583]
On iOS with provider google, `cacheEnabled` doesn't do anything. I verified this by changing the provider back to default, where it does work. I'm still able to navigate the map and it's not an image. 

I'm using the latest version.

**Comment by yannickschuchmann** [comment]
> react-native version: 0.46.1
> react-native-maps version: 0.15.3

I can confirm this. Having the same issue.

**Comment by ingmaras** [comment]
Same issue here - react-native@0.47 and react-native-maps@0.16.3

**Comment by nakamotoo** [comment]
same issue here

**Comment by pitchourou** [comment]
same, not working 
react-native-maps@0.20.1

**Comment by rborn** [comment]
@pitchourou  @nakamotoo  try the git version and let us know

**Comment by pitchourou** [comment]
> @pitchourou @nakamotoo try the git version and let us know

Still not working 
react-native-maps@0.22.0

**Comment by rborn** [comment]
@pitchourou @nakamotoo I did a search in the source code and I think it's only available for apple maps :( 

@alvelig  Maybe we should updated the docs here?

**Comment by rborn** [comment]
> Hope to see that on the next release

Well, somebody needs to make a PR for that

**Comment by lfkwtz** [comment]
was just burned by this surprise due to the lack of documentation -- so until it's fixed, opened a PR for the docs #2559
