### ISSUE TITLE
Component 'AIRMapMarker' re-registered bubbling event 'topSelect' as a direct event

### ISSUE THREAD

**Issue by MicroKibaco** [react-native-community/react-native-maps#1615]
**Component 'AIRMapMarker' re-registered bubbling event 'topSelect' as a direct event**

**Comment by Ble3k** [comment]
Have the same issue. A problem appeared after I installed some pod dependencies and started using .xcodeworkspace instead .xcodeproject while linking react-native-charts-wrapper with xcode.

**Comment by MicroKibaco** [comment]
**It is recommended to use Baidu's Echarts to replace the react-native-charts-wrapper, and maybe his function will be more robust**

**Comment by jordenchang55** [comment]
Remove ```RCT_EXPORT_VIEW_PROPERTY(onSelect, RCTBubblingEventBlock)``` in RNChartManagerBridge.h from react-native-charts-wrapper fixes the problem for me. While some feature may be not available.

**Comment by vuadenthuj1** [comment]
Do you have any idea?

**Comment by rborn** [comment]
@vuadenthuj1 what version of the map module and react-native are you using?

**Comment by vuadenthuj1** [comment]
I use react-native 0.50.3. "react-native-charts-wrapper": "^ 0.3.1" and "react-native-maps": "^ 0.18.3"

**Comment by rborn** [comment]
Try to update react-native and use the git version of react-native-maps. Let me know.

**Comment by vuadenthuj1** [comment]
Do you have integrated successfully two libraries in a higher version?

**Comment by rborn** [comment]
with the maps a custom made one (uses linked in sdk)

**Comment by vuadenthuj1** [comment]
what does that mean?

**Comment by vuadenthuj1** [comment]
So you don't have any solution for this?

**Comment by rborn** [comment]
Did you try to upgrade as I suggested?

**Comment by vuadenthuj1** [comment]
I updated react native 0.51.0 and react-native-maps 0.19 and error still appears

**Comment by hungdev** [comment]
i get same issue with   "react-native-charts-wrapper": "^0.4.3" and     "react-native-maps": "^0.21.0"
@vuadenthuj1 are you done with it?

**Comment by cesartotvs** [comment]
@hungdev It looks as though there is a collision with react-native-charts-wrapper. Do the following to fix this collisions:

1. Go to the node_modules/react-native-charts-wrapper/iOS
2. Run: grep -rn “onSelect” .
3. Replace all instances found of `onSelect` with `onChartSelect`
4. Go to the node_modules/react-native-charts-wrapper/lib
5. Replace all instances found of `onSelect` with `onChartSelect`

**Comment by hungdev** [comment]
@cesartotvs  thank you so much. It worked.

**Comment by iOSTest321** [comment]
Component 'AIRMapMarker' re-registered bubbling event 'topSelect' as a direct event , i am gettting this error and help me with solution
