### ISSUE TITLE
User location should not be hidden by Markers

### ISSUE THREAD

**Issue by timfpark** [react-native-community/react-native-maps#1668]
I have a map where I am displaying user location, polylines, and markers on the map.

When the user moves on to a position that intersects a polyline, the User Location indicator is still visible (which is great), however, when the user moves to the marker, the User Location indicator is covered by the Marker and they can't see their location.

Is there a way to make the User Location indicator the highest z index such that it occludes all of the other elements?

**Comment by austincline09** [comment]
+1

**Comment by alvelig** [comment]
try #1845

**Comment by alvelig** [comment]
May be related to #483

**Comment by Seypopi** [comment]
I have putted all my markers to negative zIndex values
