### ISSUE TITLE
iOS MapView fires onPress() even if the press target is a Polygon

### ISSUE THREAD

**Issue by IgorVanian** [react-native-community/react-native-maps#1713]
~~Hello everyone,~~

~~When I use Google Maps provider for iOS (running fine), onPress doesn't fire for Polygon.~~
~~Also, onCalloutPress doesn't fire for markers. I though there was a PR fixing this, am I wrong?~~

~~I'm using RNM 16.3.~~

~~Edit:~~

~~It does fire actually. onPress={() => console.log("123")} does log correctly but when I call my function which does this.setState(), it doesn't set any state....~~

Problem: iOS MapView fires onPress() even if the press target is a Polygon.
Platform: iOS
RNM Version: 0.16.3

**Comment by Falconerd** [comment]
I would love to be able to easily toggle this functionality. For our use-case we need our users to see polygons on their turf, but then be able to tap a location and pull up the address.

This is working on iOS due to this bug, but it is not working on android as the polygon onPress fires.
