### ISSUE TITLE
animateToBearing and animateToRegion are not working simultaneously

### ISSUE THREAD

**Issue by yanniz0r** [react-native-community/react-native-maps#1726]
Hey folks,

I'm currently experiencing issues while animating the bearing and position simultaneously. It seems like the second executed animation cancels the first one. My goal is to follow the tracked position of the user on android and ios.

```js
const position = this.state.currentPosition
this.map.animateToBearing(position.coords.heading)
this.map.animateToRegion({
  latitude: position.coords.latitude,
  longitude: position.coords.longitude,
  latitudeDelta: 0.0075,
  longitudeDelta: 0.0075,
}, 5000)
```

Is there any solution for this problem or another way to track the users position while animating the bearing to the direction the user is heading?

If you need any additional information feel free to notify me!

Thanks in advance,
Yannic

**Comment by ryanvanrooyen** [comment]
I'm having the exact same problem.  I noticed this is also an issue when trying to use animateToViewingAngle instead of animateToBearing.  Seems as tho any call to animateToRegion or animateToCoordinates resets the bearing and viewing angle.

**Comment by MiLeung** [comment]
Instead of having animateToRegion, animateToBearing, and animateToViewingAngle, I think it'd make more sense to just add more keys to the animateToRegion method config

i.e.

```javascript
this.map.animateToRegion({
  latitude,
  longitude,
  latitudeDelta,
  longitudeDelta,
  bearing,
  viewingAngle
});
```

**Comment by touqeerkhan11** [comment]
Hmm why not use a timeout? 

      this.mapRef.animateToBearing(156, 1000);

      setTimeout(() => {
        this.mapRef.animateToViewingAngle(45, 100);
      }, 200);

This seems to work...

**Comment by juergengunz** [comment]
same issue for me :(

**Comment by juergengunz** [comment]
@ryanvanrooyen did you end up finding a solution for your problem?

**Comment by yanniz0r** [comment]
Sadly I’ve not been able to find a solution yet. Using a timeout as suggested by @touqeerkhan11 didn’t help for because the animation didn’t look fluid at all.

**Comment by ryanvanrooyen** [comment]
I found a solution for iOS, I added a new native function that sets all the properties at the same time and uses a different api call that does not cause the camera to reset.  It's working great now.  I also added some helper functions that allows the function to set a vertical offset that allows the current location to be more towards the bottom of the screen instead of the middle.

Here is the new JS function I added to the MapView.js file:
`
// Add this function to class in file: node_modules/react-native-maps/lib/components/MapView.js
animateToView(latLng, altitudeMeters, bearing, viewAngle, verticalOffsetMeters, duration) {
    this._runCommand('animateToView', [latLng, 
	 altitudeMeters || 50,
	 bearing || 0,
	 viewAngle || 0,
	 verticalOffsetMeters || 0,
	 duration || 500]);
}
`

And here is the native iOS code I added to the AirMapManager.m file to implement the function:
`
- (double)radiansFromDegrees:(double)degrees
{
    return degrees * (M_PI/180.0);
}

- (double)degreesFromRadians:(double)radians
{
    return radians * (180.0/M_PI);
}

- (CLLocationCoordinate2D)coordinateFromCoord:
(CLLocationCoordinate2D)fromCoord
atDistanceKm:(double)distanceKm
atBearingDegrees:(double)bearingDegrees
{
    double distanceRadians = distanceKm / 6371.0;
    //6,371 = Earth's radius in km
    double bearingRadians = [self radiansFromDegrees:bearingDegrees];
    double fromLatRadians = [self radiansFromDegrees:fromCoord.latitude];
    double fromLonRadians = [self radiansFromDegrees:fromCoord.longitude];
    
    double toLatRadians = asin( sin(fromLatRadians) * cos(distanceRadians)
                               + cos(fromLatRadians) * sin(distanceRadians) * cos(bearingRadians) );
    
    double toLonRadians = fromLonRadians + atan2(sin(bearingRadians)
                                                 * sin(distanceRadians) * cos(fromLatRadians), cos(distanceRadians)
                                                 - sin(fromLatRadians) * sin(toLatRadians));
    
    // adjust toLonRadians to be in the range -180 to +180...
    toLonRadians = fmod((toLonRadians + 3*M_PI), (2*M_PI)) - M_PI;
    
    CLLocationCoordinate2D result;
    result.latitude = [self degreesFromRadians:toLatRadians];
    result.longitude = [self degreesFromRadians:toLonRadians];
    return result;
}

RCT_EXPORT_METHOD(animateToView:(nonnull NSNumber *)reactTag
                  withLatLng:(CLLocationCoordinate2D)latlng
                  withAltitude:(double)altitudeMeters
                  withBearing:(CGFloat)bearing
                  withAngle:(double)angle
                  withVerticalOffset:(double)offsetMeters
                  withDuration:(CGFloat)duration)
{
    [self.bridge.uiManager addUIBlock:^(__unused RCTUIManager *uiManager, NSDictionary<NSNumber *, UIView *> *viewRegistry) {
        id view = viewRegistry[reactTag];
        if (![view isKindOfClass:[AIRMap class]]) {
            RCTLogError(@"Invalid view returned from registry, expecting AIRMap, got: %@", view);
        } else {
            
            AIRMap *mapView = (AIRMap *)view;
            MKMapCamera *mapCamera = [[mapView camera] copy];
            
            CLLocationCoordinate2D coordinateAhead = [self coordinateFromCoord: latlng atDistanceKm:offsetMeters/1000 atBearingDegrees: bearing];
            
            [mapCamera setCenterCoordinate: coordinateAhead];
            //[mapCamera setCenterCoordinate: latlng];
            [mapCamera setHeading:bearing];
            [mapCamera setAltitude: altitudeMeters];
            [mapCamera setPitch: angle];
            
            
            [AIRMap animateWithDuration:duration/1000 animations:^{
                [mapView setCamera:mapCamera animated:YES];
            }];
        }
    }];
}
`
If someone was willing to help add the equivalent functionality for the android side, I would make a pull request for the feature.

**Comment by alvelig** [comment]
@ryanvanrooyen PRs are welcome.

**Comment by joachimssj** [comment]
Hi,

You can use animateToNavigation({latitude,longitude},currentHeading,angle,time)

**Comment by club9822** [comment]
> Hmm why not use a timeout?
> 
> ```
>   this.mapRef.animateToBearing(156, 1000);
> 
>   setTimeout(() => {
>     this.mapRef.animateToViewingAngle(45, 100);
>   }, 200);
> ```
> 
> This seems to work...

thanks.
using setTimeout to loading  map style before animateToRegion solved my problem
