### ISSUE TITLE
Memory Leak: JSON.stringify of map ref reveals cyclic structures

### ISSUE THREAD

**Issue by resson-ntranquilla** [react-native-community/react-native-maps#1740]
`<MapView
   ref={r=>this.map=r}
   ...
/>`

When attempting to log `this.map`, the app crashes. When attempting to log `JSON.stringify(this.map)` the error `JSON.stringify cannot serialize cyclic structures`

Edit:

Using the performance monitor, I see the memory usage spike up to 1.5GB . 

I am using: 
- `react-native-maps: ^0.17.1`
- `react-native: ^0.48.0`
- `react: ^16.0.0` 
- `expo: ^22.0.0`

**Comment by addosso** [comment]
Same problem with angular.equals(map, map). openlayer's map seems to have a circular references inside.

**Comment by resson-ntranquilla** [comment]
I'm not sure what you mean. Are you using openlayers as your tile source in `MapView.UrlTile`, and that the openlayers service is causing circular references within the `react-native-maps` code? I'm using google as my tile service.

**Comment by addosso** [comment]
I mean that:  i think, the maps objects (openlayers, google, etc) are a cyclic structures and cannot be stringified.

**Comment by resson-ntranquilla** [comment]
I don't think that's the case. The circular structure comes from the actual structure of the react elements themselves. Through painful trial and error, I have found that the `_hostParent`, `_owner`, and `_renderedChildren` all have circular references (which makes sense). I'm just confused now why it causes the app to crash when trying to assign this to the context (ie. `onMapReady={ref=>this.**map**=ref}` ). 

It must be causing some sort of memory leak. The app appears to "freeze" momentarily before crashing. I guess [cyclical dependencies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#Cycles_are_not_a_problem_anymore) have not been a problem in the browser for some time - is it not the same with mobile apps?

**Comment by rborn** [comment]
Old issue. Closing.

**Comment by sandeepsinghs** [comment]
How to handle this issue, I am still getting the same error. It is possible to remove the click from the map because I am getting this issue on the click of the map.

Thanks,
