### ISSUE TITLE
Some IOS versions won't fire onPress functions inside PanController

### ISSUE THREAD

**Issue by lulubun** [react-native-community/react-native-maps#1747]
react-native: 0.47.2
I'm trying to replicate the AnimatedViews from this link: https://github.com/airbnb/react-native-maps/blob/master/example/examples/AnimatedViews.js

I've got it mostly working the way I want but the buttons I've added into the AnimatedViews do not fire onPress when clicked on certain versions of IOS. After testing on all simulators:

5s - works
6 - works
6+ - works
6s - not working
6s+ - not working
7 - not working
7+ - not working
8 - not working
8+ - not working
SE - works
x - not working

I'm trying to link to a detailed screen for information about that map location when the button is pressed but somehow the PanController is the only action thing being registered. Any suggestions on how to make the button onPress a priority over the PanController? If I comment out the code for onPanYChange 

onPanYChange = ({ value }) => {
    console.log("onPanYChange runs", value)
    const { canMoveHorizontal, region, scrollY, scrollX, markers, index } = this.state;
    console.log('COORDINATE 2 ========', markers )
    region.stopAnimation();
    if(markers.length > 1){
      region.timing({
        latitude: scrollX.interpolate({
          inputRange: markers.map((m, i) => i * SNAP_WIDTH),
          outputRange: markers.map(m => m.location.latitude),
        }),
        longitude: scrollX.interpolate({
          inputRange: markers.map((m, i) => i * SNAP_WIDTH),
          outputRange: markers.map(m => m.location.longitude),
        }),
        duration: 0,
      }).start();
      console.log('end of coord 2')
    }
  }

the buttons actions are fired but the pan ability of the map is disabled.

**Comment by limitsapp** [comment]
any fixes?

**Comment by lulubun** [comment]
nope... anyone extra smart out there??

**Comment by limitsapp** [comment]
Hey, I got a fix. It has to do with a issue regarding force touch on the newer devices and with the Panhandler.

The quickest fix is to use onPressIn instead of onPress !

Found it [here](https://github.com/facebook/react-native/issues/3082)
