### ISSUE TITLE
Zoom greater than 20 for custom tiles

### ISSUE THREAD

**Issue by implicit-invocation** [react-native-community/react-native-maps#1748]
I try to set MapView region to something like this
```
{
  latitude: (bounds[0][0] + bounds[1][0]) / 2,
  longitude: (bounds[0][1] + bounds[1][1]) / 2,
  latitudeDelta: Math.abs(bounds[0][0] - bounds[1][0]),
  longitudeDelta: Math.abs(bounds[0][1] - bounds[1][1])
}
```
for an indoor location (small area).  
But the MapView seems never zoom as far as I want (stuck at zoomLevel 19 on iOS, 20 on Android).  
I tried the `minDelta` and `maxZoomLevel`, it can limit how much I can zoom with larger `minDelta` or smaller `maxZoomLevel`, but can never let me zoom to anywhere further than level 19.

**Comment by alvelig** [comment]
I think you should change tiles. For example you press a house (your indoor location), and then you need to switch to your custom tiles. The zoom will be still 19, but you are inside alrready. Did I get your idea? Or let me know your business case.

**Comment by vitto-moz** [comment]
I stack also on this issue. 
I have about 30 markers on map situated in different parts of a world map. 
So my goal is to zoom out until they are shown all. But map can't be zoomed out more than 20.
What can be a workaround?
