### ISSUE TITLE
[Android] polygon onPress always returns coordinates of first path

### ISSUE THREAD

**Issue by Falconerd** [react-native-community/react-native-maps#1795]
When the onPress event of a polygon is fired, it always returns the coordinates of the first point. This makes it impossible to get the location which the user has pressed if there is a polygon on top of it.

A potential workaround for right now is to draw polylines instead. There is also a workaround which involves editing the polygon java file and setting isClickable to false.

**Comment by vitto-moz** [comment]
Yes, it seems moving to polylines is a solution. Can't make polygons like this on Android, iOS works
![image](https://user-images.githubusercontent.com/19843391/42238655-414ea0c0-7f0a-11e8-8344-9531057d00db.png)
