### ISSUE TITLE
Callout is hidden randomly on annotation selected

### ISSUE THREAD

**Issue by alvelig** [react-native-community/react-native-maps#1850]

**Comment by alvelig** [comment]
https://www.youtube.com/watch?v=cq9oX8f4TK8

**Comment by alvelig** [comment]
Ok, I got it debugged. There are 3 cases:

1. If region changes to show the callout (initially the marker should be partially out of boundaries)
2. If marker is overlapped with another marker
3. Any marker in the same region after point 2.

Only iOS. Android not tested.

**Comment by mafiusu** [comment]
Anyone working on this bug actually?

**Comment by alvelig** [comment]
It's on the roadmap. But can't give you any terms when it would be ready.

**Comment by ignivaashwani** [comment]
Hi, I am getting same issue as demonstrated in video above

**Comment by mafiusu** [comment]
It's one of my key feature in my app I hope this bug gets a fix soon.
