### ISSUE TITLE
on quick double tab second tap is not processed 

### ISSUE THREAD

**Issue by dennisbejencev-an** [react-native-community/react-native-maps#1882]
platform : ios 10.3   
"react": "16.0.0-alpha.12",
"react-native": "0.48.3",
"react-native-maps": "^0.16.4",

The reason why I should track double press event is that when I press on map then header in my app is toggling, when I make double press it toggling 2 times, I need on double press don't toggle header, the toggling similar to google map app.

And when I make quick double tap, second tap is not processed they all must be processed. What can it be? Seems like double press zoom doesn't let for my second tap events process.
If instead MapView I put View, handlers works correctly

my code:
```javascript
<TouchableOpacity
    onPressIn={() => {console.log('onPress');}}
    onPressOut={() => {console.log('onPressOut');}}
>
    <MapView
        region={region}
        ref={ref => { this.mapView = ref }}
        style={s.mapView}
        onLayout={() => this.onLayout(coordinates)}
        onRegionChangeComplete={this.onRegionChange}
        showsUserLocation
    >
    </MapView>
</TouchableOpacity>
```

you can look video https://drive.google.com/open?id=1RZJBs8J7gz3lRBOZ5DUTYIcCF48tib5P

**Comment by rborn** [comment]
@dennisbejencev-an please edit the issue following the template we've put in place or we'll close the issue.

**Comment by rborn** [comment]
@dennisbejencev-an you are putting a **MapView** inside a **TouchableOpacity** so they will compete for the touch event. In this case the map will "eat" the second tap from the double tap as it's handled as "double-tap". What you could do is to try to use the `onPress` event of the MapView to toggle the header.

**Comment by alvelig** [comment]
Exposing `doubleTap` event looks like the only solution? Clearly Touchable* won't receive anything from the MapView.

**Comment by dennisbejencev-an** [comment]
can we disable onPress event on map?

**Comment by alvelig** [comment]
Nope, it won't bubble from MapView anyway, but try using Touchable* within the MapView with absolute positioning. That might be surprisingly working. Let us know if it works please or has any problems or drawbacks.

**Comment by dennisbejencev-an** [comment]
do you mean something like it?
<TouchableOpacity style={{position: 'absolute'}}>
<Map/>
</TouchableOpacity>

**Comment by alvelig** [comment]
```
<MapView 
  ...
  style={StyleSheet.absoluteFill}>
  <TouchableOpacity style={StyleSheet.absoluteFill} />
</MapView>
```

**Comment by dennisbejencev-an** [comment]
with `<MapView onPress={() => {console.log('click')}}/>` the same, somewhere onPress isn't invoked

**Comment by dennisbejencev-an** [comment]
seems like the problem is in predefined on double press zoom, seems like somewhere the predefined handler steal calling of my callback

**Comment by dennisbejencev-an** [comment]
is possible to track all presses on map????  :weary: :weary:

**Comment by dennisbejencev-an** [comment]
@alvelig in case when touchable over map then all presses are handled, but I can't move map with swipe

**Comment by alvelig** [comment]
@dennisbejencev-an yep... you are right, I did not think about that. 

So, to sum up, what is the problem and which solution do you see? What should we put to the roadmap to "fix" this problem?

**Comment by filipef101** [comment]
Any progress on this? I'm facing the same issue, I just need to know if the user tried to zoom to unlock the zoom
