### ISSUE TITLE
The 'Pods-ProjectName' target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by rash6795** [react-native-community/react-native-maps#1923]
### Problem Description
Pod installation fails when tried to use along with other cocoapods which are already being used by the project . But works fine when no other pods are installed

### Is this a bug report?
YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
YES

### Environment
    react-native: 0.50.3
    react:  16.0.0-beta.5
    react-native-maps: 0.19.0 
    Target Platform: iOS - 8 and above 
    ios Using GoogleMaps

### Steps to Reproduce
1.  Follow the cocoapods installation for "react-native-maps"
2. install additional pods like Firebase , Alamofire ,etc ... (or Any other pod )

### Expected Behavior
All the Pods to be installed successfully !

### Actual Behavior
Pod installation Failed with the following reason:

> [!] The 'Pods-mapSample' target has transitive dependencies that include static binaries: (/Users/Username/Desktop/mapSample/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /Users/Username/Desktop/mapSample/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, and /Users/Username/Desktop/mapSample/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework)

### Terminal Screenshot
![group 4](https://user-images.githubusercontent.com/34880490/34374597-ee5bb1f0-eb07-11e7-8027-a86124d69b12.png)

###  List of Pods in Project Screenshot
![screen shot 2017-12-27 at 12 52 52 pm](https://user-images.githubusercontent.com/34880490/34374288-656e9548-eb06-11e7-9dc5-39b3f3cd3aae.png)

### Reproducible Demo
No

**Comment by Jono20201** [comment]
Experiencing the same issue.

**Comment by abs-zero** [comment]
Getting the same issue here, too. This should be a bug not an enhancement.

**Comment by Josh2941** [comment]
Here also the same problem. But works fine for Android. I too think its must be a bug.

**Comment by Yandamuri** [comment]
Here also the same problem.This should be a bug.

**Comment by alvelig** [comment]
Guys, anybody who is experiencing that, please make a reproducible demo. Otherwise this does not move anywhere, remember, we are community, are we?

**Comment by rash6795** [comment]
### The Reproducible demo is available in the following link 
https://drive.google.com/open?id=1Rrr-6Muru6TA3J33288pWz0Bk8cdNUWd


## Issues Faced
**This is the Podfile when modifying according to react-native-maps documentation** 

![pod1](https://user-images.githubusercontent.com/34880490/34595237-56de6eca-f1fc-11e7-86f9-f7babdd13890.png)


**Terminal output after hitting 'pod install' and project works fine** 

![before](https://user-images.githubusercontent.com/34880490/34595236-56ad6492-f1fc-11e7-95f2-73ebfb47cea8.png)


**The Podfile after adding other Pod files** 

![pod 2](https://user-images.githubusercontent.com/34880490/34595243-62f5f520-f1fc-11e7-8836-b1fe07501ee4.png)


**Terminal output after hitting 'pod install' and there comes the error** 

![after](https://user-images.githubusercontent.com/34880490/34595241-5b5094ba-f1fc-11e7-974a-6e8bd2582876.png)

**Comment by rborn** [comment]
Everyone, could you please try the workaround found here (the pre_install script): 

https://github.com/CocoaPods/CocoaPods/issues/6993  or the updated one linked in the comment?

Let us know. Thanks.

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.

**Comment by dunklesToast** [comment]
I am still encountering this problem. The workaround seems to fix it.

**Comment by hoonblizz** [comment]
I had the same issue. Adding 

pre_install do |installer|
# workaround for CocoaPods/CocoaPods#3289
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

after target fixes the issue.

**Comment by Prophetaa** [comment]
Thanks @hoonblizz  works like a charm

**Comment by yuoppp** [comment]
(*Sponge Bob Voice*) 2 years later....

Still facing the issue

**Comment by RashVenkat6795** [comment]
@yuoppp  try hoonblizz way it works

**Comment by CyrusZei** [comment]
check so that you don't have the `use_frameworks!` in your podfile. Removed that and it worked

**Comment by dawidvdh** [comment]
Placing the following in my Podfile worked for various libraries that I had this same issue with:

```
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('NAME_OF_POD') || pod.name.start_with?('START_OF_NAME_OF_POD')
      def pod.build_type;
        # Uncomment one line depending on your CocoaPods version
        Pod::BuildType.static_library # >= 1.9
        # Pod::Target::BuildType.static_library # < 1.9
      end
    end
  end
end
```

replacing `NAME_OF_POD` and `START_OF_NAME_OF_POD` with what you require of course.

**Comment by sirmong** [comment]
Thanx, @hoonblizz , you helped so much! 👍

**Comment by imondal007** [comment]
Still facing same issue

**Comment by gabekutner** [comment]
@hoonblizz Thank you, worked for me. Placed at the end my Podfile, pod install and building worked. Thanks, is this a permanent solution tho? Or something I need to keep an eye on
