### ISSUE TITLE
Use of Animated.Interpolation in Animated Region - Instead of Animated.Value

### ISSUE THREAD

**Issue by njho** [react-native-community/react-native-maps#1929]
### Is this a bug report?
No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
    react-native: 0.50.0
    react: 16.0.0
react-native-maps: 0.17.1 

### Steps to Reproduce
How would one input an `Animated.Interpolation` (AnimatedInterpolation) in the `region` prop, rather than, an `Animated.Value`?

This would be very useful in animating the MapView with libraries such as [react-native-interactable](https://github.com/wix/react-native-interactable), where the library handles the gestures and updates the `Animated.Value`. 

For example, with `<Animated.View>` modules, we can then change values simply, by inputting the following:
```
/*---- ANIMATED OPACITY EXAMPLE/TYPICAL RN FUNCTIONALITY -----*/
<Animated.View
style={{
          opacity: this.AnimatedValue.interpolate({
                                inputRange: [-100, -100, 500, 500],
                                outputRange: [1, 1, 0, 0]
                            })}}>
</Animated.View>
```

### Reproducible Demo

**Desired Functionality which correlates with other React Native Modules <Animated.View>, etc...**

- Does not require the use of `Animated.timing({    ...    }).start()`
- Values can be directly interpolated in associated props

```
/* ----- IN CONSTRUCTOR ------*/
this._deltaY = new Animated.Value(0);

/* ------ SIMILIAR TO ANIMATEDVIEW.JS IN EXAMPLE DIRECTORY ---- */
 <MapView.Animated
            region={
                        new MapView.AnimatedRegion({
                            latitude: 37.78875,
                            longitude: -122.4324,
                            latitudeDelta: this._deltaY.interpolate({
                                inputRange: [0, BREAKPOINT1],
                                outputRange: [LATITUDE_DELTA, LATITUDE_DELTA * 0.5],
                                extrapolate: 'clamp',
                            }),
                            longitudeDelta: LONGITUDE_DELTA,
                        })}
                >

</MapView.Animated>

/* ---- INTERACTABLE.VIEW DIRECLTY MANIPULATES this._deltaY----*/
 <Interactable.View animatedValueY={this._deltaY}/ >
```
If we change the `AnimatedRegion.js` to accept `AnimatedInterpolations` as an input, we find the following structure for the `AnimatedMapRegion`. 

__As you can see `LatitudeDelta` contains the `AnimatedInterpolation`. This does not work__
![image](https://user-images.githubusercontent.com/16584869/34457836-15b04fb6-ed7b-11e7-806e-18f4e65ce36f.png)

**Current Package Requirements**
- Requires a function call to animate
- Requires use of `Animated.timing({     ...   }).start()`

```
/* ----- NECESSARY TO HAVE FUNCTION CONTINUOUSLY CALLED  TO UPDATE VALUE --- */
continuouslyCalledFunction() {
 region.stopAnimation();
        this.region.timing({
          latitude: scrollY.interpolate({
            inputRange: [0, BREAKPOINT1],
            outputRange: [
              coordinate.latitude,
              coordinate.latitude - (LATITUDE_DELTA * 0.5 * 0.375),
            ],
            extrapolate: 'clamp',
          }),
          latitudeDelta: scrollY.interpolate({
            inputRange: [0, BREAKPOINT1],
            outputRange: [LATITUDE_DELTA, LATITUDE_DELTA * 0.5],
            extrapolate: 'clamp',
          }),
          longitudeDelta: scrollY.interpolate({
            inputRange: [0, BREAKPOINT1],
            outputRange: [LONGITUDE_DELTA, LONGITUDE_DELTA * 0.5],
            extrapolate: 'clamp',
          }),
          duration: 0,
        }).start();
}

/* ------  ANIMATEDVIEW.JS IN EXAMPLE DIRECTORY ---- */
 <MapView.Animated
            region={this.region}>

</MapView.Animated>

/* ---- PANRESPONDER - Insert a lot of boiler plate to handle touches.----*/
/* ---- CALLS continuouslyCalledFunction() CONTINUOUSLY IN ORDER TO ANIMATE *---/
```
Any help would be appreciated! Even an idea of how to potentially tackle this.

**Comment by murtraja** [comment]
+1

**Comment by DavoCg** [comment]
+1 If anyone have a solution for this use case
