### ISSUE TITLE
Detecting marker size is not accurate on pressing marker

### ISSUE THREAD

**Issue by vasyas** [react-native-community/react-native-maps#1932]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.49.5
react: 16.0.0-beta.5
react-native-maps: 0.17.1 (also tested on 0.19.0)

Target platform Android/Genymotion (also tested on real Android devices)

### Steps to Reproduce

I use image for customer marker and supplying onPress handler for Marker.
OnPress gets triggered even when I click far from the marker. 

### Expected Behavior

Marker onPress should be triggered when clicking the marker. 
When pressing the map, Map's onPress should be triggered.

### Actual Behavior

Marker onPress is triggered (and marker remains selected on the demo) even when clicking outside 
the marker.

See demo video:
https://monosnap.com/file/SyaZjqksy4Zbsc8juNn1NPlcYXBfDP

### Reproducible Demo

https://snack.expo.io/rJmBIAdmz

**Comment by Benjamin-Dewey** [comment]
Same issue for me on Android using react-native-maps 0.19.0 and react native 0.51.0.
Regardless of whether or not I use a custom marker or the default marker the problem persists.

**Comment by Benjamin-Dewey** [comment]
I made a new snack that uses the latest version of everything and the bug seems to be gone.

https://snack.expo.io/ryuOtr3MX

**Comment by Benjamin-Dewey** [comment]
I made a new snack that uses the latest version of everything and the Android bug is still there.

https://snack.expo.io/ryuOtr3MX

**Comment by luigi198** [comment]
I have the same issue
