### ISSUE TITLE
[Feature Request] Add Option To Style Marker Image

### ISSUE THREAD

**Issue by hrastnik** [react-native-community/react-native-maps#1936]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native 0.48.4
react 16.0.0-alpha.12
react-native-maps: 0.15.3

### Steps to Reproduce

The documentation for MapView.Marker supports an `image` prop and the documentation states that "Only local image resources are allowed to be used.", even though passing `image={{uri: '...some_image_uri.jpg'}}` renders the image successfully on both Android and iOS devices. However, it's not possible to style the image. 

### Expected Behavior

It would be nice to have an extra prop, for example `imageStyle` that would be applied to the Marker image. Also the documentation should be updated to state it supports both local and online resources.

### Actual Behavior

Not possible to style the image. Image is rendered in it's original size and (in my case) covers almost the whole map.

### Reproducible Demo

`<MapView region={this.state.region}>
  {this.state.data.map(object => (
    <MapView.Marker
      key={object.id}
      coordinate={object.latlng}
      image={{uri: object.imageURI}}
    />
  ))}
</MapView>`

If the imageURI is a valid image URI it will get rendered in it's original size.

**Comment by alvelig** [comment]
Hi! Thank you for your suggestion, but that unfortunately is not going to be done. 

If you want to modify width/height, that must be done in your original image and you must provide @2x, @3x versions of your original image. See https://facebook.github.io/react-native/docs/images.html.

There are not much more options to modify in UIImageView (iOS) or ImageView (Android). This native "ImageViews" work totally different from `react-native`'s one.

**Comment by truca** [comment]
i was looking for this feature. Since it won't be developed, i used imagemagick to edit my images (i needed to scale them)

**Comment by hrastnik** [comment]
Well if it's not possible then I guess I'll just have to resize the image manually. 

Still, the documentation should be changed to say it allows both local and remote image resources (by passing {uri: "uri-string"} as the image prop). 

If there are other common style options shared between UIImageView and ImageView it would be nice to be able to pass a style object to the marker to control them.
