### ISSUE TITLE
[Android] App crashes if callout was added/removed from marker at runtime

### ISSUE THREAD

**Issue by satori-ytolstoguzov** [react-native-community/react-native-maps#1940]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

```
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-maps": "git+https://github.com/react-community/react-native-maps.git"
```

Target Platform: Android Emulator API 24/26 (That what I tested)

### Steps to Reproduce

If callout was added/removed from marker at runtime. App throws next error.

### Expected Behavior

Callout is added/removed without error.

### Actual Behavior

![screen shot 2018-01-05 at 1 01 11 pm](https://user-images.githubusercontent.com/31261230/34628261-97e5c370-f218-11e7-8567-b8212bbf4edf.png)

### Reproducible Demo

```js
<MapView.Marker
                coordinate={markerData.coordinate}
                identifier={markerData.id.toString()}
                key={markerData.id}
            >
                <View style={{backgroundColor: markerData.color}} />
                {markerData.callout ? <MapView.Callout tooltip><Text>Abc</Text> </MapView.Callout> : null }
</MapView.Marker>;
```

Switching `markerData.callout` in runtime will reproduce error.

https://github.com/satori-ytolstoguzov/rn-maps-callout-offset/tree/android-animation-error

**Comment by alvelig** [comment]
Did you try like that?
```
<MapView.Callout tooltip> {markerData.callout ? <Text>Abc</Text> : null } </MapView.Callout>
```

There may be a huge problem with hot replacing callout especially on Android.

**Comment by satori-ytolstoguzov** [comment]
@alvelig thanks. Forgot to mention that. Yeah, that's my current workaround. But I spent too much time catching this random error and it would be cool if it worked as expected.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
