### ISSUE TITLE
[Question] Tapping on two overlapping markers triggers the popup of both

### ISSUE THREAD

**Issue by cryzies** [react-native-community/react-native-maps#1952]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "react-native-maps": "^0.18.0",
    "react-native-meteor": "^1.2.0",
    "react-native": "^0.46.4",
    "react": "^16.0.0-alpha.12",

### Steps to Reproduce

1) Tap on Marker

### Expected Behavior

Tapping on a Marker should only trigger the popup of the closest marker to the touchevent

### Actual Behavior

It triggers both the markers in the above example

### Reproducible Demo

(Write your steps here:)

import React, { Component } from 'react';
import { View, StyleSheet } from 'react-native';
import MapView from 'react-native-maps';

class MapHome extends Component {
  render() {
    return (
      <View style={styles.container}>
        <MapView
          style={styles.map}
          initialRegion={{
            latitude: 33.831105,
            longitude: -117.130453,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
        >
          <MapView.Marker
            coordinate={{ latitude: 33.831105, longitude: -117.130453 }}
            title={'asdf3'}
            description={'afs3'}
          />
          <MapView.Marker
            coordinate={{ latitude: 33.834209, longitude: -117.130453 }}
            title={'asdf3'}
            description={'afs3'}
          />
        </MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});

export default MapHome;

**Comment by rborn** [comment]
Do the markers overlap? I'm not sure how the native part behaves in this case, but I think you are right, it should block the event bubbling.

**Comment by alvelig** [comment]
https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/LocationAwarenessPG/AnnotatingMaps/AnnotatingMaps.html#//apple_ref/doc/uid/TP40009497-CH6-SW45

And still there's an issue somewhere there for that. But I agree, naturally it should not bubble, but I'm afraid that would require refactoring all the touch detection system.

**Comment by cryzies** [comment]
@rborn yes they are overlapping
@alvelig that's what I feared

Might have to rethink the underlying theme of the app then if this is the case

**Comment by pejalo** [comment]
This issue has been driving me crazy so I created a new project to isolate it:
https://github.com/pejalo/react-native-maps-callout-bug

    "expo": "^24.0.0"
    "react": "16.0.0"
    "react-native": "0.51.0"
    "react-native-maps": "^0.20.0"

I know expo includes [its own map](https://docs.expo.io/versions/latest/sdk/map-view.html) view but I'm using this vanilla one explicitly like so:
`import MapView from 'react-native-maps';`

Strangely, the callouts are also appearing behind the markers, which was supposedly fixed in release [v0.20.0](https://github.com/react-community/react-native-maps/releases/tag/v0.20.0).

Here is a video of the behavior on the iOS 11.2 simulator:
https://youtu.be/-OXOkbWJCE8
@cryzies Can you confirm this is what you're experiencing?

When I was using `react-native-maps` about a year ago, it worked as expected. So this bug must have been introduced since then, and not just normal iOS map behavior as the link from @alvelig suggests?

This makes callouts practically unusable 😭

**Comment by meknil** [comment]
I run into the same problem.
		"react": "16.0.0",
		"react-native": "0.51.0",
		"react-native-maps": "0.20.1",

**Comment by chris-anderson67** [comment]
We are having both of these issues on the same versions as well, @meknil. 

The callouts are behind the markers and both callouts are triggered when tapping overlapping markers.

**Comment by EJohnF** [comment]
Since already 3 months no activities, I think It's good to promote it again. We also experience both problems on react-native-maps 0.20

**Comment by noll-fyra** [comment]
Experiencing the same issue on iOS. It seems to happen onPressIn rather than onPress.

**Comment by kheraprabhat** [comment]
I am using the stopPropogation method to do this.
```
onMarkerPress(e) {
    e.stopPropagation();
}
```

**Comment by ehynds** [comment]
Still hitting this issue, and @kheraprabhat's `stopPropagation` doesn't seem to work (for me, anyway). Any fresh leads on a fix?

**Comment by jmeyers44** [comment]
I'm also facing this issue, exactly as shown in the video from @777uday. You are correct @ehynds that stopPropagation for any event on the callout, marker or map component does not prevent the triggering of multiple callouts. This seems to be related to #1353

**Comment by cOdeBedient** [comment]
Was there a fix here? I see this as closed but I am experiencing the same issue.
