### ISSUE TITLE
[Android] Text in custom callout grows vertically with width of marker

### ISSUE THREAD

**Issue by satori-ytolstoguzov** [react-native-community/react-native-maps#1959]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react-native": "0.51.0",
"react-native-maps": "git+https://github.com/react-community/react-native-maps.git" (0.18.3)

### Steps to Reproduce

```
<MapView.Marker ...>
    ...
    <MapView.Callout tooltip><Text>This text should be one-liner</Text></MapView.Callout>
</MapView.Marker>
```

### Expected Behavior

I expect it to be displayed same way non-tooltip text is:
Text is displayed in one line.
![screen shot 2018-01-11 at 10 52 09 am](https://user-images.githubusercontent.com/31261230/34844382-1ba123c4-f6c6-11e7-91a6-bf89001d25f0.png)

### Actual Behavior

Text displayed vertically with same weird soft-wrapping:
![screen shot 2018-01-11 at 10 52 38 am](https://user-images.githubusercontent.com/31261230/34844406-355125bc-f6c6-11e7-988e-d91c87b09614.png)

### Reproducible Demo

https://github.com/satori-ytolstoguzov/rn-maps-callout-offset/tree/android-callout-text
Add your API key to `AndroidManifest.xml` and do `yarn install`.

**Comment by alvelig** [comment]
Both platforms?

**Comment by satori-ytolstoguzov** [comment]
Only android. On iOS callout has different issues

**Comment by satori-ytolstoguzov** [comment]
I just realized that it's not soft-wrapping. The text has width of the marker. Even if I remove some spaces it's still has same wrapping.

**Comment by alvelig** [comment]
Exactly. Wrapping Text in a View and setting width takes out this effect, doesn't it?

**Comment by satori-ytolstoguzov** [comment]
Yes. If I specify width - it's working, but it's not dynamic.

**Comment by satori-ytolstoguzov** [comment]
My goal is to have width of the callout that corresponds width of a text plus some margins. I don't know any good ways to calculate width of the text beforehand.

**Comment by rborn** [comment]
@satori-ytolstoguzov could you try to play with a combination of `minWidth`/`maxWidth` ?

**Comment by satori-ytolstoguzov** [comment]
@rborn As you suggested I played with it. It looks like `maxWidth` is ignored unless it's smaller than marker width, then it works like `width`. It's reversed for `minWidth`: if it's smaller than marker width - it's ignored, if it's bigger - it works like `width`. The width of the text is not dynamic anyway.

For example:

```js
<MapView.Callout tooltip style={{backgroundColor: 'red', minWidth: 100, maxWidth: 300}}><Text>This text should be one-liner</Text></MapView.Callout>
```

Result:

![screen shot 2018-01-12 at 10 50 51 am](https://user-images.githubusercontent.com/31261230/34890499-0342d0ae-f787-11e7-808a-60c4b38467e9.png)

**Comment by rborn** [comment]
@satori-ytolstoguzov  I was thinking to apply those on the Text, not Callout

**Comment by satori-ytolstoguzov** [comment]
It works strange. Notice that it has same height, but different width.

```
<MapView.Callout tooltip style={{backgroundColor: 'red'}}><Text style={{minWidth: 100, maxWidth: 400}}>This text should be one-liner</Text></MapView.Callout>
```
![screen shot 2018-01-12 at 2 34 19 pm](https://user-images.githubusercontent.com/31261230/34898148-5c3d1c22-f7a6-11e7-9129-1baebc857eb4.png)

```
<MapView.Callout tooltip style={{backgroundColor: 'red'}}><Text style={{minWidth: 0, maxWidth: 400}}>This text should be one-liner</Text></MapView.Callout>
```

![screen shot 2018-01-12 at 2 33 49 pm](https://user-images.githubusercontent.com/31261230/34898145-5607b196-f7a6-11e7-8cc1-4862e283113d.png)

**Comment by rborn** [comment]
Sorry, no more ideas here, maybe you could try to find a module that measures the text without rendering it.

**Comment by satori-ytolstoguzov** [comment]
Tried to do that. iOS do that easily, Android struggles with that same as JS.

**Comment by rborn** [comment]
ok, what about faking it? You know how many chars are in the text, what is the size of the widest char so you can multiply and get/set a width.
some text will have  a bigger padding, some less, but they will fit on one line.

if it's worth it, you could even make some calculations based on "thin" and "fat" chars.

**Comment by satori-ytolstoguzov** [comment]
We have also different fonts for iOS and Android, but it's doable. Thanks for the idea!

**Comment by alvelig** [comment]
```
private void wrapCalloutView() {
    // some hackery is needed to get the arbitrary infowindow view to render centered, and
    // with only the width/height that it needs.
    if (this.calloutView == null || this.calloutView.getChildCount() == 0) {
      return;
    }

    LinearLayout LL = new LinearLayout(context);
    LL.setOrientation(LinearLayout.VERTICAL);
    LL.setLayoutParams(new LinearLayout.LayoutParams(
        this.calloutView.width,
        this.calloutView.height,
        0f
    ));


    LinearLayout LL2 = new LinearLayout(context);
    LL2.setOrientation(LinearLayout.HORIZONTAL);
    LL2.setLayoutParams(new LinearLayout.LayoutParams(
        this.calloutView.width,
        this.calloutView.height,
        0f
    ));

    LL.addView(LL2);
    LL2.addView(this.calloutView);

    this.wrappedCalloutView = LL;
  }
```

**Comment by alvelig** [comment]
@satori-ytolstoguzov 
Here's the workaround:
```
<MapView.Callout tooltip>
          <View style={{ width: Dimensions.get('window').width }}>
            <View style={{ alignSelf: 'center', borderWidth: 1 }}>
            <Text style={{ alignSelf: 'center' }}>This text should be one-liner</Text>
            </View>
          </View>
        </MapView.Callout>
```
Results in:
<img width="310" alt="screen shot 2018-01-12 at 8 39 30 pm" src="https://user-images.githubusercontent.com/4231544/34899613-cb7425cc-f7d8-11e7-9e14-deb76c90828c.png">

**Comment by satori-ytolstoguzov** [comment]
@alvelig I found this place and played with layouts there but could not achieve what I wanted. I know nothing about android development.
Regarding you fix, I can't use it as is, because my app has a lot of markers close to each other, so tap on invisible part is quite possible and annoying.
I am thinking about combining what you proposed with solution from rborn and have calculated width of wrapping view. That can mitigate issue with tapping on invisible parts.

**Comment by alvelig** [comment]
@satori-ytolstoguzov I did a quick (~1 hour) review but did not find a fast way to fix that. Need to rework InfoWindow and see why the callout view is behaving itself as if it was `absoluteFillObject`, if I don't set width and height...

**Comment by XianWeiLook** [comment]
calloutCustomView: {
 flex:1,
position:'relative',
}

<callout style={styles.calloutCustomView} onPress={{}}>
<View style={{flex:1, padding:0}}>
 <Text></Text>
</View>
</Callout>

**Comment by ajbtechservices** [comment]
Why is this marked as closed? This still a bug....

**Comment by roachadam** [comment]
This is still an issue in 2024..not sure what do do I have spend hours on this stupid crap
