### ISSUE TITLE
When providing the custom map layer to MapView, map flickers on load.

### ISSUE THREAD

**Issue by saxenanickk** [react-native-community/react-native-maps#2001]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react: 16.0.0-alpha.12,
react-native: 0.48.3,

### Steps to Reproduce

1. Start the application.
2. You can notice a flickering in Map.

### Expected Behavior
Map should load with the custom map layer without flickering.

### Actual Behavior

Take a look at this: 
https://giphy.com/gifs/xT1Ra3GVr4RouOadWM/html5

**Comment by g3r4n** [comment]
@saxenanickk can you give a snippet of your code to reproduce the issue ? thank you !
