### ISSUE TITLE
Inconsistent Polygon Rendering (iOS/Android)

### ISSUE THREAD

**Issue by MichielDeMey** [react-native-community/react-native-maps#2025]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

   react-native: 0.53.0
    react: 16.2.0
	react-native-maps: 0.20.0

### Steps to Reproduce

1. Use a simple `<MapView>` component with a `<Polygon>` covering half the world.

```jsx
<MapView>
          <Polygon
            coordinates={
              [{
                longitude: 180,
                latitude: 90
              }, {
                longitude: 0,
                latitude: 90
              }, {
                longitude: 0,
                latitude: -90
              }, {
                longitude: 180,
                latitude: -90
              }, {
                longitude: 180,
                latitude: 90
              }]
            }
            strokeColor={'#ff0000'}
            fillColor={'rgba(0,0,0,0.5)'}
            strokeWidth={2}
          />
        </MapView>
```

### Expected Behavior

Polygon covers the right half the world on both iOS and Android.
The Polygon on Android is 'filled', same like on iOS.

### Actual Behavior

Polygon only covers the right half the world on iOS, partially covers the left side of the world on Android.

![screen shot 2018-02-13 at 11 50 18](https://user-images.githubusercontent.com/793406/36146669-b210bfaa-10b5-11e8-9ff4-3c4392bb53cf.png)
![screen shot 2018-02-13 at 11 50 41](https://user-images.githubusercontent.com/793406/36146668-b1f26b68-10b5-11e8-88cd-fc0d026400d7.png)

### Reproducible Demo

https://snack.expo.io/rJEdDBgvG

### Additional information

Initially, I wanted to create a polygon covering the entire world and then have holes in it to create a mask effect. However, the `<Polygon>` component does not seem to render the polygon covering the entire world, instead it's hidden.

Polygon covering the world:
```
<Polygon
            coordinates={
              [{
                longitude: 180,
                latitude: 90
              }, {
                longitude: -180,
                latitude: 90
              }, {
                longitude: -180,
                latitude: -90
              }, {
                longitude: 180,
                latitude: -90
              }, {
                longitude: 180,
                latitude: 90
              }]
            }
            strokeColor={'#ff0000'}
            fillColor={'rgba(0,0,0,0.5)'}
            strokeWidth={2}
/>
```

**Comment by socar-chef** [comment]
I made approximate and middle coordinates for mask.
And it works on me.

```
<Polygon
coordinates = {
[
    { latitude: -90, longitude: -179.99999999 },
    { latitude: 0, longitude: -179.99999999 },
    { latitude: 90, longitude: -179.99999999 },
    { latitude: 90, longitude: 0 },
    { latitude: 90, longitude: 179.99999999 },
    { latitude: 0, longitude: 179.99999999 },
    { latitude: -90, longitude: 179.99999999 },
    { latitude: -90, longitude: 0 },
    { latitude: -90, longitude: -179.99999999 },
  ]
}
```

**Comment by MichielDeMey** [comment]
@socar-chef Thanks, that seems to be a valid workaround for now!
