### ISSUE TITLE
IOS Build fails with native component "AIRMapCircle" does not exist

### ISSUE THREAD

**Issue by mobihunterz** [react-native-community/react-native-maps#2036]
### Is this a bug report?

Nope. It seems to be some configuration/installation issue. As steps followed for example setup worked and I can see Maps as well.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

I followed each and every bit of the installation instructions. I have installed npm package and setup podfile (pod install) and also put the GoogleMaps code inside AppDelegate.m. Still following the example setup instructions did very well and I was able to see maps for Demo project. However, I am not lucky enough to integrate maps in my Demo project.

### Environment

react-native: 0.53.0
react: 16.2.0
react-native-maps: 0.13.0

### Steps to Reproduce

1. Create React-Native project (react-native init ...)
2. npm install react-native-maps --save (For React-native maps integration) and followed installation steps for cocoaPods as well.
3. jscodeshift -t .../react-codemod-master/transforms/React-PropTypes-to-prop-types.js . (To use the new PropTypes module)
4. react-native run-ios (To run the project into iOS Simulator)
5. You will be seeing the error for "AIRMapCircle" does not exist

You can check the implementation of my demo: https://drive.google.com/open?id=11Rk4PEsaIbeDGUq9JX3iUOg06ByNnOAS

- Right now I have removed node_modules, pods and ios/build folders so you need to install all of these. However, the demo gives me the error.

### Expected Behavior

Maps should be loaded on screen as I have placed key in code.

### Actual Behavior

Throws error on launch "Invariant Violation: Native component for 'AIRMapCircle' does not exist"

### Reproducible Demo

https://drive.google.com/open?id=11Rk4PEsaIbeDGUq9JX3iUOg06ByNnOAS

Steps to reproduce:
1. Unzip the package and navigate to the directory in Terminal.
2. sudo npm install (sudo yarn install)
3. npm install react-native-maps --save (For React-native maps integration) and followed installation steps for cocoaPods as well.
4. cocoapods install
5. jscodeshift for PropTypes (jscodeshift -t .../react-codemod-master/transforms/React-PropTypes-to-prop-types.js .)
6. react-native run-ios

Please let me know proper solution for the issue. I have been following the installation guides and issues resolution guides since 3-4 days but I am not successfull.

Thanks a lot.

**Comment by rborn** [comment]
@mobihunterz Try to install the github version

**Comment by mobihunterz** [comment]
@rborn I cant get it. This is from github as well. Can you point me to the repository because I thought this one is the only suitable and authentic.

Thanks for prompt response.

Regards,
Paresh Thakor

**Comment by rborn** [comment]
In your package.json put 
~~~
 "react-native-maps": "https://github.com/react-community/react-native-maps.git",
~~~
and then run `yarn install`

Please let me know if it changes anything

**Comment by mobihunterz** [comment]
Hello @rborn,

Apologies for the late response but I was stuck a lot while processing your suggestion. It was some other issues but react-native was not working. So, I need to create a whole new project with map only.

I have put the suggestion you mentioned here and package.json is pasted below.

```
{
  "name": "LunchSpot",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.2.0",
    "react-native": "^0.49.5",
    "react-native-maps": "https://github.com/react-community/react-native-maps.git",
  },
  "devDependencies": {
    "babel-jest": "22.4.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

However, it still shows the same error. I tried reseting simulator and npm/yarn start with reset-cache and lots of other things as well but nothing helped.

Configuring in hybrid environment really stucks :(.

Thanks for the help.

**Comment by mobihunterz** [comment]
Hello,

Is there anyone to help me out this issue?

I am not able to integrate react-native-maps due to error mentioned above and I have followed numerous steps to resolve this but none helped.

Regards,
Paresh.

**Comment by mojotti** [comment]
@mobihunterz, Facing similar issue at the moment.

**Comment by mojotti** [comment]
For everyone who faced same problem that I did. Problem was that 'AIRMapOverlay' was not included _yet_ in react-native-maps version ^0.20.1. Solution was to use the master's version, like @rborn noted earlier.

**Comment by mojotti** [comment]
@mobihunterz if you go to Xcode and open Pods --> Development Pods --> react-native-maps, can you find files AIRMapCircles.h & AIRMapCircles.m from there? 

If not, you can try to delete your .xcworkspace project and install again according to instructions.

**Comment by hegelstad** [comment]
@mojotti I've changed the package.json to ` "react-native-maps": "https://github.com/react-community/react-native-maps.git"` and i ran `yarn install`. What other exact steps need to be done?

**Comment by mojotti** [comment]
@hegelstad, then just follow the installation instruction: https://github.com/react-community/react-native-maps/blob/master/docs/installation.md

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.
