### ISSUE TITLE
coordinateFromPoint not working

### ISSUE THREAD

**Issue by hanselsen** [react-native-community/react-native-maps#2038]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment

"react": "^16.0"
"react-native": "^0.51"
git+ssh://git@github.com/react-community/react-native-maps.git"

Tested on Android only

### Steps to Reproduce

1. Clone react-native-maps-master
2. Change example/examples/StaticMap.js
      - Add these props to `<MapView />`: 
```
    ref={r => this.map = r}
    onMapReady={() => {
        //this.map.coordinateForPoint(); not workingr, because it's coordinateFromPoint (documentation typo)
        this.map.coordinateFromPoint([0,0]).then(c => {
            console.log(c); //not resolved
        });
    }}
``` 

### Expected Behavior

I wish to get a coordinate for point 0,0 in the `then`

Also: documentation not correct. Name for coordinateFromPoint at [Methods](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#methods) is not correct while looking at the code.

### Actual Behavior

**An error occurs when executed:**
`TypeError: _reactNative.NativeModules.AirMapModule.coordinateFromPoint is not a function`

### Reproducible Demo

See; Steps to reproduce

**Comment by wasedaigo** [comment]
I cannot make it work either. The error I am receiving is 
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'apply' of undefined
```
I am using iOS

**Comment by g3r4n** [comment]
Got the same issue.
@danielgindi does your RCT_EXPORT_METHOD from AirMap should be in the AirMapManager ?
e.g like the takeSnapshot one ?

**Comment by wasedaigo** [comment]
@g3r4n you are right
@danielgindi At least this fixes iOS for me
https://github.com/wasedaigo/react-native-maps/commit/615975f438460f331dfbd611fb03f4dec285c55f

**Comment by danielgindi** [comment]
Hmm for some reason it works for me. Haven't seen the error. I can look into it, but I see that there's already a PR for fixing this :-)

**Comment by wasedaigo** [comment]
@danielgindi I think this does not happen if you are using GoogleMap

**Comment by Schabaani** [comment]
same issuse

**Comment by hanselsen** [comment]
@wasedaigo thanks. I look forward to the merge.

**Comment by wasedaigo** [comment]
@hanselsen currently the merge is blocked as we haven't tested the PR on Android. If you can confirm if it is working and leave a comment on the PR, we can merge that PR.

**Comment by rborn** [comment]
@hanselsen @Schabaani @danielgindi @g3r4n +1 if you could confirm it works ok on android. I won't be able to run a test of the PR very soon so I could use some help ❤️

**Comment by hanselsen** [comment]
@rborn at this moment I do not have the time. I will let you know later if @Schabaani or @danielgindi  or @g3r4n doesn't reply.

**Comment by g3r4n** [comment]
Sorry guys i don't have an android device.

**Comment by rborn** [comment]
Old issue, closing, please open a new one if you still have it

**Comment by rushant11** [comment]
@rborn 
@hanselsen 

![Screenshot_1732184411](https://github.com/user-attachments/assets/8b1b8340-589e-44d3-b275-67bcd6be8719)
The selected places are not pressable on the Android map. not getting coordinates in Android, in iOS, it works fine.
