### ISSUE TITLE
Feature Request: Provide `onUserLocationChange` for use with MapKit (iOS)

### ISSUE THREAD

**Issue by bramus** [react-native-community/react-native-maps#2055]
### Is this a bug report?

No, a feature request

_(Since it's a feature request I'm adjust some sections of the issue template because it's not really a good fit for this kind of issue)_

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

- iOS, Apple Maps
- All versions of all dependencies in any combination.

### Feature Request

With the merge of https://github.com/react-community/react-native-maps/pull/2032, a `onUserLocationChange` event became available but only for use with the Google map provider.

Reading the MapKit docs this kind of event can also be implemented with iOS's `MKMapView` by using [`mapView:didUpdateUserLocation:`](https://developer.apple.com/documentation/mapkit/mkmapviewdelegate/1452086-mapview?language=objc).

**Comment by rborn** [comment]
@bramus this? https://github.com/react-community/react-native-maps/pull/2032

**Comment by rborn** [comment]
@bramus fancy a PR ? 🤪

**Comment by 1uokun** [comment]
maybe [Geolocation.watchPosition() ](https://reactnative.cn/docs/0.51/geolocation.html#content)can be used to replace onUserLocationChange @bramus

**Comment by Taym95** [comment]
I would like to take this issue!

**Comment by ptrocki** [comment]
I would like to try implement it. is someone doing it ?

**Comment by rborn** [comment]
@ptrocki have a look in the current PRs, if you don't find anything related to it then go for it.
If you find something see if you can work on it and take it further ❤️
