### ISSUE TITLE
Update maps SDK to get last features

### ISSUE THREAD

**Issue by julienR2** [react-native-community/react-native-maps#2069]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.52.0
react: 16.2.0

### Question

I was checking out the release notes of the latest version of Google Maps when I found there was a new listener available: `OnMyLocationClickListener` [released on September 18 2017](https://developers.google.com/maps/documentation/android-api/releases#september_18_2017)

I made me wonder how I can get this feature to react-native-maps.. After trying to implement it on Android I got
```
error: cannot find symbol
import com.google.android.gms.maps.GoogleMap.OnMyLocationClickListener;
```

So I guess the lib doesn't refer the lastest realease of `com.google.android.gms.maps.GoogleMap` (`com.google.android.gms:play-services-maps` in the build.gradle ?) package, is it ?

I'm not really experienced with native Android dev yet, and don't quite get how to "update" to the lastest SDK and what are the implications for the lib.

If someone can put some lights on the topic or first hints, I would be keen to dig in and try to add this callback to the lib !

Thanks for your help.

**Comment by rborn** [comment]
this? https://github.com/react-community/react-native-maps/pull/2032

**Comment by julienR2** [comment]
@rborn #2032 is about `onMyLocationChange`, however I meant `onMyLocationClick` which is a "new" listener introduced on September 2017 release of GM SDK.

My question is more about how to update the GM SDK so we can access and implements these last features in react-native-maps ?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
