### ISSUE TITLE
AnimatedViews Pan is not working as expected.

### ISSUE THREAD

**Issue by efstathiosntonas** [react-native-community/react-native-maps#2076]
### Is this a bug report?

Yes

### Environment

    react-native: 0.54.0
    react: 16.3.0-alpha.1
    react-native-maps:  "0.20.1"

  Target Platform: iOS - 11.2 Simulator/iPhone 8 Plus, real device iPhone 7 11.2 // MapKit

### Steps to Reproduce

Using AnimatedViews, the PanResponder is not functioning well.

### Expected Behavior

Normal pan behavior, swipe left-right bottom-top

### Actual Behavior

PanResponder is not working well, as you see in gifs below I'm struggling to pan in both directions, left-right swipe, bottom-top. Even the red box dissapears if i drag to much to the bottom.

(Write what happened. Add screenshots!)

This is a demo from examples on real device:
![giphy1](https://user-images.githubusercontent.com/717975/37205253-cd5c6e0e-239c-11e8-914c-2775ac6781c6.gif)

This is demo from my project on real device:
![giphy](https://user-images.githubusercontent.com/717975/37205271-e176ef36-239c-11e8-8a21-dbaf551aa40a.gif)

In both situtations I'm doing normal gestures, swipe left - right, swipe bottom - top and vice versa.

**Comment by kay-es** [comment]
+1 got the same issue.

**Comment by HalvorMjoen** [comment]
+1

**Comment by meysam-70** [comment]
nobody solved this problem???????????

**Comment by ozican** [comment]
would you open the issue please? I  am facing same situation too.

**Comment by efstathiosntonas** [comment]
@ozican move on to https://github.com/archriss/react-native-snap-carousel/blob/master/README.md , it wont be hard to implement the exact same behavior with even better outcome.
