### ISSUE TITLE
Region coordinates not centered on Google Maps  

### ISSUE THREAD

**Issue by henninghall** [react-native-community/react-native-maps#2087]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "react-native": "0.53.0",
    "react": "16.2.0",
    "react-native-maps": "0.20.1",

### Steps to Reproduce

1. Render a Marker at the coordinates received from onRegionChangeComplete
2. Add provider='google'
3. Zoom out on map as much as possible. 
4. Notice how the marker is not in the center of the screen.  

### Expected Behavior

- I expect the marker to be in the center on both apple maps and google maps. In other words:
- I expect the map to return the center coordinate in onRegionChangeComplete and onRegionChange

### Actual Behavior

On apple maps (without provider="google" on iOS devices) the returned coordinate from onRegionChangeComplete/onRegionChange is always centered in the screen (as expected). Using Google maps it is not centered while zooming out. The error/offset gets unnoticeable while zoomed in or at the equator. 

**Apple maps vs Google maps:**
Purple marker indicates actual center of map. Red marker indicates coordinates received.  

<img src="https://user-images.githubusercontent.com/1652607/37279344-d3b98bc4-25ea-11e8-8c05-0f728f7df929.png" width="40%" style="float:left;"> <img src="https://user-images.githubusercontent.com/1652607/37279355-d84ce7e4-25ea-11e8-98df-d771ecef8d7f.png" width="40%" style="float:left;">

### Reproducible Demo
```

import React, { Component } from 'react';
import { Dimensions, View, StyleSheet } from 'react-native';
import MapView, { Marker } from 'react-native-maps';

export default class App extends Component {

  state = {
    region: {
      latitude: -100,
      longitude: 0,
      latitudeDelta: 10,
      longitudeDelta: 10,
    },
    marker: {
      latitude: 0,
      longitude: -100,
    }
  };

  onRegionChange = (region) => {
    this.setState({
      region,
      marker: {
        latitude: region.latitude,
        longitude: region.longitude,
      }
    });
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <MapView
          onRegionChangeComplete={this.onRegionChange}
          style={{ flex: 1 }}
          initialRegion={this.state.region}
          provider='google'
        >
          <Marker coordinate={this.state.marker} />
        </MapView>
        <View style={styles.dot} />
      </View>
    );
  }
}

const { height, width } = Dimensions.get('window');
const dotSize = 10;

const styles = StyleSheet.create({
  dot: {
    width: dotSize,
    height: dotSize,
    position: 'absolute',
    top: (height - dotSize) / 2,
    backgroundColor: 'blue',
    left: (width - dotSize) / 2
  }
});
```

I am also  interested to find a workaround to get the actual center coordinate if anyone has an idea. Thanks! 

I have tried a workaround using coordinateForPoint to check the center coordinate at each regionChange but I can't successfully get it to work with google maps on iOS.

**Comment by nthgol** [comment]
+1 i noticed this behavior sporadically

**Comment by pedro** [comment]
Oof, same issue here, having a hard time debugging this one.

Odd how the `mapPadding` prop seems to compound the problem, essentially shifting the region passed to `onRegionChange` 🤔 

Let me know of any ideas/workarounds!

**Comment by vshabanov1995** [comment]
Notices such behavior too

**Comment by hennzen** [comment]
Experiencing this behaviour, too:
when zooming in through `<MapView>`'s `animateToRegion()` method (triggered by a button), I create a new `zoomToRegion` object by leaving the current `longitude` and `latitude` values untouched while dividing the deltas by two. Same effect: the region moves into the direction of the equator.

I visualized my region and center point on http://geojson.io, and even there the center point seems out of center. My gut feeling tells me this is due to mercator projection distorting latitude. Have a look at
https://de.wikipedia.org/wiki/Mercator-Projektion#/media/File:Mercator-proj.png

Imagine a rectangle close to the pole and take its *calculated* latitude center point. It's visually off-center. Citing [Wikipedia](https://en.wikipedia.org/wiki/Mercator_projection): "the Mercator projection distorts the size of objects as the latitude increases from the Equator to the poles"

Maybe a `coordinateForPoint()` (https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#methods) could do the trick to grab a "visual" center point? Will try.

**Comment by hennzen** [comment]
`coordinateForPoint()` is currently broken https://github.com/react-community/react-native-maps/issues/2578
Working workaround demo here: https://snack.expo.io/@hennzen/zoom-to-visual-center
See README.md for details

**Comment by berkayakks** [comment]
i am still facing this problem. Has anyone found a new solution? This is very important for me

**Comment by mvrty** [comment]
If anyone else ends up here, had problems with this as well. Try adding `paddingAdjustmentBehavior="never"` to MapView (says it's default in docs but doesn't seem that way?)

**Comment by panpan31415** [comment]
> If anyone else ends up here, had problems with this as well. Try adding `paddingAdjustmentBehavior="never"` to MapView (says it's default in docs but doesn't seem that way?)

It is working well on Android, but on iOS you have to add paddingAdjustmentBehavior="never" to make it work.
