### ISSUE TITLE
AIRGoogleMapLocalTile does not exist.

### ISSUE THREAD

**Issue by floorswinkels** [react-native-community/react-native-maps#2088]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native:  0.50.0
    react-native-maps: 0.20.1
   target is iOS and using GoogleMaps

### Steps to Reproduce

1. using iOS
2. using Google Maps SDK
3. using LocalTile

### Expected Behavior

Load local generated tiles and place them on the map.

### Actual Behavior

<img width="336" alt="screen shot 2018-03-12 at 13 58 44" src="https://user-images.githubusercontent.com/4542567/37293466-a542061c-2613-11e8-83a3-6c5fb38a7d8c.png">

**Comment by hanselsen** [comment]
+1 please introduce this in a next version.

**Comment by rborn** [comment]
@floorswinkels @hanselsen try the git version please and let us know

**Comment by floorswinkels** [comment]
@rborn with the git version it's still not working.

When I switch to Apple's mapkit LocalTile is working. ( But in our case we need Google Map SDK )

**Comment by rborn** [comment]
@floorswinkels can you please set a small test/demo repo? because we have this https://github.com/react-community/react-native-maps/pull/1876 which should work. 
So maybe it's a mistake somewhere in the PR (unless I'm totally getting wrong 😹)

**Comment by ahmetabdi** [comment]
Same issue here

**Comment by ahmetabdi** [comment]
Failing on this line https://github.com/react-community/react-native-maps/blob/f553317fcaa2e3a4889f38c4bb2e215693f3f20c/lib/components/MapLocalTile.js#L46

**Comment by merryejik** [comment]
I have the same issue :(

**Comment by rborn** [comment]
@merryejik did you try with the master version ?

**Comment by merryejik** [comment]
@rborn the same :(

**Comment by locales-wellington** [comment]
the same :(

**Comment by simon4321** [comment]
Any updates on this?

**Comment by ahmetabdi** [comment]
@simon4321 are you using master or on an expo project?

**Comment by simon4321** [comment]
@ahmetabdi I'm using latest npm version without expo.

**Comment by simon4321** [comment]
@ahmetabdi tried with master as well. same issue :(

**Comment by simon4321** [comment]
Works fine with Apple Mapkit

**Comment by hariDasu** [comment]
the problem with using appleMapKit for local tiles is that many developers, such as myself, want  to use local tiles to render tiles when the client's device (ios or android) is OFFLINE.  I am unsure how this will work if the map initializes first with MapKit then loads the tiles on top when network connectivity is not available. I wish Apple would just enable a `NONE` property for MapKit, that would really greatly reduce this trouble. I have yet to configure and get the iOS to use Google Maps as the default Map without running into countless AIRMAPS not found errors.

**Comment by sinodko** [comment]
any update on this one?

**Comment by sinodko** [comment]
I found this as temporary solution... We can use UrlTile as LocalTile, we just need to add `file://` prefix to the tile's path.

    <MapView {...props}>
        <UrlTile urlTemplate={this.offlineTilesPath} zIndex={-1} />
    </MapView>

**Comment by rborn** [comment]
Closing as there is #2733 with better explanations.
