### ISSUE TITLE
Heavy UI FPS decrease just moving/panning around the map.

### ISSUE THREAD

**Issue by GonzaloRecioG** [react-native-community/react-native-maps#2092]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.51.0
    react: 16.0.0
    react-native-maps: 0.21.1
    Target Platform: iOS, iPhone 6 10.3
    Both AppleMaps + GoogleMaps

### Steps to Reproduce

Just an empty map rendered with no markers, pan around the map to see how the UI thread drops.

1. Go to the Map
2. Pan/Drag/Move Around
3. See UI thread FPS decrease

### Expected Behavior

It shouldn't drop to <10FPS when panning/dragging/moving around the map.

### Actual Behavior

It drops to <10FPS when panning/dragging/moving around the map.

### Reproducible Demo

![alt text](https://media.giphy.com/media/6tWWQNkYP1NQvH5qQF/giphy.gif "Demo")

**Comment by GonzaloRecioG** [comment]
Any update on this?

**Comment by declandowling** [comment]
I'm still experiencing this issue using:
- react: 16.3.1
- react-native: 0.55.2
- react-native-maps: 0.21.0

I've run a blank project with just a map and the UI thread drops to as low as 4 when moving around the map.

**Comment by rborn** [comment]
No reply, closing

**Comment by huuthinh245** [comment]
i have the same issue just no marker when i zoom or pan on map .  how the UI thread drops.  until 1 2 second the fpt turn 60.  @rborn  suggest add tracksViewChanges={false} for marker but I don't add marker on map. How can i fix it? thanks

**Comment by hzburki** [comment]
I have the same issue. FPS drops like crazy while zooming and panning the map. The map is empty with no markers. 

##Environment
```
react-native: 0.58.0
react: 16.6.3
react-native-maps: 0.25.0
Target Platform: iOS Simulator iPhone X, iPhone 6s and iPhone 7 Plus
Both AppleMaps + GoogleMaps
```

All the other specifications are same as in the original question

**Comment by huuthinh245** [comment]
@hzburki  i think you should on real device

**Comment by alperenkarip** [comment]
#4663

**Comment by Santosl2** [comment]
Any updates??

**Comment by MariuzM** [comment]
Still same, this maps does not feel smoth like using google maps app. zoming and panning even if it shows 59-60 just feels off feels like 30
