### ISSUE TITLE
ShowUserLocation shows even if it was set to false

### ISSUE THREAD

**Issue by LorandP** [react-native-community/react-native-maps#2116]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
Android 7.0 and 8.0
    react-native: 0.53.0
    react: 16.2.0
    react-native-maps: 0.17.0 

### Steps to Reproduce

1. Set the following properties:
          showsUserLocation={true}
          showsMyLocationButton={false}
          toolbarEnabled={false}
          showsScale={false}
          showsTraffic={false}
          showsCompass={false}
2. Open the mapview
3. Navigate on the map for 1/2 minutes

### Expected Behavior

The showUserLocation button should not appear

### Actual Behavior

The user location button appears. It is pretty hard to reproduce tough. It doesn't appear every time.

**Comment by 39otrebla** [comment]
Also, it is not possible to NOT ask user location on iOS. We have an use case where we absolutely don't need user location and we found no way to avoid the permission request!
This didn't worked:

```javascript
<MapView
  style={{ flex: 1 }}
  ref={this.setMapRef}
  showsUserLocation={false}
  followsUserLocation={false}
  showsMyLocationButton={false}
  initialRegion={this.props.region} />
```

We also tried removing `NSLocationWhenInUsageDescription`, but app crashes with the following error:
>Either NSLocationWhenInUsageDescription, NSLocationAlwaysUsageDescription or NSLocationAlwaysAndWhenInUsageDescription key must be present in Info.plist to use geolocation

The above error is raised by `RCTLocationObserver.m:407` , so it seems that this module calls native `getCurrentPosition` method on mount without taking care of whether user-position-related props are set to `false`.

**Comment by BenBach** [comment]
same problem here. Did you find a solution @39otrebla ? Any help appreciated :-)
