### ISSUE TITLE
Button (TouchableOpecitiy) places on top of map, randomly stopes functioning after map scroll 

### ISSUE THREAD

**Issue by mcmatan** [react-native-community/react-native-maps#2122]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "react-native": "0.54.0-rc.3",
    "react-native-maps": "^0.20.1",

### Steps to Reproduce

When placing buttons (TouchableOpecitiy) on top of the map, after some scroll and zoom, buttons stop responding.
I can still see them, and if they are placed inside a scrollView, scroll view still responses, but "onPress" stops receiving events

(Write your steps here:)

render () {
    return (
      <View>
        <MapView
          provider={PROVIDER_GOOGLE}
          style={styles.map}
          customMapStyle={RetroMapStyles}
          showsUserLocation
          region={this.state.region}
          onPress={() => {
            console.log(this.myMarker)
            console.log(this.map)
          }}
          ref={view => this.map = view}
        >
          <MapView.Marker
            ref={view => { this.myMarker = view }}
            coordinate={this.state.region}
            onLayout={event => {
              const layout = event.nativeEvent.layout
              console.log('height:', layout.height)
              console.log('width:', layout.width)
              console.log('x:', layout.x)
              console.log('y:', layout.y)
            }}

            onDragEnd={() => console.log('wwd')}
          />
        </MapView>
        <ScrollWithButtons dataSource={this.dataSource} />
        <View style={styles.innerComponent}>
          <NavigationBar
            text={I18n.t('AppTitle')}
            rightChild={<MenuButton />} />
        </View>
      </View>
    )
  }
}
const styles = StyleSheet.create({
  map: {
    height: '100%',
    width: '100%',
    zIndex: -1
  },
  container: {
    width: '100%',
    height: '100%'
  },
  innerComponent: {
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 1000
  }
})

### Expected Behavior

Buttons (TouchableOpecitiy) will continue to receive onPess event

### Actual Behavior

Buttons stop receiving onPress events

**Comment by buraksak35** [comment]
I have same issue did you solve this?
