### ISSUE TITLE
Auto zoom on user position on the device not on emulator (iOS)

### ISSUE THREAD

**Issue by mickaelw** [react-native-community/react-native-maps#2142]
The MapView's props showsUserLocation and followsUserLocation are set on true.
I would like use an initialRegion with a big lat & long delta.

The emulator that's work great but when I build on my iPhone after the map loading, there is a zoom in on the user location and my deltas is ignored.

- RN 0.54
- RN Maps 0.20.1

**Comment by Kirill23** [comment]
Having same issue. I managed to reproduce it on both phone (11.3) and simulator (11.3)... 
Looks like there is default zoom that comes with follow user location option. 
Quick workaround that I found is to disable followsUserLocation and use onUserLocationChange or have listener in your navigator.geolocation.watchPosition that will trigger map's method this.map.animateToRegion with coordinates and required zoom...
