### ISSUE TITLE
Mapbox/Super Cluster: Callout behind markers

### ISSUE THREAD

**Issue by GarimaMathur07** [react-native-community/react-native-maps#2147]
### Is this a bug report?

(No)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Yes)

### Environment

react-native: 0.45.1      
react: 16.0.0-alpha.12
react-native-maps: 0.17.0
AppleMaps
### Steps to Reproduce

I have about 600 markers. So, i am using https://github.com/novalabio/react-native-maps-super-cluster uses MapBox's SuperCluster https://github.com/mapbox/supercluster as clustering engine. I am facing **Callout behind markers** issue. I am using `renderMarker` with `ClustererdMapView` as follows:

```
<ClusteredMapView
			style={styles.map}
			data={this.state.pins}
			ref={o => (this.mapRef = o)}
		        renderMarker={this.renderMarker}
			renderCluster={this.renderCluster}
			fitToElements={ClusteredMapView.ANIMATED_FIT}
			edgePadding={styles.edgePaddingStyle}
			clusteringEnabled={true}
			initialRegion={{
						latitude: this.initialRegionLat,
						longitude: this.initialRegionLong,
						latitudeDelta: this.LATITUDE_DELTA,
						longitudeDelta: this.LONGITUDE_DELTA
					        }}/>

```
```
renderMarker (pin) {
	const styles = this.styleSheet();
	return (
		<Marker
			key={pin.id || Math.random()}
			coordinate={pin.location}
			ref={o => (this.marker = o)}
			calloutOffset={{ x: -8, y: 28 }}
			calloutAnchor={{ x: 0.5, y: 0.4 }}
			onCalloutPress={() => this.onPressCallout(pin)}
			image={map_pin.source}
		>
			<Callout tooltip style={styles.customCalloutView}>
				<LocationMarkerCallout title={pin.storeloc.name} description={pin.storeloc.address} />
			</Callout>
		</Marker>
	);
};
```
@alvelig Can you please suggest how can i resolve this issue.

### Expected Behavior

Callouts would not be hide behind markers.

### Actual Behavior

(Callout is hidden behind markers
![33765393-4e432e4a-dc21-11e7-8cb4-a44d8521a506](https://user-images.githubusercontent.com/7220882/38171151-1588e970-35b1-11e8-85e1-72fbdc383563.png)
 )

**Comment by alvelig** [comment]
```
react-native-maps: 0.17.0
```
Use maps from master and let us know.

**Comment by GarimaMathur07** [comment]
Thanks for the reply 👍 Is there any workaround in `react-native-maps: 0.17.0`  for support of `react-native 0.45.1` using zIndex.

**Comment by IgorVanian** [comment]
As far as I know, **react-native-maps-super-cluster** is using **react-native-maps@0.20.1**. How are you using 0.17 with it?
