### ISSUE TITLE
Marker's description don't change instantly

### ISSUE THREAD

**Issue by pnthach95** [react-native-community/react-native-maps#2160]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.48.4
react: 16.0.0-alpha.12
react-native-maps: 0.21.0

### Steps to Reproduce

```
<MapView
...>
    {this.state.data
    ? this.state.data.map((gara, index) => (
        <MapView.Marker
            key={index}
            image={this.state.selectedMarkers[gara.id] ? require('../../../assets/images/marker-65x87-inverted.png') : require('../../../assets/images/marker-65x87.png')}
            coordinate={{
                latitude: Number(gara.lat),
                longitude: Number(gara.long)
            }}
            title={gara.name}
            description={'Available: ' + gara.current_bike}
            onPress={() => {
                // Get data from server then setState(data)
                this.getData(gara.id);
            }}
         >
                  <View style={{
                    flex: 1,
                    justifyContent: 'center',
                    alignItems: 'center',
                    width: 35, height: 35,
                  }}>
                    <Text style={{ color: this.state.selectedMarkers[gara.id] ? 'orange' : 'white' }} >
                      {gara.current_bike > 99 ? `99+` : gara.current_bike}
                    </Text>
                  </View>
                </MapView.Marker>
              ))
            : null}
</MapView>
```

### Expected Behavior

When I press a marker, it will get data from server and setState(data), decription and text should be the same when gara.current_bike from server is changed.

### Actual Behavior

Decription and text aren't the same. The text changed, decription was still old state.

![screenshot_20180403-203033](https://user-images.githubusercontent.com/31266357/38253215-47ce2028-3780-11e8-81f5-a5c7a73636bf.png)

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
