### ISSUE TITLE
App Crashes when MapView.Circle center longitude is 181

### ISSUE THREAD

**Issue by BatDroid** [react-native-community/react-native-maps#2167]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.48.2
    react: 16.0.0-alpha.12
    react-native-maps: 0.21.0

### Steps to Reproduce

(Write your steps here:)

1. followed the [installation instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)
2. followed the [instruction](https://github.com/react-community/react-native-maps/blob/1e71a21f39e7b88554852951f773c731c94680c9/docs/installation.md#option-2-cocoapods)(option 2) for google map in ios.
3. use google map in ios

### Expected Behavior

show the circle in expected coordinate like when it is on apple map.

### Actual Behavior

app crashes in AirGoogleMap.m not in react native dev console without any error log!
only in this coordinate and some others the app crashes. (eg: whole asia, europe,... is fine)
there is no problem when i give this coordinate to Marker but for Circle while the map is google map (not the apple map) the app crashes.

### Reproducible Demo

         <MapView
                ref={ref=> {this.map = ref}}
                provider={PROVIDER_GOOGLE}
                style={Styles.map}
                initialRegion={this.getInitialState()}
                onRegionChange={this.onRegionChange.bind(this)}
                onRegionChangeComplete={ region => this.setState({region}) }
            >
                <MapView.Circle
                    center={{longitude: 181,latitude: 40}}
                    radius={2000 * this.state.region.longitudeDelta}
                />
            </MapView>

**Comment by jstheoriginal** [comment]
The valid range of latitude in degrees is -90 and +90 for the southern and northern hemisphere respectively. Longitude is in the range -180 and +180 specifying coordinates west and east of the Prime Meridian, respectively.

**Comment by BatDroid** [comment]
@jstheoriginal actually my problem is a little bit different. the longitude/latitude is received from the `onRegionChange` method( since i want the circle follow user movement) and when user move to this location, the ios app crashes and when i logged the amount it showed me this number.

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.

**Comment by TierryBr** [comment]
Still the same problem, if you create a very large radius, for example in the entire screen state a very large length, and when displaying this on iOS it crashes, the same does not happen on Android
