### ISSUE TITLE
error while run android in(Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.)

### ISSUE THREAD

**Issue by ariya94** [react-native-community/react-native-maps#2188]
hi
i install react native map and when i run-android i get this error
![capture1](https://user-images.githubusercontent.com/32795414/38661445-220d0012-3e46-11e8-9c0d-22802fac0ac3.PNG)
how can i fix this??

**Comment by nazrdogan** [comment]
I was facing same issue. Just follow this guide. 
https://gist.github.com/nazrdogan/87c63e89a2bfd4cefee24990e4e7ed0e

**Comment by moseslucas** [comment]
same here. I have the same issue

**Comment by ariya94** [comment]
@nazrdogan I did all the steps but i get error
![capture2](https://user-images.githubusercontent.com/32795414/38671932-0aa0002a-3e62-11e8-8638-3aafc6165846.PNG)

**Comment by nazrdogan** [comment]
@ariya94 
```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

Did you add `google()` ?

**Comment by deorukhkarchaitanya** [comment]
Do https://github.com/react-community/react-native-maps/issues/2188#issuecomment-380757839

Make sure your gradle-wrapper.properties has 

**distributionUrl = https\://services.gradle.org/distributions/gradle-4.1-all.zip**

and your app/build.gradle has

**implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-base:10.0.1'
    implementation 'com.google.android.gms:play-services-maps:10.0.1'**

**Comment by moseslucas** [comment]
Okay I got it. The problem is that, the latest `react-native-maps` is using syntax for **Gradle 3**.
So we get that error. to fix it, either **Update gradle 3 ** or hack the `react-native-maps` package inside `./node_modules`. Yup, inside `./node_modules` and change the `build.gradle`  and replace:

`compileOnly` -> `provided`
`implementation` -> `compile`

**Comment by deorukhkarchaitanya** [comment]
Yes. Personally I'd prefer if we moved back to Gradle 2. Because most of the other packages are on Gradle 2. I'll have to generate an APK and put it through testing to see if anything is breaking.

**Comment by JohnStratoudakis** [comment]
Does anybody know how to fix this for the examples that come bundled with react-native-maps?

**Comment by ariya94** [comment]
@nazrdogan 
yes add it but still i have an error for google ()

**Comment by ariya94** [comment]
@deorukhkarchaitanya 
i done those but get this error
![capture3](https://user-images.githubusercontent.com/32795414/38764515-cbb53320-3fc5-11e8-908d-cdc0846ae181.PNG)

**Comment by ariya94** [comment]
@nazrdogan 
@deorukhkarchaitanya 
thanks guys
my problem solved
i change the build tools to 26.0.2 and solve
but build tools 26.0.2 can be a problem for other components like (nativebase , ...)

**Comment by nazrdogan** [comment]
@ariya94  I think its not problem for `nativebase`, but can be problem other native plugin. I added my app `react-native-camera ` its makes problem for me and I used this guide.

 https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by stevemu** [comment]
I created an empty project to test the official instruction for Android, it didn't work. I tried every solution listed here but they don't work for me. 
![image](https://user-images.githubusercontent.com/7694000/38845550-ec12ff7e-41c5-11e8-944a-556ac49dda58.png)

**Comment by ariya94** [comment]
@stevemu 
did add implementation method in app/build.gradle?

**Comment by raktec** [comment]
Does anybody know step by step add react-native-maps in android?
its working in mu ios app but lot of effort in android  but not successful.

**Comment by nazrdogan** [comment]
my app working fine with this steps.
 https://gist.github.com/nazrdogan/87c63e89a2bfd4cefee24990e4e7ed0e

**Comment by stevemu** [comment]
I may have found a solution. In my test project, the newest version of the map (^0.21) with newest react native (0.55.2) works under iOS. But under Android, I had to use map 0.20.1 with newest react native version. So what I had to do is have the Android side use map 0.20.1, while the iOS can use the newest map version. 

To that, I copied the map 0.20.1 to an separate folder. eg /older_modules/react-native-maps_0.20.1, then in settings.gradle, reference this older version:

```
rootProject.name = 'androidMapTest'

include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../older_modules/react-native-maps_0.20.1/lib/android')


include ':app'
```

**Comment by moseslucas** [comment]
So after researching, trial and error I was able to make my maps work, with updated gradle version 3 and building a signed apk successfully.

So I wrote a tutorial on how to install and use the latest `react-native-maps` on your project.
Follow the guide/tutorial here: https://medium.com/@lukeses09/install-react-native-maps-with-gradle-3-on-android-44f91a70a395

**Comment by rborn** [comment]
@moseslucas aren't the installation docs accurate? if so maybe you can participate with a PR ? 🤗

**Comment by moseslucas** [comment]
@rborn  the installation doc is accurate but there wasn’t any note to upgrade grade to version **2** in order for `react-native-maps` to work. 

It’s aso worth noting that in the docs, using `react-native link` is discouraged. But actually we can still use it, then just add just the few remaining configs that wasn’t included in the link instead. That way, tha installion/setup is faster.

**Comment by rborn** [comment]
I agree we can use link, however it breaks if you wanna use google maps on ios. If anybody can fix this I'm all for it

**Comment by moseslucas** [comment]
I agree, since the tutorial I made is only for **Android**, using `react-native link` might not be advisable if you're also developing for iOS. I hope `react-native` update it's out of the box gradle version to 3 in the future.

**Comment by moseslucas** [comment]
@raktec I made a step-by-step guide installation of `react-native-maps` with the fix for gradle 3 [here](https://medium.com/@lukeses09/install-react-native-maps-with-gradle-3-on-android-44f91a70a395).

**Comment by LucasLpr** [comment]
@moseslucas I followed your step-by-step guide, but now when I assemble my app to make an apk, the build is successfull but when I install the apk it says : "App Not Installed".
(I don't have this app already installed on my smartphone, and I tried with others smartphones same thing)

**Comment by KarimFereidooni** [comment]
You can fix this by navigating to node_modules/react-native-maps/lib/android/build.gradle and changing these lines

    compileOnly "com.facebook.react:react-native:+"
    implementation "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
    implementation "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
    implementation "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"

to

    provided "com.facebook.react:react-native:+"
    compile "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
    compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
    compile "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"

**Comment by LucasLpr** [comment]
Didn't fix anything :/ Cannot build the app ... Only working in dev mode ...

my build.gradle /app :
```
dependencies {
    implementation(project(':react-native-onesignal'))
    implementation(project(':react-native-intercom'))
    implementation "io.intercom.android:intercom-sdk:3.+"
    implementation(project(':react-native-linear-gradient'))
    implementation(project(':react-native-i18n'))
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-base:+'
    implementation 'com.google.android.gms:play-services-maps:+'
}

```

```
android {
    lintOptions {
        abortOnError false
    }
    compileSdkVersion 26
    buildToolsVersion "26.0.1"

    defaultConfig {
        applicationId "com.xxx"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
...
```

**Comment by RyanThomas73** [comment]
I attempted to follow the many links/guides to updating to gradle v4 + android gradle plugin v3 only to find gradle then blows up attempting to pull in my other react-native dependencies which are still targeting the android gradle plugin v3 syntax.

**Comment by leofontes** [comment]
@RyanThomas73 follow @KarimFereidooni suggestion, worked for me!

**Comment by koswarabilly** [comment]
@RyanThomas73 follow @KarimFereidooni , it works for me too!

**Comment by amed** [comment]
#### Building hack-script:

- run `$ yarn add replace-in-file --dev`
- create a file `scripts/react-native-maps-hack.js` with the content:
```
const replace = require('replace-in-file')
const file = './node_modules/react-native-maps/lib/android/build.gradle'
const options1 = {
  files: file,
  from: /compileOnly/g,
  to: 'provided'
}

const options2 = {
  files: file,
  from: /implementation/g,
  to: 'compile'
}

replace(options1)
  .then(changedFiles => {
    console.log('modified compileOnly:', changedFiles)
  })
  .catch(error => {
    console.error('Error occurred:', error)
  }).then(
    () => {
      replace(options2)
        .then(changedFiles => {
          console.log('modified implementation:', changedFiles)
        })
        .catch(error => {
          console.error('Error occurred:', error)
        })
    }
  )
console.log('react-native-maps is fixed!')

```

- run `$ node scripts/react-native-maps-hack.js` **at the root of the project.**


**Optional:**

You can add the previous hack to `scripts` to feel the luxury that node grant. 
in `package.json` in `scrpits` add:
```
"react-native-maps-hack": "node scripts/react-native-maps-hack.js",
```
run `$ yarn run react-native-maps-hack` to get the code running.

**Comment by goliath45** [comment]
Then you much help me please ?

**Comment by ProMasoud** [comment]
There are two working solution for this issue

solution 1.
easily update gradle version to 3

solution 2. 
change `./node_modules/react-native-maps/lib/android/builg.gradle`

`compileOnly ` --> `provided`
`implementation` --> `compile`

**Comment by jamesone** [comment]
@KarimFereidooni I tried doing this but after trying to build my project I get:

```
Conflict with dependency 'com.android.support:support-v4' in project ':react-native-maps'. Resolved versions for compilation (26.1.0) and packaging (24.0.0) differ. This can generate runtime errors due to mismatched resources.
:react-native-maps:prepareDebugDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:prepareDebugDependencies'.
> Dependency Error. See console for details.
```

You can see the forked `react-native-maps` repo I'm using here: https://github.com/jamesone/react-native-maps/tree/rm-airgooglemaps - I forked off of @mikemorris PR which adds support for using `react-native link` so we don't need to use Carthage (note: The fork contains the most recent rn-maps changes).

Sidenote: iOS works flawlessly

**Comment by mikemorris** [comment]
@jamesone You could try excluding the `com.android.support:support-v4` library from react-native-maps like to default to using the version supplied by what I'm guessing is another package.
```
compile(project(':react-native-maps')){
      exclude group: 'com.android.support', module: 'support-v4'
})
```

Alternatively, you could try something like https://github.com/react-native-community/react-native-camera/issues/1532#issuecomment-392081796 to force resolution to a particular version of `com.android.support:support-v4` for all packages.

**Comment by jamesone** [comment]
@mikemorris I tried adding:

```
compile(project(':react-native-maps')){
      exclude group: 'com.android.support', module: 'support-v4'
})
```

but it didn't work. It threw the exact same error as listed here: https://github.com/react-community/react-native-maps/issues/2188#issuecomment-413134041

----

Here is my `build.gradle`:

```gradle
// Tried this, but it doesn't work same v4- support error
    compile (project(':react-native-maps')) {
        exclude group: 'com.android.support', module: 'support-v4'
    }

    // 1. ALSO TRIED THIS:
    //    compile(project(':react-native-maps')) {
    //        exclude group: 'com.google.android.gms', module: 'play-services-base'
    //        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    //    }
    // 2. ALSO TRIED THIS:
    // compile project(':react-native-maps');

    // Tried this, but it doesn't work same v4- support error
    compile ("com.android.support:support-v4:26.0.1") {
        force = true //<-- force dependency resolution to 26.0.1 in my case
    }

    compile fileTree(dir: "libs", include: ["*.jar"])
    compile ("com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}")
    
    // From previous RN version (0.55) - Tried this, but it doesn't work same v4- support error
    // compile('com.android.support:appcompat-v7:23.0.2') {
    //     exclude group: 'com.google.android.gms', module: 'play-services'
    // }

    compile('com.google.android.gms:play-services-base:+') {
        force = true;
    }
    compile('com.google.android.gms:play-services-maps:+') {
        force = true;
    }

    


    // compile "com.facebook.react:react-native:+" // RN 0.56 upgrade line
    // from node_modules
    compile('com.facebook.react:react-native:+') {
        exclude group: 'com.google.android.gms', module: 'play-services'
    }
    compile 'com.android.support:multidex:1.0.1'
```

**Comment by Richi2293** [comment]
Hi, any news?

**Comment by epeli** [comment]
Here's a [patch-package](https://www.npmjs.com/package/patch-package) patch

https://gist.github.com/epeli/f7a518f22c485d0cb9c7eb1b12d63631

from the node_modules/gradle.build workaround https://github.com/react-community/react-native-maps/issues/2188#issuecomment-385420099

**Comment by jamesone** [comment]
Here is what my native android files look like:


`app/Build.gradle -> dependencies {:`

```
....
  compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
....
```

build.gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

task wrapper(type: Wrapper) {
    gradleVersion = '4.4' //version required
}

buildscript {
    repositories {
        /**
         * Must stay in this order
         */
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
            }
        }
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "$rootDir/../node_modules/react-native/android" }
        mavenCentral()
    }
}

ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```

Once this in place, you'll need to:

1. Install `gradle` (if you haven't already) (you can do this via brew)
2. `cd android`
3. `gradle wrapper`
4. Once `gradle wrapper` has successfully ran
5. `./gradlew assemble` 

This is what I had todo to get mine working

Check this answer here for more details: https://stackoverflow.com/a/27982996/4140346

**Comment by Oneted11** [comment]
I got this error among others that were similar, I just changed compile to implementation in the apps build.gradle and it suddenly started building again. I'd suggest to start with that

**Comment by akhileshsinha06** [comment]
Best Solution --
https://github.com/react-native-community/react-native-camera/issues/1490#issuecomment-381852316

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
