### ISSUE TITLE
Marker [animateMarkerToCoordinate] error

### ISSUE THREAD

**Issue by Norris1z** [react-native-community/react-native-maps#2195]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes
### Steps to Reproduce

1. Create a `Marker` 
2. Assign a variable to the `ref`
3. Try to animate the marker to a given coordinate using the `animateMarkerToCoordinate`  method.

### Expected Behavior

The `Marker` will animate (move) to the new cordinates`

### Actual Behavior

![whatsapp image 2018-04-13 at 15 12 40](https://user-images.githubusercontent.com/18237132/38742874-2f31e220-3f2d-11e8-9b1b-6e27a61d2ae1.jpeg)

### Reproducible Demo

https://snack.expo.io/@norris1z/marker-bug

I don't know why this demo doesn't show the bug but it crashes expo

**Comment by julienR2** [comment]
@Norris1z can you have a look at this example ? https://github.com/react-community/react-native-maps/issues/1701#issuecomment-367156798
It seems you should use `this.marker._component.animateMarkerToCoordinate`, plus I guess you should use it on an `Marker.Animated`. Let us know how it goes.

**Comment by Norris1z** [comment]
Still the same

**Comment by Norris1z** [comment]
Just tried running the [Animate Marker Example](https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedMarkers.js) and it produced the same error

**Comment by Norris1z** [comment]
Any update on this issue

**Comment by rpavez** [comment]
Any update on this issue?

**Comment by Norris1z** [comment]
I had to use something like
```
   // lets say we have the coordinates in our state
    this.state = {
      coordinate: new AnimatedRegion({
        latitude: LATITUDE,
        longitude: LONGITUDE,
      }),
    };

   // we animate it using
   const { coordinate } = this.state;
    const newCoordinate = {
      latitude: LATITUDE + ((Math.random() - 0.5) * (LATITUDE_DELTA / 2)),
      longitude: LONGITUDE + ((Math.random() - 0.5) * (LONGITUDE_DELTA / 2)),
    };

    coordinate.timing(newCoordinate).start();
````

**Comment by abhayca** [comment]
Thank you for the response. But I am looking the answer for the Android platform (not iOS). Do you have the answer for it. This line is a source for error:
`this.marker._component.animateMarkerToCoordinate(newCoordinate, 500);`

**Comment by Norris1z** [comment]
@abhayca i know it's for IOS as per the example code but it works on android too. I had to rely on that while waiting for a fix for this error

**Comment by abhayca** [comment]
@Norris1z 

```
const newCoordinate = {
      latitude: LATITUDE + ((Math.random() - 0.5) * (LATITUDE_DELTA / 2)),
      longitude: LONGITUDE + ((Math.random() - 0.5) * (LONGITUDE_DELTA / 2)),
    };
```

This is not working for me :(

**Comment by abhayca** [comment]
My code:

```
animate(location) {
    const { coordinate } = this.state;
    const newCoordinate = {
      latitude: location.latitude  + ((Math.random() - 0.5) * (LATITUDE_DELTA / 2)),
      longitude: location.longitude  + ((Math.random() - 0.5) * (LONGITUDE_DELTA / 2))
    };

    if (Platform.OS === 'android') {

      //this command will move the MARKER to the new location when the user double clicks on one of the locations in the drop down
      if (this.marker) {
        this.marker._component.animateMarkerToCoordinate(newCoordinate, 500);
      }
    } else {
      coordinate.timing(newCoordinate).start();
    }
```
@Norris1z 
Where am I wrong, pl. guide.

**Comment by Norris1z** [comment]
try
```
animate(location) {
    const { coordinate } = this.state;
    const newCoordinate = {
      latitude: location.latitude  + ((Math.random() - 0.5) * (LATITUDE_DELTA / 2)),
      longitude: location.longitude  + ((Math.random() - 0.5) * (LONGITUDE_DELTA / 2))
    };

      //this command will move the MARKER to the new location when the user double clicks on one of the locations in the drop down
      coordinate.timing(newCoordinate).start();
}
```

**Comment by abhayca** [comment]
@Norris1z 
Thank you so much, you made my day. This piece of code is running perfectly fine on Android Virtual Device:
`coordinate.timing(newCoordinate).start();`

Thanks once again.

**Comment by themakerman** [comment]
Any fixes on this if we want to use this.marker._component.animateMarkerToCoordinate(newCoordinate, 500);

**Comment by themakerman** [comment]
@Norris1z The solution works but marker doesnt responds instantaneosly to new coordinates from 
`onPanDrag={(e) => this.tryAnimation(e.nativeEvent.coordinate)}`
or onRegionChange={(newCoords) => this.tryAnimation(newCoords)}

Its updating the position after a second. Can you please help me out?

My final line is like this while calling the animation:
`this.state.coordinate.timing({latitude, longitude},1).start();`

**Comment by themakerman** [comment]
Ok. I just understood that markers on android are bitmaps and they cannot be animated. Maybe one way to animate them is by rendering pure react native animated views outside of map and using ref property of map to figure out their absolute positioning.

**Comment by kumarkundan** [comment]
> I had to use something like
> 
> ```
>    // lets say we have the coordinates in our state
>     this.state = {
>       coordinate: new AnimatedRegion({
>         latitude: LATITUDE,
>         longitude: LONGITUDE,
>       }),
>     };
> 
>    // we animate it using
>    const { coordinate } = this.state;
>     const newCoordinate = {
>       latitude: LATITUDE + ((Math.random() - 0.5) * (LATITUDE_DELTA / 2)),
>       longitude: LONGITUDE + ((Math.random() - 0.5) * (LONGITUDE_DELTA / 2)),
>     };
> 
>     coordinate.timing(newCoordinate).start();
> ```

It's not working ... can you give us something more.. some more lines of code ..... anyway where is marker's refrence ...

**Comment by antgel** [comment]
Is `animateMarkerToCoordinate` even supposed to work? If not, can it just be deleted from the docs? So many people are falling into this trap. If yes, what's the solution to make it work?

Also, a tip for people posting "not working", you're not giving anybody useful information to help debug the problem, it just creates noise.

**Comment by tattivitorino** [comment]
What about multiple markers? all the examples I found show only one marker being animated, what about a list of markers that need to be animated each from to their specific positions? If I need to keep the AnimatedRegion as coordinate in the state to animate from will I need to have an animated region for each marker? :(

**Comment by kumarkundan** [comment]
> What about multiple markers? all the examples I found show only one marker being animated, what about a list of markers that need to be animated each from to their specific positions? If I need to keep the AnimatedRegion as coordinate in the state to animate from will I need to have an animated region for each marker? :(

can you post your sample code ... i have seaching for a solution from 4-5 days still not able to animate marker from one lat,lng to other lat,lng ... please post a sample code ....THANKS IN ADVANCE

**Comment by qja0707** [comment]
I used like below
`
<MapView>
<MapView.Marker
    ref={(marker_=>{this.marker = marker}}
</MapView>

this.marker.animateMarkerToCoordinate(this.region,3000)
`
and it works on Android

**Comment by higoramp** [comment]
> I used like below
> 
> ```
> <MapView>
> <MapView.Marker
>     ref={(marker_=>{this.marker = marker}}
> />
> </MapView>
> 
> this.marker.animateMarkerToCoordinate(this.region,3000)
> ```
> 
> and it works on Android

This works for me. Thanks!

don't  know why, but _component was undefined.

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-community/react-native-maps/issues/2195#issuecomment-627986050

**Comment by chespinoza** [comment]
this issue shouldn't be closed in my opinion, I was just testing the cited code and it doesn't work in my android emulator neither in my android phone, the only thing that works is:

```
coordinate.timing(newCoordinate).start();
```
I could check that the method `animateMarkerToCoordinate` exists for the marker object but it doesn't make any change to the marker. This method is also used in the examples:

https://github.com/react-native-maps/react-native-maps/blob/c542b04dce6565fca1cb57bfc98f46482ea950db/example/examples/AnimatedMarkers.js#L46

So a lot of people starting with this lib is going to get same errors 'cause the code it's wrong, issues like this will continue to be created until the examples will be amended.

**Comment by karlito40** [comment]
Sadly the cited code does not work anymore as chespinoza said. Only `coordinate.timing` does.

**Comment by JKKholmatov** [comment]
Any updates? `this.marker.animateMarkerToCoordinate(newCoordinate, 500)` not working in Expo project, anyone who could made it work?
