### ISSUE TITLE
onCalloutPress doesn't fire when using customMapStyle and provider

### ISSUE THREAD

**Issue by jackcbrown89** [react-native-community/react-native-maps#2223]
### Is this a bug report?

Yes

### Environment

`"react": "16.3.1"`
`"react-native": "0.55.3"`
`"react-native-maps": "^0.21.0"`

### Expected Behavior

Clicking a Callout should trigger the `onCalloutPress` event.

### Actual Behavior

 `onCalloutPress` is not triggered; however, when `customMapStyle` and `provider` are not provided to `<MapView>`, `onCalloutPress` is triggered. Additionally, the Callouts and Markers look different now that I've passed in a `customMapStyle`.

Here's a comparison (first one is without `customMapStyle`):
<img width="238" alt="default" src="https://user-images.githubusercontent.com/5186405/39393000-182001ae-4ac0-11e8-80a9-cd6ff54f6da8.png">
<img width="240" alt="custom" src="https://user-images.githubusercontent.com/5186405/39393001-1c7bc83c-4ac0-11e8-99a6-06a20ec96576.png">

### Reproducible Demo

```
class SomeScreen extends React.PureComponent {

renderMarkers = () => {
  return this.state.venue_list.map((venue, key) => {
    return (
      <Marker
        ...
        onCalloutPress={() => console.log("It worked with a custom map")}
      >
      ...
      </Marker>
    )
  })
}

render() {
  return (
    <View style={styles.container}>
    ...
    <MapView
      ref="map"
      customMapStyle={mapStyle}
      provider={PROVIDER_GOOGLE}
      onRegionChangeComplete={this.onRegionChange}
      ...
    >
    {this.renderMarkers()}
    </MapView>
    ...
    </View>
  )
}

onRegionChange = () => {
    this.refs.fitToElements(true);
}

}
```

## PLEASE DON'T COMMENT +1's
That's why a higher power invented the  👍

**Comment by gorobets-da** [comment]
You can use callout as a temporary solution:
```javascript
<Marker
    key={project.id}
    coordinate={{
      longitude: project.longitude,
      latitude: project.latitude
    }}
  >
    <Callout
      onPress={() => this.onMarkerPress(project)}
     >
       <Text>{project.name}</Text>
     </Callout>
</Marker>
```

Worked for me with specified provider.

**Comment by chrise86** [comment]
This is still an issue when using Google maps. on iOS. When using native maps it works fine.

**Comment by danieldanielecki** [comment]
As per https://stackoverflow.com/a/57234216/11127383 to make it working on both `Android` and `iOS` we need to add `onCalloutPress={() => eventHandler()}` inside `<Marker />`, for `Android`, and `onPress={() => eventHandler()}` inside `<Callout />`, for `Android`.
