### ISSUE TITLE
Callout show not correct position after animateToRegion

### ISSUE THREAD

**Issue by truckhiem** [react-native-community/react-native-maps#2235]
Hi I'm trying to using map to show our location but I have a problem like this:
When I tap on marker, I will animateToRegion to let that marker is center after that Callout will be show. My problem here is Callout show not correct position with new position of marker, because animateToRegion function was change marker location on map. 

Could you please to help me?
Thanks

**Comment by thatgriffith** [comment]
+1

**Comment by eprueba111** [comment]
Try to set tooltip property to false Ex: <Callout tooltip={false}></Callout>

**Comment by eprueba111** [comment]
Try to set tooltip property to false.`<Callout tooltip={false}></Callout>`
