### ISSUE TITLE
On iOS+Google Maps, the initialRegion property doesn't work

### ISSUE THREAD

**Issue by sargunv** [react-native-community/react-native-maps#2239]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-navigation": "1.5.11"

That version of expo comes with react-native-maps 0.21.0

Platform: Google Maps on iOS

### Steps to Reproduce

Create a MapView (Google Maps) with an `initialRegion` property and run it on iOS. 

### Expected Behavior

It should start at the region that was set, just like on iOS Apple Maps and Android Google Maps.

### Actual Behavior

The map will start all the way zoomed out, as if there was no region set. 

### Reproducible Demo

https://snack.expo.io/B1KBGrp6G

```jsx
<MapView
  style={{ flex: 1 }}
  provider={MapView.PROVIDER_GOOGLE}
  initialRegion={{
    latitude: 47.6062,
    longitude: -122.3321,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }}
  onPress={() => Alert.alert('onPress')}
  onLongPress={() => Alert.alert('longPress')}
  onPoiClick={() => Alert.alert('onPoiClick')}
/>
```

Using `region` instead of `initialRegion` works fine, however.

**Comment by vgeorge** [comment]
I'm using version 0.20.1, same issue. If I pass `region` property or use `.animateToRegion()`, it works fine, but setting `initialRegion` only centers the map to the coordinates without considering `latitudeDelta` and `longitudeDelta` values.

**Comment by adamnator92** [comment]
but when you perform `setState` action, the map will animate back to the region. 
any solution for this?
