### ISSUE TITLE
Provider Google IOS onPanDrag

### ISSUE THREAD

**Issue by kacperkurek** [react-native-community/react-native-maps#2249]
Why is onPanDrag event on iOS not supported by Google provider?

**Comment by emilefleming** [comment]
I am also experiencing this problem. I didn't see anything in the documentation saying this was not supported for Google maps on iOS but the provided function never runs.

**Comment by enourinick** [comment]
Same for me +1

**Comment by salah-ghanim** [comment]
fixed on master
