### ISSUE TITLE
Add new pods below this line comment

### ISSUE THREAD

**Issue by alvelig** [react-native-community/react-native-maps#2263]
https://facebook.github.io/react-native/docs/linking-libraries-ios.html says:
```
Note: If your iOS project is using CocoaPods (contains Podfile) and linked 
library has podspec file, then react-native link will link library using Podfile. 
To support non-trivial Podfiles add # Add new pods below this line 
comment to places where you expect pods to be added.
```

Shall we add `# Add new pods below this line` to our example Podfile in INSTALLATION.MD?

**Comment by rborn** [comment]
@alvelig  so if we do this, link would work?
we can do it nevertheless

**Comment by alvelig** [comment]
@rborn I haven't had luck to study it thoroughly :( Hoped you had lol. Well, let's leave it like this and I'll figure it out later. (Or maybe someone else :D)

**Comment by rborn** [comment]
@alvelig I'll try to give it a shot one of these days.

I should also close your issue as it's not respecting the template 🤪 So maybe you want to update it to give an example?

**Comment by alvelig** [comment]
I thought a while about how to comply with the template and didn't find how :( No examples or reproduction steps are applicable here...  It's some kind of "feature request".

**Comment by rborn** [comment]
At least add the template, we might wann thing later on how to change it to accept "feature"
