### ISSUE TITLE
Can't find libAirMaps.a in Build phases 

### ISSUE THREAD

**Issue by himaanshi** [react-native-community/react-native-maps#2268]
I am following  this tutorial to integrate google maps in react native link: https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14

After dragging AirGoogleMaps folder into project. I am expecting 

![1_2vwb_r8uy7offv3w_7iqyw](https://user-images.githubusercontent.com/15032532/40218219-f7231698-5a8d-11e8-824b-74307b085bc6.png)

But in my project libAirMaps.h is missing:

![screen shot 2018-05-18 at 11 24 43](https://user-images.githubusercontent.com/15032532/40218259-205f687c-5a8e-11e8-95a4-e1a9c10a089e.png)

Environment: 
  react-native-cli: 2.0.1
react-native: 0.55.4
	
  Target Platform: Xcode Version 9.3.1 (9E501) / I Phone 6 simulator

**Comment by Juniper11** [comment]
@himaanshi Did you find a solution?

**Comment by floraSy** [comment]
1. Use **Xcode** to open project
2. Find **Libraries** in Project Navigator and click right to choose **Add Files to "[Your Project]" ...**
3. Find **AirMaps.xcodeproj** in **node_modules/react-native-maps/lib/ios** and add it
4. Find **Link Binary With Libraries** in **Build Phases** and add **libAirMaps.a**

**Comment by floraSy** [comment]
Or you can see this: https://medium.com/@juanli_dev/install-react-native-maps-bccae45b6083

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.
