### ISSUE TITLE
CallOut with inside TouchableWithoutFeedback not click on iOS

### ISSUE THREAD

**Issue by invyctus92** [react-native-community/react-native-maps#2279]
Is this a bug report?

Yes

Have you read the Installation Instructions?

Yes

Environment
react-native-maps: 0.21.0
react-native: 0.53.0
react: 16.2.0

Steps to Reproduce

Create a react native app using react-native init.
Follow installation instructions to the dot.
Use Marker and CallOut with inside TouchableWithoutFeedback in Maps

Actual Behavior
TouchableWithoutFeedback in CallOut not click on iOS but work in debug mode
In Image not click modalities as School 

![simulator screen shot - iphone 6 - 2018-05-24 at 10 22 09](https://user-images.githubusercontent.com/13299821/40473443-80f18d8e-5f3c-11e8-9d97-f8af91785272.png)
![simulator screen shot - iphone 6 - 2018-05-24 at 10 22 13](https://user-images.githubusercontent.com/13299821/40473444-810d3de0-5f3c-11e8-98e0-56cf7b78fa9a.png)
![simulator screen shot - iphone 6 - 2018-05-24 at 10 22 18](https://user-images.githubusercontent.com/13299821/40473445-812c3204-5f3c-11e8-8053-4b197d158cf6.png)

`ReturnPoints = () => {
    {
      let viewRef = [null, null];
      const points = this.state.points.map((item, num) => (
        <MapView.Marker
          key={item.key}
          coordinate={{ latitude: item.latitude, longitude: item.longitude }}
          ref={view => {
            viewRef[num] = view;
          }}
          onPress={() =>
            Platform.OS === "ios"
              ? viewRef[num].showCallout()
              : this.showType(num, viewRef)
          }
        >
          {Platform.OS === "ios" ? (
            <MapView.Callout>
              {this.state.type.map((elem, index) => (
                <TouchableWithoutFeedback
                  key={index}
                  onPress={
                    this.state.selectType[num ? 0 : 1] !== index
                      ? () => this.SelectType(index, viewRef, num)
                      : null
                  }
                >
                  <View>
                    <Text
                      style={{
                        textAlign: "center",
                        fontSize: 16,
                        color:
                          this.state.selectType[num ? 0 : 1] === index
                            ? "grey"
                            : this.state.selectType[num] === index
                              ? "blue"
                              : "black",
                        fontWeight: "900"
                      }}
                    >
                      {elem}
                    </Text>
                  </View>
                </TouchableWithoutFeedback>
              ))}
            </MapView.Callout>
          ) : null}
        </MapView.Marker>
      ));
      return points;
    }
  };`

`render() {
    return (
      <View style={StyleSheet.absoluteFillObject}>
        <MapView
          ref={ref => {
            this.mapRef = ref;
          }}
          style={[
            StyleSheet.absoluteFillObject,
            {
              bottom: 0,
              flex: 1
            }
          ]}
          onLayout={() => {
            this.mapRef.fitToCoordinates(
              [
                { latitude: 38.106662, longitude: 13.369795 },
                { latitude: 38.118129, longitude: 13.362802 }
              ],
              {
                edgePadding: { top: 20, right: 20, bottom: 20, left: 20 },
                animated: false
              }
            );
          }}
          onPress={e => this.AddPoint(e.nativeEvent.coordinate, this.mapRef)}
        >
          {this.ReturnPoints()}
        </MapView>
        {Platform.OS !== "ios" ? this.ButtonAndroid() : null}
        {this.state.selectType[0] !== -1 && this.state.selectType[1] !== -1 ? (
          <View style={styles.buttonContainer}>
            <TouchableWithoutFeedback onPress={() => this.OK()}>
              <View style={styles.buttonBox}>
                <Text style={styles.buttonGoOnText}>Ok</Text>
              </View>
            </TouchableWithoutFeedback>
          </View>
        ) : null}
      </View>
    );
  }`

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
