### ISSUE TITLE
New Maps update requires Games Play Services ?

### ISSUE THREAD

**Issue by IgorVanian** [react-native-community/react-native-maps#2282]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.54.2
react: 16.3.0
react-native-maps: 0.21.0

### Steps to Reproduce

Build the app with latest Play Services:

```
implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-base:+'
    implementation 'com.google.android.gms:play-services-maps:+'
```
### Expected Behavior

MapView should be loaded.

### Actual Behavior

MapView is not loading (white screen)
and this error shows in logcat:
```
[GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:*********>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/games
```

My thoughts is that since the latest maps update from google, Maps implies a **play-services-games** requirement, because they consider it a gaming service from now on...

Maybe I'm totally wrong.

**Comment by mobius1983** [comment]
Hello friend, you solved the problem, it shows me the blank screen
