### ISSUE TITLE
ld: library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by stoneWeb** [react-native-community/react-native-maps#2285]
After `pod install` I get this error `ld: library not found for -lDoubleConversion` in XCode build.
The same problem occurs when I reinstall and try to change its version，I tried RN 0.54, 0.53, 0.52
react-native-cli: 2.0.1
react-native: 0.55.4
xcode: 9.3.1 (9E501)

I try to find a lot of places, and I rarely encounter this error.
I don't know where the problem might be.

**Comment by codeandproduce** [comment]
same problem

**Comment by jordan-jarolim** [comment]
same problem here.

**Comment by rborn** [comment]
Old issue, closing, please open a new one if you still have it
