### ISSUE TITLE
Local custom tiles on iOS

### ISSUE THREAD

**Issue by Zeldroxe** [react-native-community/react-native-maps#2288]
### Is this a bug report?

No.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

    react-native: 0.55.4
    react: 16.3.1
    react-native-maps: ^0.21.0

Target Platform: iOS - 11.2 / iPhone 6, Android 8.0.0 / Huawei Mate 10 Pro

### Expected Behavior

Hello,

I would like to store custom tiles with a zip file in my app bundle and extract them at startup. I succeeded on android thanks to react-native-zip-archive (https://github.com/mockingbot/react-native-zip-archive) and its function unzipAssets which allows me to recover my zip file from the assets folder of my app. However, this function is not available on iOS .... How can I store local tiles on iOS?

### Actual Behavior

Can't extract tiles from my ZIP file on iOS (because I can't store it in assets folder), how to have local tiles on iOS?

### Reproducible Demo
On Android
```
   <MapView
    	style={styles.map}
   	mapType={Platform.OS == "android" ? "none" : "standard"}
   	region={this.state.region}
   >
   	<LocalTile
   		pathTemplate='/storage/emulated/0/myApp/map/{z}/{x}/{y}.png'
   		tileSize={256}
   	/>
   </MapView>
```

**Comment by sinodko** [comment]
I would recommend you to store your zip files on some custom API server. Then download zip file (if it was not downloaded yet) and unzip + save your tiles to your device. It could be better solution at least for your application bundle size.
