### ISSUE TITLE
Making react-native link work

### ISSUE THREAD

**Issue by k0nserv** [react-native-community/react-native-maps#2289]
Hello 👋, 

I deleted the template because this is neither a bug report nor do I want help. I'm creating this issue to better understand what the technical reasons for not supporting `react-native link` are and whether these are issues that could be resolved if someone(me possibly) would dedicate time to solving them. The lack of `react-native link` is quite concerning and the fact that it seems like `react-native-maps` removes the ability for a project to use `react-native link` at all seems non ideal. I've searched the issue, but I've been unsuccessful in finding any technical explanation of why `react-native link` is to be avoided.

**Comment by SandeshVakale** [comment]
Hello @k0nserv, 
Some days ago I used `react-native link` in my project.
Everything was working cool on my iOS simulator, android simulator, and Android devices.

But on iOS devices, my application started showing white screen on start. And nothing was rendering after that.
I unlink library and did all steps manually again to resolve the issue.

Maybe other developers are having other issues. Don't know.

Thanks.

**Comment by alvaromb** [comment]
It would be great to support `react-native link`. I can help with this, but I don't know where to start.

**Comment by dcp12345678** [comment]
So is the path forward for this react-native-maps that react-native link cannot be used in your project at all? That seems like a pretty severe limitation.  Also, with airbnb "sunsetting" their use of react-native, what is the path forward for this project? Will it be maintained going forward?

**Comment by rborn** [comment]
@dcp12345678 the maintenance of this repo is long time ago in the hands of the community. So aby help it's welcomed.
@alvaromb replied in https://github.com/react-community/react-native-maps/issues/1954#issuecomment-403778312

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.
