### ISSUE TITLE
MapView: mapType='none' not working on iOS

### ISSUE THREAD

**Issue by Timmitry** [react-native-community/react-native-maps#2294]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.55.3
react: 16.3.1
react-native-maps: 0.21.0

Target Platform: iOS - 11.2 Simulator/iPhone 6

AppleMaps

### Steps to Reproduce

Use a MapView in any component and set `mapType` to `none`:

```html
<MapView mapType='none' />
```

### Expected Behavior

A blank map is shown

### Actual Behavior

An error is shown:

```
Invalid MKMapType 'none'. should be one of: (
    hybrid,
    hybridFlyover,
    mutedStandard,
    satellite,
    satelliteFlyover,
    standard
)
```

### Discussion

It seems that apple maps do not support [not showing a map](https://developer.apple.com/documentation/mapkit/mkmaptype). However, the [MapView documentation](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md) says it should be possible.

Would switching to Google Maps be a possible workaround?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by LiamBateman** [comment]
I've managed to re-create this issue using the latest on IOS. 

Exact same code as above, IOS doesn't seem to support mapType='none'

**Comment by rborn** [comment]
@LiamBateman yes indeed: https://github.com/react-native-community/react-native-maps/blob/72b0f77e31d18959e91acb036d5f91ab46e11ef2/example/examples/CustomTiles.js#L34

Fancy a PR to the docs? ❤️

**Comment by LiamBateman** [comment]
Perfect, yea I'll sort that out.

**Comment by LiamBateman** [comment]
https://github.com/react-native-community/react-native-maps/pull/2774

**Comment by jrmgx** [comment]
> @LiamBateman yes indeed: https://github.com/react-native-community/react-native-maps/blob/72b0f77e31d18959e91acb036d5f91ab46e11ef2/example/examples/CustomTiles.js#L34
> 
> Fancy a PR to the docs? ❤️

Any insights on why it is not possible to do? 

I am willing to look at it and find a way to achieve a workaround (the goal is to have an empty mapKit to have your own tiles, as overwise you have the default mapKit that overlays yours). 

I am pretty sure there is a way, I have seen native app using mapKit with externals tiles without the ugly overlay.

For now, I am stuck with this hybrid view, own tiles but mapKit overlay no matter which options I try
![The ugly overlay](https://github.com/user-attachments/assets/c05fb67e-a84a-4203-b47f-a35a39a2b27c)
