### ISSUE TITLE
how to set marker's initial position at bottom of the MapScreen

### ISSUE THREAD

**Issue by kishanj918** [react-native-community/react-native-maps#2295]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes
### Environment

    react-native:0.55.4
    react: 16.3.1
    react-native-maps: ^0.21.0

### Actual Behavior
Initially marker is showing at the center of the Map Screen 
But as per my requirement it should at the bottom of the Map Screen  

![our](https://user-images.githubusercontent.com/3994657/40842446-8a853b58-65cb-11e8-822d-b0f001140d52.png)

### Expected Behavior
Marker should be at bottom of the Map Screen

<img width="242" alt="required" src="https://user-images.githubusercontent.com/3994657/40842521-c8d7b2aa-65cb-11e8-89b4-eb9cebf0c307.png">

**Comment by sagargheewala** [comment]
I have the same problem... Any ideas?
