### ISSUE TITLE
[Google Maps][Bug] mapPadding is overlaying Google logo

### ISSUE THREAD

**Issue by kacperkurek** [react-native-community/react-native-maps#2336]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

react-native: 0.55.4,
react-native-maps: 0.21.0,
provider: GoogleMaps
Android
### Steps to Reproduce

add mapPadding={{ left: 0, right: 0, top: 0, bottom: 60 }} to MapView component

### Expected Behavior

Google logo position should change to upper.

### Actual Behavior

Google logo disappear. It is overlayed by map. If you change bottom to 15 it is partially visible 

### Reproducible Demo

https://snack.expo.io/Byk6LOBZm

**Comment by breadadams** [comment]
Seeing the same on
```
"react-native": "0.54.2",
"react-native-maps": "^0.19.0",
platform: Android
provider: GoogleMaps
```

Setting `bottom` to 15 as described by @KacperKurek 👇 

![jun-20-2018 12-53-47](https://user-images.githubusercontent.com/5795227/41654251-20008d24-7489-11e8-828d-f0ae6587ff9e.gif)

Initially the logo shows fully at the default position, then is clipped by the padding when map loads

**Comment by thomasw** [comment]
Let me add here before someone brings it up that this is also reproducible when explicitly using the styles outlined in the Android section of the installation guide: https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#on-android

See: https://snack.expo.io/Skz8tiffQ

And perhaps more importantly, I noticed that I wasn't seeing this behavior universally in my map components. It works in contexts where I've applied a workaround for https://github.com/react-community/react-native-maps/issues/1033.

See: https://snack.expo.io/Hyobssfzm

After a 1 second delay and a forced re-rendering, the logo appears in its proper spot.

**Comment by breadadams** [comment]
Yep, I noticed that too @thomasw

**Comment by Billy-** [comment]
FWIW, here's my solution, which seems to work well. It also fixes #549 for me (which is apparrently fixed but I haven't updated yet)

```js
// Of course you could use normal component state, but I'm a recompose hipster ;)
const enhance = withState('hackyState', 'hackTheState', false)

const Map = ({ hackyState, hackTheState, ...rest }) => (
  <View style={{ marginTop: -hackyState, paddingTop: +hackyState }}>
    <MapView
      {...props}
      // This one solves #2336
      onLayout={(...args) => {
        props.onLayout && props.onLayout(args)
        hackTheState(!hackyState)
      }
    >
      {React.Children.map(children, child => {
        if (child.type === Marker) {
          return React.cloneElement(child, {
            onPress: (...args) => {
              child.props.onPress && child.props.onPress(...args)
              // This one solves #549
              hackTheState(!hackyState)
            },
          })
        }
        return React.cloneElement(child)
      })}
    </MapView>
  </View>
)

export default enhance(Map)
```

**Comment by breadadams** [comment]
@Billy- I'm trying to follow along with your solution and implement it on my own map, but I don't really understand what the whole `hackyState`/`hackTheState`/etc. are doing. Also I think there are some "typos" with the use of `...rest` and then referring to it as `...props`/`props.*`?

Could you clarify how this works? So far from what I've applied updating `mapPadding` in a method passed to `onLayout` still gives me the cut-off Google logo. Thanks

**Comment by Billy-** [comment]
@breadadams Sorry, fixed the mistake(s) and added some explanation.

**Comment by markmssd** [comment]
@Billy- your hacky trick worked for me, thanks!
Would be nice if we didn't need to force an update like that, just like it works for iOS. Is there any way it in the library itself?

I can try a PR with some guidance!
