### ISSUE TITLE
Crash on Android: "southern latitude exceeds northern latitude"

### ISSUE THREAD

**Issue by macrozone** [react-native-community/react-native-maps#2345]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react": "16.3.1",
"react-native": "0.55.4",
"react-native-maps": "^0.21.0",

### Steps to Reproduce

Hard to reproduce atm for me.

### Description

I found this crash on crashreporter on android:

```
java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (78.44545846550506 > 15.155867229988225)
        at com.google.android.gms.common.internal.zzbq.zzb
        at com.google.android.gms.maps.model.LatLngBounds.<init>
        at com.airbnb.android.react.maps.AirMapView.setRegion(AirMapView.java:415)
        at com.airbnb.android.react.maps.AirMapManager.setRegion(AirMapManager.java:80)
```

We set `region` to be an animated region, no manual setting latitude. Also these latitude values are way out of what we use, that's why i think it might be a bug in the library. 

Under which conditions might this error happen?

**Comment by karlas** [comment]
Same error here, and can't really understand why, since on iOS all works ok

**Comment by davidpricedev** [comment]
I've seen this as well (no known reproduction steps). However, I'm seeing it at a different point in the code: 

com.airbnb.android.react.maps.AirMapView$11.onCameraMove
AirMapView.java - line 302
java.lang.IllegalArgumentException: southern latitude exceeds northern latitude

AirMapView.java: 299-306
```java
map.setOnCameraMoveListener(new GoogleMap.OnCameraMoveListener() {
  @Override
  public void onCameraMove() {
>   LatLngBounds bounds = map.getProjection().getVisibleRegion().latLngBounds;
    cameraLastIdleBounds = null;
    eventDispatcher.dispatchEvent(new RegionChangeEvent(getId(), bounds, true));
  }
});
```

**Comment by jaydenwindle** [comment]
I've also experienced this issue. iOS was working fine, but Android would experience this crash. 

In my case, the error was caused by accidentally passing in a negative `latitudeDelta` value to `region`. To fix it, I used the absolute value (`Math.pos(latitudeDelta)`).
