### ISSUE TITLE
Adding custom marker has an unexpected behaviour 

### ISSUE THREAD

**Issue by luisgurmendez** [react-native-community/react-native-maps#2349]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.44.2
react: 16.0.0-alpha.6
react-native-maps: ^0.15.2

in iOS using AppleMaps

### Steps to Reproduce

Add a custom makers, and there are more markers in the map but not visible.

### Expected Behavior

Only one marker should be added.

### Actual Behavior

Multiple markers are added. Moreover: 

I have several markers. Markers that are not in the actual map's visual area are replacated when adding new markers. These not expected replacated markers are also dragged around when moving in the map and also when onPress they go away. See videos below.

![appvideo3](https://user-images.githubusercontent.com/17949470/41784173-4c5eddca-7615-11e8-94a8-92223bbacc95.gif)

And without custom makers..

![appvideo2](https://user-images.githubusercontent.com/17949470/41783735-024cec1e-7614-11e8-9802-fca3600ead71.gif)

### Reproducible Demo

A copy of the repo can be found [here](https://github.com/luisgurmendez/Cajeros.git)

Steps. 
1. Click on the right bottom blue button
2. Place the blue circle where you want to create a new marker
3. Press on the green button.

**Comment by nhuthuynh195** [comment]
same problem !!!

**Comment by nhuthuynh195** [comment]
how to fix it, this is big problem !!!!
