### ISSUE TITLE
ANDROID only: Custom Marker w/ styled view as child, does not update when state changes.

### ISSUE THREAD

**Issue by jamiesonbates** [react-native-community/react-native-maps#2372]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

Versions:
react-native: 0.55.3
react: 16.3.1
react-native-maps: git+https://github.com/react-community/react-native-maps.git

Target Platform: IOS + Android, reproducible on device and sum.

Google Maps for both.

### Steps to Reproduce

1. Display a list of custom markers, each with a custom styled View as a child.
2. Setup a filter button, so that if toggled, some of the view within the marker will have its height and width cut in half.
3. Click on filter button.

### Expected Behavior

Markers that are filtered should have their size changed.

### Actual Behavior

Android only.

No markers size changes.

### Reproducible Demo

No demo yet.

**Comment by jamiesonbates** [comment]
A work around is to apply a unique key to each marker in the list. 

If you have a unique id associated with the data point already, you might already have a unique id (otherwise maybe the index).

However, if you want to conditionally change the child View's style on android, you can apply a list of strings based upon boolean logic that would change your styling.

I.E. `(uniqueID + bool1 ? 'bool1 : '' + bool2 ? 'bool2' : '')`

**Comment by n2ctech** [comment]
⚠ Sometimes the marker completely disappear from the map on some android devices with this strategy (got this bug on android galaxy S6) when the change is triggered.
