### ISSUE TITLE
Cannot make examples work

### ISSUE THREAD

**Issue by JiDai** [react-native-community/react-native-maps#2380]
I follow this guide to install examples but it does not work : https://github.com/react-community/react-native-maps/blob/master/docs/examples-setup.md

### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

react-native@0.54.4
react@16.4.1
react-native-maps@ 0.21.0

### Steps to Reproduce

```
git clone git@github.com:react-community/react-native-maps.git
cd react-native-maps
nom install
```

### Expected Behavior

No error happen on build

### Actual Behavior

Ann error occur during `npm run build:ios` command

```
[!] CocoaPods could not find compatible versions for pod "yoga":
  In snapshot (Podfile.lock):
    yoga (= 0.54.2.React)

  In Podfile:
    yoga (from `../../node_modules/react-native/ReactCommon/yoga/yoga.podspec`)

Due to the previous naïve CocoaPods resolver, you were using a pre-release version of `yoga`, without explicitly asking for a pre-release version, which now leads to a conflict. Please decide to either use that pre-release version by adding the version requirement to your Podfile (e.g. `pod 'yoga', '= 0.54.2.React'`) or revert to a stable version by running `pod update yoga`.
```

I have tried to run  `pod update yoga`, but it does not work
I have tried to change `yoga` requirements to force version but no luck

**Comment by jordan-jarolim** [comment]
Same problem here.
