### ISSUE TITLE
using bounds on the map

### ISSUE THREAD

**Issue by rayjadore** [react-native-community/react-native-maps#2391]
please how can i use coordinatinates such as { latitudeHi: 6.574999999999989, longitudeHi: 3.4000000000000057,  longitudeLo: 3.3874999999999886,  latitudeLo: 6.5625 } to dispaly an area on the map ?

**Comment by jamiesonbates** [comment]
@rayjadore check out `setMapBoundaries` in the react-native-maps documentation under "methods." I haven't used it myself yet, but it seems to fit your use case. Allows you to set northEast and southWest LatLng points. 

If you simply want the map to be focused on a specific area when it loads, you should set the `initialRegion`, which requires, latitude, longitude, latitudeDelta, and longitudeDelta (delta is zoom level I believe.

**Comment by lyseiha** [comment]
@jamiesonbates How can we force the zoom in-out only focus to the center of the screen ?
Example: you gonna zoom in or out on the other edge of the screen but the map it's zoom focus only the center of the map.

**Comment by lyseiha** [comment]
When we zoom, The lat and long not change but only change the lat-delta and long-delta only.

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.
