### ISSUE TITLE
Setting a minZoomLevel value will break the initialRegion prop on Apple Maps

### ISSUE THREAD

**Issue by lfkwtz** [react-native-community/react-native-maps#2400]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.55.4
react: 16.3.1
react-native-maps: 0.21.0

Target Platform: iOS 11.4.1 w/ Apple Maps

### Steps to Reproduce

1. Set a `minZoomLevel` (2 or more should do it)
2. Set an `initialRegion` to a specific location

example:
````
{
  latitude: 30.2672,
  longitude: -97.7431,
  latitudeDelta: 0.15,
  longitudeDelta: 0.15
}
````

### Expected Behavior

Map should be centered and zoomed into Austin, TX based on the `initialRegion` object

### Actual Behavior

Map will be centered on the US at the `minZoomLevel`

### Reproducible Demo

https://snack.expo.io/BJ_xpbYNQ

It seems as if the initial animation that zooms into the `minZoomLevel` will occur first. Once that animation finishes, the `initialRegion` param is ignored

The culprit is the `animated` boolean [here](https://github.com/react-community/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapManager.m#L794)

Setting it to false will allow `initialRegion` to work as expected. The negative I saw in this change though, is that if a user zooms out past the bounds of `minZoomLevel`, the map will not animate back into view, but jarringly snap.

**Comment by micchyboy237** [comment]
I'm having this issue as well, can anyone please fix this

**Comment by dengue8830** [comment]
it seems is the zoom effect on apple maps which prevents the map to use the initialRegion, in my case i commented the minZoomLevel and it works without any zoom effect, if i leave it the maps does a zoom effect and the initialRegion is not used

**Comment by rodrigowpl** [comment]
@lfkwtz I try your workaround and don't work. Maps don't re-render to a new minZoomLevel

**Comment by lfkwtz** [comment]
@rodrigowpl works for me --> https://snack.expo.io/SkIUHq-eE
