### ISSUE TITLE
[iOS] Marker onPress() triggering twice

### ISSUE THREAD

**Issue by NikoMontana** [react-native-community/react-native-maps#2410]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.51.0
    react: 16.0.0
	react-native-maps: 0.21.0 or "git+ssh://git@github.com/react-community/react-native-maps.git"
    Target Platform: eg: iOS - 11.2 iPhone 6s - GoogleMaps

### Steps to Reproduce

MyMapView.js
```          
      <MapView
            style={styles.map}
            region={{
              latitude: this.state.user_lat,
              longitude: this.state.user_lng,
              latitudeDelta: 0.015,
              longitudeDelta: 0.0121
            }}
            rotateEnabled={false}
          >
            {this.state.task_markers.map(marker => (
              <Marker
                key={marker.key}
                coordinate={marker.latlng}
                title={marker.title}
                description={marker.description}
              >
                <PriceMarker amount={marker.budget} />
              </Marker>
      </MapView>
```
PriceMarker
```
import React from "react";
import PropTypes from "prop-types";

import { StyleSheet, Text, Animated } from "react-native";

import Globals from "../../../utility/globals";

class AnimatedPriceMarker extends React.Component {
  render() {
    const { amount, selected, style } = this.props;

    return (
      <Animated.View style={[styles.container, style]}>
        <Animated.View
          style={[
            styles.bubble,
            {
              //backgroundColor: background,
              //borderColor: border
            }
          ]}
        >
          <Text style={styles.dollar}>€</Text>
          <Text style={styles.amount}>{amount}</Text>
        </Animated.View>
        <Animated.View style={[styles.arrowBorder, {}]} />
        <Animated.View style={[styles.arrow]} />
      </Animated.View>
    );
  }
}

AnimatedPriceMarker.propTypes = {
  amount: PropTypes.number.isRequired,
  style: PropTypes.any
};

const styles = StyleSheet.create({
  container: {
    flexDirection: "column",
    alignSelf: "flex-start"
  },
  bubble: {
    flex: 0,
    flexDirection: "row",
    alignSelf: "flex-start",
    backgroundColor: "#FF5A5F",
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderRadius: 3,
    borderColor: "#D23F44",
    borderWidth: 0.5
  },
  dollar: {
    color: "#fff",
    fontSize: 10
  },
  amount: {
    color: "#fff",
    fontSize: 13
  },
  arrow: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 4,
    borderTopColor: "#FF5A5F",
    alignSelf: "center",
    marginTop: -9
  },
  arrowBorder: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 4,
    borderTopColor: "#D23F44",
    alignSelf: "center",
    marginTop: -0.5
  },
  selectedBubble: {
    backgroundColor: "#4da2ab",
    borderColor: "#007a87"
  },
  selectedArrow: {
    borderTopColor: "#4da2ab"
  },
  selectedArrowBorder: {
    borderTopColor: "#007a87"
  }
});

export default AnimatedPriceMarker;
```

### Expected Behavior

Open Marker Information only once.

### Actual Behavior

If I click on the Marker, it opens the Marker information but triggers then another Marker onPress. So with one click it will display two Marker information, where the first Marker information will be closed. It happens more often if the two Markers are close to each other. 

### Reproducible Demo

No one availiable, sry.

**Comment by adapptor-jez** [comment]
I was experiencing the same issue with custom callouts in markers. I was able to work around it by setting `pointerEvents` to `"auto"` on my `Marker` component. This prevented `onPress` from being called on iOS (not Android though), but `onSelect` still worked.

**Comment by esutton** [comment]
@adapptor-jez Adding  pointerEvents="auto" to <Marker> did not help me on iOS.  Can you please add example to your comment?

See bounce after pin touched.

![on-press-bounce](https://user-images.githubusercontent.com/6115047/52280781-42ed8500-2922-11e9-94bb-8ad2e5f8a75f.gif)

````
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-maps": "^0.20.0",
````

**Comment by esutton** [comment]
@rborn why was this issue closed?

Is there a fix?

**Comment by maartenvandillen** [comment]
@NikoMontana I have the same issue. It's not like the example that @esutton is showing, but really a different, close by, marker that opens. So it's opening the callout of the marker you tapped on, then closes that callout and opens the callout of another marker which stays open. Did you ever solve this?

**Comment by gen1lee** [comment]
setting pointerEvents to "auto" helps but onPress is called after delay.
