### ISSUE TITLE
Wrong documentation about MapView prop-types (possibly more ..?)

### ISSUE THREAD

**Issue by Titozzz** [react-native-community/react-native-maps#2415]
### Is this a bug report?

Yes, there is an issue with documentation

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, but irrelevant.

### Environment

Android, using my react-native-maps fork based on v0.21.

### Steps to Reproduce

Use a MapView component. Inside the docs it is written,
```
  /**
   * A Boolean indicating whether indoor maps should be enabled.
   * Default value is `false`
   *
   * @platform android
   */
  showsIndoors: PropTypes.bool,
```
However the default value isn't false, I had to set it manually to false in order to disable it

### Expected Behavior

Documentation should be updated to match what is happening right now or default behaviour should be set.

### Actual Behavior

Prop showIndoors isn't false by default.

### A little backstory on why !

Inside my sentry logs I had a lot of stack trace that I did not understand such as

> StackOverflowErrorjava.util.Arrays in copyOf
> stack size 1038KB

> StackOverflowErrorjava.util.HashMap in createEntry
> stack size 1038KB

> StackOverflowErrorcom.google.maps.api.android.lib6.gmm6.model.p in hashCode
> stack size 1038KB

and many more...

then suddenly today I opened a map to a particular address (in London) and my app was crashing, so I digged

All theses bugs are linked to that thread 
https://issuetracker.google.com/issues/35829548

And the temporary workaround is to disable indoors. Which is how I saw that the default show be disabled. But only setting it manually did the trick 🎉 

EDIT: docs inside [MapView.md](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md) is correct, I'm talking about docs inside the code [here](https://github.com/react-community/react-native-maps/blob/master/lib/components/MapView.js#L245)

**Comment by rborn** [comment]
@Titozzz  PR ? 😊
