### ISSUE TITLE
Optimizations for static maps

### ISSUE THREAD

**Issue by davinctor** [react-native-community/react-native-maps#2431]
### Is this a bug report?
No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yup

### Environment
 react-native: 0.56.0
 react: 16.3.1
 react-native-maps: 0.21.0
 Target Platform: eg: iOS - 11.3 Simulator/iPhone SE, Android 7.1.1
 GoogleMaps

### Steps to Reproduce
Actually not needed
### Expected Behavior
Actually not needed

### Actual Behavior
Actually not needed

### Reproducible Demo
I don't have one.

## The question
Currently, I'm rendering a list with geofences and it (list) has some lags on scrolling (not much).
So I want to know are there any optimizations for displaying static maps? (by static I mean that `pitchEnabled` & `rotateEnabled` & `scrollEnabled` & `zoomEnabled` & `zoomControlEnabled` are false).
Thanks!

**Comment by stajics** [comment]
You should use cacheEnabled attribute. Note that its not working for GoogleMaps provider on iOS. (#1583)
