### ISSUE TITLE
Examples does not work

### ISSUE THREAD

**Issue by namgk** [react-native-community/react-native-maps#2434]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

I'm raising an issue about the setup instruction for Example Project. I've read them all here: [https://github.com/react-community/react-native-maps/blob/master/docs/examples-setup.md](https://github.com/react-community/react-native-maps/blob/master/docs/examples-setup.md)

### Environment

Not relevant as I'm not doing anything on my own project. I just try to build/run the cloned code, example.

### Steps to Reproduce

1. git clone https://github.com/react-community/react-native-maps.git
2. cd react-native-maps
3. yarn
4. yarn run:android

### Expected Behavior

It builds and run

### Actual Behavior

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/namtrang/workspace/react-native-maps/lib/android/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating project ':react-native-maps-lib'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### Reproducible Demo

https://github.com/react-community/react-native-maps/blob/master/docs/examples-setup.md

**Comment by Petrux25** [comment]
Apparently it is related to the Graddle version. I tried this solution (#2155) but even after changing the build.gradle I got a different build error.

**Comment by mikeyamato** [comment]
Same with iOS.

I'm following the [instructions](https://github.com/react-native-community/react-native-maps/blob/master/docs/examples-setup.md) but noticed that the command `npm run build:ios` within `package.json` results in `"build:ios": "bundle install --path ./example/ios/bundles && bundle exec pod install --project-directory=./example/ios/",`. It appears that we are missing the `/bundles` folder within `/ios`.

<img width="616" alt="screen shot 2019-01-02 at 4 01 08 pm" src="https://user-images.githubusercontent.com/27756216/50618486-d6591380-0ea7-11e9-9eca-d0dd2db04a54.png">
