### ISSUE TITLE
Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. 

### ISSUE THREAD

**Issue by chrise86** [react-native-community/react-native-maps#2450]
When running `react-native run-android` the build fails with the error above.

In my case I think it may be brought about by using the following code in `android/build.gradle`, which is necessary due to issues with other projects not being updated:

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.3"
            }
        }
    }
}
```

I could be wrong, however in my project I can't get to the compilation stage of this package without the above.

If I replace the offending line (line 46) of `lib/android/build.gradle`:

```
// from
compileOnly "com.facebook.react:react-native:+"
// to
compile "com.facebook.react:react-native:+"
// or
provided "com.facebook.react:react-native:+"
```

Then running `react-native run-android` then results in:

```
Could not find method implementation() for arguments [com.google.android.gms:play-services-base:10.2.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

which is pointing to the next line (line 47):

```
46: compileOnly "com.facebook.react:react-native:+"
47: implementation "com.google.android.gms:play-services-base:$googlePlayServicesVersion" // this one
48: implementation "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
49: implementation "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
```

In my case, I also have the following in my `app/build.gradle`:

```
compile(project(':react-native-maps')) {
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
}
```

But I guess the problem is with it understanding what `implementation` is.

### Environment

React Native: `0.56.0`
React: `16.4.1`
react-native-maps: `0.21.0`

### Steps to Reproduce

`react-native run-android`

**Comment by arshidkv12** [comment]
Same issue here. I upgraded gradle then it is working fine. But some other functions not working.

**Comment by lastpeony** [comment]
Could not find method implementation() for arguments [project ':react-native-maps', build_5yzom2lyrek7xvyvgp2oo4gzp$_run_closure1$_closure3$_closure4@32e28f91] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   
i have this error.updated to gradle 3 still same.wasted 5 hours trying to solve this tried everything on internet but still couldnt

**Comment by rborn** [comment]
@chrise86 try to upgrade gradle in _PROJECT_PATH_/android/gradle/wrapper/gradle-wrapper.properties to
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

**Comment by YTPSourceCode** [comment]
I sole this problem. But its not a true method. 

You must change this lines.
ProjectPath/node_modules/react-native-maps/lib/android/build.gradle 
`implement "com.facebook.react:react-native:+"
  implement "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
  implement "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
  implement "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
`

to 

`compile "com.facebook.react:react-native:+"
  compile "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
  compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
  compile "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
`

**Comment by samcyn** [comment]
@YTPSourceCode solution works. I think there maybe a better solution but for now that's a life saver.

**Comment by aanjan123** [comment]
@YTPSourceCode after implementing that i got this error 

....\node_modules\react-native-maps\lib\android\src\main\java\com\airbnb\android\react\maps\AirMapCircle.java:69: error: cannot access zza
    if (circleOptions == null) {
                      ^
  class file for com.google.android.gms.common.internal.safeparcel.zza not found
