### ISSUE TITLE
Custom markers are not applying opacity when rendered first time

### ISSUE THREAD

**Issue by rahmanmarija** [react-native-community/react-native-maps#2470]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

(Write your steps here:)

We have a map that renders new custom markers when scrolling or zooming in and they should have transparency. Currently they first get rendered as a normal fully visible image and then they get transparency.

### Expected Behavior

Custom markers should apply style right away when they are rendered.

Did anyone had a problem like this and found solution?

**Comment by feargswalsh92** [comment]
I got opacity to work  on first render  for my markers by using opacity as a prop rather than as a style. 
```
<MapView.Marker
                      onPress = {(e) => { e.stopPropagation(); _toggleCategoryIconSelected(place.facebookId); this._onMarkerPress() }}
                      key = {place.facebookId}
                      opacity = {((filteredMarkers.includes(place.facebookId)) ? 0.5
                        : ((!categoryIconSelected && filteredMarkers.length > 0))) ? 0.5 : 1} >
```

NB everything except the opacity prop is irrelevant to you here.
