### ISSUE TITLE
Lint Errors found in the project

### ISSUE THREAD

**Issue by veeran-dev** [react-native-community/react-native-maps#2473]
### Is this a bug report?

NO

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
"react": "16.3.1",
   "react-native": "^0.55.3",
"react-native-maps": "^0.18.3",
Target Platform: eg: redmi A1 / android 6.1

### Issue

* What went wrong:
Execution failed for task ':react-native-maps:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  **Errors found:**

  ..\node_modules\react-native-maps\lib\android\build.gradle: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.1.0, 23.0.1. Examples include com.android.support:support-compat:26.1.0 and com.android.support:appcompat-v7:23.0.1 [GradleCompatible]

**Comment by dylmye** [comment]
It looks like it might be due to being built with gradle 2.1.4 or the settings directing you to target 26? I get this after following android setup instructions:

```
λ gradlew lint

> Configure project :app
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-maps
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```
[...]
```
 Errors found:

  A:\path\app-root-folder\node_modules\react-native-maps\lib\android\build.gradle: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 25.2.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:support-media-compat:25.2.0 [GradleCompatible]

**Comment by gamoridev** [comment]
Has someone found any solution?
I'm with the same issue, while running with `'com.android.tools.build:gradle:3.1.4'` and these settings:

```
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
```

**Comment by thekingrenz23** [comment]
did you solve the problem?

**Comment by Rawan-Eltobgy** [comment]
Still having the same issue
