### ISSUE TITLE
Iphone 7 - Blurred/Pixelated border on markers

### ISSUE THREAD

**Issue by FloSugar** [react-native-community/react-native-maps#2484]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

 
Google map

### Steps to Reproduce

(Write your steps here:)

1. Create more than 2 markers on the map
2. Use an iPhone 7 (device)
3. Create a circled custom marker with border **in light colors** (white, yellow...): no problem when using darker colors such as red, black, purple... 
4. Zoom/Unzoom and admire blurred pixels
 
### Expected Behavior

See 2 markers on the map.

### Actual Behavior

My problem is that when there are **2 or more markers** on the map, their borders appear blurry with a low/medium level of zoom with strange black pixels (Screen A).

### Reproducible Demo

**MARKER**

 ```
         <Marker
         key={`${singleEvent.uid}${Date.now()}`}
         coordinate={eventInfos.coordinates}
         >
        <View style={bigProfileImage}>
          <UserPhoto
            imageStyle={bigMarker}
            img={img}
          >
            Thomas
          </UserPhoto>
        </View>
        <View style={iconStyle}>
          <Image
            resizeMode={'cover'}
            resizeMethode={'resize'}
            style={{ width: 22, height: 22 }}
            source={sample}/>
        </View>
        <Callout tooltip />
      </Marker>
```

**STYLING**

```
    const border = {
      borderWidth: 2,
      borderColor: HEXCOLOR.pureWhite,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    }

[...]

      bigProfileImage: {
        width: 72,
        height: 72,
        borderRadius: 36
      },
      bigMarker: {
        ...border,
        borderWidth: 4,
        borderRadius: 39,
        height: 78,
        width: 78,
      },
```

### Possible leads

- When zooming on one of the two markers, weird black pixels disappears (screen B).

- No problem at all with one marker (screen C).

- No problem when using darker colors such as red, black, purple... But problem also persists with white, yellow and other light colors.

- Also, I tested this in iphone 5, 6, 7 & X (devices) and it only occurs on iphone 7. Might be related to device resolutions ?

- I didn't see any problem on android for now.

(Paste the link to an example project and exact instructions to reproduce the issue.)

### Attached screen

*Screen A - 2 markers - medium zoom*
[![Screen A - 2 markers - medium zoom][1]][1]

*Screen B - 2 markers - high zoom*
[![enter image description here][2]][2]

*Screen C - 1 markers - medium zoom*
[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/i3zbB.jpg
  [2]: https://i.stack.imgur.com/IAZSM.jpg
  [3]: https://i.stack.imgur.com/XB2t6.jpg

**Comment by rborn** [comment]
It might be the screen resolution as you say, I can only have 2 ideas:
- play with the size of the marker: make a width 70 or 74
- add a background color (I have high hopes with this one 😄 )

**Comment by FloSugar** [comment]
Tried both, didn't work ! Also tried playing with border radius but result is the same :-( 

Any other idea ? Also tried with iPhone X and getting no problem. Its seems specific to iphone 7..

![img_68096ccc7219-1](https://user-images.githubusercontent.com/5587278/45368007-cf4d8300-b5e2-11e8-863b-7db5d424ffb3.jpeg)

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.
