### ISSUE TITLE
coordinate property in "onPoiClick" and "onPress". Can't get precise coordinate on press within POI area

### ISSUE THREAD

**Issue by vitto-moz** [react-native-community/react-native-maps#2496]
### Is this a bug report?

NOT SURE ===> But definitely lack of functionality 

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment
"react": "16.3.0"
"react-native-maps": "0.21.0"
"react-native": "0.54.3"

### Steps to Reproduce
here is my MapView usage: 
```

onPressHandler(e) {
            const coordinate = e.nativeEvent.coordinate
        ..............
}

<MapView
          provider={PROVIDER_GOOGLE}
          style={styles.map}
          ref={ref => this.map = ref}
          showsUserLocation={true}
          onMapReady={this.onMapReady}
          zoomEnabled={true}
          maxZoomLevel={20}
          mapType={this.props.mapType}
          onPress={this.onPressHandler} // <===== this method is for drawing
          onPoiClick={this.onPressHandler} //  <===== this method is for drawing
          onRegionChange={this.onRegionChange}
          showsPointsOfInterest={false}
          cacheEnabled={true}
        >
```
So, I set "this.onPressHandler" for "onPress" and "onPoiClick" properties to use it for drawing by means of pressing on map.
My issue is: when I don't set handler for "onPoiClick" all pressings within POI area are skipped (onPress handler is not called). On the other hand when "onPoiClick" handler is set - as a coordinates in handler argument (e.nativeEvent.coordinate) I have coordinate of POI, but not the point I actually pressed. But for drawing precise geofences I need coordinate of point I pressed, not POI coordinate

### Expected Behavior
I think there should be an option to skip events of pressing on POI in favor of "onPress" handler 
  or
onPoiClick handler should receive both coordinates (POI and actual pressed point)

### Actual Behavior

When I don't set handler for "onPoiClick" all pressings within POI area are skipped(onPress handler is not called). On the other hand when "onPoiClick" handler is set - as a coordinates in handler argument (e.nativeEvent.coordinate) I have coordinate of POI, but not the point I actually pressed. But for drawing precise geofences I need coordinate of point I pressed, not POI coordinate
![iphone_6_-_11_3](https://user-images.githubusercontent.com/19843391/45713077-c3d7fa00-bb96-11e8-8d06-ab609a03cdcd.png)

**Comment by koxelez** [comment]
Getting this problem as well. POIs get in the way and prevent from getting precise coordinates.

I tried:
Workaround: setting the "showsPointsOfInterest={false}" prop.
Result: POIs keep showing up

Workaround: instead of using the "coordinate" property, getting the "position" and using "coordinateForPoint()"
Result: Returns the POI's position, same result as using "coordinate"

I'm still looking for ways to solve this. I'm currently trying get around the POI events

**Comment by koxelez** [comment]
New workaround: keep the map from showing any POIs by setting their visibility to "off" using the "customMapStyle" prop.

```
customMapStyle={[
              {
                "featureType": "poi",
                "stylers": [
                  {
                    "visibility": "off"
                  }
                ]
              },
            ]}
```
Works for me!
Idea taken from #768

**Comment by oliwen** [comment]
I'm having the same issue and it's not a viable solution for me to disable all poi. I still need to have country names visible for instance.

This works as expected on android, onPress always triggers and returns the correct coordinates.

**Comment by valeriik** [comment]
To disable all poi - it's absolutely not a viable solution!!!

**Comment by rushant11** [comment]
![Screenshot_1732184411](https://github.com/user-attachments/assets/16bf248b-5aea-4e15-98bc-a20693102b1e)
