### ISSUE TITLE
Retina 2x tiles from Mapbox displayed incorrectly

### ISSUE THREAD

**Issue by timfpark** [react-native-community/react-native-maps#2498]
### Is this a bug report?

Yes
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.56.1
    react: 16.4.1
    react-native-maps: "react-community/react-native-maps"
    iOS:  Target iOS 11.2 / iPhone X

### Steps to Reproduce

1. Use UrlTile with Mapbox with 2x retina tiles ala:

<UrlTile urlTemplate={'https://api.mapbox.com/styles/v1/mapbox/outdoors-v9/tiles/512/{z}/{x}/{y}@2x?access_token=pk...'} tileSize={512} />

### Expected Behavior

Map uses mapbox tiles with retina resolution.

### Actual Behavior

Tiles are jumbled, like only the first 256x256 of the tile is being used and not the full 512x512.

<img width="373" alt="screen shot 2018-09-19 at 5 35 50 pm" src="https://user-images.githubusercontent.com/712001/45789194-3c8c9400-bc33-11e8-8251-7d982af33bac.png">

### Reproducible Demo

Use the [tileOverlay sample ](https://github.com/react-community/react-native-maps#tile-overlay-using-tile-server) substituting the UrlTile above.

**Comment by radeno** [comment]
Looks like this PR should fix it. https://github.com/react-community/react-native-maps/pull/2589
Anyway, if you use Mapbox tiles, is not easier to you use their RN implementation ? https://github.com/mapbox/react-native-mapbox-gl

**Comment by cglacet** [comment]
Mapbox stopped maintaining their RN implementation, questions like this one will matter even more now.
