### ISSUE TITLE
Attempted to assign to readonly property when opening map a second time

### ISSUE THREAD

**Issue by christian-hess-94** [react-native-community/react-native-maps#2509]
I have a React Native (0.44.0) app that has a Google Maps built into it. This map shows markers that are programatically added to display the locations of all the subway stations in my city. 

This is the code that populates the markers into the MapView:
```
oesteMarkers = this.state.oesteStations.map(station => (

            <Marker key={station.name}
                coordinate={
                    {
                        latitude: station.lat,
                        longitude: station.lng
                    }
                }
                anchor={
                    {
                        x: anchorX,
                        y: anchorY
                    }
                }
            >
                <View style={styles.stationOeste} />
                <MarkerCalloutCard station={station} route="oeste" />
            </Marker>
        ))
```

> MarkerCalloutCard

 code for my custom callout which simply personalizes the callout with some information about the station that is represented by that specific marker. It has the station prop which is passed from the array 

> this.state.oesteStations

This is an array of coordinates (lat, lng) which get populated into the map view. These coordinates correspond to subway stations scattered throughtout my city and include their latitude and longitude, name and destination.

Also, I make the use of polylines, which are populated as follows:

```
<Polyline
                        coordinates={AllStations.polylineArrays.oeste}
                        strokeColor={Colors.routes.oeste}
                        strokeWidth={10}
                    />
```

> AllStations 

is a JS file that contains arrays for all the subway stations.

> .polylineArrays

 is an array of arrays wich contains the arrays used to render the polylines for each subway line

> .oeste

 is which array i'm choosing to populate that specificr polyline.

When I open the map once, it shows all stations, including PolyLines and my custom Callouts. But when I return to the previous screen and open the map again i get the red message:

> Attempted to assign to readonly property.

Alreayd tried messing around in the code to fix this, but to no avail. Can any one help me? Also, i'm running the app for android.

**Comment by christopherdro** [comment]
Trying to clean the repo, please comment or mention me to re-open the issue if is still the case. Thanks!
