### ISSUE TITLE
How to set the map to the default region and zoom level after the navigating back to Map screen?

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-community/react-native-maps#2519]
### Is this a bug report?

(write your answer here)
No, it's a question 

No, it's a question

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)
Yes

### Environment

  react-native: 0.55.1
    react: 16.0.0
	react-native-maps: 0.21.0
Target platform: Android 7.1.1

### Steps to Reproduce

(Write your steps here:)

1. Zoom in or zoom up the map 
2. Change current location to any other location 
3. Navigate to another screen 
4.Navigate to the map screen again 

### Expected Behavior

(Write what you thought would happen.)

1. Map go to the default position and default zoom level 

### Actual Behavior

1. Map stays on the same position, which user left it after zooming and changing map position

My code: 
```
 <MapView
     provider={PROVIDER_GOOGLE}
     style={styles.map}
     region={{
       latitude: this.props.latitude!=null ? this.props.latitude: 37.78825,
       longitude: this.props.longitude!=null ? this.props.longitude: -122.4324,
       latitudeDelta: 0.015*5,
       longitudeDelta: 0.0121*5,
     }}
     customMapStyle={mapStyle}
   > 
```

**Comment by seco35** [comment]
Like all the other dynamic stuff in react-native works with -> Use state.
You're using the prop given to your view.

in your constructor do following:
```
constructor(props){
        this.state = {
            lat: this.props.latitude!=null? this.props.latitude: 37.78825,
            lng: this.props.longitude!=null ? this.props.longitude: -122.4324,
            latDelta: 0.015*5,
            lngDelta: 0.0121*5,
        }
    }
```

and use the values in your state in your map like:

```
 <MapView
     provider={PROVIDER_GOOGLE}
     style={styles.map}
     region={{
       latitude: this.state.lat,
       longitude: this.state.lng,
       latitudeDelta: this.state.latDelta,
       longitudeDelta: this.state.lngDelta,
     }}
     customMapStyle={mapStyle}
   > 
```

The last and the most important part is to change the values, if user intends to change the view.
And before navigating you've to set your state again to the props values like this:

```
this.setState({
            lat: this.props.latitude!=null? this.props.latitude: 37.78825,
            lng: this.props.longitude!=null ? this.props.longitude: -122.4324,
            latitudeDelta: 0.015*5,
            longitudeDelta: 0.0121*5,
        });
// YOUR NAVIGATING CODE GOES HERE e.g. navigate("myNextScreen"); IF YOU'RE USING React // Navigation
```

**Comment by rborn** [comment]
Very old issue, and with solution, closing.

**Comment by reiui9** [comment]
how is going to setting default zoom level ?

**Comment by Saliheen** [comment]
I did it like this

**Comment by Saliheen** [comment]
I idid it like this  
```
**mapRef.current.animateToRegion( {
            center: {
              latitude: latitude,
              longitude: longitude,
            },
            pitch: 0,
            heading: 0,
            altitude: 10,
            zoom: ZOOM_LEVEL,
          },
          {duration: MAP_ANIMATION_DURATION},);**
```
