### ISSUE TITLE
IOS - Module install via link mess up custom font

### ISSUE THREAD

**Issue by MelanieJourne** [react-native-community/react-native-maps#2521]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, multiples times.

### Environment

Extract of package.json:
  "dependencies": {
    "md5": "2.2.1",
    "pouchdb-react-native": "6.4.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-device-info": "0.22.5",
    "react-native-i18n": "2.0.15",
    "react-native-navigation": "1.1.484",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "react-native-maps": "0.21.0"
  },

### Steps to Reproduce

I add a functional app containing a navigation and several others component. I was using custom font for my application. Everything went fine.
I did the manual installation for Android and launch the app. Everything went fine, my app was displayed, my font were corrected.
However, when installing for iOS, everything went wrong. 
The app no longer recognises the font and error is displayed at launch.

Here are the steps I took : 
1. Execute the command : npm install --save react-native-maps
2. Execute : react-native link react-native-maps
3. Check that .xcodproj has been added to Librairies folder
4. Check that .a has been added to "link binary with librairies"
5. Execute react-native run-ios
6. Error with custom font : Unrecognized font family  

The font were installed previously manually on iOS and Android separately. I also try to re-install them with the folder ./assest/file and react-native-link but the problem persists.
I also try to install the maps module without the react-native link by adding manually the .xcodeproj & library but the problem persists.

### Expected Behavior

I excepted the app to display the app smoothly or at least to have an error concerning the map or the module. 

### Actual Behavior

The app displays an error at launch concerning my custom font (which were working perfectly fine before and are still working perfectly fine on Android)
![simulator screen shot - iphone 6 - 2018-09-28 at 15 24 50](https://user-images.githubusercontent.com/14292474/46211461-dfc86200-c333-11e8-81ce-cabc6ce22db9.png)

### Reproducible Demo

1. Create a project
2. Install custom font
3. Install react native maps

### Additional comments

Could it be another module/librairie that I use ?
Has anyone else experience this problem ?

**Comment by rborn** [comment]
Old issue, closing, please open a new one if you still have it
