### ISSUE TITLE
showsScale is not working with GoogleMaps provider 

### ISSUE THREAD

**Issue by jbadiascolab** [react-native-community/react-native-maps#2531]
### Is this a bug report?

yes

### Have you read the Installation Instructions?

yes

### Environment

    react-native-maps: 0.21.0
    react-native: 0.55.4
    react: 16.4.1

### Steps to Reproduce

Create a MapView with the showsScale parameter activated

### Expected Behavior

The scale appears on the map

### Actual Behavior

Scale is not showing on the map.

### Reproducible Demo

                             <MapView 
                                   style={styles.map}
                                   region={this.state.region}
                                   **showsScale={true}**
                                   showsCompass={true}
                                   mapType={"standard"}
                               >
                               </MapView>

**Comment by rborn** [comment]
Please update your issue following the template or I'll close it.

**Comment by rafauke** [comment]
@jbadiascolab The documentation mentions that `showsScale` property is available for Apple Maps only.

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-community/react-native-maps/issues/2531#issuecomment-495614761

**Comment by TusharKoul** [comment]
is there a way to show scale when using Google maps?
