### ISSUE TITLE
Check if the device supports the "Google Play Service"

### ISSUE THREAD

**Issue by TusharSangani** [react-native-community/react-native-maps#2533]
### Is this a bug report?

NO

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
 react native version : 0.554
 react-native-maps : 0.21.0

### Steps to Reproduce

(Write your steps here:)

1. I am testing the map in android application and it worked in android phones, but when I tested it in genymotion emulator it gave error like "Application wont run without Google play service which are not supported by your device" .

2. The application is to be used in a scanner device that run on android, so I wanted to check if the device does not support the google play service before loading the map, so that a warning message can be given.

### Expected Behavior

The react-native-map library should have some way to detect the support the google play service 
support.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
I'm not sure this should be in this package. If you want a google map then you need to have the services integrated.

You could try to use other modules that check for this and act accordingly but I don't know how well it would work. 

@alvelig thoughts on this?
