### ISSUE TITLE
Why do I need an API key when using OSM?

### ISSUE THREAD

**Issue by crockpotveggies** [react-native-community/react-native-maps#2536]
### Is this a bug report?

Unknown

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, installation requires me to obtain and set an API key. However, I want to use tiles from OpenStreetMaps and an API key should be irrelevant here.

### Environment

    react-native: 0.57.1
    react: 16.5.0
    react-native-maps: 0.21.0
    Target Platform: Android Rockchip PX5

### Steps to Reproduce

1. Create new project, follow installation instructions
2. Omit an API key
3. Set `urlTemplate` to `'http://c.tile.openstreetmap.org/{z}/{x}/{y}.png`
4. Receive error demanding an API key for Google API.

### Expected Behavior

Package would detect OSM and not require an API key.

### Actual Behavior

App crashes with API key error.

### Reproducible Demo

Self explanatory.

**Comment by crockpotveggies** [comment]
Turns out many others have similar feedback, and there's a PR that needs attention: https://github.com/react-community/react-native-maps/pull/2348

**Comment by fqborges** [comment]
@crockpotveggies The problem here is that even tough you are using OSM tiles, the map provider (that is the core map feature) is still backed by Google maps and it requires a Google Maps API Key.

**Comment by crockpotveggies** [comment]
Hmm that does make sense. @fqborges looks like you're the author of that PR I referenced, has anyone given you a timeline to merge that?

**Comment by fqborges** [comment]
@crockpotveggies nope. Probably I still have issues on my side, no docs on that PR referencing installation instructions, etc. I hope it is merged as experimental, so we can have a wider test base.

**Comment by jibin2706** [comment]
@fqborges It is using javascript api or native api (android maps API)

**Comment by sinodko** [comment]
Hello guys I would like to use the react-native-maps in my project but I was little bit scared about setting up billing information during getting an API key from Google. I need to use my custom map tiles downloaded from my api server. Does this new Google policy means that using react-native-map for my use-case will not be free?

**Comment by fqborges** [comment]
Google Maps is not free anymore. They changed the revenue model to give you a $200 free monthly usage instead (https://cloud.google.com/maps-platform/pricing/), and charge for what exceeds that. 

They say: "For most of our users, the $200 monthly credit is enough to support their needs. You can also set daily quotas to protect against unexpected increases."

In our case, we use Google Maps in a couple of small projects, and we have never been charged over the free $200. We had to set up a billing account, though.

**Comment by rborn** [comment]
Old issue and explanation given. Closing.
