### ISSUE TITLE
MapView width and height only crop component

### ISSUE THREAD

**Issue by GuilleDF** [react-native-community/react-native-maps#2549]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz
    react: 16.5.2
    react-native-maps: provided by expo

  Target Platform: iOS - 12 iPhone 6s (GoogleMaps), Android 7.1.1 BQ Aquaris X

### Steps to Reproduce

1. Create a MapView, setting width and height in the style prop so that it forms a rectangle with larger width than height (for example {width: 500, height: 200} and pass minZoomLevel={0}
2. Pinch to try and zoom out as far as possible
3. Repeat the process with the full height of the screen

### Expected Behavior

With the 1st rectangle I expected to be able to see the whole world on my screen.

### Actual Behavior

I can ony see a fraction of a continent, it looks like changing the width and height of the component simply crop the view, making small zoomed out maps impossible.

### Reproducible Demo

https://snack.expo.io/Byg0F5ls7

**Comment by rborn** [comment]
Add some code examples please

**Comment by GuilleDF** [comment]
Is the snack not enough? What code do you want me to show exactly?
