### ISSUE TITLE
Fatal exception: Error while updating property 'region' of a view managed by: AIRMap com

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-community/react-native-maps#2551]
### Is this a bug report?
yes!

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

yes

### Environment

```
    react-native: 0.55.1
    react: 16.0.0
react-native-maps: 0.21.0
```

### Steps to Reproduce

(Write your steps here:)
```
  getMapRegion = () => ({
    latitude: this.props.latitudeMap,
    longitude: this.props.longitudeMap,
    latitudeDelta: 0.015*5,
    longitudeDelta: 0.0121*5,
  });

render() {
    return (
    <MapView
         provider={PROVIDER_GOOGLE}
         style={styles.map}
         region={this.getMapRegion()}
         customMapStyle={mapStyle}
       >
       </MapView> 
})
```

### Expected Behavior

Map doesn't crash and doesn't send errors

(Write what you thought would happen.)

### Actual Behavior

Getting such error: ` java.lang.RuntimeException
com.facebook.react.bridge.JSApplicationIllegalArgumentException. Fatal exception: Error while updating property 'region' of a view managed by: AIRMap com`

(Write what happened. Add screenshots!)

**Comment by rborn** [comment]
@Luckygirlllll Can you add more info from the error log?

**Comment by rborn** [comment]
@Luckygirlllll are you passing the props correctly ? 
You can also try without a function calling the props directly
