### ISSUE TITLE
app crash after build complete with this error java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions

### ISSUE THREAD

**Issue by peyman-hakemi** [react-native-community/react-native-maps#2562]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.55.4
    react: "16.0.0-beta.5"
	react-native-maps: 0.21.0 

  Target Platform:  Android 6.0/nexus 5x/Android Studio etc

### Steps to Reproduce

my project not open source and im working on it long time ago
but i can tell you witch dependency im using

    "appcenter": "1.7.1",
    "appcenter-analytics": "1.7.1",
    "appcenter-cli": "1.1.1",
    "appcenter-crashes": "1.7.1",
    "appcenter-push": "1.7.1",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "mobx": "3.3.2",
    "mobx-react": "4.3.5",
    "native-base": "2.3.3",
    "react": "16.0.0-beta.5",
    "react-addons-update": "15.6.2",
    "react-native": "0.55.4",
    "react-native-auto-height-image": "1.0.0",
    "react-native-communications": "2.2.1",
    "react-native-custom-picker": "0.3.1",
    "react-native-device-info": "0.14.0",
    "react-native-easy-toast": "1.0.9",
    "react-native-fs": "2.11.18",
    "react-native-immediate-phone-call": "1.0.0",
    "react-native-linear-gradient": "2.4.0",
    "react-native-maps": "0.21.0",
    "react-native-modal": "4.1.1",
    "react-native-progress": "3.4.0",
    "react-native-restart": "0.0.7",
    "react-native-settings": "0.0.1-alpha5",
    "react-native-snap-carousel": "3.7.5",
    "react-native-sound": "0.10.9",
    "react-native-splash-screen": "3.0.6",
    "react-native-svg": "6.3.1",
    "react-native-text-hypertext": "0.15.0",
    "react-native-timer": "1.3.1",
    "react-native-version-number": "0.3.0",
    "react-native-wheel-picker": "1.2.0",
    "react-navigation": "1.0.0-beta.15",
    "rn-fetch-blob": "0.10.13",
    "superagent": "3.7.0"

### Expected Behavior

im expect that my project just open like before and work fine. my project build succefuly and my packager load 100% 

### Actual Behavior

after packager load complete my app get crash with this error
java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions

### My thought

its look like somthing in here (my guest is react native maps google play services) and google play services base not match
my project work just fine a week ago but not work know.

+--- com.google.android.gms:play-services-gcm:11.8.0
+--- com.google.android.gms:play-services-location:11.8.0
+--- project :react-native-maps
|    +--- com.google.android.gms:play-services-base:10.2.4 -> 16.0.1
|    |    +--- com.google.android.gms:play-services-basement:16.0.1
+--- com.google.android.gms:play-services-base:+ -> 16.0.1 (*)
|    \--- com.google.android.gms:play-services-basement:[11.0.4] -> 16.0.1 (*)

and my build gradle 

```
compile project(':rn-fetch-blob')
    compile project(':react-native-linear-gradient')
    compile(project(':react-native-svg')) {
        exclude group: "com.android.support", module: "appcompat-v7"
    }
    compile project(':react-native-settings')
    compile 'com.airbnb.android:lottie:2.5.1'
    compile project(':react-native-fs')
    compile project(':react-native-splash-screen')
    compile project(':react-native-maps')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
	compile 'com.facebook.fresco:animated-base-support:1.3.0'
    compile 'com.facebook.fresco:animated-gif:1.3.0'
    compile 'com.google.android.gms:play-services-gcm:11.8.0'
    compile "com.google.android.gms:play-services-base:+"
    compile 'com.google.android.gms:play-services-location:11.8.0'
    compile 'com.google.android.gms:play-services-maps:+'
    compile project(':react-native-version-number')
    compile project(':react-native-wheel-picker')
    compile project(':react-native-immediate-phone-call')
    compile project(':appcenter')
    compile project(':appcenter-crashes')
    compile project(':appcenter-analytics')
    compile project(':appcenter-push')
    compile project(':react-native-device-info')
    compile project(':react-native-restart')
    compile project(':react-native-sound')
```

thanks in advance

**Comment by siderakis** [comment]
I'm getting similar errors on Android, were you able to fix this?

**Comment by luisfuertes** [comment]
+1

**Comment by rborn** [comment]
Closing as it's fixed by https://github.com/react-native-community/react-native-maps/pull/2587
