### ISSUE TITLE
[Android] IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by todorone** [react-native-community/react-native-maps#2564]
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.56.0
react: 16.4.1
react-native-maps: 0.22
platform: Android

### Steps to Reproduce

Bug is rare and hard to catch. Probably connected with dynamic markers, adding/removing them dynamically on map.

### Expected Behavior

No bugs.

<img width="626" alt="screen shot 2018-10-29 at 10 47 49 am" src="https://user-images.githubusercontent.com/423701/47638718-04e50600-db68-11e8-883b-1d889d3f3b14.png">

**Comment by mluedke2** [comment]
I believe this is the issue solved by [this PR](https://github.com/react-community/react-native-maps/pull/2545). It was merged after release 0.22.0.

Until it's in a release, I use this in my `package.json`:

`"react-native-maps": "git://github.com/react-community/react-native-maps.git#fc3cf881450c91e494abe06c602ed680655f8d18",`

**Comment by Balasnest** [comment]
Is this resolved? Facing this problem in android.

**Comment by dragneel30** [comment]
I am experiencing this now in 0.24.0 react-native-maps

**Comment by haithem-rihane** [comment]
I am alse experiencing this now in 0.24.0 react-native-maps

**Comment by haithem-rihane** [comment]
I have resolved by fixing import

from

`import MapView, Marker  from "react-native-maps";`

to

`import MapView, { Marker } from "react-native-maps";`
