### ISSUE TITLE
Support for tileSize in UrlTile props

### ISSUE THREAD

**Issue by albullington** [react-native-community/react-native-maps#2567]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.57.1
    react: 16.5.0
    react-native-maps: 0.22.0

  Target Platform: iOS Simulator and iOS 12 on iPhone SE, using AppleMaps

### Steps to Reproduce

1. Followed the [Tile Overlay example](https://github.com/react-community/react-native-maps#using-a-custom-tile-overlay) to add a urlTemplate to my project.
2. Checked on simulator and test devices, including an iOS 12 - iPhone SE. Tiles showed up on the map, but they were choppy with a line running vertical and horizontal, as in the screenshot below. 
3. Checked on Android 6 -- no issues. 
4. I was able to fix this issue by adding support for tileSize in this file `react-native-maps/lib/ios/AirMaps/AIRMapUrlTile.m`, using the following line of code after line 62: 

```
self.tileOverlay.tileSize = CGSizeMake(512, 512);
```

### Expected Behavior

![img_d99797ac3d11-1](https://user-images.githubusercontent.com/35536439/47756576-efeb9e00-dc5f-11e8-8c07-7552917b2369.jpeg)

Tile size 512 should be supported so tiles render correctly on AppleMaps/iOS. Ideally, there would be a tileSize prop built into the [UrlTile component](https://github.com/react-community/react-native-maps/blob/72b0f77e31d18959e91acb036d5f91ab46e11ef2/lib/components/MapUrlTile.js) like there is for local tiles. 

### Actual Behavior
![img_1458](https://user-images.githubusercontent.com/35536439/47756147-2d4f2c00-dc5e-11e8-9a35-4eae7febb358.jpg)

512 tiles did not render correctly; the map appeared to have vertical and horizontal lines running through the center, as shown above. 

### Reproducible Demo

```
import React from "react";
import { View } from "react-native";
import MapView, { PROVIDER_DEFAULT, UrlTile } from "react-native-maps";

const LocationMap = ( { region, id } ) => (
  <View>
    <MapView
      region={region}
      provider={PROVIDER_DEFAULT}
      style={styles.map}
      zoomEnabled={false}
      rotateEnabled={false}
      scrollEnabled={false}
      maxZoomLevel={7}
    >
      <UrlTile
        urlTemplate={"https://api.inaturalist.org/v1/colored_heatmap/{z}/{x}/{y}.png"}
      />
    </MapView>
  </View>
);

export default LocationMap;
```

**Comment by rborn** [comment]
@albullington are you sure this is not already working ? https://github.com/react-community/react-native-maps/blob/108bf755ba0ff0a7b9cdc1b6d29d9d9593b44ffe/README.md#tile-overlay-using-local-tiles  (I didn't test, I'm just asking)

**Comment by albullington** [comment]
@rborn there seems to be support for tileSize if you're able to save the tiles locally, but not for urlTemplate.

**Comment by shrikantkunte** [comment]
@rborn can we change default map view to satellite or terrain view?
