### ISSUE TITLE
Zooming does not have momentum

### ISSUE THREAD

**Issue by traviswimer** [react-native-community/react-native-maps#2579]
### Is this a bug report?

No. (feature request)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

"react": "16.3.1"
"react-native": "0.55.4"
"react-native-maps": "0.22.0"

I am referring to the functionality using GoogleMaps. I have not used the native iOS maps SDK to know if it functions the same.

### Steps to Reproduce

1. Quickly pinch-to-zoom on a map view

### Expected Behavior

Zoom movement should maintain momentum. In other words, if you move your fingers quickly while pinching-to-zoom it should continue to zoom after releasing with decaying speed.

### Actual Behavior

Zooming stops immediately after lifting your fingers.

### Reproducible Demo

To understand this issue, look at how zooming works on the official Google Maps app. Zooming is very intuitive because the speed of your "pinching" increases the speed of the zoom.

With the current implementation of `react-native-maps`, zooming from the highest level to the lowest could take about 10 pinches. On Google Maps it would be around 3.

I tried to get a good screen-capture, but couldn't find an app that worked well. So, let me know if my explanation was not clear.

**Comment by traviswimer** [comment]
@rborn Is this feature available now in the latest version, or why was it closed? Thanks.

**Comment by rborn** [comment]
I don't think it is, I just cleanup the repo from very old issues and yours was a victim of this. 
If you think is important please open a new one following the new template.
Thanks and sorry for any annoyance 😻
