### ISSUE TITLE
Polyline component API don't work?

### ISSUE THREAD

**Issue by maihonganh1997** [react-native-community/react-native-maps#2583]
### Is this a bug report?
maybe yes or no

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)
Yes
### Environment
 react-native: 0.57.4
 react: 16.6.0-alpha.8af6728
react-native-maps: 0.22.1
Target Platform: Android 5.1.1

### Steps to Reproduce

I tried below but application stop

` constructor(props) {
        super(props);

        this.state = {
            coordinate: {
                latitude: 10.764929,
                longitude: 106.697514,
            },
            arrayPolyline : [
                {
                    latitude: 10.764929,
                    longitude: 106.697514
                },
                {
                    latitude: 10.7595885,
                    longitude: 106.68939
                }

            ]
        };
    }`

` <Polyline
                    coordinates={this.state.arrayPolyline}
                    strokeWidth={2}
                    strokeColor={"#1727ff"}
/>
`

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jmanuelhk** [comment]
i have the same problem in android 8.1.0 and react native maps v0.22.0
