### ISSUE TITLE
[Android] App crashes on launch. rn-firebase + rn-maps

### ISSUE THREAD

**Issue by joseguya** [react-native-community/react-native-maps#2584]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

OS: macOS Mojave 10.14.1
React Native: 0.57.4
react-native-maps: 0.22.1
react-native-firebase: 5.1.0

### Steps to Reproduce

I have this top build.gradle:

`buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        jcenter()
    }
    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath 'com.google.gms:google-services:4.0.1'
    }
}

allprojects {
    buildDir = "$rootDir/build/${rootProject.name}/${project.name}"
    repositories {
        google()
        mavenLocal()
        maven { url 'https://maven.google.com' }
   
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://maven.fabric.io/public' }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }     
        jcenter()
    }
}
`

And this /app/build.gradle:

`
android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "py.com.kynox.pelotajara"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 138
        versionName "1.3.8"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }

    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    dexOptions {
        dexInProcess = false
    }
    flavorDimensions "devStages"

    productFlavors {
        dev {
            applicationIdSuffix ".dev"
            versionNameSuffix "-dev"
            println "Using Dev google-service.json"
            copy {
                from 'src/dev/'
                include '*.json'
                into '.'
            }
            copy {
                from 'src/dev/'
                into 'src/main/'
                include 'res/**'
            }
            dimension "devStages"

        }
        prod {
            applicationIdSuffix ""
            versionNameSuffix ""
            println "Using Production google-service.json"
            copy {
                from 'src/prod/'
                include '*.json'
                into '.'
            }
            copy {
                from 'src/prod/'
                into 'src/main/'
                include 'res/**'
            }
            dimension "devStages"
        }
        staging {
            applicationIdSuffix ".staging"
            versionNameSuffix "-staging"
            println "Using Staging google-service.json"
            copy {
                from 'src/staging/'
                include '*.json'
                into '.'
            }
            copy {
                from 'src/staging/'
                into 'src/main/'
                include 'res/**'
            }
            dimension "devStages"
        }
    }
}

dependencies {
    /* PLAY SERVICES */
     implementation "com.google.android.gms:play-services-base:16.0.1"

    /* FIREBASE */
    implementation project(':react-native-firebase')
    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation "com.google.firebase:firebase-invites:16.0.4"
    implementation "com.google.firebase:firebase-config:16.1.0"

    /* RN AND OTHER LIBRARIES*/
    implementation 'com.facebook.react:react-native:+'
    implementation project(':lottie-react-native')
    implementation project(':react-native-view-shot')
    implementation project(':react-native-share')
    implementation project(':react-native-vector-icons')
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms'
    }
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-fabric')
    implementation('com.crashlytics.sdk.android:crashlytics:2.6.3@aar') {
        transitive = true;
    }
    implementation(project(':react-native-fbsdk')) {
        exclude(group: 'com.facebook.android', module: 'facebook-android-sdk')
    }
    implementation 'com.facebook.android:facebook-android-sdk:4.31.0'
    implementation ("com.google.android.gms:play-services-maps:+") {
        force = true;
    }
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.android.support:multidex:1.0.1'
    implementation fileTree(include: ['*.jar'], dir: 'libs')

}
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
`

### Expected Behavior

The app should run without crashing

### Actual Behavior

App crashes on launch, logcat throws this error: 

> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;

### Reproducible Demo

Just install react-native-firebase with react-native-maps

**Comment by Titozzz** [comment]
There is no version 16.0.1 for com.google.android.gms:play-services-maps, so that might be an issue.

I'm gonna create a fork to address that issue.

**Comment by Titozzz** [comment]
There you go, please test it by using 
`yarn add react-native-maps@https://github.com/Titozzz/react-native-maps.git#cf5c310fa8655f04b4389fa48190b110d498f1c4`

#2587

**Comment by joseguya** [comment]
Thanks! I'll try it and let you know.

**Comment by Titozzz** [comment]
you need to specify googlePlayServicesMapsVersion as said inside the PR

**Comment by joseguya** [comment]
I'm still getting: 

> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;

My top project's build.gradle has this on top: 
`ext {
    googlePlayServicesVersion = "16.0.1"
    googlePlayServicesAuthVersion = "16.0.1"// this is how react-native-google-signin does 
    googlePlayServicesMapsVersion = "16.0.0"
}
`

And my dependencies: 

`dependencies {
    /* FIREBASE */
    implementation project(':react-native-firebase')

    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation "com.google.firebase:firebase-invites:16.0.4"
    implementation "com.google.firebase:firebase-config:16.1.0"

    /* PLAY SERVICES */
    implementation ("com.google.android.gms:play-services-base:16.0.1")
    implementation ("com.google.android.gms:play-services-maps:16.0.0")


    /* RN AND OTHER LIBRARIES*/
    implementation 'com.facebook.react:react-native:+'
    implementation project(':lottie-react-native')
    implementation project(':react-native-view-shot')
    implementation project(':react-native-share')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-maps')
    `

**Comment by joseguya** [comment]
Nevermind, some misconfigurations on react was breaking the app. That PR really helped! Thanks!

**Comment by luisfuertes** [comment]
@Titozzz PR works! Thanks!

**Comment by SimVanLee** [comment]
@Titozzz You saved me ! Thanks so much. 
My crash occured with RN Maps and RN Push Notifications on launch

**Comment by arapocket** [comment]
@Titozzz Thank you, sir.

**Comment by pabloLarios24** [comment]
i have this problem Could not find com.google.android.gms:play-services-vision:16.0.1
