### ISSUE TITLE
Image marker not show in android version 8.0  when Build Android target sdk version 26  

### ISSUE THREAD

**Issue by i3IGm** [react-native-community/react-native-maps#2586]
react-native": "^0.46.4"
react-native-maps: "^0.17.1"

**Comment by Vishaldhanotiya** [comment]
Hello @i3IGm  You can use [this](https://www.npmjs.com/package/react-native-svg)    

> <MapView.Marker
>                 key={index}
>                 coordinate={{
>           latitude: marker.latitude,
>           longitude: marker.longitute,
>         }}
>                 onPress={() => this.markerClick (index)}
>               >
> <Svg width={90} height={90}>
>         <Imagesvg href={require ('../../../res/images/ic_selected_location.png')} width={90} height={90} /> 
>       
>     </Svg>
>    </MapView.Marker>

**Comment by alexpopa-work** [comment]
Didn't work for me. I have tried all the possible solutions found online and the problem persists...

**Comment by Vishaldhanotiya** [comment]
Hello @alexpopa-work 

You can try this force to re-render image after it is loaded the first time.

`<MapView.Marker key={index} coordinate={{ latitude: marker.latitude, longitude: marker.longitute, }} ><ImageBackground`   style={{width:0, height:0}}
                        onLoad={() => this.forceUpdate()}>
     <Text style={{width:0, height:0}}>{Math.random()}</Text>
</ImageBackground>
                      <Svg width={60} height={60}>
                        <Imagesvg
                          href={require ('../../../res/images/ic_selected_location.png')}
                          width={60}
                          height={60}
                        />

                      </Svg></MapView.Marker>`

**Comment by vladinko0** [comment]
I solved this issue by replacing 16-bit gamma integer Image with 8-bit gamma integer Image. It can be done in Gimp, once exporting Image select 8bpc RGBA.

**Comment by akshaygpta007** [comment]
https://github.com/react-native-community/react-native-maps/issues/1870#issuecomment-485329883

check above comment

**Comment by faustoct** [comment]
This worked for me
````
<Marker coordinate={region} tracksViewChanges={false} >
              <View>
                <View style={{borderRadius: 5, backgroundColor: '#000', padding: 5, marginBottom: 3}}>
                  <Text style={{color:'#fff',fontWeight: 'bold', fontSize: 12, textAlign:'center'}}>{title}</Text>
                </View>
                <View style={{flex: 0, flexDirection: 'row', alignSelf: 'center', borderColor:'#000', borderWidth: 1, borderRadius: 5, zIndex:1, backgroundColor: '#000'}}>
                  <ImageBackground style={{width:32, height:32, borderRadius: 5}} resizeMode={'cover'} source={pic}>
                    <Text style={{width: 0, height: 0}}>{Math.random()}</Text>
                  </ImageBackground>
                </View>
                <View style={{backgroundColor: 'transparent', borderWidth: 4, borderColor: 'transparent', borderTopColor: '#000', alignSelf: 'center', marginTop: -1}} />
              </View>
            </Marker>
                    // **** This line is very very important ****
                    <Text style={{width: 0, height: 0}}>{Math.random()}</Text>

                </ImageBackground>

````
Replace `Image` for `ImageBackground`
