### ISSUE TITLE
iOS Error : Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_GMSServices", referenced from:  objc-class-ref in AppDelegate.o

### ISSUE THREAD

**Issue by vivekshah-zymr** [react-native-community/react-native-maps#2590]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
	"react-native-maps": "^0.22.1",

###  Target Platform: 

 iOS - 12.0 Simulator/iPhone XR
 Apple map works fine, But I want to use google maps. And that gives me error.

### Steps to Reproduce

I just add 'react-native-maps' in the project, setup CocoaPods and add enable google map from AppDelegate.m but this step gives me error like below.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GMSServices", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Expected Behavior

  It should run, and display google map on iPhone.

**Comment by rborn** [comment]
Very old issue, closing. Please re-open if you still have it.

**Comment by geekymsk** [comment]
i have the same issue. any solution?

**Comment by geekymsk** [comment]
i have the same issue? any solution @vivekshah-zymr @rborn. please help

**Comment by geekymsk** [comment]
i got it solved by adding $(inherited) in 
BuildSettings->Linking->Other Linker Flags.

**Comment by rizwanatta** [comment]
this needs to be reopened! I am stuck . on it like from 2 days nothing on google helped

**Comment by rizwanatta** [comment]
@rborn did anybody had a solution?

**Comment by rajaiosrg** [comment]
can some one tell me the solution if it worked?
i was trying with xcode11 too, still i am facing this.

**Comment by mochadwi** [comment]
still facing this issue in m1

**Comment by balaganeshbala** [comment]
Adding these in Other Linker Flags fixes this issue:

`-l"c++" -framework GoogleMaps -framework GoogleMapsBase -framework GoogleMapsCore`

<img width="613" alt="Screenshot 2022-07-22 at 12 04 41 PM" src="https://user-images.githubusercontent.com/6623097/180378375-ac295b98-3be4-4803-919c-192af16fa699.png">
