### ISSUE TITLE
Tappable Polyline (android)

### ISSUE THREAD

**Issue by Escarpe** [react-native-community/react-native-maps#2591]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.55.4
    react: 16.3.1
    react-native-maps: 0.22.1

### Steps to Reproduce

Create MapView
Add onPress event on MapView
Create Polyline
Run android version
Tap on Polyline
Check what happened

### Actual Behavior

Polyline doesn't have ability to turn off "tapable"
When i want to tap on MapView through Polyline i can't do this.
And when i add onPress to Polyline i'm getting coordinates only for first point ( i need coordinates where i tap )
Maybe u can add "tappable" prop to Polyline, like in Polygon

**Comment by jmanuelhk** [comment]
in what way it implements polyline in android ?. my App closes when i add it. i have v.0.22.0 react native maps.

**Comment by techieyann** [comment]
Bumping. Setting tappable={false} on a Polyline does not allow me to capture the map onPress event.
