### ISSUE TITLE
Crash in latest expo

### ISSUE THREAD

**Issue by EgorZotov** [react-native-community/react-native-maps#2593]
### Is this a bug report?
Yes
(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
react-native-maps@0.22.1,
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz"

### Steps to Reproduce

1. Build standalone app with Expo. 
2. Open mapview in app.
3. App crashes.

Map is working fine on Android standalone and expo app for both platforms. But crashes in ios standalone. 
### Expected Behavior
App not crashing.
![llpubm2g_je](https://user-images.githubusercontent.com/23280344/48773526-b34c1900-ecd8-11e8-981a-6d09daa858be.jpg)

### Actual Behavior
App crashed to homescreen without any error.

### Reproducible Demo
I need some time to assemble demo. But i will add logs from device when app crash. Maybe it will help to figure out problem.
```
ошибка    13:57:26.871693 +0300    SpringBoard    HW kbd: Failed to set (null) as keyboard focus
ошибка    13:57:26.910430 +0300    assertiond    [com.apple.WebKi:2455] SyscallError: setpriority(PRIO_DARWIN_ROLE, 2455, 3): No such process
ошибка    13:57:26.927033 +0300    assertiond    [com.apple.WebKi:2456] SyscallError: setpriority(PRIO_DARWIN_ROLE, 2456, 3): Operation not supported
ошибка    13:57:27.111157 +0300    symptomsd    Can't get most elevated app state from dictionary {
    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "com.carbiru.carbi";
    SBApplicationStateKey = 0;
    SBApplicationStateProcessIDKey = 2454;
    SBApplicationStateRunningReasonsKey =     (
                {
            SBApplicationStateRunningReasonAssertionIdentifierKey = Resume;
            SBApplicationStateRunningReasonAssertionReasonKey = 10000;
        }
    );
}
```

UPDATE: I was using google maps and it was the reason of crash. After switch to ios native maps everything working. But it will be good if we can figure out something for google.

**Comment by mchirlin** [comment]
I am also having this same issue, google maps are crashing on ios standalone.

**Comment by wcandillon** [comment]
I'm experiencing the same issue since the upgrade to SDK31. Unfortunately, in my case, I cannot really switch to Apple maps. Could it be that now providing an api key on iOS is mandatory?

**Comment by checkmatez** [comment]
@EgorZotov I feel there is a solution to this: https://forums.expo.io/t/how-to-set-googlemaps-with-gmsservices-provideapikey/17770/3?u=syndicate
Basically, set GoogleApiKey in app.json under "ios": {"config": {}}

**Comment by wcandillon** [comment]
Yes I tried it and I can confirm that this is the solution. It used to work without the key.

**Comment by rborn** [comment]
Closing, old issue.
