### ISSUE TITLE
initialRegion not respected when having a lot of markers - Android

### ISSUE THREAD

**Issue by compojoom** [react-native-community/react-native-maps#2595]
I have a map with specified initialRegion. On iOS this works as expected - my map starts at the specified region. On Android however I first see the world map at 0,0 and then it jumps to the region I've specified. This only happens when my map has a lot of markers. If I render just few - the map on android also starts at the expected location.

### Is this a bug report?
Yes

### Environment
    react-native: 0.57.0
    react: 16.6.0
	react-native-maps: 0.22.1
  Target Platform: Android

### Steps to Reproduce
I've created a reproducible demo here:
https://github.com/compojoom/react-native-maps/tree/initial_region_markers_bug

Follow the normal example setup to run the example
https://github.com/compojoom/react-native-maps/blob/initial_region_markers_bug/docs/examples-setup.md

then go to the Custom markers demo

### Expected Behavior
The map should start at the specified initialRegion

### Actual Behavior
The map starts at 0,0 and jumps to initailregion

### Reproducible Demo
https://github.com/compojoom/react-native-maps/tree/initial_region_markers_bug

**Comment by rborn** [comment]
Wait for the map to trigger `onMapReady` and then try to add the markers

**Comment by compojoom** [comment]
My original code has onMapReady={() => {
this.setState({mapReady: true})
}}
and I was only rendering the markers when mapReady. But this is not helping...

I just pushed this version as well:
https://github.com/compojoom/react-native-maps/commit/bc8d969c56ca6c3a14afc022df01c9aae4ba4e7f

**Comment by rborn** [comment]
is `onRegionChangeComplete` triggered when the map reached the initialRegion? maybe use that?

**Comment by compojoom** [comment]
@rborn - sorry I don't really follow with the `onRegionChangeComplete`? What do you want me to do there? I only see one region - but the map switches from world map to the specified region?

The funny thing is that with our app in debug mode it was often appearing correct, but in release mode it was always displaying first 0,0 and then switching to the specified region. But anyway - what does the slowness of debug mode has to do with this? Isn't the initialRegion the one  that should render immediately?

**Comment by rborn** [comment]
My understanding is that the map starts with 0,0 and then it animates to initialRegion (no idea why :| ).
By `onRegionChangeComplete` I was thinking to use it instead of `onMapReady` to set the flag and load the markers

**Comment by compojoom** [comment]
Okay, if I use onRegionChangeComplete to set the mapReady state to true, then the map loads at the correct region.....

So is this a bug, or expected behavior or what?

**Comment by rborn** [comment]
I don't think it's a bug, but more a performance issue due to the js-native bridge.
The map is trying to get to the initial region but because you set all the markers upfront it will wait for the bridge to finish sending the whole data (markers) and then move to initialRegion.

At least that's how I see things. It works now correctly ?

**Comment by compojoom** [comment]
Yes, now it works correctly. At least the demo. Have to check in the real app.

What's the point of specifying a region when the map is going to load at 0,0 first?

The google maps js api doesn't do that if you specify the initial coordiantes of the map. it's strange that the android sdk does this.

**Comment by rborn** [comment]
The js map has nothing to do with the native one.

Also all you do in RN has a cost of crossing the bridge, so be aware of this for anything you do, not only the map.

Why it loads with 0.0 might be something in the google sdk or the way is implemented in the module (maybe to avoid some undefined starting point), I don't know.

**Comment by compojoom** [comment]
The current behavior is not something that someone would expect. In our app I'm rendering just 10 markers - they are all rendering a custom view. So I initially thought that it was the custom marker, until I realized that it happens with the normal markers as well. 

So mapReady is firing so early, but the map is obviously not ready. so  mapReady is worthless in this case. 

How should someone new to the library figure this out? It's not documented anywhere, it's not intuitive that this is the error. Moreover it behaves correctly on iOS with google maps... So imagine the surprise when someone tests on iOS and then comes to android and sees this... 

You can close the issue if you feel that this is not a bug, but I've seen several places where people were wondering why the initialRegion was not respected and that is most probably the reason. I don't know how the native android maps work, but this feels like a bug to me and not something I would expect in the native sdk.

**Comment by rborn** [comment]
Usually iOS behaves but Android not so much.

I agree with you. It's frustrating but it is what it is. 
We do whatever we can with the resources we have to make it work (sometimes they are workarounds like this one)
When the modules are supported by companies or individuals and they evolve well and are maintained  everybody rushes to use it very happily , but when the module moves to the community and it becomes a matter of each of us to bring their own contribution, well... the happiness is not happening anymore 😕

If you think this is something that should be present in the documentation please add it in the troubleshooting section, make a PR and I'll review it.

**Comment by MelanieJourne** [comment]
Hello,
I have the same problem as you do for about 100+ markers. The map is at 0,0 for almost 8 seconds.

Can your provide the sample code you use to solve the problem ? 
When I put the marker creation after the `onRegionChangeComplete` is completed, the markers don't appear...

Thanks a lot

**Comment by limatheusm** [comment]
> I don't think it's a bug, but more a performance issue due to the js-native bridge.
> The map is trying to get to the initial region but because you set all the markers upfront it will wait for the bridge to finish sending the whole data (markers) and then move to initialRegion.
> 
> At least that's how I see things. It works now correctly ?

Thank you! It's exactly behavior in my case.

**Comment by alx1024** [comment]
Hi! I know this is old, but I got around the problem by first just getting the geolocation and setting the region/initialRegion, so the map loads fast by just getting those and is centered on a valid point, then in "componentDidUpdate" i call the function to load the markers, that way the map loads with the correct user position instead of (0,0), then the markers show up a bit later, which imo has a nicer UI look to it than the map starting zoomed out at (0,0), the second render does not flicker and looks nice
