### ISSUE TITLE
FollowsUserLocation and showUserLocationButton not working (both platforms)

### ISSUE THREAD

**Issue by gusoskar** [react-native-community/react-native-maps#2596]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Steps to Reproduce

I have this is my MapView configuration

              <MapView
                ref={ map => { this.map = map }}
                style={styles.map}
            	initialRegion={initialRegion}
            	showsUserLocation={true}
            	followsUserLocation={true}
                showsMyLocationButton={true}
                 >
               </MapView>

### Expected Behavior

1. The "my location" button is showing
2. The map follows user location

### Actual Behavior

1. The location button is not showing on iOS, on Android it is showing when device is rotated to landscape. The button on Android doesn't seem to be working though.
2. The follow location is working on iOS, but no on Android

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by joaodematejr** [comment]
+1   I'm going through the same problem

    "react": "16.6.3",
    "react-native": "0.58.5",
    "react-native-maps": "^0.23.0",

**Comment by CesarDenis** [comment]
+1 Same problem
```
"react": "16.6.3",
"react-native": "0.58.5",
"react-native-maps": "^0.23.0",
```

**Comment by emech-en** [comment]
+1 Same problem
```
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-maps": "^0.25.0",
```

 @CesarDenis @joaodematejr Any updates?

**Comment by RZsam** [comment]
+1  same 
  
      "react": "16.8.6",
      "react-native": "^0.61.1",
      "react-native-maps": "0.25.0",

**Comment by cosmarc** [comment]
+1 same 
```
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-maps": "^0.25.0",
```

**Comment by markymc** [comment]
I looked into the source and it seems that `followsUserLocation` isn't supported in Google Maps, unless I'm missing something? I'll create an issue.

**Comment by hamedABS** [comment]
same problem

`   "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-maps": "0.25.0",
`

**Comment by tafelito** [comment]
followsUserLocation only works on iOS using Apple Maps, not Google's

**Comment by markymc** [comment]
I opened an issue a while ago regarding the documentation needing to be updated at https://github.com/react-native-community/react-native-maps/issues/3206

**Comment by rborn** [comment]
Closing, please check https://github.com/react-native-community/react-native-maps/pull/3371
