### ISSUE TITLE
animateToX functions should return a promise after the animation is finished

### ISSUE THREAD

**Issue by BrodaNoel** [react-native-community/react-native-maps#2600]
### Is this a bug report?
**No.** It is a Feature Request.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes (even the [TS file](https://github.com/react-community/react-native-maps/blob/39c994fdea83b02392fb908938a9bca2b083e6be/index.d.ts#L219))

### Environment
"expo": "^31.0.0"
"react": "16.5.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz"
Target Platform: All
Using Google Maps

### Steps to Reproduce
N/A

### Expected Behavior
`animateToX` functions should return a promise after the animation is finished.

Example of use:
```js
this.map.animateToRegion(region, duration).then(() => {
  // things
});
```

### Actual Behavior
Function returns `void`

### Reproducible Demo
N/A

**Comment by BrodaNoel** [comment]
@rborn done

**Comment by rafaeluzzi** [comment]
+1
