### ISSUE TITLE
MapView.Marker not show on ios 

### ISSUE THREAD

**Issue by jituumaria** [react-native-community/react-native-maps#2604]
<MapView.Marker
                                                      coordinate={{ latitude: Number(marker.merchant.store_lat) === null ? LATITUDE:Number(marker.merchant.store_lat), longitude: Number(marker.merchant.store_lng) === null ? LONGITUDE:Number(marker.merchant.store_lng) }}
                                                      key={marker.id}
                                                      image={imgCurrentLoc}
                                                      >

                                                      <MapView.Callout tooltip={false}
                                                      onPress={() => this.markerClick(marker)}
                                                      >
              ........

  </MapView.Callout>
                                                     
                                                      </MapView.Marker>

**Comment by radeno** [comment]
@jituumaria format your code and add your environment versions
