### ISSUE TITLE
Programatically select a marker?

### ISSUE THREAD

**Issue by allthetime** [react-native-community/react-native-maps#261]
Hi, I want to be able to select a marker via some interface that is not the marker itself, so that it is pulled forward and rests on top of the others. Is this possible?

**Comment by esutton** [comment]
I use this to programmatically show a marker callout.

        `this.refs[markerSelected.label].showCallout();`

https://github.com/lelandrichardson/react-native-maps/blob/master/docs/marker.md

**Comment by allthetime** [comment]
That brings up the callout, but doesn't actually bring the marker to the forefront. 

What I have is, depending on the current zoom of the map, markers crowding each other, and I'm looking for a way to bring one of those markers on top of the others without having to physically touch it (which may be difficult or nearly impossible to do because of the grouping of the markers).

**Comment by jrichardlai** [comment]
@allthetime seems that its not possible without showing the infowindow http://stackoverflow.com/questions/14771569/google-maps-v2-marker-zordering-set-to-top/14771740#14771740

**Comment by esutton** [comment]
I also need a solution to markers crowding each other.  I think this will be a challenging problem to solve.

**Comment by kesha-antonov** [comment]
<img width="744" alt="screen shot 2016-09-12 at 12 31 02" src="https://cloud.githubusercontent.com/assets/11584712/18431250/d2080760-78e4-11e6-9608-8015d3a18b15.png">

**Comment by kesha-antonov** [comment]
Hello guys!

I have another use case:
1. User touch map and set marker
2. User try drag marker (and he can't because it's not selected yet)
3. He tries drag again and succeeded.

So question is "how to preselect marker"?

**Comment by edward8628** [comment]
I write something like <MapView.Marker style={{zIndex: 1}}> if this marker is the current marker, otherwise zIndex: 0

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by brandon-austin-lark** [comment]
wondering if anyone has found a solution for this?
