### ISSUE TITLE
map marker

### ISSUE THREAD

**Issue by fatemehmemar123** [react-native-community/react-native-maps#2611]
hi,
i want the marker's image change when the user moves the map
Generally i have two marker's image
when map fixed one marker's image show and
when map move another one show

**Comment by rborn** [comment]
@fatemehmemar123  please stop reposting the same issue  (https://github.com/react-community/react-native-maps/issues/2610).

I closed you r previous one for not following the template which it seems you didn't do it the second time either. Please update your issue with that or I'll also close it

**Comment by EricPKerr** [comment]
You'll do something like:

```
onRegionChange = () => {
  this.setState({regionChanged: true});
}

render() {
<MapView
  onRegionChange={this.onRegionChange}
  ...>
  <Marker image={this.state.regionChanged ? 'image1' : 'image2'}
</MapView>
}
```
