### ISSUE TITLE
Support React Native 0.56> and Babel 7

### ISSUE THREAD

**Issue by bithavoc** [react-native-community/react-native-maps#2613]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.57.7
    react: 16.6.1
    react-native-maps: 0.22.1 or master c68fadbda7410d6153bd9da885b068940167c6b3

### Steps to Reproduce

1. Create a new project using `react-native init`.
2. Add `yarn add react-native-maps@0.22.1`.

### Expected Behavior

The project should run successfully when running from Xcode or the Command Line.

### Actual Behavior

Fails to compile in Simulator or Device since `react-native-maps` still depends on Babel6 `babel-preset-react-native`.

`react-native-maps` should depend on `metro-react-native-babel-preset`.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by radeno** [comment]
@bithavoc are you sure?
We are using React Native Maps on React Native 0.57.7 without any issue. `babel-preset-react-native` is dev dependency, then is not use.

**Comment by rborn** [comment]
The module works with RN 0.57.+, it's a matter of your settings
