### ISSUE TITLE
Google Maps on iOS is very slow

### ISSUE THREAD

**Issue by nicomontanari98** [react-native-community/react-native-maps#2616]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

 react: 16.6.3 
 react-native: 0.57.7 
 react-native-maps: 0.21.0
 Target Platform: eg: iOS - 10 Simulator/iPhone XS/iPhone 6s
 Map: GoogleMaps

### Expected Behavior

Fluid map end 60 fp/s, like Android

### Actual Behavior

Very slow map and 9 or 10 fp/s, also if i remove all markers

<img width="235" alt="schermata 2018-12-07 alle 11 58 09" src="https://user-images.githubusercontent.com/15747776/49643975-6aee6400-fa17-11e8-99c2-d575980fbbe1.png">

### Reproducible Demo

Use google maps on iOS

**Comment by SvetlozarKalchev** [comment]
It's unusable on iOS for me too. I am using **react-native 0.55.2**. I've tried using **react-native-maps 0.21.0** and **0.22.1**, but performance is atrocious with both versions. There's extremely high CPU usage when rendering even few markers (10-20). Even if I don't render any markers, the CPU usage goes to 100% when dragging the map and the frame rate drops extremely. 

This package is currently unusable if you want to show a Google map.

iOS 12, iPhone 7+ and various simulators.

**Comment by luispeerez** [comment]
I had an issue yesterday with a customer's iphone 7 plus, I have tested on iphone xr, 8, and none of those had problems with the maps, I am going to test if tracksViewChanges prop on Marker component fix the issue

**Comment by bruteforcecat** [comment]
interesting. the performance in iphone 5S, SE, 6 are faster. UI fps stay close to 60 when dragging or animating

**Comment by alexandrius** [comment]
This was best what I could come up with.

```
shouldComponentUpdate(nextProps) {
    if (this.props.activities !== nextProps.activities) {
        this.setState({ tracksViewChanges: true }, () => {
            setTimeout(() => {
                this.setState({ tracksViewChanges: false });
            }, 2000)
        })
    }
    return true;
}
```

setting tracksViewChanges: false in componentDidUpdate didn't work for me

**Comment by victormartingarcia** [comment]
We are experiencing this performance issues with Google Maps on iOS as well.

@alexandrius does this solution have any side effect? Are all markers drawn properly?

**Comment by alexandrius** [comment]
@victormartingarcia In theory it has. Markers may not be drawn in 2 seconds timeframe. 
Also method needs to be debounced

**Comment by victormartingarcia** [comment]
@alexandrius how can you debounce the shouldComponentUpdate(nextProps) lifecycle method? Do you use any library for that?

**Comment by alexandrius** [comment]
@victormartingarcia You only debounce this.setState({ tracksViewChanges: false });
I use lodash.debounce

```
constructor() {
    this._disableTracksViewChangesDelayed = debounce(this._disableTracksViewChanges.bind(this), 2000);
}

_disableTracksViewChanges() {
    this.setState({ tracksViewChanges: false });
}

shouldComponentUpdate(nextProps) {
    if (Utils.isIOS() && this.props.activities !== nextProps.activities) {
        this.setState({ tracksViewChanges: true }, () => {
            this._disableTracksViewChangesDelayed();
        })
    }
    return true;
}

```

**Comment by victormartingarcia** [comment]
@alexandrius thanks for your help. Your solution works great, but seems to me that there is a little flickering due to debounce that I managed to solve following this pretty similar solution: 

https://github.com/react-native-community/react-native-maps/issues/369#issuecomment-340334468

**Comment by victormartingarcia** [comment]
Well.. seems that other solution is not perfect either :(

![tracksviewchanges](https://user-images.githubusercontent.com/659832/50722853-ea825800-10d5-11e9-906c-2e615ed5bc34.gif)

Even though the markers do not change on the server, sometimes are not drawn on the app until next refresh (event on RegionChangeComplete).

I am pretty sure it is something related to tracksViewChanges or component lifecycle, any ideas @alexandrius ?

![tracksviewchanges](https://user-images.githubusercontent.com/659832/50722872-17366f80-10d6-11e9-8986-a82f4e64ec82.gif)

**Comment by victormartingarcia** [comment]
For those interested, I found a much better way to improve Marker performance on iOS-Google Maps.

See https://github.com/react-native-community/react-native-maps/pull/2650

**Comment by alexandrius** [comment]
@victormartingarcia thanks for suggestion. I wasn't at the computer on the weekend.
Thanks for suggestion though I was playing with idea of publishing react-native-maps with added icon prop too.
For future convenience people can use my library until this pull gets merged
https://www.npmjs.com/package/react-native-maps-icon

**Comment by nicomontanari98** [comment]
@rborn why did you close it? The problem is not resolved

**Comment by rborn** [comment]
@nicomontanari98 did you try with the last version and with the solution from https://github.com/react-native-community/react-native-maps/pull/2650? we just published 0.23 ?

**Comment by nicomontanari98** [comment]
@rborn yes, i updated it now. Thank you

**Comment by royken** [comment]
Having the same issue here. Cannot zoom the map, cannot click on marker, cannot drag the map. It is just unsusable

**Comment by royken** [comment]
I am using version 0.26, witg react-native 0.61.2
