### ISSUE TITLE
YellowBox warning on react-native 0.58.0-rc.1

### ISSUE THREAD

**Issue by vovkasm** [react-native-community/react-native-maps#2620]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.58.0-rc.1
react: 16.6.3
react-native-maps: from git, currently at commit ccd48792b74ba810b0e01c60dfc2b5c42f191e72

Target Platform: iOS (GoogleMaps)

### Steps to Reproduce

I think just launch application with embedded MapView is enough to reproduce.

### Expected Behavior

No warnings.

### Actual Behavior

Yellow box warning popups: Accessing view manager configs directly off UIManager view UIManager[‘AIRGoogleMap’] is no longer supported.

According to stack trace, warning is here: decorateMapComponent.js:35
```
export const googleMapIsInstalled = !!NativeModules.UIManager[getAirMapName(PROVIDER_GOOGLE)];
```

![warning in maps](http://vovkasm.skitch.vovkasm.org/maps-warning_21BE411D.png)

**Comment by nwaughachukwuma** [comment]
Any resolution to this yet? Cause am getting same error for UiManager[AirMapLite]

**Comment by salah-ghanim** [comment]
@nwaughachukwuma fixed on master, should be included in the next release

**Comment by nwaughachukwuma** [comment]
Alright cool. Thanks for the update

**Comment by aksonov** [comment]
@salah-ghanim I still see the warning for latest master, probably that fix was not enough:

![Screenshot_1552468067](https://user-images.githubusercontent.com/1321329/54266568-efe99c00-4577-11e9-9a15-55088bde22d6.png)

**Comment by vovkasm** [comment]
Yes, here: https://github.com/react-native-community/react-native-maps/blob/master/lib/components/MapView.js#L815

**Comment by vovkasm** [comment]
Someone can create followup to #2671. May be we can centralize this logic.

**Comment by declanelcocks** [comment]
@vovkasm Added a follow up PR https://github.com/react-native-community/react-native-maps/pull/2740 to fix the lines you mentioned.
