### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by iamdarknight** [react-native-community/react-native-maps#2622]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

All latest

### Steps to Reproduce

Use NPM version 22.1 with Camera function

### Expected Behavior

Camera props and methods on MapView should work

### Actual Behavior

NPM version has no Camera implementation yet

### _Inquiry_
When will the repo be published to npm and if not soon is it safe to use repo directly in project?

**Comment by Faggioni** [comment]
Anyone else has this issue?. Camera props don't work properly on React Native v0.57.1. Thanks in advance.. :)

**Comment by iamdarknight** [comment]
I checked the downloaded NPM module for RNMaps and it didn't have the camera implementation as the repo src files. As such i assumed that the repo was yet to be published to npm. When i tested it v22.1 had no Camera implementation.

**Comment by rborn** [comment]
You can point your package.json to the repo for now (until it gets published)

**Comment by ryanbennettvoid** [comment]
When pointing to the repo's `v0.22.1` tag, the methods don't exist. When pointing to just the repo (`master` I guess) and attempting to use a camera method, it shows the error `Cannot read property 'apply' of undefined`.

**Comment by cooperbrown9** [comment]
Hello, any updates on this? Camera isnt working for me. I get undefined when I point to the repo and try  to async this.map.getCamera()
Can anyone please help??

**Comment by congnguyen91** [comment]
+1

**Comment by congnguyen91** [comment]
I released that the issue came from my map rendered again if it received a prop=> ref is null => ref has a right value.
