### ISSUE TITLE
Getting position throwing error message: "Location request timed out"

### ISSUE THREAD

**Issue by ps0305** [react-native-community/react-native-maps#2624]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Steps to Reproduce

navigator.geolocation.getCurrentPosition((position) => {
                  console.log(position);
                }

### Expected Behavior

Suppose to get position object.

(Write what you thought would happen.)

### Actual Behavior

Getting below pasted in console.
```js
{TIMEOUT: 3, POSITION_UNAVAILABLE: 2, PERMISSION_DENIED: 1, message: "Location request timed out", code: 3}
```

(Write what happened. Add screenshots!)

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Whallas** [comment]
I'm getting the same error on an android device API 21. However, when I run in an android emulator API 28 it works well. I really don't know what happens because the permissions are automatically accepted on APIs 23 or less.

**Comment by aniksharif** [comment]
@ps0305 How did you solve it?
