### ISSUE TITLE
error: unmappable character for encoding ASCII         // ??\_(???)_/??

### ISSUE THREAD

**Issue by ziyoshams** [react-native-community/react-native-maps#2628]
I don't know where else to ask for help. Any comment or suggestion is appreciated.

I am not sure if this is a bug.

Running
```
    "react": "^16.6.3",
    "react-native": "^0.57.7",
    "react-native-maps": "^0.22.1",
```

Building for Galaxy S9
Android Studio Version 3.2.1 (Build October 8, 2018)

```
/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:136: error: unmappable character for encoding ASCII
        // ??\_(???)_/??
           ^
/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:136: error: unmappable character for encoding ASCII
        // ??\_(???)_/??
            ^
/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:136: error: unmappable character for encoding ASCII
        // ??\_(???)_/??
                ^
/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:136: error: unmappable character for encoding ASCII
        // ??\_(???)_/??
                 ^
/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:136: error: unmappable character for encoding ASCII
        // ??\_(???)_/??
                  ^
/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:136: error: unmappable character for encoding ASCII
        // ??\_(???)_/??
                      ^
/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:136: error: unmappable character for encoding ASCII
        // ??\_(???)_/??
                       ^
:react-native-maps:androidJavadocs
7 errors
:react-native-maps:androidJavadocs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:androidJavadocs'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/node_modules/react-native-maps/lib/android/build/tmp/androidJavadocs/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 5s
```

**Comment by ziyoshams** [comment]
Apparently I had versioning problem. Solved by following https://github.com/anhtuank7c/maps-example

**Comment by mikemorris** [comment]
Related to https://github.com/react-native-community/react-native-maps/blob/51ff72393bd81cc1df4bef2fa48fa1da0779ab31/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L138, but for some reason this error doesn't seem to get hit when all dependencies are installed, linked and configured properly.

**Comment by px-amaac** [comment]
For the past 2 months we have had no problems with this issue and no changes in dependencies. Randomly it showed up again after a clean build and npm install. I am unable to find an actual solution to this problem and this issue has caused days of headaches. The current solution to this problem for my team when it randomly shows up is to re-import the project which is ridiculous. It seems that nobody really knows why this is happening and sometimes changes in gradle files fix it. Since nobody can give an actual solution is there any way these characters could be removed from the library and replaced with a more descriptive comment?

**Comment by jatinsandilya** [comment]
I had a similar issue with another library, setting this in my `gradle.properties` solved it for me. 

`org.gradle.jvmargs='-Dfile.encoding=UTF-8'`
