### ISSUE TITLE
fitToCoordinates zoom level works incorrect

### ISSUE THREAD

**Issue by avet-m** [react-native-community/react-native-maps#2629]
Hi.

I tried dynamically change my map padding by _fitToCoordinates_ function and it works perfect. 
But the problem come on when I want to change the zoom level of coordinate. Unfortunately, **latitudeDelta** and **longitudeDelta** they both aren't affect on zoom level. 

```
_fitToCoordinates = (destSnapPoint) => {
        this.mapRef.current._component.fitToCoordinates(
            [{
                latitude: 59.978315,
                longitude: 30.314519,
                latitudeDelta: 0.02,
                longitudeDelta: 0.02,
            }],
            {
                edgePadding: {
                    top: 0,
                    right: 0,
                    bottom: destSnapPoint,
                    left: 0,
                },
                animated: true,
            },
        );
    };
```

Any ideas ?

**Comment by jacek213** [comment]
@rborn when using `fitToCoordinates` on a single coordinate, it gets zoomed really aggressively. It is a corner case happening for a single coordinate only. Is there a way to control the zoom level in this case?

**Comment by BransonGitomeh** [comment]
@jacek213 i was having this issue with fitToCoordinates too but i couldnt get it to work, what did work is `animateToRegion`, like this

```
                mapRef.animateToRegion(
                  {
                    latitude,
                    longitude,
                    latitudeDelta: 0.01,
                    longitudeDelta: 0.01
                  },
                  2000
                );
```

for anyone who might run into this in future.

**Comment by doongsilee** [comment]
I was facing this issue too. try [maxZoomLevel](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md) It worked for me.

**Comment by farazdw** [comment]
> I was facing this issue too. try [maxZoomLevel](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md) It worked for me.

But maxZoomLevel won't allow to zoom even if the user wanted to. What I want is to control the level of zoom 'fitToCoordinates" gives

**Comment by mausv** [comment]
I was facing the same issue with fitToCoordinates, wrapping the call to that function inside of a requestAnimationFrame worked for me.

```js
requestAnimationFrame(() =>
  this.mapRef.fitToCoordinates(
    [
      {
        latitude: eastMostPoint + latDelta / 3,
        longitude: northMostPoint + lngDelta / 3
      },
      {
        latitude: westMostPoint - latDelta / 3,
        longitude: southMostPoint - lngDelta / 3
      }
    ],
    {
      edgePadding: { top: 10, right: 10, bottom: 10, left: 10 },
      animated: false
    }
  )
)
```

**Comment by MichaelKim39** [comment]
Hey, there is a better workaround which is to use `mapRef.current.animateCamera` which allows you to specify zoom level

```
mapRef.current?.animateCamera({
  center: userLatLng,
  zoom: <CUSTOM_ZOOM>,
  altitude: <CUSTOM_ALTITUDE>,
});
```
