### ISSUE TITLE
geometry.spherical.computeOffset and set Marker

### ISSUE THREAD

**Issue by HarryTgerman** [react-native-community/react-native-maps#2632]
I want to set a Marker given only distance (in meter) and degree (°) from current position. 
I used the Google geometry library as shown in this jsFiddle http://jsfiddle.net/geocodezip/u7qjn9xj/.
Is there any way I could do this in react-native?

**Comment by gabrielporcher** [comment]
Any update on this? 

spherical.computeOffSet it is a method that helps a lot to make cutouts inside a circle.

> computeOffset(from, distance, heading[, radius])
> Parameters: 
> from:  [LatLng](https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLng)|[LatLngLiteral](https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLngLiteral)
> distance:  number
> heading:  number
> radius:  number optional
> Return Value:  [LatLng](https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLng)
> Returns the LatLng resulting from moving a distance from an origin in the specified heading (expressed in degrees clockwise from north).
