### ISSUE TITLE
Animated mapPadding

### ISSUE THREAD

**Issue by avet-m** [react-native-community/react-native-maps#2635]
hi

Is there a way to animate mapPadding ?

**Comment by ovidiu-balau** [comment]
Is there any solution to this?

**Comment by avet-m** [comment]
@ovidiu-balau try to use method **fitToCoordinates** 

https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md

**Comment by hewad-netlinks** [comment]
I tried with **fitToCoordinates** but google logo is not moving with edgePadding 
is there any solution to perform animated padding with **mapPadding** property
