### ISSUE TITLE
iOS with GoogleMaps without CocoaPods need recursive framework search path

### ISSUE THREAD

**Issue by MrLoh** [react-native-community/react-native-maps#2636]
### Is this a bug report?

It's about a missing step in the installation instructions

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.57.8
    react: 16.6.3
    react-native-maps: 0.22.1

### Description

I was following the [instructions](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios) to enable google maps on iOS, without using CocoaPods to include this library. First of all, I am really glad I can run without CocoaPods for installing this library, CocoaPods has cost me already way too many hours. 

I encountered an issue. While running the script added the location to the framework search paths, it wasn't set as a recursive search path and the install would fail. Fixing the search path in Xcode to be recursive, solved the issue, but this should either be documented or the script should be altered. 

----

~~By the way, I am installing only google maps via CocoaPods, which works straight forward, I have had extremely bad experiences installing the react native source code via CocoaPods so I am avoiding that, but maybe this is an option for a good installation that you would consider, opting for only installing the real dependencies via CocoaPods and leaving the package installed 'normally'~~

**Comment by nicomontanari98** [comment]
At the second step of the "Enabling Google Maps on iOS" in the documentation there is [this link](https://developers.google.com/maps/documentation/ios-sdk/start) for manually installation of google maps

**Comment by MrLoh** [comment]
I am aware of that link, and I guess you are right that it already explains how to use CocoaPods to install only the google maps dependency. 

However the point of this issue is that it mentions nowhere that you need to set framework search path to recursive for things to work, which the provided script does not do automatically

**Comment by MrLoh** [comment]
Ok, so I figured out how to set a recursive search path, simply add `/**` so my post install script now looks like this: `./node_modules/react-native-maps/enable-google-maps 'ios/Pods/GoogleMaps/**'`

There could be a note in the Readme about how to set a recursive path, but I am gonna close this issue to reduce the clutter in this repo.
