### ISSUE TITLE
Wrong deployment target for newer versions of Xcode

### ISSUE THREAD

**Issue by DealPete** [react-native-community/react-native-maps#2638]
I get this warning in XCode 10.1:

`warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'AirMaps')`

It appears the newest version of Xcode doesn't support a deployment target less than 8.0.

**Comment by grifotv** [comment]
@DealPete you can do this in your project https://github.com/flutter/flutter/issues/22123#issuecomment-423618945
