### ISSUE TITLE
Point data type not explained in documentation

### ISSUE THREAD

**Issue by psadeghian** [react-native-community/react-native-maps#2643]
The following Marker properties receive Point data type inputs: 

- centerOffset
- calloutOffset
- anchor
- calloutAnchor

However, it is not explained in the documentation what this data type is. Note, Javascript does include a Point data type.

**Comment by psadeghian** [comment]
I assume a Point data type is the following: {x: Number, y: Number}

**Comment by rborn** [comment]
It is https://github.com/react-native-community/react-native-maps/blob/master/docs/marker.md#types
