### ISSUE TITLE
Why onLayout method is not documented?

### ISSUE THREAD

**Issue by BrodaNoel** [react-native-community/react-native-maps#2645]
### Is this a bug report?
No

Guys, why is `onLayout` not documented on https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md?

I'm not sure if this is because it's not recommendable to use, or if it's deprecated, or if you just forgot it.

BTW, it's gonna be nice to know which is the difference between onMapReady and onLayout.

Thanks!

**Comment by rborn** [comment]
`onLayout` is the inherited [`View` event ](https://facebook.github.io/react-native/docs/view#onlayout) thus not sure we need to document it.
`onMapReady` is triggered when the map finished loading so you can start operate on it.

**Comment by jonathanstiansen** [comment]
Hey Rborn, 

We reproduced a bug on expo MapView (which is supposedly a thin wrap on react-native-maps), where when we have a marker before loading happens and we try to render it after onReady it crashed on Android standalone, 1/2 the time. [Here](https://stackoverflow.com/questions/57617703/recent-mapview-issue-in-expo-standalone-android/57617704#57617704) is my description of the issue.

I think this should either be documented thats something else calls `fitToCoordinates` or `onLayout` should be better documented.
