### ISSUE TITLE
Blank map on Expo android

### ISSUE THREAD

**Issue by hasinifoss** [react-native-community/react-native-maps#2646]
### Is this a bug report?

Yes

In my expo app, I'm using react-native-maps. I'm getting a blank map on android, but for ios it is working fine. But the map markers are shown on both android and ios.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react": "^16.0.0",
"react-native": "^0.55.2",
"expo": "^27.0.1",
"react-native-maps": "^0.22.1",

### Expected Behavior

In expo apps, the map should be shown regardless of the OS.

(Write what you thought would happen.)

### Actual Behavior

In iOS the map is rendered correctly on expo app.
In android map is not rendered, only the map markers are shown.

**Comment by auctus10** [comment]
You don't need to install react-native-maps separately  for expo. Expo has 'react-native-maps' pre configured in expo kit.

You can import MapView from 'expo'.

**Comment by szmarci** [comment]
I have the same issue. Blank on Android, fine on iOS (I'm importing maps from expo)

**Comment by christopherdro** [comment]
@auctus10 Is correct. No need to install react-native-maps if you are using Expo.

**Comment by auctus10** [comment]
@szmarci  Can you post your code here?

**Comment by szmarci** [comment]
@auctus10 I've managed to track down this bug. I was using custom map styles, and for some reason whenever there was a color definition in the JSON there was an additional space at the end, like this `"#402d2d ". iOS did not care for that and just rendered the map anyway but Android just showed a blank map. After removing the space all is well on both system.

**Comment by ericrprates** [comment]
@hasinifoss you need to enable Maps Static API on Google Console Developer and add in your app.json the key, like this: android.config.googleMaps.apiKey

I hope this helps you!

**Comment by mohmdalfaha** [comment]
@ericrprates  I am facing the same after making``` expo build:android``` I have done the steps for adding the api key from google console but still the map is just showing Google logo and blank.

**Comment by cokealmonacid** [comment]
@mohmdalfaha Did you solve it?

**Comment by kriit24** [comment]
Same issue, when i run expo start then map shows, but when i run expo run:android then backround is light grey and logo is visible

And i have installed like: https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md

**Comment by ger88555** [comment]
Same issue, I'm using `expo run:android` (a dev client). The background is light gray and the Google logo is visible at the bottom.

**Comment by anhquan291** [comment]
Facing the same issue. Any solutions yet guys? Thanks

**Comment by ger88555** [comment]
In my case I had to follow the steps @mohmdalfaha did to setup the API credentials on the App. Since I'm using Expo's dev client (https://docs.expo.dev/development/introduction/) so I had to delete the `android/` folder and re-build the dev client for the changes to take effect. Hope it helps.

**Comment by hanamurayuki** [comment]
I also face same problem. 
IOS is ok, but blank map on android with `eas build`.
Reason is google map api authorization. (logo exists, but map is brank)

Document was updated on Fri Nov 25 2022.
https://docs.expo.dev/versions/latest/sdk/map-view/

> # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> 
> 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> For development builds
> - If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> - After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> - `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`

Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, 
but we need to upload  `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials >  Application Identifiers > click your project's package name and under Android Keystore), 

After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.

**Comment by MaizNadeem** [comment]
IDK. I was using local android build, it worked until one time I opened the app and found this behavior. I switched to eas build and added SHA-1 restriction to Maps API key on GCP. Then it worked.
