### ISSUE TITLE
Bug in MapView component in iOS

### ISSUE THREAD

**Issue by Ryanholly3** [react-native-community/react-native-maps#2647]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.55.1
    react: 16.3.1
    react-native-maps: ^0.22.1

Using AppleMaps

Project created with ViroReact (https://docs.viromedia.com/docs/quick-start) through 'react-viro init' 

### Steps to Reproduce

Unable to successfully use MapView component imported from react-native-maps. 

1. clone project (https://github.com/Ryanholly3/virtualGeocache),
2. npm install dependencies. 
3. Run "react-native link react-native-maps" in command line. (installation instruction in react-native-maps docs: Build configuration on iOS using React-native link)
4. install Viro-media app on iOS device
5. In root of project, run npm start. Initiates ngrok.io package server.
6. enter ngrok.io url from command line into testbed on Viro-media app to run app on device.
7. Error (below) appears.

### Expected Behavior

Expected AppleMap to render in MapScreen.js

### Actual Behavior

Bug in MapView component from react-native-maps

![image](https://user-images.githubusercontent.com/28697083/50657102-a9ae0600-0f52-11e9-8689-4513d2d586f2.png)

Error above references line 793 of node_modules/react-native-maps/lib/components/MapView.js. Screenshot of line below. AIRMap does not exist (const declaration of AIRmap on line 790).

![image](https://user-images.githubusercontent.com/28697083/50657083-9ac75380-0f52-11e9-8a90-1870caf846e9.png)

### Reproducible Demo

https://github.com/Ryanholly3/virtualGeocache

The MapView component is imported and used in js/MapScreen.js

**Comment by rborn** [comment]
Closing, old issue. Also seems more related to ViroMedia than this module.
