### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by oliverdolgener** [react-native-community/react-native-maps#2648]
With recent changes introducing the new camera system I'd like to see a new release 0.22.2 for using it with expo. Thanks in advance

**Comment by rborn** [comment]
@oliverdolgener fancy a PR for changelog similar to this one? 🤗 https://github.com/react-native-community/react-native-maps/pull/2574/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e? 
The last published commit is `c7a55f5`


@christopherdro 🐽

**Comment by christopherdro** [comment]
I'd suggest we do a new version release. 0.23.0

**Comment by rborn** [comment]
@christopherdro totally agree

**Comment by hoboman313** [comment]
I'm really hopeful for a new release soon as there was recently a critical iOS improvement with #2650
(personally I'm pulling from master now)

**Comment by rborn** [comment]
@hoboman313 looks like @oliverdolgener doesn't reply, so maybe you could help with the changelog? 
I mean this is a community project, and we're all trying to do as much as we can but we also need help :)

**Comment by oliverdolgener** [comment]
@rborn oh sorry, I didn't it. Sure I'll try to do it.

**Comment by christopherdro** [comment]
https://github.com/react-native-community/react-native-maps/releases/tag/v0.23.0

**Comment by christopherdro** [comment]
Thank you @oliverdolgener !
