### ISSUE TITLE
Play Services Maps

### ISSUE THREAD

**Issue by vincentvella** [react-native-community/react-native-maps#2652]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.57.8
react: 16.6.3
react-native-maps: github:react-community/react-native-maps#master

### Steps to Reproduce

1. Follow installation instructions
2. Gradle sync problems when linked with android
3. Read stack trace - "Failed to resolve: com.google.android.gms:play-services-maps:16.0.1"

### Expected Behavior

The step the error is coming from should link and download play-services-maps

### Actual Behavior

The play-services-maps version is currently being written in a dynamic format with the wrong behavior so instead of using version 16.0.0 it is using an unpublished version of play-services-maps - "16.0.1"

![image](https://user-images.githubusercontent.com/22749569/51004060-143ce400-1507-11e9-8eee-c844574f15a4.png)

### Reproducible Demo

No reproducible demo but it is on master, it breaks during sync because the version of maps is incorrect.

**Comment by vincentvella** [comment]
I've identified the problem and am creating a PR

**Comment by vincentvella** [comment]
PR is referenced above 👍 , hope this is merged soon as it currently breaks all builds that are referencing "react-native-maps#master" because there hasn't been a recent NPM release.

**Comment by wil93** [comment]
I encountered this probem too, is there some way I can fix it before the next release?

**Comment by vincentvella** [comment]
@wil93 that will fix it temporarily unless you install your node modules through a CI process.

**Comment by rborn** [comment]
#2653 merged, closing
