### ISSUE TITLE
Double touch for move the map

### ISSUE THREAD

**Issue by aevpraid** [react-native-community/react-native-maps#2656]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react-native": "^0.57.1",
"react": "16.6.0-alpha.8af6728",
"react-native-maps": "^0.22.1"

target platform: both

### Steps to Reproduce
--

### Expected Behavior
--

### Actual Behavior
--

### Reproducible Demo
--

Hello! 

I want to allow moving around the map only when I touch with two fingers on the screen.
Is it possible to implement using this library?

Thanks!

**Comment by sudiddo** [comment]
is there any workaround for this issue, i need this feature too :(

**Comment by dylanrhodius** [comment]
Has this been implemented?

**Comment by florianmatthiaschristoph** [comment]
Any news on this? Would be super important for our mobile UX. 
There is a default feature of Google maps on mobile websites (Overlay with "Use two fingers to move the map" on scroll) - Is there any way to force this overlay in react-native-maps?

**Comment by rborn** [comment]
My 2c is that you are breaking the user expectations trying to implement this gesture. 
On native mobile environment the maps move on drag with one finger and 2 fingers are used to zoom, rotate or change the camera angle.

What websites are doing is a workaround to prevent the users to be trapped in the map in a scrollable context.

**Comment by florianmatthiaschristoph** [comment]
@rborn I totally agree. 

Our problem is that we have the map in a scrollable context and it takes up about two-thirds of the screen height. Also, it's the top element and exactly within the natural scroll area. So if the user wants to scroll down he moves the map. But we do not want to disable the map-movement in general with scrollEnabled false. And that's why I was asking if there is any way add a move with two fingers-functionality/overlay.

**Comment by gino8080** [comment]
up needed this feature too to use in a scrollable container

**Comment by Hissvard** [comment]
I was able to hack it together like
```jsx
const [scrollEnabled, setScrollEnabled] = useState(true);
const [panHandlers, setPanHandlers] = useState({});
useEffect(() => {
    const panResponder = PanResponder.create({
        onStartShouldSetPanResponder: () => true,
        onMoveShouldSetPanResponder: () => true,
        onPanResponderStart: (event, gesture) => {
            setScrollEnabled(gesture.numberActiveTouches === 2);
        }
    });
    setPanHandlers(panResponder.panHandlers);
}, []);

return (
    <View {...panHandlers}>
        <MapView pitchEnabled={false} scrollEnabled={scrollEnabled}/>
        {!scrollEnabled && <View style={{position: 'absolute', top: 0, right: 0, bottom: 0, left: 0}} />}
    </View>
);
```
But it doesn't work 100% of the time since I'm pretty bad at dealing with panHandlers. Not very elegant but might be useful to someone.

**Comment by puremana** [comment]
Would also like this feature implemented, couldn't manage to get Hissvard's hack to work unfortunately.

**Comment by louislefebvre** [comment]
Hi,
I apologize for digging out this request, but yeah, we use a map in a scrollable context too, and we would be glad if there was natively an API to only use two-fingers moving onto the map instead of only one. Anyone got something?

**Comment by florianmatthiaschristoph** [comment]
Hi @louislefebvre 
Maybe this helps: We managed to solve it with a simple layer on top of the map. It initially has 0% opacity and fades up to 100% on touch. The layer itself has a transparent black background and contains an animated icon and the text "Double-tap to interact with the map". After some time it fades out again. On double-tap, the layer disappears completely and the map beneath it is interactive. It still works well for our use case.

**Comment by rborn** [comment]
@louislefebvre the behaviour of the map is the underlaying native one. Both ios and android maps have one finger move. 
I strongly suggest to follow this because otherwise you break the UX for mobile app users. The behaviour you are describing is web (for mobile) and it's more a workaround where you'd have a map as big as the screen or bigger and one finger only won't let you scroll the page.

I'll close the issue now.

**Comment by sonalvish** [comment]
> I was able to hack it together like
> 
> ```js
> const [scrollEnabled, setScrollEnabled] = useState(true);
> const [panHandlers, setPanHandlers] = useState({});
> useEffect(() => {
>     const panResponder = PanResponder.create({
>         onStartShouldSetPanResponder: () => true,
>         onMoveShouldSetPanResponder: () => true,
>         onPanResponderStart: (event, gesture) => {
>             setScrollEnabled(gesture.numberActiveTouches === 2);
>         }
>     });
>     setPanHandlers(panResponder.panHandlers);
> }, []);
> 
> return (
>     <View {...panHandlers}>
>         <MapView pitchEnabled={false} scrollEnabled={scrollEnabled}/>
>         {!scrollEnabled && <View style={{position: 'absolute', top: 0, right: 0, bottom: 0, left: 0}} />}
>     </View>
> );
> ```
> 
> But it doesn't work 100% of the time since I'm pretty bad at dealing with PanResponder. Not very elegant but might be useful to someone.

It works nicely for me . 
Thanks
