### ISSUE TITLE
Problems building a release .apk 

### ISSUE THREAD

**Issue by ksairi** [react-native-community/react-native-maps#2659]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes, my configuration looks the same as the instructions mentioned.

### Environment
    react-native: 0.57.3
    react: 16.6.0
    react-native-maps: 0.22.1

### Steps to Reproduce

Being in the root of the react native project
- `cd android && ./gradlew assembleReleaseStaging`

### Expected Behavior

To have a .apk signed and ready to install (If I comment the mentions of this dependency, the apk is successfully created)

### Actual Behavior

The built failed showin the following error:

* What went wrong:
Could not resolve all files for configuration ':react-native-maps:releaseCompileClasspath'.
> Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints: 
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'directdrinks:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: releaseRuntimeClasspath uses version 24.0.0
        Constraint path 'directdrinks:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: releaseRuntimeClasspath uses version 24.0.0

> Could not resolve com.android.support:support-annotations:27.1.1.
  Required by:
      project :react-native-maps > com.facebook.react:react-native:0.57.3 > com.android.support:appcompat-v7:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.3 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-core-utils:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.3 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-fragment:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.3 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-vector-drawable:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.3 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-core-utils:27.1.1 > com.android.support:support-compat:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.3 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-fragment:27.1.1 > com.android.support:support-core-ui:27.1.1
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints: 
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'directdrinks:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: releaseRuntimeClasspath uses version 24.0.0
        Constraint path 'directdrinks:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: releaseRuntimeClasspath uses version 24.0.0

> Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps > com.android.support:support-v4:24.0.0
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints: 
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'directdrinks:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.3' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'directdrinks:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: releaseRuntimeClasspath uses version 24.0.0
        Constraint path 'directdrinks:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: releaseRuntimeClasspath uses version 24.0.0

## app/build.gradle

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion '28.0.3'

    defaultConfig {
      applicationId "com.directdrinks.directdrinksrep"
      minSdkVersion rootProject.ext.minSdkVersion
      targetSdkVersion rootProject.ext.targetSdkVersion
      versionCode 1
      versionName "1.6.4"
      ndk {
          abiFilters "armeabi-v7a", "x86"
      }
    }
    signingConfigs {
      release {
        if (project.hasProperty("MYAPP_RELEASE_STORE_FILE")) {
          storeFile file(MYAPP_RELEASE_STORE_FILE)
          storePassword MYAPP_RELEASE_STORE_PASSWORD
          keyAlias MYAPP_RELEASE_KEY_ALIAS
          keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
      }
    }
    splits {
      abi {
          reset()
          enable enableSeparateBuildPerCPUArchitecture
          universalApk false  // If true, also generate a universal APK
          include "armeabi-v7a", "x86"
      }
    }
     buildTypes {
      debug {
        // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager.
        // However, because CodePush checks for updates in all modes, we must supply a key.
        buildConfigField "String", "CODEPUSH_KEY", '"DUMMY_DEV_KEY"'
        applicationIdSuffix ".debug"
      }
      releaseStaging {
        initWith(buildTypes.release)
        applicationIdSuffix ".staging"
        signingConfig signingConfigs.release
        // def props = new Properties()
        // file("../extra.properties").withInputStream { props.load(it) }
        if (project.hasProperty("CODEPUSH_STAGING")) {
          buildConfigField "String", "CODEPUSH_KEY", CODEPUSH_STAGING
        }
        matchingFallbacks = ['release', 'debug']
      }
      release {
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        signingConfig signingConfigs.release
        // def props = new Properties()
        // file("../extra.properties").withInputStream { props.load(it) }
        if (project.hasProperty("CODEPUSH_PRODUCTION")) {
          buildConfigField "String", "CODEPUSH_KEY", CODEPUSH_PRODUCTION
        }
        matchingFallbacks = ['release', 'debug']
      }
      debug {
        debuggable true
      }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
      variant.outputs.each { output ->
        // For each separate APK per architecture, set a unique version code as described here:
        // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
        def versionCodes = ["armeabi-v7a":1, "x86":2]
        def abi = output.getFilter(OutputFile.ABI)
        if (abi != null) {  // null for the universal-debug, universal-release variants
            output.versionCodeOverride =
                    versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
        }
      }
    }
}

dependencies {
    implementation project(':react-native-add-calendar-event')
    implementation project(':react-native-signature-capture')
    implementation project(':react-native-camera')
    implementation (project(':react-native-device-info')){
        exclude group: 'com.google.android.gms'
    }
    implementation (project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation project(':react-native-vector-icons')
    implementation (project(':react-native-camera')) {
      exclude group: "com.google.android.gms"
      compile 'com.android.support:exifinterface:27.+'
      compile ("com.google.android.gms:play-services-vision:10.2.4") {
          force = true;
      }
    }
    implementation project(':react-native-code-push')
    implementation project(':react-native-fs')
    implementation project(':react-native-photo-view')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.android.gms:play-services-base:16.1.0'
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
  into 'libs'
}
```
## android/build.gradle

```
buildscript {
    ext {
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        mavenLocal()
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
        maven { url "https://maven.google.com" }
    }
}

ext {
    compileSdkVersion   = 26
    targetSdkVersion    = 26
    supportLibVersion   = "27.1.1"
    googlePlayServicesVersion = "10.2.4"
    androidMapsUtilsVersion = "0.5+"
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.10.1'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

**Comment by Peeeep** [comment]
This also happened to me after upgrading to latest Gradle. 

Changeing back to `'com.android.tools.build:gradle:3.2.1'`and `gradleVersion = '4.6` solved the problem for me.

**Comment by ksairi** [comment]
nice @Peeeep. Thank you, it worked like a charm!

**Comment by ProfessionalAmateur** [comment]
Hello - Ive having the same issue.  Did you actually downgrade the gradle version?  Or did you just change the versions in the build.gradle files?  Im not sure if I need to go into android studio and change the installed versions through there?

**Comment by ksairi** [comment]
@ProfessionalAmateur change the versions in the build.gradle files through the android studio
