### ISSUE TITLE
Could not resolve all files for configuration ':react-native-maps:debugCompileClasspath'.

### ISSUE THREAD

**Issue by vishesh774** [react-native-community/react-native-maps#2663]
### Is this a bug report?

Yes, The linking to react-native is successful but fails to run the project

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, I have read all the instructions and followed them as well.

### Environment
"react": "16.6.1",
"react-native": "0.57.6",
"react-native-maps": "^0.22.1",

### Steps to Reproduce

(Write your steps here:)

1. On running the command "react-native run-android", The following errors are encountered in the terminal:

Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps > com.android.support:support-v4:24.0.0
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:

Could not resolve com.android.support:support-annotations:27.1.1.
  Required by:
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1

### Expected Behavior
Should have compiled successfully

(Write what you thought would happen.)

### Actual Behavior
 The above mentioned errors are logged in the console and the app doesn't start successfully.

(Write what happened. Add screenshots!)
> Configure project :react-native-firebase
react-native-firebase: using React Native prebuilt binary from /Users/vishesh/learning/xemo-local-app/node_modules/react-native/android

> Task :react-native-maps:compileDebugRenderscript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-maps:debugCompileClasspath'.
> Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0

> Could not resolve com.android.support:support-annotations:27.1.1.
  Required by:
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-core-utils:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-fragment:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-vector-drawable:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-core-utils:27.1.1 > com.android.support:support-compat:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-fragment:27.1.1 > com.android.support:support-core-ui:27.1.1
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0

> Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps > com.android.support:support-v4:24.0.0
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s

**Comment by vnd-ranga** [comment]
Sm issue with gradle4.10.1

**Comment by steventilator** [comment]
I am faced with the same error after upgrading to Gradle 4.10. 

@vnd-ranga Where did you make this change you suggested?

**Comment by jaredandrews** [comment]
@steventilator I did the same thing as @vnd-ranga and it worked. The change would be in your top level gradle file. I had to do a rebuild after as well to make the error completely go away.

**Comment by noahtallen** [comment]
Rather than downgrading the gradle version, I was also able to fix the error by adding the support libs to the `react-native-maps` gradle file. Perhaps something changed in gradle such that this is required now?? If someone with experience recommends this as the way forward (assuming we'll need to keep updating gradle in the future), I'm happy to make a PR adding this:

`build.gradle`:
```
  def supportLibVersion = safeExtGet('supportLibVersion', DEFAULT_SUPPORT_LIB_VERSION)
  implementation "com.android.support:appcompat-v7:$supportLibVersion"
  implementation "com.android.support:support-media-compat:$supportLibVersion"
  implementation "com.android.support:support-v4:$supportLibVersion"
```

Obviously this doesn't work even as a short-term solution because this file is in `node_modules` and won't persist anywhere other than my own machine :)

**Comment by RobTS** [comment]
This should get some visibility :)

**Comment by JanScheuermann** [comment]
@vnd-ranga worked for me too, thanks a lot

**Comment by trainbolt** [comment]
+1 +1 +1 on this... 

Why in the world are we needing to downgrade the gradle classPath to make this work. As stated by @vnd-ranga ... and also by @noahtallen about adding the dependencies to the `react-native-maps` gradle.

Someone needs to get this sorted because these issues are wasting a lot of people's time and I'm not even going to bring up how the iOS install section should be overhauled.

**Comment by rtkhanas** [comment]
@noahtallen there is an awesome https://github.com/ds300/patch-package package that solves the issue with node_modules!

**Comment by noahtallen** [comment]
Thanks! I've seen that but never gotten the chance to really learn it :P

**Comment by sumittiwari87** [comment]
Still have same issue for me. 

 ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.1"
        androidMapsUtilsVersion = "0.5+"
    }

implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-maps')

 "react": "16.8.3",
    "react-native": "0.59.0",
    "react-native-maps": "^0.23.0",

**Comment by danniarreza** [comment]
So um, any solution or workaround to this other then downgrading the gradle?

**Comment by chancyWu** [comment]
To use the react-native 0.59.0, we have to upgrade the gradle build tools to 3.3.0 which will encounter the same issue?

**Comment by danniarreza** [comment]
Hey @chanchyWu, recently I just faced the same issue as you and found that current usable solution is to install react-native-maps from master branch. Check the other issue someone mentioned about what I said just now. Hope it helps

**Comment by chancyWu** [comment]
@danniarreza you means you are trying the 0.24-rc1? i trying to change to the 0.24-rc1 in package.json, but it's not available. How do you change the package.json?

**Comment by chancyWu** [comment]
@danniarreza Thanks. Follow https://github.com/react-native-community/react-native-maps/issues/2737#issuecomment-472341877 to solve temporarily.

**Comment by akhileshsinha** [comment]
run 
npm install git://github.com/react-native-community/react-native-maps.git#master --save

for the temp solution....

**Comment by lcustodio** [comment]
I was facing the same problem - updating to the latest version solve it. `"react-native-maps": "^0.24.2",`

**Comment by elijahmurray** [comment]
@lcustodio Much better solution, worked for me. Thanks!

**Comment by ebnerdeath** [comment]
@lcustodio Much better solution, worked for me. Thanks!

**Comment by Atomo87** [comment]
Solution:   node_modules -> react-native-maps -> lib ->android->
file  -> build.gradle 
 dependencies {
 implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"

}
