### ISSUE TITLE
Transform longitudeDelta and longitudeDelta to meters [Question]

### ISSUE THREAD

**Issue by zgrybus** [react-native-community/react-native-maps#2668]
### Is this a bug report?

no

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

 "react-native": "0.57.7"
    "react": "16.6.1"
    "react-native-maps": "^0.23.0"

### Question

How could i transform Region Props ( actually i think that i should probably use delta's props ) to meters?

I want to change Circle's radius when user change delta's props ( by zooming in / out ).

Could not find any Math operation on google :(

**Comment by rborn** [comment]
@zgrybus did you check this? https://github.com/react-native-community/react-native-maps/issues/505#issuecomment-421323208

or this?
https://www.movable-type.co.uk/scripts/latlong.html

**Comment by zgrybus** [comment]
@rborn  Thanks, works! :)

For other people



     private getRadius(lat: number, lng: number, lngRadius: number): number {
         return this.getDistanceBetweenPoints(
            { lat: lat, lng: lng - lngRadius / 2 },
            { lat: lat, lng: lng + lngRadius / 2 } 
         )
     }

    private getDistanceBetweenPoints(point1: Point, point2: Point): number {
        const earthRadius: number = 6371;
        const [dLat, dLng] = [
            this.degToRadians(point2.lat - point1.lat),
            this.degToRadians(point2.lng - point1.lng)
        ];
        const  a = 
            Math.sin( dLat / 2 ) * Math.sin( dLat / 2 ) +
            Math.cos(this.degToRadians(point1.lat)) * Math.cos(this.degToRadians(point2.lat)) * 
            Math.sin( dLng / 2 ) * Math.sin( dLng / 2 );
        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt( 1 - a )); 
        return Math.abs(( earthRadius * c ) * 350);
    }

    private degToRadians(deg: number): number {
        return deg * ( Math.PI / 180 );
    }

**Comment by bkdev98** [comment]
Hi @zgrybus, what does `lngRadius` mean in your formula?

**Comment by yasir-netlinks** [comment]
Hi there, what's `lngRadius` here ?

**Comment by knofz-qt** [comment]
@bkdev98 @yasir-netlinks 
Probably radius of the circle. It should work without it ( but i am not sure! )
