### ISSUE TITLE
Device gets heated after using the map for some time.

### ISSUE THREAD

**Issue by BasilJohn** [react-native-community/react-native-maps#2669]
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Steps to Reproduce

(Write your steps here:)

1.Use Google Map on IOS device(I had used IPHONE X).
2.Work with maps for some time probably around 15 mins.
3.Device gets heated.

### Expected Behavior

I understand the device will get heated when using Maps, but i see there is a huge raise in temperature.
Would like to know if there are any ways to debug this and find the actual issue on why this happening

### Actual Behavior

The device gets heated a lot when using react-native-maps.

### Reproducible Demo

Any insights will of great use.

**Comment by oliverdolgener** [comment]
I think it highly depends on what exactly you are doing with the map. Are you just using the plain map or rendering expensive things like polygons, markers etc.?

**Comment by BasilJohn** [comment]
> I think it highly depends on what exactly you are doing with the map. Are you just using the plain map or rendering expensive things like polygons, markers etc.?

I tried just loading the map too find if its because of the markers, but even without the markers i face this issue.And this is more dominant on IOS devices.Have you faced any heating issues?

**Comment by oliverdolgener** [comment]
I've been experiencing device heating as well. I tried to minimize rerendering of the map as much as possible. Only show what really needs to be shown at a time. But I think the native implementation is pretty expensive on resources

**Comment by jfluence** [comment]
For IOS, I noticed that if you have any custom view inside of a marker, the cpu usage is forced up to ~98% constantly vs ~2% - 5% with the default marker option.

**Comment by rborn** [comment]
Closing, old issue. Please open a new one if you still have it
