### ISSUE TITLE
coordinateForPoint is undefined when using Google maps

### ISSUE THREAD

**Issue by psadeghian** [react-native-community/react-native-maps#2673]
The coordinateForPoint method is undefined when using GoogleMaps on Android or IOS. 
Note, the method works fine when using MapKit on IOS. 

I am using "react-native-maps": "^0.23.0"

**Comment by psadeghian** [comment]
The following Snack link is using the MapView component provided by expo, while the example is not using the latest version of react-native-maps,  it does show the coordinateForPoint method only working on iOS and not on Android. 

[Snack example](https://snack.expo.io/BkxBj5GmV)

**Comment by rborn** [comment]
@psadeghian please update your comment following the template or I'll close the issue
