### ISSUE TITLE
Geolocation API is not working on Android devices.

### ISSUE THREAD

**Issue by archana-iron** [react-native-community/react-native-maps#2677]
I working on GPS tracking app, where we track our users distance travel , from initial location to their destination. User needs to click a button to start his/her tracking, this would be his/her starting location. On click of this button we are getting it's current latitude and longitude. 
To get it's current location I am using react native default Geolocation API, here is the link https://facebook.github.io/react-native/docs/geolocation#getcurrentposition

on clicking of button I am checking for ACCESS_FINE_LOCATION Android permission
Functions is listed below::
```
async onTrackingStart() {
		if (isIOS) {
			this.proceedTracking();
		} else {
			const fineLocationgranted = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION);

			if (fineLocationgranted) {
				this.proceedTracking();
			}
			else {
				const requestFineLocationGranted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION);
				if (requestFineLocationGranted) {
					this.proceedTracking();
				} else {
					if (__DEV__) {
						this.showToast('ACCESS_FINE_LOCATION Denied');
					}
				}
			}
		}

	} 
```

If permission is set it will call proceedTracking() function where I am getting it's current location, check this function::

```
proceedTracking() {
		navigator.geolocation.getCurrentPosition(response => {
			if (response && response.coords) {
				this.saveTrackingLogs(response.coords);
			}
		},
			(error) => {
				this.onGeolocationErrorOccurCallback(error);
			},
			GeolocationOptions
		)
	}
```
Now my code stops here. It will generate error here only in case of Android devices. And I am not able to start my tracking because it returns nothing in response. 
Here response is blank?? Why??
Error ::: 

> {"TIMEOUT":3,"POSITION_UNAVAILABLE":2,"PERMISSION_DENIED":1,"message":"Location request timed out", "code":3}

Please suggest me how can I resolve this? And what is the problem in this code. I am not able to detect this issue. I have set all the permissions(both location and gps). But problem occurs again and again. On ios devices there is no issue.

**Comment by SanchezQb** [comment]
Try using react-native-geolocation-service.

**Comment by archana-iron** [comment]
I am using using react-native-geolocation-service. 
After all setup I have this issue, 

> TypeError: Cannot read property 'getCurrentPosition' of undefined
>     at Object.getCurrentPosition$ (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:162211:33)
>     at tryCatch (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:21370:19)
>     at Generator.invoke [as _invoke] (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:21543:24)
>     at Generator.prototype.(anonymous function) [as next] (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:21413:23)
>     at tryCatch (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:21370:19)
>     at invoke (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:21446:22)
>     at blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:21474:13
>     at tryCallTwo (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:20708:7)
>     at doResolve (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:20872:15)
>     at new Promise (blob:http://localhost:8081/0786bd13-e17c-404e-8e19-b46bdfbaf7f3:20731:5)

still I am not able to get my current location?? Why this is happening? Please suggest me a solution.
