### ISSUE TITLE
Can not use getCamera() method

### ISSUE THREAD

**Issue by daihalu** [react-native-community/react-native-maps#2679]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES. But I have not followed Build configuration on Android Instructions.

### Environment
"expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-maps": "^0.23.0"
Device: android 7

### Steps to Reproduce

I try to control camera in mapView by using getCamera method but I get this error: 
`[Unhandled promise rejection: TypeError: undefined is not an object (evaluating` `_reactNative.NativeModules.AirMapModule.getCamera')]`
`Stack trace:`
  `node_modules\react-native-maps\lib\components\MapView.js:600:40 in getCamera`
  `screens\HomeScreen.js:18:25 in getCamera$`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:44 in tryCatch`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:288:30 in invoke`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:44 in tryCatch`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:152:28 in invoke`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:187:17 in <unknown>`
  `node_modules\promise\setimmediate\core.js:45:7 in tryCallTwo`
  `node_modules\promise\setimmediate\core.js:200:23 in doResolve`
  `node_modules\promise\setimmediate\core.js:66:12 in Promise`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:186:27 in` `callInvokeWithMethodAndArg`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:209:38 in enqueue`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:233:8 in async`
  `null:null in getCamera`
  `screens\HomeScreen.js:70:27 in onPress`
 `node_modules\react-native\Libraries\Components\Touchable\TouchableOpacity.js:212:45 in` `touchableHandlePress`
  `node_modules\react-native\Libraries\Components\Touchable\Touchable.js:803:34 in` `_performSideEffectsForTransition...`
### Expected Behavior

I expected that I can animate camera when I have some pickers without using fitToCoordinates method.
Thank in advance

**Comment by techieyann** [comment]
getCamera is async, are you properly accessing it?

**Comment by daihalu** [comment]
> getCamera is async, are you properly accessing it?
Yes, i did. getCamera works normally when i use react-native-maps with out using expo app and test on android device. But It get error like what i mentioned when i test with expo client app

**Comment by troyamtec** [comment]
I've the same issue.

**Comment by troyamtec** [comment]
Can you provide the solution please?

**Comment by rborn** [comment]
@troyamtec you need to use a newer version of the module.
