### ISSUE TITLE
Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by grabowski74** [react-native-community/react-native-maps#2680]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Steps to Reproduce

im trying to put maps on my app, but the same ERROR appears.

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

https://drive.google.com/file/d/15nfujP3VgpfXdWYQEfbYlnWIaD4E9wDV/view?usp=sharing

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
@grabowski74 your AndroidManifest.xml file seems to be broken.

**Comment by grabowski74** [comment]
how can i fix this?

**Comment by rborn** [comment]
post your file here, and please wrote code, not a screenshot again 😉

**Comment by rborn** [comment]
Closing no reply.
