### ISSUE TITLE
How to calculate area of the polygon created by the user?

### ISSUE THREAD

**Issue by prashantvv** [react-native-community/react-native-maps#2683]
Hello, I'ld like to put a temporary issue to check how to calculate the area of the polygon drawn by the user in react native. As there is no direct function so far. I checked Geolib, fencing and other libs, but unable to get area from the coordinates array generated by the polygon.
 Kindly suggest me any solution if exists or any url link where I just pass the array and I get the area in response. or any manual function to calculate the area.

Thanks

**Comment by prav02** [comment]
https://github.com/react-native-community/react-native-maps/issues/2365#issuecomment-459861113

This solved my problem try this.
