### ISSUE TITLE
Cannot change maker image on ios (from null to something)

### ISSUE THREAD

**Issue by mfazekas** [react-native-community/react-native-maps#2686]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

Expo: 0.32.0
react-native: 0.57.0
react: 16.5.0
react-native-maps: 0.22.1
iOS with apple maps

### Steps to Reproduce

See  https://snack.expo.io/@mfazekas/react-native-map-image-change-issue

0. This by default places a marker without image. 
1. Press Image1 to change the image attribute of marker to some image. (Nothing happens)
2. Press toggle twice to remove/readd the marker, now the marker has the image

### Expected Behavior

At 1.) i'd either expect the marker to change to the image or a warning to appear that it's not supported.

### Actual Behavior

Changing the image attribute of a marker (from null to valid image or vica versa) has no effect on iOS.

### Reproducible Demo

https://snack.expo.io/@mfazekas/react-native-map-image-change-issue

**Comment by chrise86** [comment]
Also facing this issue. I want to change the marker image when the marker is selected.
