### ISSUE TITLE
re-rendering Polygons issue

### ISSUE THREAD

**Issue by sidgore1** [react-native-community/react-native-maps#2691]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
  react-native: 0.58.4
  react: 16.3.3
react-native-maps:0.23.0

### Steps to Reproduce

(Write your steps here:)

1.While rendering polygons ,the polygons are shown perfectly on MapView.
2.But when the polygons are rendered rendered using some if conditions,they render perfectly for the first time if the condition is met but for further matches ,they show strange behavior.
3.Some times the polygons from previous conditions get rendered even though they shoul'nt.
4.some Polygons that meet new if else conditions render while some dont.

Following screen shots are for the same conditions.In first one the polygonbs render properly.

<img width="601" alt="screen shot 2019-02-09 at 11 46 30 am" src="https://user-images.githubusercontent.com/46716162/52523530-7735ae00-2c60-11e9-97c6-6426439197bd.png">
<img width="601" alt="screen shot 2019-02-09 at 11 47 09 am" src="https://user-images.githubusercontent.com/46716162/52523531-7735ae00-2c60-11e9-8fe7-317e46bd890d.png">

**Comment by compojoom** [comment]
how are you rendering the polygons? Try to give them uniq keys every time you render them. This should force the map to redraw them.
