### ISSUE TITLE
I want to guide a user to follow a path. My task is to build a arrow and instruct a user to follow a path and a arrow must face towards the distination. How can i do it with react-native google maps

### ISSUE THREAD

**Issue by sandeepghimire77** [react-native-community/react-native-maps#2703]
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by alvelig** [comment]
SO question
