### ISSUE TITLE
pinColor change not working on Android

### ISSUE THREAD

**Issue by RobTS** [react-native-community/react-native-maps#2706]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

  react-native: 0.58.5
  react: 16.8.3
  react-native-maps: 0.23.0

### Steps to Reproduce

In my scenario, you can click together a route by dropping markers on the map. The first one is green ("start"), the last one is red ("end"), the middle one's are blue. So whenever a marker is added, the component renders again with the markers changing to the appropriate color. On iOS, this works perfectly and if I remember correctly, it was working on Android back in the day as well. Now, all subsequent markers keep the initially set color on Android ("red" for all after the first).

### Expected Behavior

Marker color updates to the new one (blue) on Android, just as it does on iOS.

### Actual Behavior

Marker keeps initially set color.

### Reproducible Demo

Will try to follow up with a sample if you have issues. But changing color of a marker after a one second timeout should be setup enough to showcase the issue.

**Comment by RobTS** [comment]
Also, I managed to hack together a fix using one of my favorite tools for unwilling React components: Using the "key"-attribute to force a rebuilt of the marker.

```
<MapView.Marker
    key={idx === self.props.track.markers.length - 1 ? "end" : idx}
    pinColor={idx === self.props.track.markers.length - 1 ? Colors.pureRed : Colors.boatBlue}/>
```

**Comment by rborn** [comment]
@RobTS did you try to set `tracksViewChanges` to `true` while changing the color?

**Comment by msanchezdev** [comment]
@rborn I have the same problem, and set `tracksViewChanges` to `true` but still not working

**Comment by esutton** [comment]
On Android, I am seeing displayed pinColors that do not match what I set them to.  

It is not consistent.  I set 50 pins to yellow and all are displayed yellow.

Then I reload app, set 50 pins to yellow, however some are displayed as yellow and maybe half are red?

**tracksViewChanges** true or false makes no difference.

````
    Pixel 3A running Android 64-bit

    "react": "^16.8.6",
    "react-native": "0.59.9",
    "react-native-maps": "^0.24.2",
````

**Comment by GabrielScalici** [comment]
Allowed colors for Marker are : red, tomato, orange, yellow, green,  gold, wheat, linen, tan, blue, aqua, teal, violet, purple, indigo, turquoise, navy and plum.
Like: 
<MapView.Marker
            pinColor={'green'}
...

**Comment by 18clans** [comment]
I tried using only the colors @GabrielScalici mentioned but still no luck on Android.
