### ISSUE TITLE
Initial Region inicializa generando un parpadeo

### ISSUE THREAD

**Issue by Alekano** [react-native-community/react-native-maps#2709]
### ¿Es este un informe de error?
"Si"

### Leíste las instrucciones ?
"Si"
### Environment
"expo": "31.0.4"
"react-native-maps":"0.22.0"

### Pasos para reproducir
Obtengo una Region de inicializacion y paso esta props al componente MapView el cual a la hora del primer render ignora totalmente mi región , luego de un segundo genera un parpadeo y actualiza a la región especificada.

### Comportamiento Esperado
Necesito que no genere ese parpadeo y se cargue directamente hacia esa posicion.

`<MapView ref={(ref) => { this.mapView = ref }} mapType={this.props.mapType} initialRegion={this.props.initialRegion} mapPadding={this.state.mapPadding} > {this.props.children} </MapView>`

**Comment by Alekano** [comment]
Leí sobre algunas posibles soluciones pero ninguna fue concreta.

**Comment by alvelig** [comment]
You can't change initialRegion on the fly. Put this before your <MapView .../>.

```
if(initialRegion === undefined) {
  return null;
}
```

**Comment by Alekano** [comment]
Lo sigue haciendo..

**Comment by jasmo2** [comment]
¿Obtuviste alguna solución @Alekano ?

**Comment by gonzalodiazcavuoti** [comment]
Hubo alguna solución a este problema? @Alekano
