### ISSUE TITLE
React-native-maps-clustering

### ISSUE THREAD

**Issue by rashrao76** [react-native-community/react-native-maps#2710]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

Environment
 react-native: 0.55.3
    react: 16.3.2
	react-native-maps: 0.23.0 

### Steps to Reproduce
I have used MapView from react-native-maps and the map is rendering the required info with the markers. Now i wanted to use clusters in my map. So i used "react-native-maps-clustering".
i imported 
import Marker from 'react-native-maps';
import MapView from 'react-native-map-clustering';

i am getting the following run time error because of this.

TypeError:null is not an object(evaluating:'markerprops')

(Write your steps here:)

1. Use MapView from  'react-native-map-clustering' instead of 'react-native-maps'

### Expected Behavior

should see maps with clusters

(Write what you thought would happen.)

### Actual Behavior

runtime error with markerprops

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/39483427/53412656-ed236e80-39ef-11e9-964f-09ad27ca3392.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
This should belong to `react-native-map-clustering` not to this module. Please open an issue there
