### ISSUE TITLE
'React/RCTView.h' file not found in xcode 10

### ISSUE THREAD

**Issue by Balasnest** [react-native-community/react-native-maps#2711]
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.57.2
    react: 16.3.0
    react-native-maps: 0.23.0 
   Target Platform: iOS - Simulator/iPhone 
   Using GoogleMaps

### Steps to Reproduce
1. Followed the same podfile description and did `pod install`. Even though not using `use_framework`
2. Build is **failed** saying `React/RCTView.h` not found.
3. If I remove `libAirMap.a` from `link binary with libraries`, build is **success** and later getting error saying `Invariant Violation: requireNativeComponent: "AIRMapMarker" was not found in the UIManager.`

### Expected Behavior
It should successfully build the project  and display the map.

### Actual Behavior
![screen shot 2019-02-27 at 12 12 18 am](https://user-images.githubusercontent.com/6050520/53474117-404dfd80-3a92-11e9-9ba3-230a7a8013ad.png)

**Comment by rborn** [comment]
@Balasnest please don't comment in multiple places, and if you open a new issue try to respect the template.

**Comment by alvelig** [comment]
Yes, @Balasnest, if you followed the template, you'd have resolved the issue.
As far as I can see in your Podfile description, you didn't follow [Installation Instructions](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#using-cocoapods). Especially the Podfile section.

**Comment by Balasnest** [comment]
@rborn Sorry. I have updated the query.
@alvelig Tried exactly the same. But this what happening from me. 

> 3\. If I remove `libAirMap.a` from `link binary with libraries`(else build failed with RCTView.h), build is **success** and later getting error saying `Invariant Violation: requireNativeComponent: "AIRMapMarker" was not found in the UIManager.`

**Comment by rborn** [comment]
@Balasnest did you  try to set xcode to build to legacy system? https://github.com/facebook/react-native/issues/19573 (scroll down)

**Comment by Balasnest** [comment]
@rborn Yes. Build is set to legacy system and my current project was working. I am badly got stuck in iOS. Android implementation is almost ready.

This is my podfile setup and did `AirMaps.xcodeproj` as manual link.

```
platform :ios, '9.0'
target 'myApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
 # Pods for myApp
  pod 'Firebase/Core','4.3.0'
  pod 'Firebase/Messaging'
  pod 'TwilioVideo', '~> 2.5.5'
  pod 'AppsFlyerFramework'
  pod 'GoogleMaps'
end
```

I did't install a React pod since I already have the React library, otherwise it cause conflicts within my Xcode set-up.

Please let me know what caused this break.

**Comment by alvelig** [comment]
@Balasnest Where are `yoga` and `React` lines?

The Podfile doesn't appear to be from the installation instructions.

**Comment by alvelig** [comment]
This is not a bug. Please use StackOverflow for questions.

**Comment by Balasnest** [comment]
- Worked after adding **only** this line: (React was added through npm)
`pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"`

@alvelig  @rborn  Thanks a lot! and thanks for your fast and quick reponse.

**Comment by Thanhcao86** [comment]
add   pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec' in Pod
worked for me
