### ISSUE TITLE
React-Native Show Markers inside Circle Or 500m Radius of my Current Location

### ISSUE THREAD

**Issue by funkyyy** [react-native-community/react-native-maps#2714]
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

my Question:

Hey Guys,

i hope you can help me :/.

Is it possible to Display the Markers inside a Circle or 500m Radius of my Current Position????

**Comment by rborn** [comment]
really @funkyyy ? you just leave the template empty?
I mean, if you don't make this small effort to complete it, how do you expect people to help you ?

**Comment by alvelig** [comment]
@rborn I advocate pro moving all questions to SO
