### ISSUE TITLE
The `bounds` property of MapOverlay does not work as documented

### ISSUE THREAD

**Issue by codazzo** [react-native-community/react-native-maps#2715]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
react-native: 0.57.8
react: 16.8.2
react-native-maps: 0.23.0

### Steps to Reproduce

1. Try to use the `<Overlay>` component as described in the [docs](https://github.com/react-native-community/react-native-maps/blob/42ff69aa2618604f47920364cf4cb84de916b263/docs/overlay.md).
2. Notice how passing as `bounds` an array of `LatLng` as described in the above docs (see `type LatLng` at the bottom of the page) does not work
3. The format that works is an array of `[NW, SE]` (this is expected) in which each entry _is itself an array_ of `[latitude, longitude]`.

### Expected Behavior
An array of `{latitude: Number, longitude: Number}` objects should be accepted as `bounds`

### Actual Behavior
A different format is accepted (`[NW, SE]` where both `NW` and `SE` are `[lat, lng]`).

### Reproducible Demo
https://snack.expo.io/@codazzo/mapoverlay-bug
It shows an overlay even though the format of the `bounds` property does not match the docs.

**Comment by juanjsebgarcia** [comment]
Thanks for this issue! Helped me work out why my implementation was not working. The documents currently don't match the implementation. I imagine the docs are the desired implementation?
