### ISSUE TITLE
Cannot read property 'AIRMap' of undefined

### ISSUE THREAD

**Issue by nishantWM** [react-native-community/react-native-maps#2718]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
  "react": "16.6.3"
  "react-native": "0.58.0"
  "react-native-maps": "^0.23.0",
 Target Platform: all devices

### Steps to Reproduce

1. Include MapView component
2. Draw route using polyline on the MapView
3. Error message 

### Expected Behavior

 The route is drawn on the map

### Actual Behavior

Error message pops up "Cannot read property 'AIRMap' of undefined"
![rn_maps_err](https://user-images.githubusercontent.com/37836195/53619745-75835880-3c16-11e9-803f-32d2c470d889.png)
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

I traced back the issue to `MapView.js` file in line number `815` there is typo  where its accessing
`NativeModules.UIManagerz[getAirMapName(this.props.provider)].Commands[name];`
whereas it should be 
`NativeModules.UIManager[getAirMapName(this.props.provider)].Commands[name];`

**Comment by simdani** [comment]
Did you run `react-native link react-native-maps` inside a terminal ?

**Comment by nishantWM** [comment]
@simdani 
> Did you run `react-native link react-native-maps` inside a terminal ?

No i linked it manually.
I have mentioned that there is a mistake in accessing `UIManager` from` NativeModule`s in the `MapView.js` file. Look at the last section in problem description

**Comment by radeno** [comment]
@nishantWM manual linking is little bit pain. If you can then use Cocoapods.

**Comment by SrLazar0** [comment]
[https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md](url)

Add import com.airbnb.android.react.maps.MapsPackage; and new MapsPackage() in your MainApplication.java :

`import com.airbnb.android.react.maps.MapsPackage;`
```
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
                new MainReactPackage(),
                new MapsPackage()
        );
    }
````

**Comment by rborn** [comment]
Old issue, closing
