### ISSUE TITLE
Problem with rendering markers.Please help me.

### ISSUE THREAD

**Issue by ilyaux** [react-native-community/react-native-maps#2728]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react": "16.5.0",
"react-native": "0.58.6",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-native-maps": "0.23",
Target Platform: Android - 8.0 [Google Maps]

### Steps to Reproduce

1. Take the coordinates from the json file.
2. Display  many Marker with the coordinates from the json file on a MapView

### Expected Behavior

Show markers on the map.

### Actual Behavior

Error: 
`TypeError: TypeError: undefined is not an object (evaluating 'this.state.dataSource.map')`

### Reproducible Demo

Demo: https://snack.expo.io/@ilyaux/vigorous-macaroni-and-cheese

The complete code block looks like this:
```
{this.state.dataSource.map(item => (
 <Marker coordinate={item.latlng} />
   ))}
```
Coordinates for the marker I take from the json file, maybe the error is here ?

```
"latlng": {
      "latitude": 53.6937,
      "longitude": -336.1968
    },
```

I need your help.Full code:
```

export default class MapScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      title: "Map",
      region: {
        latitude: 53.67,
        longitude: 23.83,
        latitudeDelta: 0.04,
        longitudeDelta: 0.09
      }
    };
  }

  componentDidMount() {
    return fetch(url)
      .then(response => response.json())
      .then(responseJson => {
        this.setState(
          {
            dataSource: responseJson
          },
          function() {}
        );
      })
      .catch(error => {
        console.error(error);
      });
  }

  render() {
    const { title } = this.state;
    return (
      <View style={{ flex: 1, backgroundColor: "#1f1f1f" }}>
        <View style={styles.Header}>
```

**Comment by rborn** [comment]
Please update the issue following the template

**Comment by DanielBoening** [comment]
The json is not yet loaded when the map is first loaded. Try the following:

`{this.state.dataSource && this.state.dataSource.map(item => (
     <Marker coordinate={item.latlng} />
   ))}
`

So marker will only be displayed if you have an dataSource Array.

**Comment by rborn** [comment]
@ilyaux still have the issue?

**Comment by rborn** [comment]
No reply, closing
