### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'k[R].params') 

### ISSUE THREAD

**Issue by darijus** [react-native-community/react-native-maps#2729]
### Is this a bug report?

Bug report

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Followed every step of instructions several times

### Environment

react-native: 0.58.5

### Steps to Reproduce

Run on android

### Expected Behavior

Compile

### Actual Behavior

Error

![Alt text](https://i.postimg.cc/DncgKW0B/Screenshot-20190310-131353-01.jpg "Error")

**Comment by rborn** [comment]
Old issue, closing
