### ISSUE TITLE
Polyline accuracy problem

### ISSUE THREAD

**Issue by brunojs02** [react-native-community/react-native-maps#2739]
### Is this a bug report?

i don't know

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

react-native: 0.58.4
react: 16.8.3
react-native-maps: 0.23.0
Target: Android 27

### Steps to Reproduce

- create a simple project (react-native init projectName)
- install the library (npm i react-native-maps)
- link the library (react-native link react-native-maps)
- install mapbox polyline library (npm i @mapbox/polyline) cause i'm using Google Directions API

### Expected Behavior

Polyline drawn correctly on streets

### Actual Behavior

Polyline drawing above houses

![image](https://user-images.githubusercontent.com/7714813/54300786-597ba180-459c-11e9-843e-cc8c8e252d24.png)

### Reproducible Demo

https://github.com/brunojs02/react-native-maps-example

**Comment by egeucak** [comment]
This issue is not related to react native maps. The reason is you are decoding the overview line, which is just the overview. You need to decode the steps instead.

**Comment by brunojs02** [comment]
When I decode the steps, the map gets frozen and takes about 8/10 seconds to center and show the route!!
Ps: with the link example above, i get 17704 latlng.
