### ISSUE TITLE
'airmapcoordinate.h file not found' but can jump to definition

### ISSUE THREAD

**Issue by dominikuswilly** [react-native-community/react-native-maps#2742]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
react-native: 0.55.4
react: 16.3.1
react-native-maps: 0.23.0
Target Platform: iOS - 12 /iPhone 7+, using GoogleMaps
XCode : 10

### Steps to Reproduce

1. Do the installation based on installation guide.
2. When starting run on XCode, error message appeared, 'airmapcoordinate.h file not found'.
3. Search on [https://github.com/react-native-community/react-native-maps/issues/458](url), the problem can't be solved although I've updated the path.
4. I found #import "airmapcoordinate.h" can be "jump to definition" but system can't find that file.

### Expected Behavior

Message Error 'airmapcoordinate.h file not found' on XCode has been solved.

### Actual Behavior

Did I miss one step before?
![Screen Shot 2019-03-15 at 16 25 32](https://user-images.githubusercontent.com/5032568/54422123-5d482900-4740-11e9-9268-3fcb759dec63.png)

![Screen Shot 2019-03-15 at 16 20 10](https://user-images.githubusercontent.com/5032568/54422107-56b9b180-4740-11e9-895e-61020ae632e3.png)

**Comment by christopherdro** [comment]
Please make sure you have the library added to your projects header search paths.

**Comment by salah-ghanim** [comment]
@dominikuswilly please make sure you have the react native maps pods in place for iOS if you follow the iOS setup instructions found in [installation](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md) 

you should not have this error
