### ISSUE TITLE
Update to new GoogleMaps 3.0.1

### ISSUE THREAD

**Issue by wesdewitte** [react-native-community/react-native-maps#2748]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.57.7
react: 16.6.1
react-native-maps: 0.23.0
Using google maps

### Issue
Notice: The Google Play Services version of the Places SDK for Android (in Google Play Services 16.0.0) is deprecated as of January 29, 2019, and will be turned off on July 29, 2019. A new version of the Places SDK for Android is now available.

Im also using this package: https://github.com/tolu360/react-native-google-places

which requires the need for version 3.0.1 of GoogleMaps to use.

Can the podspec be update to the new version?

  s.dependency 'GoogleMaps', '3.0.1'
instead of 
  s.dependency 'GoogleMaps', '2.5.0'

**Comment by rborn** [comment]
@wesdewitte fancy a PR ?

**Comment by wesdewitte** [comment]
Sadly, right now i don't have time to fully test this PR.
It would be great if someone can find the time to test this PR.

**Comment by maxivu** [comment]
Can't wait to see this released.

**Comment by rborn** [comment]
@maxivu I think we're fine with android: https://github.com/react-native-community/react-native-maps/blob/master/lib/android/build.gradle#L25

that should  be the last version, right?

**Comment by compojoom** [comment]
anyone has a changelog with 3.0.1? I'm looking here: https://developers.google.com/maps/documentation/ios-sdk/releases, but it is at 2.7.0 - what has been added/fixed in 3.0.1?

**Comment by rborn** [comment]
hmm @compojoom I think it's a misunderstanding here - google places is the one that needs to be udpated, but we don't use that sdk as far as I know, so maybe false alarm @wesdewitte ?

**Comment by maxivu** [comment]
@rborn react-native-maps has specified 2.5.0 in pod spec, which creates problem with apps that wants to use places sdk in conjunction. 
Places SDK is available post 3.x.x and hence why this request exists.

I have tested this change on iPhone 8 with 12.1 ios.

Tried following things:
1. OnPoiClicked
2. OnMarkerPressed
3. Rendering of maps in general
4. Default text callout when marker is selected.

Above are working with the changes suggested above.

**Comment by kidmysoul** [comment]
Cannot not use the new version of react-native-google-places because of cocoapod spec 

this is my podfile
<img width="598" alt="スクリーンショット 2019-04-06 19 07 20" src="https://user-images.githubusercontent.com/15664045/55668064-4e681880-589f-11e9-99a4-95aea7a41e69.png">

and error is
<img width="813" alt="スクリーンショット 2019-04-06 19 07 06" src="https://user-images.githubusercontent.com/15664045/55668077-70619b00-589f-11e9-9251-a522ff1e2cbf.png">

**Comment by rphlmr** [comment]
@kidmysoul if you want to use a custom version of GoogleMaps, you have to upgrade the GoogleMaps version in "YourApp/node_modules/react-native-maps/react-native-google-maps.podspec" too.

Don't forget to delete your Podfile.lock (YourApp/ios/Podfile.lock) before a pod install.

**Comment by tyjing** [comment]
hi, i am new to react native. can anyone tell me how to upgrade GoogleMaps v2.7.0 to v3.0.3? 
i have no idea on how to update even i upgraded react-native-maps to the newest version, i am still getting GoogleMaps v2.7.0

**Comment by kidmysoul** [comment]
@tyjing 

"react-native-maps": "git://github.com/react-native-community/react-native-maps.git#master",

**Comment by tyjing** [comment]
@kidmysoul i am still getting this issue

> [!] CocoaPods could not find compatible versions for pod "GooglePlaces":
  In Podfile:
    GooglePlaces (~> 3.0.3)
Specs satisfying the `GooglePlaces (~> 3.0.3)` dependency were found, but they required a higher minimum deployment target.

and i removed the '~> 3.0.3' from the pod file and install, the googlemaps version is still remain v2.7.0

**Comment by kidmysoul** [comment]
@tyjing 

try to remove your pods folder and do "pod update" and do "pod install"

**Comment by tyjing** [comment]
still the same,
what should i do if this is showing?
![image](https://user-images.githubusercontent.com/30327028/57978450-d4e84c00-7a40-11e9-9b01-558cb220fd6e.png)

**Comment by kidmysoul** [comment]
@tyjing 
if you see there master branch podfile(https://github.com/react-native-community/react-native-maps/blob/master/react-native-google-maps.podspec), you will notice that they use GoogleMaps version 3.0.3. 

so look up your node_modules find where react-native-maps is and find if the podfile is correct3.0.3 version (make sure you installed the master version)

if OK, maybe your other library that also use GoogleMaps(which is a old version) that got conflicted with this library.

**Comment by dblommesteijn** [comment]
I'm stuck with this dependency issues as well. I have concluded the following:

v0.24.4 tag/ release of this repository did include the podspec dependency for GoogleMaps => 2.5.0.

As this git-blame tells you: https://github.com/react-native-community/react-native-maps/blame/99492e92abeb1e2e14450491396e37b07ef678ab/react-native-google-maps.podspec#L20

I'm going to report a new issue, where the maintainer(s) should tag a new release and release that one to npm and yarn.

**Comment by kidmysoul** [comment]
> @tyjing
> in your package.json
> "react-native-maps": "git://github.com/react-native-community/react-native-maps.git#master",

I think i made a mistake.
it should be :
`https://github.com/react-native-community/react-native-maps.git#master`
