### ISSUE TITLE
tracksViewChanges workaround not effective with animated custom markers

### ISSUE THREAD

**Issue by geekazoid-at** [react-native-community/react-native-maps#2749]
### Is this a bug report?
Yes, most likely it is

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
react-native: 0.57.8
react: 16.6.3
react-native-maps: 0.22.1 (also tried with 0.23, same result)

OS: Android (untested on iOS, but will make up for this soon)

### Steps to Reproduce
Using custom markers and the maps library in general worked totally fine for me, besides the jumping/flickering markers. I could work around this issue with the extensively discussed tracksViewChanges fix.

Now I implemented animated markers as this is crucial for my app. Sadly, I am back to the jumping/flickering marker behaviour, BUT only when the marker is moving.

I made sure animation is triggered only once, as well as trying with or without toggling tracksViewChanges or leaving it set to true/false.

### Expected Behavior
Smooth animation without flicker/jumping to different (previous?) locations while animating.

### Actual Behavior
The marker seems to jump to different or a previous location while animating. Otherwise it seems smooth as butter.

### Reproducible Demo
If this is not a known issue I will happily create a minimal reproducible demo for this.
First I'd like to hear your opinion on this as it is already late, I am sick and need to go to bed. Sorry...

I expext it won't help overly much, but here is a pastebin with the animated marker component.
[https://pastebin.com/0kGZies1](https://pastebin.com/0kGZies1)

**Comment by geekazoid-at** [comment]
I actually got it 50% working.
I looked at the example App, sorry I didn't do before. It is a great source for working example code.

I realized that the `newLocation` in `coordinate.timing(newCoordinate).start();` is a location with `latitude` and `longitude` and not another `AnimatedRegion`.

The example in the ReadMe differs quite much, not only in the fact that it spreads the coordinate.

```
this.state.coordinate.timing({
        ...nextProps.coordinate,
        duration
      }).start();
```

I didn't yet get the special Android OS handling working yet. I expect this to be a problem with the state handling but I could not find the problem.

When I get my code fixed 100% I'll happily update the ReadMe or example code, if the solution is an interesting finding.

Inputs are still welcome. Thank you.

**Comment by irvinSing** [comment]
Hi, did u have any luck with this issue?

**Comment by geekazoid-at** [comment]
> Hi, did u have any luck with this issue?

Yes, but the issue was a very different one. I had another map instance running (because of the way I had navigation implemented) which ultimately caused the flickering and iirc this is only the case on Android.

If someone is still struggling with this issue, I'd recommend making sure absolutely no other map instance is active and retest. Hope that helps someone!
