### ISSUE TITLE
showsScale - IOS map only - Improve Doc

### ISSUE THREAD

**Issue by gkueny** [react-native-community/react-native-maps#2757]
### Is this a bug report?

no

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

* react-native: 0.58.4
* react: 16.6.3
* react-native-maps: 0.23.0

* Target Platform: Android

### Steps to Reproduce

Create a react-native Project. Display A Map with `showsScale={true}`. On Android, we have no scale.

### Expected Behavior

Doc should mention that `showsScale` props it's IOS only (with IOS native map)

### Actual Behavior

Doc not mention that.

### See

* https://github.com/react-native-community/react-native-maps/search?q=showsScale&unscoped_q=showsScale 
> In `lib/ios/AirGoogleMaps/AIRGoogleMapManager.m` line **72** we have this comment : `//RCT_EXPORT_VIEW_PROPERTY(showsScale, BOOL)  // Not supported by GoogleMaps`

### Solution

I will be happy to submit a PR to update doc, but I want to be sure it's not a bug and `showSclae` is really IOS only (with IOS native map)

**Comment by rborn** [comment]
@gkueny PR please 🤗 I think there is no scale control for google maps, people are creating their owns

**Comment by rborn** [comment]
Closed by https://github.com/react-native-community/react-native-maps/pull/2759
