### ISSUE TITLE
 UI FPS decrease just moving/panning around the map on ios

### ISSUE THREAD

**Issue by huuthinh245** [react-native-community/react-native-maps#2758]
### Is this a bug report?
yes

(write your answer here)
drop FPS UI when zoom in  or pan on maps on simulator IOS

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)
yes

### Environment
   "react": "16.8.3",
    "react-native": "^0.59.1",
"react-native-maps": "^0.23.0",

### Steps to Reproduce

(Write your steps here:)

1. I'm just implement react-native maps into project. I don't add marker just simple map.
2. Zoom in or pan on maps  fps is dropped. Until 2 second fps is back to 60

### Expected Behavior
 fps ui > 50 when zoom in or pan on map

(Write what you thought would happen.)

### Actual Behavior
UI FPS decrease on simulator ios
![a](https://user-images.githubusercontent.com/27191029/54808178-04354380-4cb2-11e9-91b1-72f93b0efcf4.gif)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by sinodko** [comment]
Yep Google Maps on simulator have very poor performance. Try it on real device and performance should be much better.

**Comment by huuthinh245** [comment]
thanks your advice

**Comment by rborn** [comment]
@huuthinh245 can we close this?

**Comment by khanh21011999** [comment]
It still issue on PROVIDER_GOOGLE , it will drop to 40FPS

**Comment by factorycreacom** [comment]
@khanh21011999 i am having the same problem on real device. Is there a solution?
