### ISSUE TITLE
RN maps doesn't compile anymore on the recent RN 0.59.1 (neither even 0.58.6)

### ISSUE THREAD

**Issue by greenais** [react-native-community/react-native-maps#2762]
According to doc's "we are not officially going to support this module on anything but the latest version of React Native" it looks strange...
Forced to stay on aged "react-native": "0.57.7", "react-native-maps": "0.22.1", where it still works(

### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes. And followed strictly

### Environment
    "react": "16.8.3",
    "react-native": "0.59.1",
    "react-native-maps": "^0.23.0"
    Target Platform:  Android 7.1.1/Android Studio simulator (latest)

### Steps to Reproduce
1. init fresh RN project 
2. strictly follow RNM installation instructions
3. run build

### Expected Behavior
Project builds

### Actual Behavior
Plenty of build errors similar to this:
-------------------------------------------------------------------------------
Could not resolve all files for configuration ':react-native-maps:debugCompileClasspath'.
> Could not resolve com.android.support:support-compat:25.2.0.
  Required by:
      project :react-native-maps
   > Cannot find a version of 'com.android.support:support-compat' that satisfies the version constraints:
        Dependency path 'a_test:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-compat:28.0.0'
....

### Reproducible Demo
Please see Steps to Reproduce abowe

**Comment by rborn** [comment]
@greenais please try the git version and let us know.

**Comment by greenais** [comment]
@rborn 

Did:
npm remove --save react-native-maps
npm i --save git+https://github.com/react-native-community/react-native-maps.git
gradlew clean

ERR: --------------------------------------------------
> Task :react-native-maps:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\sov\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\9c21aef8bc41b5824547538e8b39a4b1\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\a_test\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\sov\.gradle\caches\transforms-1\files-1.1\drawee-1.10.0.aar\f0a9481bfa19727a8a355705ed4afa55\res\values\values.xml:3:5-58:857: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\sov\.gradle\caches\transforms-1\files-1.1\drawee-1.10.0.aar\f0a9481bfa19727a8a355705ed4afa55\res\values\values.xml:3:5-58:857: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.

-----------------------------------------------
I can recall - the same happened when I tried to build latest RNM on RN 0.58.6 as it was suggested in one SO topics.

**Comment by mykhailo-melnyk** [comment]
@greenais 
Please try to use this version:
 "react-native-maps": "https://github.com/react-native-community/react-native-maps/archive/v0.24-rc1.tar.gz"

it worked for me

**Comment by greenais** [comment]
@mykhailo-melnyk 
Nope, unfortunately, completely the same error as with git above:
---------------------------------------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
...
---------------------------------------
gradle is the most recent as well - just updated via Android Studio during RN init

**Comment by rborn** [comment]
@greenais 
do you have  in 
`gradle-erapper.properties` -> `distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`
and `android/build.gradle` -> `classpath 'com.android.tools.build:gradle:3.2.1'`

**Comment by mykhailo-melnyk** [comment]
My settings:

distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip

and 

classpath 'com.android.tools.build:gradle:3.3.0'

**Comment by greenais** [comment]
@rborn 
I have
gradle-wrapper.properties:  
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

android/build.gradle: 
classpath 'com.android.tools.build:gradle:3.3.1'

**Comment by onzedix** [comment]
Im' also facing the same problem. I've made a new React Native App and added the plugin. It does not compile at all, neither with a react-native link, neither with the install process given :(

Any solution ?

**Comment by marcelobarbosaO** [comment]
solved putting modulating and putting no `react-native-maps`  `build.gradle`

`dependencies {
  def googlePlayServicesVersion = safeExtGet('googlePlayServicesVersion', DEFAULT_GOOGLE_PLAY_SERVICES_VERSION)
  // Variable lookup order : googlePlayServicesMapsVersion > googlePlayServicesVersion > DEFAULT_GOOGLE_PLAY_SERVICES_MAPS_VERSION
  def googlePlayServicesMapsVersion = safeExtGet('googlePlayServicesMapsVersion', safeExtGet('googlePlayServicesVersion', DEFAULT_GOOGLE_PLAY_SERVICES_MAPS_VERSION))
  def androidMapsUtilsVersion = safeExtGet('androidMapsUtilsVersion', DEFAULT_ANDROID_MAPS_UTILS_VERSION)

  compileOnly "com.facebook.react:react-native:+"
  implementation "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
  implementation "com.google.android.gms:play-services-maps:$googlePlayServicesMapsVersion"
  implementation "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"

  implementation "com.android.support:support-core-utils:28.0.0"
  implementation "com.android.support:support-core-ui:28.0.0"
  implementation "com.android.support:support-fragment:28.0.0"
}`

**Comment by huuthinh245** [comment]
i fix with implement it
  implementation "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
  implementation "com.google.android.gms:play-services-maps:$googlePlayServicesMapsVersion"
  implementation "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
//add this line
  implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"

**Comment by haztares** [comment]
> i fix with implement it
> implementation "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
> implementation "com.google.android.gms:play-services-maps:$googlePlayServicesMapsVersion"
> implementation "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
> //add this line
> implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"

Thanks you! But I think it solution temporary and we waiting update from react-native-maps for the next version

**Comment by maiquemalmeida** [comment]
>   implementation "com.android.support:support-core-utils:28.0.0"
>   implementation "com.android.support:support-core-ui:28.0.0"
>   implementation "com.android.support:support-fragment:28.0.0"

This worked for me in RN 0.59.0. Thanks!

**Comment by usmanf8c** [comment]
I have been having this issue for the past few weeks and have spent countless hours trying to resolve it.

I have had it working in the prior to that on Android (on both AVD and physical Android device), and on IOS too.

I have tried all of the suggestions above as well as many other solution online to no luck.

react-native-cli: 2.0.1
react-native: 0.59.2
react-native-maps: 0.23.0

@greenais , @onzedix - have you guys had any luck?

**Comment by Metroninja** [comment]
using the linked `"react-native-maps": "https://github.com/react-native-community/react-native-maps/archive/v0.24-rc1.tar.gz"` resolves this issue for me.
my root build.gradle relevant bits
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
...
          configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-location:16.0.0"
                force "com.google.android.gms:play-services-maps:16.0.0"
                force "com.google.android.gms:play-services-base:16.1.0"
            }
        }
ext {
    compileSdkVersion   = 27
    targetSdkVersion    = 27
    compileSdkVersion = 28
    buildToolsVersion = "28.0.3"
    googlePlayServicesVersion = "11.8.0" 
    androidMapsUtilsVersion = "0.5+"
    mapsServicesVersion = "16.0.0"
    locationServicesVersion = "16.0.0"
    playServicesVersion = "16.1.0"
    supportLibVersion   = "28.0.0"
}
```
app build.gradle
```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion '28.0.3'

    defaultConfig {
        ....
        minSdkVersion 19
        targetSdkVersion rootProject.ext.targetSdkVersion
        googlePlayServicesVersion = rootProject.ext.googlePlayServicesVersion
    }
  ...
dependencies {
    implementation "com.google.android.gms:play-services-maps:{$rootProject.ext.mapsServicesVersion}"
    implementation project(':react-native-maps')
}
```

**Comment by usmanf8c** [comment]
> using the rc1 zip resolved the issue for me on rn 59.2.
> package.json
> 
> ```
> {
> ...
>   "react-native-maps": "https://github.com/react-native-community/react-native- 
>  maps/archive/v0.24-rc1.tar.gz",
>   "react-native": "^0.59.2",
> ...
> }
> ```
> my root build.gradle relevant bits
> 
> ```
> buildscript {
>      ...
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.3.2'
>         classpath 'com.google.gms:google-services:4.2.0'
>    }
> }
> ...
> 
> allprojects {
>   repositories {
>       ...
>         configurations.all {
>             resolutionStrategy {
>                 force "com.google.android.gms:play-services-maps:16.0.0"
>             }
>         }
>     }
> }
> 
> ext {
>     compileSdkVersion   = 27
>     targetSdkVersion    = 27
>     compileSdkVersion = 28
>     buildToolsVersion = "28.0.3"
>     googlePlayServicesVersion = "11.8.0" 
>     androidMapsUtilsVersion = "0.5+"
>     mapsServicesVersion = "16.0.0"
>     locationServicesVersion = "16.0.0"
>     playServicesVersion = "16.1.0"
>     supportLibVersion   = "28.0.0"
> }
> ```
> app build.gradle
> 
> ```
> android {
>     compileSdkVersion rootProject.ext.compileSdkVersion
>     buildToolsVersion '28.0.3'
> 
>     defaultConfig {
>         ....
>         minSdkVersion 19
>         targetSdkVersion rootProject.ext.targetSdkVersion
>         googlePlayServicesVersion = rootProject.ext.googlePlayServicesVersion
>     }
>   ...
> dependencies {
>     implementation "com.google.android.gms:play-services-maps:{$rootProject.ext.mapsServicesVersion}"
>     implementation project(':react-native-maps')
> }
> ```

Thanks so much for taking th etime do post this.

I got an error related to the app/build.gradle:

```
A problem occurred evaluating project ':app'.
> Could not set unknown property 'googlePlayServicesVersion' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=19, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=27, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=com.mapapp, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.
```

I'll try other ways - or I may just forego the map part for now, carrying on learning/developing/working and revisit the maps implementation at some point later :)

**Comment by gopinathnet** [comment]
> @greenais
> Please try to use this version:
> "react-native-maps": "https://github.com/react-native-community/react-native-maps/archive/v0.24-rc1.tar.gz"
> 
> it worked for me

Thank you for your solution and saved my time, finally this solution worked for me after few days build issues,
I have solved using following steps
1) didn't touch build.gradle (project level) 
2) app->build.gradle , just update implementation project(':react-native-maps') and  Setting files 
3) use "<uses-library android:name="org.apache.http.legacy" android:required="false"/> " in the AndroidManifest ( inside application tag and just before google keys)
4)"react": "16.8.3",
    "react-native": "0.59.2",
    "react-native-maps": "https://github.com/react-native-community/react-native-maps/archive/v0.24-rc1.tar.gz"

**Comment by JamzWork** [comment]
add this line in react-native-maps app level gradle dependency

 //add this line
`  implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"`

    "react": "16.8.3",
    "react-native": "^0.59.2",
    "react-native-maps": "^0.22.1",

This solved the issue for me.

**Comment by RWOverdijk** [comment]
The RC works for me. Is there an ETA on the full release?

**Comment by endenwer** [comment]
1. Change package version to `"react-native-maps": "https://github.com/react-native-community/react-native-maps/archive/v0.24-rc1.tar.gz"`
2. Set in `android/gradle/wrapper/gradle-wrapper.properties` `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
3. Set  in `android/build.gradle`
```
classpath 'com.android.tools.build:gradle:3.3.0'
``` 
and
```
buildToolsVersion = "28.0.3"
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"
```
This fixed the issue for me.

**Comment by usmanf8c** [comment]
> 1. Change package version to `"react-native-maps": "https://github.com/react-native-community/react-native-maps/archive/v0.24-rc1.tar.gz"`
> 2. Set in `android/gradle/wrapper/gradle-wrapper.properties` `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> 3. Set  in `android/build.gradle`
> 
> ```
> classpath 'com.android.tools.build:gradle:3.3.0'
> ```
> and
> 
> ```
> buildToolsVersion = "28.0.3"
> compileSdkVersion = 28
> targetSdkVersion = 28
> supportLibVersion = "28.0.0"
> ```
> This fixed the issue for me.

Just tried this. It works!

To clarify, all of the settings were like the quote by default, except the package version. I changed it to "https://github.com/react-native-community/react-native-maps/archive/v0.24-rc1.tar.gz" in package.json

**Comment by SystemBlad** [comment]
Hi everyone,
The solutions presented here indicates to change the react-native-maps to master or v0.24-rc1 versions,  but doing this the performance of maps decrease  a lot when showinng 300 marks or more. 
This BUG is not shown in version v0.23.0.

I don´t recoment change the version for production application, just for debugging.

Someone knows when a new library version will be released?

**Comment by RWOverdijk** [comment]
@SystemBlad If what you're saying is true, that's actually great news for my app, because it's really really slow and I thought it was just my poor coding. If not, it's still my poor coding.

Either way, good question. When is the next release?

**Comment by SystemBlad** [comment]
@RWOverdijk to avoid the slow map problem you can use the previous version 0.23.0 adding these lines:

  implementation "com.android.support:support-core-utils:28.0.0"
  implementation "com.android.support:support-core-ui:28.0.0"
  implementation "com.android.support:support-fragment:28.0.0"

To react-native-maps gradle. Suggested by @marcelobarbosaO.
I think for now it is the best solution

**Comment by rborn** [comment]
@SystemBlad we just release `0.24.2` could you please test if it works ok for you?

**Comment by skb1129** [comment]
@rborn version `^0.24.0` solves this issue, it can be closed.

**Comment by rborn** [comment]
Closing as  per https://github.com/react-native-community/react-native-maps/issues/2762#issuecomment-484636664

**Comment by SystemBlad** [comment]
> @SystemBlad we just release `0.24.2` could you please test if it works ok for you?

@rborn. Thanks for this new release.
With several marks the application run slowly when user moves the map, it happends just on Android. I'm going to do an example project detailing the problem and then I will create a new issue.

**Comment by RWOverdijk** [comment]
@SystemBlad Could you please mention me in the new issue? I'd like to follow it.

**Comment by greenais** [comment]
@rborn Unfortunately I'm still getting "Android resource linking failed" error at compile stage on the most recent "react-native": "0.59.5".
Tried all versions 0.24+
gradlew cleaned, any suggestions, perhaps?
