### ISSUE TITLE
Not able get maps view in react native app

### ISSUE THREAD

**Issue by Ratanracha** [react-native-community/react-native-maps#2767]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

I have red the instruction and I found some mismatching between folder structure from instructions and my react native app folder structure 

### Environment
   react-native: "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
    react: 16.5.0
	react-native-maps:"^0.23.0"

 
  Target Platform: Andriod 

### Steps to Reproduce

(Write your steps here:)

1. Run the command '**npm install -g create-react-native-app**' in node.js console window
2. Run the command '**create-react-native-app AwesomeProject**'
3. It will create a project with following folder structure
![image](https://user-images.githubusercontent.com/48963229/55023994-f3732d80-5023-11e9-80ad-45c0969122e2.png)

4. Here am not able to find Andriod and IOS which is leading to confusion.
5. As per the instructions I have to made some changes in AndriodManifest.xml etc.. as per the following screen shot

![image](https://user-images.githubusercontent.com/48963229/55024316-a04daa80-5024-11e9-895f-0fb12b218ae2.png)

6. Here am not find these files to make changes so help in resolving this and let me know how to user maps view in React 0.59 version

Please let me know if you need any more details if you are not understanding my issue

Thank you in advance.. 
### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
You are using Expo, this module is intended to be used with `react-native init`

**Comment by Ratanracha** [comment]
Now how can use maps view.
Send me a article or guide me how to use maps view

**Comment by rborn** [comment]
https://docs.expo.io/versions/latest/sdk/map-view/

**Comment by Ratanracha** [comment]
Still this documentation is guiding me to the same blog for installation of react native maps where am not able to do that since I don't have some folders which blog is saying. For even configuring google maps and providing API keys it is guiding me to add Key in andriodmanifest file which am not able to find as you can see in the below screen shot

![image](https://user-images.githubusercontent.com/48963229/55273137-171cc900-52ed-11e9-946e-0d18af7fd630.png)

So can you help me with process how can I show maps in my current react native app or guide me to create new react native app in a proper way to use maps.
