### ISSUE TITLE
 Library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by gmars** [react-native-community/react-native-maps#2770]
d: warning: directory not found for option '-L/Users/marswill/Library/Developer/Xcode/DerivedData/tuxiaotu-gddyedgwmkkenfbkzynandijowch/Build/Products/Debug-iphoneos/DoubleConversion'
ld: warning: directory not found for option '-L/Users/marswill/Library/Developer/Xcode/DerivedData/tuxiaotu-gddyedgwmkkenfbkzynandijowch/Build/Products/Debug-iphoneos/Folly'
ld: warning: directory not found for option '-L/Users/marswill/Library/Developer/Xcode/DerivedData/tuxiaotu-gddyedgwmkkenfbkzynandijowch/Build/Products/Debug-iphoneos/React'
ld: warning: directory not found for option '-L/Users/marswill/Library/Developer/Xcode/DerivedData/tuxiaotu-gddyedgwmkkenfbkzynandijowch/Build/Products/Debug-iphoneos/glog'
ld: warning: directory not found for option '-L/Users/marswill/Library/Developer/Xcode/DerivedData/tuxiaotu-gddyedgwmkkenfbkzynandijowch/Build/Products/Debug-iphoneos/yoga'
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chaoa888** [comment]
怎么解决的呢？
