### ISSUE TITLE
Not working on Android Pie

### ISSUE THREAD

**Issue by renishdeveloper** [react-native-community/react-native-maps#2773]
React native maps is working fine on Android till android version 7, but when I tested the app on Android version 9(Pie), the app crash

react-native-cli: 2.0.1
react-native: 0.58.6
"react-native-maps": "^0.23.0"
Target Platform: Android 9

**Code**
```
<MapView
    style={styles.mapView}
    onMapReady={() => {

    }}
    region={{
        latitude: this.props.currentState.lat,
        longitude: this.props.currentState.lng,
        latitudeDelta: this.props.currentState.latitudeDelta,
        longitudeDelta: this.props.currentState.longitudeDelta,
    }}
    showsUserLocation={true}>
    <Marker
        draggable
        coordinate={{
            latitude: this.props.currentState.lat,
            longitude: this.props.currentState.lng,
        }}
        title={"Marker title"}
        description={"Marker description"}
        onDragEnd={(e) => console.log(e.nativeEvent.coordinate)}
    />
</MapView>
```

**Comment by rborn** [comment]
@renishdeveloper please try with the master version, I have an app that works on Pie without problems.

**Comment by grifotv** [comment]
@renishdeveloper update the Gradle dependencies to the following:

```
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "15.0.1"
        androidMapsUtilsVersion = "0.5+"
    }
```

https://github.com/react-native-community/react-native-maps/pull/2727#issuecomment-471712384

**Comment by grsabreu** [comment]
@renishdeveloper https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

If you have this log in your `adb logcat`
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
```

You need to add this to your AndroidManifest.xml `application`
```
      <uses-library android:name="org.apache.http.legacy" android:required="false"/>
```

See https://issuetracker.google.com/issues/79478779#comment11 and https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

**Comment by rborn** [comment]
@renishdeveloper is this still an issue for you?

**Comment by agoqui** [comment]
Thanks @fakenickels ! So great! For me it's ok!

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-community/react-native-maps/issues/2773#issuecomment-479488331

**Comment by RasikBhil** [comment]
sas

**Comment by samerdernaika** [comment]
my solution was to install the certificate within the app

**Comment by energy-uktc** [comment]
> @renishdeveloper https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library
> 
> If you have this log in your `adb logcat`
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
> ```
> 
> You need to add this to your AndroidManifest.xml `application`
> 
> ```
>       <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```
> 
> See https://issuetracker.google.com/issues/79478779#comment11 and https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library



> @renishdeveloper https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library
> 
> If you have this log in your `adb logcat`
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
> ```
> 
> You need to add this to your AndroidManifest.xml `application`
> 
> ```
>       <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```
> 
> See https://issuetracker.google.com/issues/79478779#comment11 and https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library



> @renishdeveloper https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library
> 
> If you have this log in your `adb logcat`
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
> ```
> 
> You need to add this to your AndroidManifest.xml `application`
> 
> ```
>       <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```
> 
> See https://issuetracker.google.com/issues/79478779#comment11 and https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

**Comment by pstanton** [comment]
as per the [doc](https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library) you can use 
`
        playServicesVersion = "16.1.0"
`

in android/build.gradle

I'd rather this than specifically requiring legacy libraries.
