### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by dragneel30** [react-native-community/react-native-maps#2787]
This only happens when I put a marker on mapview

Here is my code:
```

<View style={styles.main}> 
         <MapView style={styles.map} 
            initialRegion={{
              latitude: 14.643350,
              longitude: 121.037990,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}>
              <Marker coordinate={{lat: 14.643350, lng: 121.037990}}  title={"test"} key={1} identifier={1}/>
        </MapView>
      </View>
```

But when I removed the Marker it works.

**Comment by fmchan** [comment]
i have the same problem. how to solve?

**Comment by ParthMaisheri** [comment]
> This only happens when I put a marker on mapview
> 
> Here is my code:
> 
> ```
> 
> <View style={styles.main}> 
>          <MapView style={styles.map} 
>             initialRegion={{
>               latitude: 14.643350,
>               longitude: 121.037990,
>               latitudeDelta: 0.0922,
>               longitudeDelta: 0.0421,
>             }}>
>               <Marker coordinate={{lat: 14.643350, lng: 121.037990}}  title={"test"} key={1} identifier={1}/>
>         </MapView>
>       </View>
> ```
> 
> But when I removed the Marker it works.

use  marker tag like this <MapView.Marker>
