### ISSUE TITLE
react-native-maps:compileDebugJavaWithJavac FA ILED

### ISSUE THREAD

**Issue by artaro** [react-native-community/react-native-maps#2788]
### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

"react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-maps": "^0.23.0"

### Steps to Reproduce

I just follow install instructions and run my project and this appeared after that.

info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

> Task :react-native-maps:compileDebugJavaWithJavac FA
ILED
/Users/artaro/TestMapMap/node_modules/react-native-map
s/lib/android/src/main/java/com/airbnb/android/react/m
aps/AirMapModule.java:18: error: cannot find symbol
import com.facebook.react.uimanager.UIBlock;
                                   ^
  symbol:   class UIBlock
  location: package com.facebook.react.uimanager
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/RegionChangeEvent.java:15: error: no suitable constructor found for Event(int)
    super(id);
    ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int,long) is not applicable
      (actual and formal argument lists differ in length)
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:90: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock() {
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:149: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock()
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:192: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock()
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:229: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock()
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:262: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock()
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/ViewAttacherGroup.java:23: error: cannot find symbol
    this.setOverflow("hidden"); // Change to ViewProps.HIDDEN until RN 0.57 is base
        ^
  symbol: method setOverflow(String)
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:129: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package
    if (!contextHasBug(appContext.getCurrentActivity())) {
                                 ^
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:130: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package
      superContext = appContext.getCurrentActivity();
                               ^
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:133: error: cannot find symbol
      if (!contextHasBug(reactContext.getCurrentActivity())) {
                                     ^
  symbol:   method getCurrentActivity()
  location: variable reactContext of type ThemedReactContext
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:134: error: cannot find symbol
        superContext = reactContext.getCurrentActivity();
                                   ^
  symbol:   method getCurrentActivity()
  location: variable reactContext of type ThemedReactContext
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java:127: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/artaro/TestMapMap/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java:130: error: cannot find symbol
    super.setZIndex(view, zIndex);
         ^
  symbol: method setZIndex(AirMapMarker,float)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
14 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
15 actionable tasks: 1 executed, 14 up-to-date
error Could not install the app on the device, read th
e error above for details.
Make sure you have an Android emulator running or a de
vice connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.

### Expected Behavior

I just hope my project can run fine.

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by stevenheffner** [comment]
Did you add this line

`import com.airbnb.android.react.maps.MapsPackage;`

and this line 

`new MapsPackage()`

into your  *MainApplication.java*?

**Comment by Aymanov3** [comment]
yes

**Comment by artaro** [comment]
> Did you add this line
> 
> `import com.airbnb.android.react.maps.MapsPackage;`
> 
> and this line
> 
> `new MapsPackage()`
> 
> into your _MainApplication.java_?

I already add it.

**Comment by artaro** [comment]
I need some help :(

**Comment by christopherdro** [comment]
@artaro Have you tried running the example app?

**Comment by skb1129** [comment]
Same as https://github.com/react-native-community/react-native-maps/issues/2762

**Comment by rborn** [comment]
Closing as duplicate
