### ISSUE TITLE
why react-native-maps is getting crashed when coordinates is given from remote server.

### ISSUE THREAD

**Issue by TusharGuptaAdinav** [react-native-community/react-native-maps#2795]
### Is this a bug report?

(Yes)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Yes)

### Steps to Reproduce

(1.installed "react-native-maps": "0.22.0"
2.Fetched coordinates from remote server node.js using POST
3.using Mapview.marker
4.App is getting crashed with error "Uncaught Error:Requiring unknown module "undefined"" when build,
5.It is working fine in devmode )

1. 2. 3.

### Expected Behavior

(Mapview should show markers with the coordinates from remote server)

### Actual Behavior

(App Got Crashed)
package.json 
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^9.0.0",
    "body-parser": "^1.17.2",
    "concurrently": "^4.1.0",
    "connect-history-api-fallback": "^1.6.0",
    "dotenv": "^4.0.0",
    "errorhandler": "^1.5.0",
    "expo": "^32.0.0",
    "firebase": "^5.8.4",
    "lottie-react-native": "^2.5.11",
    "moment": "^2.24.0",
    "native-base": "^2.10.0",
    "node": "^11.9.0",
    "prop-types": "*",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-collapsible": "^1.4.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-datepicker-modal": "^1.0.2",
    "react-native-floating-action": "^1.14.1",
    "react-native-gifted-chat": "^0.7.2",
    "react-native-image-grid": "^1.0.0",
    "react-native-image-picker": "^0.28.0",
    "react-native-modal": "^7.0.2",
    "react-native-maps": "0.22.0",
    "react-native-parallax-scroll-view": "^0.21.3",
    "react-native-progress": "^3.6.0",
    "react-native-responsive-dimensions": "^1.0.2",
    "react-native-share": "^1.1.3",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-tab-view": "^1.0.2",
    "react-native-ui-kitten": "^3.1.2",
    "react-navigation": "^3.0.9",
    "react-navigation-backhandler": "^1.2.0",
    "react-timer-mixin": "^0.13.4",
    "validate.js": "^0.12.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
### Reproducible Demo
 

(Paste the link to an example project and exact instructions to reproduce the issue.)
![Screenshot_2019-04-06-14-09-51-153_com adinavlabs bdapp](https://user-images.githubusercontent.com/34834162/55667188-97f03d80-5876-11e9-8ef0-db3771a4f208.png)

**Comment by rborn** [comment]
This seems to be an implementation issue. Without any code sample we cannot help. 
I'll close this for now.
