### ISSUE TITLE
Update readme file with latest android gradle file.

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-community/react-native-maps#2797]
### Is this a bug report?

 "Yes":

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

 i have read all the installation file of android. every where i getting only 26 version or old version sdk.
my problem is :-
1. i am not able to add react native maps with successfully synced gradle with 28 sdk version.

i have successfully added library in ios with manual link.

### Environment

    "react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-maps": "^0.23.0",

Android : -

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 26
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}`

### Expected Behavior

Gradle and work successfully.

### Actual Behavior

Gradle and work  both not done successfully

**Comment by edu1525** [comment]
I also have this issue, please heeelp!!!!!

**Comment by Biplovkumar** [comment]
No reply came via community ?

**Comment by Biplovkumar** [comment]
step 1 :- 
Packeage.json :- 
` "react-native-maps": "https://github.com/react-native-community/react-native-maps.git"`
step 2 :- 
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 26
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.1.0"
        androidMapsUtilsVersion = "0.5+"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }



Note :- Gradle fine but restart App after some time, its a big issue ,Memory leak issue.   

Please reply , i have spoiled my whole day in react native maps implementation.

![Screenshot 2019-04-12 at 4 26 15 PM](https://user-images.githubusercontent.com/30401136/56032840-c1124180-5d40-11e9-96cf-98bc15a71fc6.png).

**Comment by Biplovkumar** [comment]
Always restart the emulator.
Please help ?

**Comment by rborn** [comment]
@Biplovkumar  try again please with the latest version `0.24.2`

**Comment by skb1129** [comment]
@rborn Same as https://github.com/react-native-community/react-native-maps/issues/2798, can be closed now.

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-community/react-native-maps/issues/2797#issuecomment-484638085

**Comment by Biplovkumar** [comment]
https://github.com/react-native-community/react-native-maps/issues/2797#issuecomment-484395667

Not solved by this .
