### ISSUE TITLE
Gradle issue on compilation (api 28)

### ISSUE THREAD

**Issue by edu1525** [react-native-community/react-native-maps#2798]
Hi, i'm trying to use this library in my project. I have followed the tutorial but when I try to compile the project, this message is printed on console : 
"Could not resolve all files for configuration ':react-native-maps:debugCompileClasspath'.
> Could not resolve com.android.support:support-compat:26.1.0.
  Required by:
      project :react-native-maps"

I'm importing lib in build gradle(app) like: **"implementation project(':react-native-maps')"** and in build.gradle(android) I have those ext variables: 
 ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "15.0.1"
        androidMapsUtilsVersion = "0.5+"
    }

**I'm using 3.3.1 gradle version** and in my package.json I have this versions: 
   "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-maps": "^0.23.0"

I don't know what to do anymore to resolve this issue, pleaase can somebody help-me ???

**Comment by skb1129** [comment]
Try using the master branch directly, react-native-maps v0.23.0 is not working with react-native v0.59.0. Just put the git URL for the react-native-maps repository in the package.json file.
```
"react-native-maps": "https://github.com/react-native-community/react-native-maps.git",
```

**Comment by edu1525** [comment]
@skb1129 thaaanks a lot boy, you saved my life.

**Comment by Biplovkumar** [comment]
> Try using the master branch directly, react-native-maps v0.23.0 is not working with react-native v0.59.0. Just put the git URL for the react-native-maps repository in the package.json file.
> 
> ```
> "react-native-maps": "https://github.com/react-native-community/react-native-maps.git",
> ```

My ios part which is working fine,that is affected. so this solution is not working fine.
1. Memory leak.
2. Crash.

**Comment by Biplovkumar** [comment]
Hey @rbon ,
Sorry to say u,
It is the issue of this template.
After adding react native maps in API 28, gardle is not working fine.
Everyone stuck in android thing.

**Comment by Biplovkumar** [comment]
Hey @rbon ,
Sorry to say u,
It is the issue of this template.
After adding react native maps in API 28, gardle is not working fine.
Everyone stuck in android thing.

**Comment by Biplovkumar** [comment]
hey @edu1525 

**Package.json:-** 

```
   "react-native": "0.59.4",
   "react-native-maps": "https://github.com/react-native-community/react-native-maps.git",
```

 **Android Project gradle :-** 

  ```
 // Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.1.0"
        androidMapsUtilsVersion = "0.5+"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```



**App level gradle :-** 

```
def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
    defaultConfig {
        applicationId "com.floronapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"
    }
    }

    dependencies {
    implementation project(':react-native-maps')  
}
```


**Android MainApplication.java change :-** 

```
import com.airbnb.android.react.maps.MapsPackage;
new MapsPackage()
```

**Setting.gradle file change :-** 
 
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```

**AndroidManifest.xml change inside Application Tag:-** 

```
<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="*******************************" />

```

For more check this :- [link](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#build-configuration-on-android)

**Comment by Biplovkumar** [comment]
Gradle problrm is solved but still memory issue.

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-community/react-native-maps/issues/2798#issuecomment-480561977
