### ISSUE TITLE
onRegionChangeComplete returns 0 longitude or sometimes random lat long(mostly negative values)

### ISSUE THREAD

**Issue by EleeMosinarY** [react-native-community/react-native-maps#2802]
Sometimes when map opens onRegionChangeComplete  returns  random regions mostly returns longitude 0 and i'm using initialRegion property along with onRegionChangeComplete 

I'm getting this region
{
longitudeDelta: 0.49999929964542383,
latitudeDelta: 0.8597136848955765,
longitude: 0,
latitude: 6.38378239159465e-15
}

instead of this region {
longitudeDelta: 0.030211396515369415,
latitudeDelta: 0.05157664999429379,
longitude: 73.1523017026484,
latitude: 6.848942325333203
}

**Comment by lyseiha** [comment]
+1

**Comment by HossamSamir** [comment]
+1
