### ISSUE TITLE
How can I install application in my android device

### ISSUE THREAD

**Issue by MansiThakkar** [react-native-community/react-native-maps#2804]
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by MansiThakkar** [comment]
Can you explain I got the error while running the app in android?

**Comment by rborn** [comment]
You got what error ? Why don't you follow the issue template of you want help? How are we supposed to know what's happening on your device if you don't describe the issue?

**Comment by MansiThakkar** [comment]
when I download the project and in terminal I install npm and after that, I use command react-native run-android this command is not working
