### ISSUE TITLE
[Question] When 0.24 version will be publish on npm?

### ISSUE THREAD

**Issue by ohjeyong** [react-native-community/react-native-maps#2805]
_This post is about simple question so I ignore the template._

May I ask when 0.24 will be published on npm?
I would like to express my gratitude and appreciation to the contributors of react-native-maps, and with _no offence_, can I share the release plan on 0.24 version?
I think many people who are using this package will have problem when they are going to upgrade react-native version 0.59.x because react-native-maps' latest version 0.23 is not compatible with react-native 0.59.x.

Thank you again with this great package.

**Comment by jchavezjs** [comment]
It's been i while since 0.59 came out. For the moment, you can install react-native-maps in your RN0.59 project using "react-native-maps": "https://github.com/react-native-community/react-native-maps.git#v0.24-rc1" inside your package.json

**Comment by ohjeyong** [comment]
Yes, I'm currently using 0.24-rc1 in my project and it works perfectly fine with react-native 0.59.x, so I have more curious about the reason why 0.24 is not published on npm.

**Comment by rborn** [comment]
@christopherdro  any plans to promote RC to GA ?

@ohjeyong we could use some help in creating the changelog so if you fancy a PR let me know

**Comment by christopherdro** [comment]
@rborn Just published 0.24.0

@salah-ghanim If we want to have release candidates in the future we have to bump versioning in a few places before tagging the release. Here is an example of changes required before a release. https://github.com/react-native-community/react-native-maps/pull/2666/files
