### ISSUE TITLE
Sometime app frozen/map distored after zoom in and zoom out map.

### ISSUE THREAD

**Issue by kduy969** [react-native-community/react-native-maps#2809]
Sometime my app frozen after zoom in and zoom out map. I leave the screen for a few minute but nothing change, and app not crash too.

Sometime zoom in and zoom out mapview also cause map distorted

![Skype_Picture_2019_04_13T05_29_09_096Z](https://user-images.githubusercontent.com/5911229/56075136-cd9da500-5de7-11e9-8fd7-afe3dd924489.jpeg)

### Is this a bug report?

Yes

### Have you read the [Installation Instructions]

Yes

### Environment

    react-native: 0.59.1
    react: 16.8.3
    react-native-maps: 0.23.0 
    map provider: Google
    platform: iOS
    device: iPhone X Max

### Steps to Reproduce

I can't reproduce it's consistently , it's happen very randomly when I zoom in and zoom out google map , I also have some marker and circle on map, most of the time it's work correct.

**Comment by salah-ghanim** [comment]
@kduy969 this can't be handled as a bug report since we don't have any details provided.
Please spend time analysing ideally using a sample project and once you find out the exact bug source we're happy to look into it.

But freezes sound like too many rerender attempts or too much communication over the bridge, please try to optimize there.

Feel free to submit a new issue with better description / more details.

**Comment by iamabdulhaseeb** [comment]
> Sometime my app frozen after zoom in and zoom out map. I leave the screen for a few minute but nothing change, and app not crash too.
> 
> Sometime zoom in and zoom out mapview also cause map distorted
> 
> ![Skype_Picture_2019_04_13T05_29_09_096Z](https://user-images.githubusercontent.com/5911229/56075136-cd9da500-5de7-11e9-8fd7-afe3dd924489.jpeg)
> 
> ### Is this a bug report?
> Yes
> 
> ### Have you read the [Installation Instructions]
> Yes
> 
> ### Environment
> ```
> react-native: 0.59.1
> react: 16.8.3
> react-native-maps: 0.23.0 
> map provider: Google
> platform: iOS
> device: iPhone X Max
> ```
> 
> ### Steps to Reproduce
> I can't reproduce it's consistently , it's happen very randomly when I zoom in and zoom out google map , I also have some marker and circle on map, most of the time it's work correct.

Did you solve this?

**Comment by SirPhemmiey** [comment]
Any update on this issue, please?
