### ISSUE TITLE
Rotate maps/marker

### ISSUE THREAD

**Issue by khankuan** [react-native-community/react-native-maps#281]
Hi, is there a way to allow rotation of the map as well as the marker image?

**Comment by Elyx0** [comment]
I'd like to rotate the map to face what the phone is facing too.

**Comment by perkola** [comment]
Bump. Also interested in this.

**Comment by kcfgl** [comment]
I would definitely be interested in rotating a custom marker image.

**Comment by jojonarte** [comment]
Bump.

**Comment by kevando** [comment]
Can't you just add a transform? This works for me.

```
<MapView.Marker
            image={missileImg}
            style={{backgroundColor:'#ccc',transform: [{rotate: '50deg'}],}}  
/>
```

**Comment by jojonarte** [comment]
#765

**Comment by dorthwein** [comment]
+1

**Comment by sandinosaso** [comment]
Rotate the map itself: https://github.com/airbnb/react-native-maps/pull/1544

**Comment by aaronbuchanan** [comment]
^ has been merged in for anyone looking for this

**Comment by Musigwa** [comment]
Hello guys, I have seen the awesome support for the map rotation that has been added but i'm not able rotate the map towards the direction of device's motion as shown on the GIF [airbnb#1544](https://github.com/react-community/react-native-maps/pull/1544). could anyone help me with the codes please?? thanks in advance.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by haratmalli** [comment]
Anybody can  tell me about how to rotate the marker image towards the vehicle moving direction.

**Comment by Emmanuel-umeh** [comment]
> Anybody can tell me about how to rotate the marker image towards the vehicle moving direction.

If you are using expo, you can use the Location.watchHeadingAsync function https://docs.expo.io/versions/latest/sdk/location/#locationwatchheadingasynccallback to subscribe to heading updates and probably set it in your state. Then on your marker you can use the transform property like this
style ={{
   transform: [
                  {
                    rotate:
  
                     
                      !this.state.heading ? 
                        "0deg"
                        : `${this.state.heading }deg`,
                  },
                ],
               

}}

it will keep rotating to your users device heading.
To rotate the map you can use the centerCamera provided by expo and pass in the heading as an argument.

**Comment by tungxuan1656** [comment]
> > Bất kỳ ai có thể cho tôi biết về cách xoay hình ảnh điểm đánh dấu theo hướng di chuyển của xe.
> 
> Nếu bạn đang sử dụng hội chợ triển lãm, bạn có thể sử dụng chức năng Location.watchHeadingAsync https://docs.expo.io/versions/latest/sdk/location/#locationwatchheadingasynccallback để đăng ký cập nhật tiêu đề và có thể đặt nó ở trạng thái của bạn. Sau đó, trên điểm đánh dấu của bạn, bạn có thể sử dụng thuộc tính biến đổi như thế này
> 
> ```
> style ={{
>    transform: [
>                   {
>                     rotate:
>                      !this.state.heading ? 
>                         "0deg"
>                         : `${this.state.heading }deg`,
>                   },
>                 ],
>                
> 
> }}
> ```
> 
> nó sẽ tiếp tục xoay theo tiêu đề thiết bị người dùng của bạn. Để xoay bản đồ, bạn có thể sử dụng centerCamera do hội chợ cung cấp và chuyển vào tiêu đề như một đối số.
> 
> Trong trường hợp điểm đánh dấu di chuyển thay vì chỉ xoay, bạn có thể áp dụng neo và bù đắp cho Điểm đánh dấu như thế này
> 
> ```
> 
>               anchor={{x: 0.5, y: 0.5}}
>               centerOffset={{x: 0.5, y: 0.5}}
> ```

Helped me 💯. Thank you
