### ISSUE TITLE
Prevent MapView from re-rendering on Marker position change

### ISSUE THREAD

**Issue by matthieu994** [react-native-community/react-native-maps#2811]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.58.6
    react: 16.8.4
    react-native-maps: 0.24.0

### Steps to Reproduce

1. Render a MapView with dynamic latitude and longitude
2. Add a Marker
3. Change the Marker position

### Expected Behavior

I would like the MapView to not re-render when the Marker position change, as it causes the map to focus on the initial region.

### Actual Behavior

When I change the Marker position, the entire map seems to re-render and focus on the initial region.

### Reproducible Demo

```
  componentDidMount() {
    navigator.geolocation.getCurrentPosition(
      position => {
        this.coords = position.coords
      },
      error => console.warn(error)
    )
  }

  setLocation(e) {
    this.setState({ selectCoordinates: e.nativeEvent.coordinate })
  }

  render() {
    if (!this.coords) return null

    return (
      <View>
        <MapView
          provider={PROVIDER_GOOGLE}
          style={styles.map}
          region={{
            latitude: this.coords.latitude,
            longitude: this.coords.longitude,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121
          }}
          onPress={e => this.setLocation(e)}
        >
          {this.state.selectCoordinates && (
            <Marker coordinate={this.state.selectCoordinates} />
          )}
        </MapView>
      </View>
    )
  }

```

**Comment by salah-ghanim** [comment]
@matthieu994 this is a question better suited for stackoverflow 
but use initialRegion instead of region it should work

see 

https://github.com/react-native-community/react-native-maps/blob/master/README.md

**Comment by Dgs-asohail4** [comment]
@ma

**Comment by Dgs-asohail4** [comment]
@matthieu994 did you find the solution, i am facing same problem
