### ISSUE TITLE
How to change loading tiles color?

### ISSUE THREAD

**Issue by vlkosinov** [react-native-community/react-native-maps#2814]
When I use a dark theme in my application, it's annoying that the map are flashing bright tiles. So question here, how to change color of this tiles? Same behaviour on Android and iOS.  
```
react-native: 0.59.3
react-native-maps: 0.24
```
```js 
<View style={{ flex: 1 }}>
  <MapView
    loadingBackgroundColor="red"
    loadingIndicatorColor="red"
    style={{
      flex: 1,
      backgroundColor: 'red',
    }}
    provider={PROVIDER_GOOGLE}
    customMapStyle={mapStyle}
    zoomEnabled={false}
    scrollEnabled={false}
    rotateEnabled={false}
    region={regionFrom(59.995424, 30.248924, 1000)}
  />
</View>
```

![ezgif-4-8467f45170c5](https://user-images.githubusercontent.com/4584879/56212447-b7e7e400-6062-11e9-91de-9ade33d9223a.gif)

<img width="536" alt="Screenshot 2019-04-16 at 16 10 52" src="https://user-images.githubusercontent.com/4584879/56212718-42304800-6063-11e9-9f3e-a73632ba676c.png">
<img width="536" alt="Screenshot 2019-04-16 at 16 10 14" src="https://user-images.githubusercontent.com/4584879/56212720-42304800-6063-11e9-94a3-7662a84471b6.png">

**Comment by aylok1n** [comment]
same problem(((

**Comment by top-kat** [comment]
@rborn I understand there is no issue template or this one and it can be annoying. However, this is something that happens in google map, whatever devices we are using.

Do you think you can nevertheless give an advice on how to solve that ?

**Comment by NiccoloCase** [comment]
same problem
