### ISSUE TITLE
Feature Request: Allow MapView to be queried for current user location

### ISSUE THREAD

**Issue by netshade** [react-native-community/react-native-maps#2819]
### Is this a bug report?

No ( Feature request )

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

All

### Feature Request

I would like to make it such that the map view can be queried for its view of what the current user location is. On iOS I would use [this functionality](https://developer.apple.com/documentation/mapkit/mkmapview/1452459-userlocation), and on Android I would use [this functionality](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient) to allow for clients to query the map for the current location.

Rationale: I've observed on iOS that using the geolocation interfaces will sometimes return lat / lngs that do not correspond to the current position of the blue dot representing the user's current location.

I'm happy to provide a PR, but would like confirmation that this would be a desirable feature before I submit it.

**Comment by rborn** [comment]
@netshade we already have `onUserLocationChange` (for google maps only) - is this what you need?

**Comment by netshade** [comment]
In this case I wanted an identical interface on Google and Apple maps, and an immediate method ( give me the location as of right now ) rather than an eventual method ( give me the location when a change is detected ).

**Comment by rborn** [comment]
@netshade if this is something you could make a PR for (cross-platform, and both providers) I'll be more than happy to review (with my limited knowledge) and merge 🤗

**Comment by netshade** [comment]
Awesome - I plan on doing so in the next month. I'll close this ticket just to reduce noise, and reference it when I actually submit the PR.

**Comment by Un3qual** [comment]
Any update on this?

**Comment by netshade** [comment]
While it would still be useful, it became not necessary for the project that I needed the feature for; therefore I am extremely unlikely to do it.
