### ISSUE TITLE
Re-render only polygon without loading whole Map

### ISSUE THREAD

**Issue by jahir-pm** [react-native-community/react-native-maps#2820]
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jahir-pm** [comment]
I want to draw polygon as per the filter state value changes without reloading the whole map. The issue already posted on [here](https://stackoverflow.com/questions/55701961/the-whole-map-rendering-every-time-when-state-got-changed)

**Comment by rborn** [comment]
This is not a proper template and you already have the question on SO. 
Why do you post multiple times?

Closing
