### ISSUE TITLE
Android installation fails

### ISSUE THREAD

**Issue by Darkiman** [react-native-community/react-native-maps#2823]
### Is this a bug report?

Yes 

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"@react-native-community/async-storage": "^1.3.3",
    "i18n-js": "^3.2.1",
    "react": "16.8.3",
    "react-native": "0.59.4",
    "react-native-device-info": "^1.5.0",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-maps": "^0.24.2",
    "react-native-settings-list": "^1.8.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.8.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"

![image](https://user-images.githubusercontent.com/9611234/56456451-56cb5380-6375-11e9-8469-c5ccf301b06d.png)

![image](https://user-images.githubusercontent.com/9611234/56456458-72cef500-6375-11e9-9d64-8206f26092a8.png)

Target Platform: Android 9.0/Nexus 5X

### Steps to Reproduce

1. yarn install
2. react-native start
3. react-native run-android

### Expected Behavior

Application load normally

### Actual Behavior

Got error after followings steps from installation instruction
![image](https://user-images.githubusercontent.com/9611234/56456398-639b7780-6374-11e9-9c4f-bfb2e03122b7.png)

### Reproducible Demo

https://github.com/Darkiman/react-native-app/tree/maps

**Comment by rborn** [comment]
You forgot to install the modules correctly, In this case is not the map module but the i18n.
(Check you imported the packages and then call them in MainAplication.java )

**Comment by verochan** [comment]
We're experiencing this same issue in our project. We tried a project branch without react-native-maps and the project loads ok on the Android emulator, but after installing react-native-maps we get this error:

![react-native-maps_android_error](https://user-images.githubusercontent.com/4173284/56645184-7ddb9b00-667d-11e9-8ee3-46ffd04978d2.png)

package.json

```
"dependencies": {
    "babel-preset-react-native": "^4.0.1",
    "i18n-js": "^3.2.1",
    "immutable": "^4.0.0-rc.12",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-native": "0.59.4",
    "react-native-device-info": "^0.26.1",
    "react-native-elements": "^1.0.0",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-localize": "^1.1.2",
    "react-native-maps": "0.24.2",
    "react-native-sqlite-storage": "3.3.9",
    "react-native-vector-icons": "^6.2.0",
    "react-navigation": "^3.2.1",
    "sinon": "^7.3.1",
    "styled-components": "^4.2.0"
  }
```

Android SDK tools

![androidsdktools](https://user-images.githubusercontent.com/4173284/56645585-44eff600-667e-11e9-9312-9fa678f10d4b.png)

Android SDK platforms

![androidsdkplatforms](https://user-images.githubusercontent.com/4173284/56645564-3bff2480-667e-11e9-95a2-6a58a33966a1.png)

We also updated react-native-languages to react-native-localize just in case, but the error keeps appearing, and as we commented before, before installing react-native-maps, the project loaded ok, so we think this is unrelated. On iOS, the maps work ok.

**Comment by Darkiman** [comment]
> You forgot to install the modules correctly, In this case is not the map module but the i18n.
> (Check you imported the packages and then call them in MainAplication.java )

It works fine unitll adding
```
        googlePlayServicesVersion = "11.8.0"
        androidMapsUtilsVersion = "0.5+"
```
and full file looks like:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "11.8.0"
        androidMapsUtilsVersion = "0.5+"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
Maps on ios working fine

**Comment by rborn** [comment]
@Darkiman  try `googlePlayServicesVersion = "16.1.0"` and if it works maybe you can make a PR to update the docs 😊

**Comment by Darkiman** [comment]
> @Darkiman try `googlePlayServicesVersion = "16.1.0"` and if it works maybe you can make a PR to update the docs 😊

Thanks 👍 
Now it works

But I got second error

![image](https://user-images.githubusercontent.com/9611234/56669619-1b54c000-66ba-11e9-82e3-43742ee8157f.png)

Google play Service installed

![image](https://user-images.githubusercontent.com/9611234/56669765-51923f80-66ba-11e9-90a8-3c5a3e8bc736.png)

And emulator has Play Store

![image](https://user-images.githubusercontent.com/9611234/56669819-6a025a00-66ba-11e9-94ca-244ea619f23f.png)

**Comment by rborn** [comment]
@Darkiman https://github.com/react-native-community/react-native-maps/issues/2778

**Comment by Darkiman** [comment]
fixed by [this](https://github.com/react-native-community/react-native-maps/issues/2778#issuecomment-486304526)

**Comment by verochan** [comment]
> @Darkiman try `googlePlayServicesVersion = "16.1.0"` and if it works maybe you can make a PR to update the docs

This worked for our project too :+1: . Then we experienced the same problem with Google Play Services and some one more related with the android ```build.gradle``` tools and sdk versions, which we finally solved, thanks :)
