### ISSUE TITLE
setCamera or animateCamera not working

### ISSUE THREAD

**Issue by kenobi91** [react-native-community/react-native-maps#2825]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yea

### Environment

I just tried to call setCamera or animateCamera, i upgraded map from 0.21 to 0.24.2 and some of methods are deprecated and new one should be used.

### Expected Behavior

Camera view would animate me to desired location provided by Camera object.

### Actual Behavior

I got error saying "Cannot read property 'apply' of undefined" and i already checked to see if my ref to map is ok.
![Simulator Screen Shot - iPhone 6 - 2019-04-22 at 09 22 24](https://user-images.githubusercontent.com/42681932/56488911-3b308c00-64e0-11e9-9379-f850a32b35fc.png)

### Reproducible Demo

Just add this.map.setCamera(camera, duration)
to componentDidMount and error occures.

**Comment by rborn** [comment]
Did you create a ref for the map first (`this.map`) ?
Also you cannot operate on the map until is ready, so the `componentDidMount` is not exactly the right place. Try with `onMapReady`

**Comment by kenobi91** [comment]
Yes i did create, also i had problems with iOS build so i had to revert to 0.21 version. It throws an error regarding some dummy file missing but i haven't copy that error. I will try one more time and then post more of that problem. As for setCamera and animateCamera i did receive map prop so it wans't undefined and i will also try to call it on onMapReady. Thanks :)

**Comment by Isaacs9** [comment]
inside your ref set this way ref = {map => this.mapView = map}
and the other functions or buttons you need to call with this.mapview.

**Comment by rborn** [comment]
Very old issue and old version. Closing.
