### ISSUE TITLE
MapView.getMapBoundaries typescript declaration defines the wrong return type

### ISSUE THREAD

**Issue by mizerlou** [react-native-community/react-native-maps#2827]
### Is this a bug report?

yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.5 => 0.59.5 
      react-native-maps: 0.24.2
      using google maps

### Steps to Reproduce

checkout react-native-maps and look at index.d.ts, specifically `MapView.getMapBoundaries`, it says it returns a `{northEast: LatLng; southWest: LatLng}`.  however, the implementation returns a `Promise<{northEast: LatLng; southWest: LatLng}>`

### Expected Behavior

`MapView.getMapBoundaries` in the .d.ts file should return `Promise<{northEast: LatLng; southWest: LatLng}>`

### Actual Behavior

`MapView.getMapBoundaries`  in the .d.ts currently returns `{northEast: LatLng; southWest: LatLng}`

**Comment by rborn** [comment]
Closing as https://github.com/react-native-community/react-native-maps/pull/2828 is  merged

**Comment by strdr4605** [comment]
@rborn, when a new version of the package with this fix will be released?

**Comment by rborn** [comment]
@strdr4605 well, if somebody helps with the changelog maybe @christopherdro can push a release.
