### ISSUE TITLE
Xcode Build error: library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by realripley00** [react-native-community/react-native-maps#2829]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

 react-native: 0.57.7
    react: 16.6.1
	react-native-maps: 0.24.2

### Steps to Reproduce

yarn add react-native-maps to existing react project, following instructions in readme. react-native run-ios or open xcode ->product->run

### Expected Behavior

App builds successfully

### Actual Behavior

Build Fails with error 
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Screenshot

<img width="532" alt="Screen Shot 2019-04-24 at 1 05 02 AM" src="https://user-images.githubusercontent.com/23426271/56633681-24e41680-662d-11e9-9dde-9444950ec463.png">

**Comment by rborn** [comment]
Did you use the correct Podfile ?  https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#using-cocoapods

**Comment by realripley00** [comment]
I believe so, this is what my podfile looks like:

`# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MY-PROJECT-NAME' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'TwilioVideo', '2.2.2'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  # pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  # pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end`

**Comment by rborn** [comment]
that's weird

did you do the next steps?
```
npm install
cd ios && pod install
cd ../
```

you might also try a `pod repo update && pod update`

**Comment by rmartinezoliva** [comment]
@realripley00 
Maybe you open xcode 
with the XXX.xcodeproj and you must open xcode with the XXX.xcworkspace
![Captura de Pantalla 2019-05-02 a la(s) 3 14 13 p  m](https://user-images.githubusercontent.com/34873868/57104229-6b043e80-6ced-11e9-9f54-57aa98e6dee0.png)

**Comment by ArkaneKhan** [comment]
Same error is happening to me failed to build.

**Comment by indaam** [comment]
If you use ios, you can try m5 cli => https://github.com/indaam/m5-cli#user-content-create-react-native-project-1

**Comment by dorshay6** [comment]
Same thing happening to me while building from xcode but not when building from cli

**Comment by rborn** [comment]
No reply, closing

**Comment by ashwindatye** [comment]
> @realripley00
> Maybe you open xcode
> with the XXX.xcodeproj and you must open xcode with the XXX.xcworkspace
> ![Captura de Pantalla 2019-05-02 a la(s) 3 14 13 p m](https://user-images.githubusercontent.com/34873868/57104229-6b043e80-6ced-11e9-9f54-57aa98e6dee0.png)

This works ! thanks

**Comment by venzersiz** [comment]
Thank you! Really helpful.

**Comment by ashwindmk** [comment]
If nothing works, try regenerating your xcodeproj and xcworkspace for your ios app.

1. `react-native upgrade <version> --legacy true`

2. `cd ios`

`pod deintegrate`

`rm Podfile.lock`

3. Make sure your Podfile has all the dependencies:

`
target 'YourProject' do
  pod 'React', :path => '../node_modules/react-native/', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # other podspecs
end
`

4. `pod install --repo-update --verbose`

5. Now open YourProject.xcworkspace and run the app.

**Comment by Joseph-Ryu** [comment]
I am also getting this, and I am using . xcworkspace

**Comment by Ethaan** [comment]
I did follow all the steps mentioned above, and nothing seems to fix my issue, running `react-native run-ios` work great, but running from xcode it keeps throwing the `Xcode Build error: library not found for -lDoubleConversion`

**Comment by besil** [comment]
> @realripley00
> Maybe you open xcode
> with the XXX.xcodeproj and you must open xcode with the XXX.xcworkspace
> ![Captura de Pantalla 2019-05-02 a la(s) 3 14 13 p m](https://user-images.githubusercontent.com/34873868/57104229-6b043e80-6ced-11e9-9f54-57aa98e6dee0.png)

This worked for me! Thanks!

**Comment by psrrao** [comment]
I manage to solve this issue.

Make sure you make the build after opening workspace in XCode.

e.g. open .xcworkspace not the .xcodeproj

**Comment by ralvesfull** [comment]
> @realripley00
> Maybe you open xcode
> with the XXX.xcodeproj and you must open xcode with the XXX.xcworkspace
> ![Captura de Pantalla 2019-05-02 a la(s) 3 14 13 p m](https://user-images.githubusercontent.com/34873868/57104229-6b043e80-6ced-11e9-9f54-57aa98e6dee0.png)

Tks man....Solved

**Comment by AhmedAbuelenin** [comment]
I opened from .xcworkspace and still have the same problem with xcode 12.1.1, react native 0.63.3
can't find any way to solve it, i tried every thing on the internet with no luck till now.
updated to the last  cocoapods, pod install, rm -rf node_modules, yarn install
any help is appreciated

**Comment by chris-hatton** [comment]
@ashwindmk It's not clear what `<version>` should be here in your suggestion...

> If nothing works, try regenerating your xcodeproj and xcworkspace for your ios app.
> 
> **1.** `react-native upgrade <version> --legacy true`
