### ISSUE TITLE
Latest RN & RNM: build failed - linking references

### ISSUE THREAD

**Issue by greenais** [react-native-community/react-native-maps#2835]
### Is this a bug report?
yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Thoroughly, as usual

### Environment
  "react": "16.8.3",
  "react-native": "0.59.5",
  "react-native-maps": "^0.24.2"
  Target Platform:  Android 7.1.1/Android Studio simulator (latest)
  Windows 8.1

### Steps to Reproduce
1. init fresh RN project
2. strictly follow RNM installation instructions
3. run build

### Expected Behavior
Project builds

### Actual Behavior
(1) With project-wide properties in android/build.gradle:
```
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\greenais\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\9c21aef8bc41b5824547538e8b39a4b1\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\aa_test\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\greenais\.gradle\caches\transforms-1\files-1.1\drawee-1.10.0.aar\f0a9481bfa19727a8a355705ed4afa55\res\values\values.xml:3:5-58:857: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\greenais\.gradle\caches\transforms-1\files-1.1\drawee-1.10.0.aar\f0a9481bfa19727a8a355705ed4afa55\res\values\values.xml:3:5-58:857: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
```

(2) Without project-wide props, but with implementation statemets in android/app/build.gradle:
```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: android.support.v4.accessibilityservice.AccessibilityServiceInfoCompat

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.accessibilityservice.AccessibilityServiceInfoCompat
```

### Reproducible Demo
Please see Steps to Reproduce above

**Comment by greenais** [comment]
UPD:
once I set (in project-wide approach) the most recent SDK and googlePS versions:
```
ext {
    compileSdkVersion   = 28
    targetSdkVersion    = 28
    buildToolsVersion   = "28.0.3"
    supportLibVersion   = "28.0.0"
    googlePlayServicesVersion = "16.1.91"
    androidMapsUtilsVersion = "0.5+"
}
```
project builds but (which is probably expected) I've got blank screen with message:
"aa_test is having trouble with Google Play services. Please try again."

BTW, in worked previous versions (with 26 in ext in project-wide way)
"react-native": "0.57.7",
"react-native-maps": "0.22.1"
RN was always warning at build time that requested 26 taget version will be ignored as RN anyway will use its latest ang greatest

**Comment by rborn** [comment]
@greenais  try to add this in your `android/app/build.gradle` in the `dependencies` sections
```
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:support-v4:${rootProject.ext.supportLibVersion}"
```

**Comment by greenais** [comment]
@rborn, it worked, THANK you!
BTW, 
`implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}" `
was already there
Should docs be updated for non-project-wide approach?
Recommended project-wide still doesn't work, then

**Comment by rborn** [comment]
@greenais I think we should add this to troubleshooting - I found out that this issue is not always showing. So if you would want to add in troubleshooting something like "if you encounter this cases of not found resources ..." and make a PR would be great 🤗

**Comment by greenais** [comment]
Done
[PR #2838](https://github.com/react-native-community/react-native-maps/pull/2838)
