### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by AlexandreMaistret** [react-native-community/react-native-maps#2836]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, I followed everything, everything works fine except onPanDrag().

### Environment

    react-native: 0.59.1
    react: 16.8.3
    react-native-maps: 0.24.2

### Steps to Reproduce

```
onPanDrag = (region) => {
  console.log(region);
}

render() {
  return (
    <MapView
      initialRegion={initialRegion}
      style={{ flex: 1 }}
      onPanDrag={this.onPanDrag}
      showsScale={false}
      showsTraffic={false}
      showsIndoors={false}
      zoomControlEnabled={false}
      rotateEnabled={false}
      pitchEnabled={false}
      toolbarEnabled={false}
    />
  )
};

```

### Expected Behavior

I am expecting that the onPanDrag returns me : `{ coordinate: LatLng, position: Point }` like it is written in the documentation.

### Actual Behavior

The onPanDrag() returns :
![image](https://user-images.githubusercontent.com/14938428/57000028-14461a00-6bb2-11e9-9033-e771b2b4a315.png)

which is not what I am expecting.

**Comment by rborn** [comment]
`onPanDrag` is a `nativeEvent`. In the docs it says you need to access `e.nativeEvent` which will contain the `coordinates` key. https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#events

Closing.
