### ISSUE TITLE
FAILURE: Build failed with an exception. When i try to link React-Native-Maps to my app.

### ISSUE THREAD

**Issue by zainshabir00** [react-native-community/react-native-maps#2837]
Hey there!
My app was working fine before, But when i installed react-native-maps and linked react-native-maps to my app and then i try to run app after linking it, my app is not working, It's not running, It's giving me the error in cmd. And when i un-linked react-native-maps then my app runs fine.
here is the error with screenshot:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\zains\.gradle\caches\transforms-2\files-2.1\9c553c4586932d43142cca15f598f488\jars\classes.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 57s
117 actionable tasks: 117 executed
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
```

Here is the screenshot:
![image](https://user-images.githubusercontent.com/48385304/57006778-df12e980-6bfc-11e9-940f-77b088461b9d.png)

Please sir help me to solve this issue. I want maps to run on my app.

**Comment by rborn** [comment]
@zainshabir00 please update the issue following the template, ping me and I'll reopen it

**Comment by zainshabir00** [comment]
> @zainshabir00 please update the issue following the template, ping me and I'll reopen it

Sir i have updated the issue with the code that i've implemented on my app to link react-native-maps. have a look on it and please re-open my issue and help me to solve it. It's just because of linking react-native-maps to my app.

**Comment by zainshabir00** [comment]
> @zainshabir00 please update the issue following the template, ping me and I'll reopen it

Are you there? Can you re-open my issue now?

**Comment by rborn** [comment]
@zainshabir00 don't post multiple times please, 

And you didn't update the issue following the template.

To understand why is this important - we'll try to implement a bot that will do this automatically and for the issues not following the template it will close it right away.

Also keep in mind we do this in our free time, so if you want to be helped make an effort and follow the requirements.

**Comment by zainshabir00** [comment]
> @zainshabir00 don't post multiple times please,
> 
> And **you didn't update** the issue following the template.
> 
> To understand why is this important - we'll try to implement a bot that will do this automatically and for the issues not following the template it will close it right away.
> 
> Also keep in mind we do this in our free time, so if you want to be helped make an effort and follow the requirements.

What the hell wrong with you men? I've updated the issue with the steps of code i have implemented to link it manually in my app, in same process which is written in your instructions. You don't wanna help.
