### ISSUE TITLE
Custom component for loading indicator

### ISSUE THREAD

**Issue by epicfaace** [react-native-community/react-native-maps#2844]
It would be nice to be able to specify a custom component for the loading indicator (i.e. something that shows up when `loadingEnabled` is `true`). Is this something you might be willing to accept as a PR?

**Comment by rborn** [comment]
@epicfaace any PR is welcome,if you are willing to make one please be sure is cross-platform so we have the same behaviour on both ios and android.
I'll close the issue now and wait for your PR.
❤️
