### ISSUE TITLE
React-Native-Maps: LongitudeDelta and LatitudeDelta calculation ?

### ISSUE THREAD

**Issue by AlexMachin1997** [react-native-community/react-native-maps#2854]
### Is this a bug report?

No, It's a query.

So I've installed the react-native-maps and It was incredibly easy to set up and configure. However, I'm very confused about the latitudeDelta and longitudeDelta. It's required yet it's unclear how I could possibly calculate the deltas.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes and was installed correctly. I'm just experiencing a minor inconvenience. 

### Environment

react: 16.6.3
react-native: 0.58.6
react-native-maps: ^0.24.2,
Target platform: Android

### Steps to Reproduce

N/A as it's a query.

### Expected Behavior

N/A

(Write what you thought would happen.)

### Actual Behavior

N/A

### Reproducible Demo

I don't have a demo with a reproducible as It's not exactly an issue. However, I do have a link to my Github project. The project can be found [here](https://github.com/AlexMachin1997/Shopping-List-Assistant/blob/master/src/Screens/ItemTracking.js).

**Comment by rborn** [comment]
@AlexMachin1997 A little google research would have get you to one of the many articles explaining how this works. 
One is this: https://pusher.com/tutorials/carpooling-react-native-part-2

I'll close the issue as it's suited to StackOverflow. However 👍 for using the issue template.

**Comment by AlexMachin1997** [comment]
What do you think I've been doing for past few daya.no one had a clear answer.

**Comment by rborn** [comment]
@AlexMachin1997 Maybe dig deeper? 🤗

https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#types

> Latitude and longitude are self explanatory while latitudeDelta and longitudeDelta may not. On the developer.apple.com website this is how the "latitudeDelta" property is explained:
> 
>     The amount of north-to-south distance (measured in degrees) to display on the map. Unlike longitudinal distances, which vary based on the latitude, one degree of latitude is always approximately 111 kilometers (69 miles).
> 
> If this is not enough, you can find a visual explanation on stackoverflow.

**Comment by wmonecke** [comment]
@rborn You sound condescending.
