### ISSUE TITLE
Google Map API Service Problem.

### ISSUE THREAD

**Issue by Xumochuan** [react-native-community/react-native-maps#2855]
How are you?
I'd like to use google map in my project.
But I can't see any result.
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yea. I have checked more time installation.md

### Environment
"react": "16.8.3",
"react-native": "0.59.3",
"react-native-maps": "^0.24.2",

### Steps to Reproduce

![err](https://user-images.githubusercontent.com/47884397/57501060-9b189680-7318-11e9-87f6-58f1f953ce16.png)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
Please do not post multiple times.
