### ISSUE TITLE
Android doesn't fill polygon with curls

### ISSUE THREAD

**Issue by Janitor93** [react-native-community/react-native-maps#2859]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.57.5
    react: 16.6.3
    react-native-maps: 0.22.1
    Target Platform: Android

### Steps to Reproduce

I need to use Polygon with fillColor property. It works fine. But on Android exists a case when fillColor doesn't work. When I have polygon with curl on corner. I attach the [screenshot](https://imgur.com/HPY9a5m) to show. But on iOS it fills correctly. If I remove this curl, then on Android fillColor will work.

Example polygon coordinates from screenshot:

> const polygon = [
  {
    latitude: 53.87403686885931,
    longitude: 27.69729779408011,
  },
  {
    latitude: 53.87622973452703,
    longitude: 27.69729779408011,
  },
  {
    latitude: 53.87622973452703,
    longitude: 27.711366048067024,
  },
  // start curl
  {
    latitude: 53.87622973452703,
    longitude: 27.712366048067029,
  },
  {
    latitude: 53.87992973452703,
    longitude: 27.711366048067700,
  },
  // end curl
  {
    latitude: 53.87403686885931,
    longitude: 27.69729779408011,
  },
];

### Expected Behavior

I expected the result like on iOS - [screenshot](https://imgur.com/SpQf6ps)

### Actual Behavior

fillColor doesn't work on Android - [screenshot](https://imgur.com/HPY9a5m)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by oliverdolgener** [comment]
Polygons may not intersect. I thought it would be the same on both platforms.

**Comment by Janitor93** [comment]
Do you mean that iOS works incorrect?

**Comment by oliverdolgener** [comment]
No, but both iOS and Android are based on different Google Maps SDKs so it may be possible that there are some minor differences. A complete rework of the Android SDKs is in beta right now. Maybe it will be possible on Android soon

**Comment by rborn** [comment]
Polygons crossed coordinates/self intersection are considered invalid. https://gis.stackexchange.com/a/43668
Therefore is possible that the sdk is ignoring that.

I'll close this now ❤️
