### ISSUE TITLE
Mapview doesn't  zoom back to initial region after delete all markers

### ISSUE THREAD

**Issue by beamkatana** [react-native-community/react-native-maps#2863]
### Is this a bug report?
No

### Environment
Android & iOS
react: 16.6.0-alpha.8af6728
react-native: 0.57.4
react-native-maps: 0.22.1
react-native-maps-super-cluster: 1.5.0

### Steps to Reproduce

Use Mapview, ClusteredMapView and Marker
Use initialRegion to customize the initial region
Use data to pass the marker list (for test purpose i put 1) 
Use renderMarker method in ClusteredMapView to rendere markers
Drop the item from marker list in order to have the list empty

### Expected Behavior
The map should returns to its default region

### Actual Behavior
The map returns to the center of the entire world map

**Comment by rborn** [comment]
I'm not sure I understand what's the issue

**Comment by beamkatana** [comment]
When I remove all markers from the MapView the region changes but in the wrong coordinates.
I expected the map to return to its initial position.

**Comment by beamkatana** [comment]
> I'm not sure I understand what's the issue
