### ISSUE TITLE
How can I remove WMSTile from MapView

### ISSUE THREAD

**Issue by chienvu123** [react-native-community/react-native-maps#2866]
i am showing WMS on a MapView. 
then
i remove WMSTile component, but WMSTile of MapView still exist.
code
```
{this.state.isShowWMS ? (
              <WMSTile
                urlTemplate={templateUrl}
                zIndex={1}
                opacity={1}
                tileSize={256}
              />
            ) : null}
```
- version:
 + react-native: 0.57.8
 + react-native-maps: 0.24.2

**Comment by andrey-shostik** [comment]
Be sure that your WMSTile is rerendered, try to sen opacity 0
