### ISSUE TITLE
Extend maximumZ beyond default 20 on iOS

### ISSUE THREAD

**Issue by benjamin-halter** [react-native-community/react-native-maps#2871]
### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

react-native: >= 0.51.0
react: >= 16.0.0
react-native-maps: 0.24.0

### Steps to Reproduce

1. Download repository
2. Launch example project for iOS
3. Make sure "Use GoolgeMaps?" is off
4. Go to "Custom tiles"

### Expected Behavior

You can zoom to a level of 23.

### Actual Behavior

You can only zoom to a level of 20. ( As defined https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md by the maxZoomLevel prop.) Issue is my tiles go to a zoom level of 23 and is required that users can zoom in that far. Google maps appears to allow a much greater zoom level than iOS allows - however comes with its own handful of issues. 

### Reproducible Demo

Can be demonstrated by the repository example project.

**Comment by christopherdro** [comment]
@benjamin-halter Looks like the max zoom level is harcoded here. https://github.com/react-native-community/react-native-maps/blob/1c2b8f894f1f1f008ce7628ee54f0afbab21bd85/lib/ios/AirMaps/AIRMap.m#L27 

You could try and change this to see if it works for you then submit a pull request with the changes.

**Comment by gplayman** [comment]
@christopherdro I checked it in my project today. But your solution not working. I changed this const to 30, 10, 15 and iOS build still show too much zoom depth on the map. You can check it with 2gis and OSM custom tiles: 

https://tile1.maps.2gis.com/tiles?x={x}&y={y}&z={z}&v=1&ts=online_sd
http://c.tile.openstreetmap.org/{z}/{x}/{y}.png 

Help me, please.
