### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by bara495** [react-native-community/react-native-maps#2875]
# Question
Most frequent template/example for working with location and locateMeButton is referenced here - https://github.com/react-native-community/react-native-maps/issues/209#issuecomment-350907665 - and I have tried and it works... 
BUT, I can't get my head around the navigator variable and how is it supplied to this component since it is not a prop and it is not declared anywhere and I want to understand the code fully and how/why does it work.

Please help,
Kind regards!

**Comment by christopherdro** [comment]
This question is better suited for stack overlow but you should find our answer on the react native docs for geolocation. https://facebook.github.io/react-native/docs/geolocation

> As a browser polyfill, this API is available through the navigator.geolocation global - you do not need to import it.
