### ISSUE TITLE
'Google-Maps-iOS-Utils/GMUKMLParser.h' file not found while building XCode

### ISSUE THREAD

**Issue by jacquesdev** [react-native-community/react-native-maps#2876]
# Bug

I initially had react-native 0.58.6 installed alongside react-native-maps 0.23.0, and everything was perfect, maps working etc.

I then tried upgrading to react-native 0.59.8, and as part of that for Android, I had to update the react-native-maps plugin to 0.24.2, which then worked fine. I then tried to build Xcode, and ran into the issue below.

<img width="873" alt="Screenshot 2019-05-21 at 22 19 18" src="https://user-images.githubusercontent.com/7842197/58131419-8ee4e100-7c16-11e9-803a-125aa959c293.png">

I tried a couple of solutions, but nothing I have tried so far worked. The strange thing is that even when I rollback to the previous version of the plugin and react-native, I am now totally unable to build my Xcode project, without getting this error. I have even gone so far as to delete Xcode, and my projects to delete out any temporary files that may have caused these issues, but for whatever reason, I simply cannot build.

The files that are apparently missing are definitely there.

<img width="272" alt="Screenshot 2019-05-21 at 22 26 41" src="https://user-images.githubusercontent.com/7842197/58131835-90fb6f80-7c17-11e9-9c52-4d79eebe5428.png">

That specific package does seem to be missing from the linked headers, but even if I do add it in there, it doesn't seem to fix the error (even after I cleaned the project first)

<img width="799" alt="Screenshot 2019-05-21 at 22 28 50" src="https://user-images.githubusercontent.com/7842197/58131951-f0597f80-7c17-11e9-9ed0-ad00abf9f542.png">

My podfile is below:

```
platform :ios, '9.0'

target 'Olio' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.0'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'
  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
            target.remove_from_project
        end
    end
end
```

## Environment info

React native info output:

```bash
 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 4.34 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-24 | Intel x86 Atom_64, android-25 | Android TV Intel x86 Atom, android-25 | Intel x86 Atom_64, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: 0.24.2

## Steps To Reproduce

Since I have exhausted all other avenues, I thought I'll log a bug report, I am surprised no-one else has run into something similar recently, and I can't figure out what I am doing wrong.

It seems at least two other people are also experiencing the same issue:
https://github.com/react-native-community/react-native-maps/issues/2066#issuecomment-493246746

https://github.com/react-native-community/react-native-maps/issues/2066#issuecomment-494229202

Any advice gladly welcomed!

**Comment by rborn** [comment]
@jacquesdev did you follow the  `Enabling Google Maps on iOS` step https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios ? 

Read it carefully as might need recursive search path

**Comment by rborn** [comment]
@jacquesdev also take a look at this, there is an example repo that works: https://github.com/react-native-community/react-native-maps/issues/2867#issuecomment-494318370

**Comment by joohimks** [comment]
@jacquesdev I am experiencing this issue as well.

**Comment by jacquesdev** [comment]
Thanks @rborn, I did follow the steps as mentioned, however it didn’t seem to make a difference.

And I wonder why it worked before without any of these steps?

Can you confirm I did the right thing in the postinstall. The first part is something like this.

‘.../enable-google-maps’ 

Can you confirm that is what the plugin needs (and it’s not just an example)

Regarding the second part of path that needs replacing, the example mentioned ‘ios/frameworks/GoogleMaps’.

The example suggests that you add all the frameworks directly under the project which means they exist under ios/, so I added the second part as ‘ios/**’.

Will check the example project in the meantime, thanks for your help so far, much appreciated, looking forward to getting to the bottom of this.

Just as an aside - the error seems to be related to not being able to find GoogleMapsiOSUtilities (which is in the pods). Can you confirm what the postinstall step does (since it seems all the required files are already in the Pods?), and how that will enable the AirGoogleMaps to find the correct files. It’s been driving me crazy and just wondering about why it’s happening.

**Comment by jacquesdev** [comment]
@joohimks, was it working previously for you or is this on a new installation of the plugin?

**Comment by joohimks** [comment]
Same identical scenario as yours letter by letter and version to version!

**Comment by jacquesdev** [comment]
Haha great to hear I’m not the only one, will let you know if I manage to make any progress.

**Comment by joohimks** [comment]
That would be appreciated!

**Comment by rborn** [comment]
@jacquesdev the docs say `ios/frameworks/GoogleMaps` so I'd add `ios/frameworks/GoogleMaps/**` not `ios/**` as you'll make recursive the whole ios folder.

I installed the google maps sdk in a separate folder so I don't have it in the project (to be used by more than one project, stage less code in git,etc)

As for why it worked and it doesn't anymore, I cannot say. Some say computers are an exact science but I really start to think that not like this 🤣

Anyway, you could try to do the next:

git new branch and /or backup 🤣
delete `node_modules`,`package-lock.json`, `ios/Pods`, `ios/Podfile.lock` (yes folders and files)
run `npm install`, `react-native link react-native-maps` (this should say you're already linked), `cd ios && pod install`
run `cd .. && react-native run-ios`

All this keeping the podfile you already have.


Hope it helps

**Comment by mwcm** [comment]
experiencing the same issue, different combinations of deleting/cleaning/reinstalling pods & npm packages have no effect

**Comment by stevenheffner** [comment]
It was working initially. I went to a branch without react-native-maps installed, then when I came back this error appeared. I have tried @rborn's suggestion with no luck.

**Comment by joohimks** [comment]
@jacquesdev @mwcm @stevenheffner Here how I fixed it through a this [comment.](https://github.com/tolu360/react-native-google-places/issues/227#issuecomment-494733969)

Only difference is I have downgraded react-native-maps to:
`"react-native-maps": "^0.19.0",`

And it worked perfectly.

**Comment by stevenheffner** [comment]
@joohimks It worked for me too, however that version is over a year old 🤣

**Comment by joohimks** [comment]
@stevenheffner Whatever man, at least it gives a room to breathe and deliver :D

**Comment by stevenheffner** [comment]
> @stevenheffner Whatever man, at least it gives a room to breathe and deliver :D

True, but in looking to see how old that version is, I saw a slew of fixes and stuff that can now go wrong in my app 🤣

**Comment by mwcm** [comment]
@joohimks works for me too! can finally get back to work, thank you 🙂

**Comment by superdhuang** [comment]
I just downgrade my cocoapod from 1.7.0 to 1.6.1, then it works fine for me now.

**Comment by farrrr** [comment]
it's cocoapods 1.7.0 Header path issue. #8836
when you change Google-Maps-iOS-Utils to Google_Maps_iOS_Utils, and all works.

```c
#import <Google_Maps_iOS_Utils/GMUKMLParser.h>
#import <Google_Maps_iOS_Utils/GMUPlacemark.h>
#import <Google_Maps_iOS_Utils/GMUPoint.h>
#import <Google_Maps_iOS_Utils/GMUGeometryRenderer.h>
```

**Comment by jacquesdev** [comment]
@superdhuang and @farrrr, thank you so much, you are geniuses. I have been agonising over this for three days now, and it's the exact thing, and explains why it was happening 'randomly'.

I recently updated from `cocoapods-1.7.0.beta.3` to `cocoapods-1.7.0.rc.2`, which caused this issue.

I'm sure that is what most other people on here did as well.

![carlton](https://user-images.githubusercontent.com/7842197/58231198-4c162c80-7d2e-11e9-9a3e-c48e281d71e8.gif)

**Comment by mwcm** [comment]
that was it for me too, had installed 1.7.0.rc.2

**Comment by stevenheffner** [comment]
> it's cocoapods 1.7.0 Header path issue.
> [CocoaPods/CocoaPods#8836](https://github.com/CocoaPods/CocoaPods/issues/8836)
> when you change Google-Maps-iOS-Utils to Google_Maps_iOS_Utils, and all works.
> 
> ```c
> #import <Google_Maps_iOS_Utils/GMUKMLParser.h>
> #import <Google_Maps_iOS_Utils/GMUPlacemark.h>
> #import <Google_Maps_iOS_Utils/GMUPoint.h>
> #import <Google_Maps_iOS_Utils/GMUGeometryRenderer.h>
> ```

This fixed the issue locally, so thanks! Im wondering how this will now work with a team. Do I now have to tell them to each do the same thing?

**Comment by jacquesdev** [comment]
At the bottom of the Podfile.lock the cocoapods version is defined. Make sure it’s not rc2

**Comment by farrrr** [comment]
> > it's cocoapods 1.7.0 Header path issue.
> > [CocoaPods/CocoaPods#8836](https://github.com/CocoaPods/CocoaPods/issues/8836)
> > when you change Google-Maps-iOS-Utils to Google_Maps_iOS_Utils, and all works.
> > ```c
> > #import <Google_Maps_iOS_Utils/GMUKMLParser.h>
> > #import <Google_Maps_iOS_Utils/GMUPlacemark.h>
> > #import <Google_Maps_iOS_Utils/GMUPoint.h>
> > #import <Google_Maps_iOS_Utils/GMUGeometryRenderer.h>
> > ```
> 
> This fixed the issue locally, so thanks! Im wondering how this will now work with a team. Do I now have to tell them to each do the same thing? Will this be something that is fixed soon?

Cocoapods team fixed and merged. wait for cocoapods new release.

**Comment by mdere-unbound** [comment]
@farrrr - based on that issue - does that mean when they release 1.7.1 do we just do another pod install and it should fix it?

**Comment by farrrr** [comment]
@mdere-unbound yep.

**Comment by pianoman730** [comment]
@farrrr How could we find out when that happens?

**Comment by kanso-michael** [comment]
Just a note for anyone using App Center, as a workaround you can add a `appcenter-post-clone.sh` file at the root of your project with the following contents to ensure that your remote build uses a working version of `cocoapods`.

```
#!/usr/bin/env bash
#
# Removes the latest version of CocoaPods  which may have lack of backward compatibilities
# Installs version 1.5.3 which has no compatibility issues
# 1.5.3 can be changed to another version you'd prefer

echo "running post-clone scripts"
echo "uninstalling all cocoapods versions"
sudo gem uninstall cocoapods -ax
echo "installing cocoapods version 1.5.3"
sudo gem install cocoapods -v 1.5.3
```

Hopefully this is of use to someone!

**Comment by mdere-unbound** [comment]
1.7.1 released but it doesn't seem like it fixed it? Can someone confirm?

**Comment by rborn** [comment]
@mdere-unbound just to be sure, did you do all the stuff here? https://github.com/react-native-community/react-native-maps/issues/2876#issuecomment-494736735

**Comment by NeerajNema1988** [comment]
@kanso-michael - Thank you. It works like a charm.

**Comment by NoumanSakhawat** [comment]
> it's cocoapods 1.7.0 Header path issue.
> [CocoaPods/CocoaPods#8836](https://github.com/CocoaPods/CocoaPods/issues/8836)
> when you change Google-Maps-iOS-Utils to Google_Maps_iOS_Utils, and all works.
> 
> ```c
> #import <Google_Maps_iOS_Utils/GMUKMLParser.h>
> #import <Google_Maps_iOS_Utils/GMUPlacemark.h>
> #import <Google_Maps_iOS_Utils/GMUPoint.h>
> #import <Google_Maps_iOS_Utils/GMUGeometryRenderer.h>
> ```

Thanks you it work

**Comment by ebwinters** [comment]
For me what worked was replacing the problematic import to a relative path. Example:
```Objective-C
#import <Google_Maps_iOS_Utils/GMUKMLParser.h>
#import "GMUKMLParser.h"
```
