### ISSUE TITLE
Memory Leak. 2,000 Observers

### ISSUE THREAD

**Issue by mikeKane** [react-native-community/react-native-maps#2882]
# Bug

I have a function on iOS and android that. pulls information every seconds adds location and sends it to react native. 

React Native maps will get updated once per second to display a new coordinate. 

After 10 seconds the programs stops responding. After looking through instruments via Xcode I see 

```  
 4 Foundation -[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:]
``` 

Called 2,079 times in 35 seconds. 

The stack trace shows
 ```   
0 libsystem_malloc.dylib calloc
   1 libobjc.A.dylib class_createInstance
   2 libobjc.A.dylib +[NSObject allocWithZone:]
   3 Foundation _NSKeyValueObservationInfoCreateByAdding
   4 Foundation -[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:]
   5 Foundation -[NSObject(NSKeyValueObserverRegistration) addObserver:forKeyPath:options:context:]
   6 PingifyV2 -[AIRMapMarker initWithFrame:] /Users/_kane7161/Xcode/Connectify/pingifyV2/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapMarker.m:34
   7 PingifyV2 -[AIRMapMarkerManager view] /Users/_kane7161/Xcode/Connectify/pingifyV2/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapMarkerManager.m:27
   8 PingifyV2 -[RCTComponentData createViewWithTag:] /Users/_kane7161/Xcode/Connectify/pingifyV2/node_modules/react-native/React/Views/RCTComponentData.m:71
   9 PingifyV2 __50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke /Users/_kane7161/Xcode/Connectify/pingifyV2/node_modules/react-native/React/Modules/RCTUIManager.m:951
  10 PingifyV2 __RCTExecuteOnMainQueue_block_invoke /Users/_kane7161/Xcode/Connectify/pingifyV2/node_modules/react-native/React/Base/RCTUtils.m:247
  11 libdispatch.dylib 0x102f476ef
  12 libdispatch.dylib 0x102f48c73
  13 libdispatch.dylib 0x102f566fb
  14 CoreFoundation __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  15 CoreFoundation __CFRunLoopRun
  16 CoreFoundation CFRunLoopRunSpecific
  17 GraphicsServices GSEventRunModal
  18 UIKitCore UIApplicationMain
```

Is React Native creating and storing a new instance for every update?

The Map is the home screen on a stack navigator. So its front and center of the app.

## Environment info

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 96.53 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```

**Comment by rborn** [comment]
Can you give more details and what exactly happens when you get the reply from the web service?
Are you adding new markers, are you re-rendering the map, etc?

Also do you really need a once per second refresh? (just asking)

**Comment by mikeKane** [comment]
Thanks for replying. 

I am doing a ping test. So the map updates with each ping so a user can see information. I have the UI retrieving data once per second instead of when each ping receives a reply. 

I have modified it to only update every 5 seconds. 1 second was way to much I just never expected to see the memory climb up to 300MBs in a matter of seconds and get killed.

I am adding new markers every 5 seconds, I would expect the markers with the same keys not to get redrawn every time but that seems to happen. 

I would like to not re-render the map and just add more markers as information comes in. 

Is this possible?

**Comment by rborn** [comment]
How many markers do you have? Also are they custom markers?

**Comment by mikeKane** [comment]
It gets bogged down around the 10th Marker. 

Here is the actual Marker code 

```
marker(marker, index) {
    var title = "Network: " + marker.ping.network.name;
    var description =
      "Adapter: " + marker.ping.adapter + " RTT: " + marker.ping.rtt + "ms";
    return (
      <MapView.Marker
        coordinate={{
          latitude: marker.location.latitude,
          longitude: marker.location.longitude
        }}
        key={marker.ping.network.name + marker.id}
        pinColor={marker.color}
        title={title}
        description={description}
      />
    );
  }
```

Here is my map code 

```
 <MapView
          // provider={PROVIDER_GOOGLE}
          initialRegion={this.props.coordinate}
          style={styles.map}
          key="mapView"
          showsUserLocation={markers.length > 0 ? false : true}
          followsUserLocation={true}
          ref={ref => (this.map = ref)}
        >
          {screenProps.pings[0] != null &&
            screenProps.pings.map((marker, index) =>
              this.getMarkers(index, marker).map((pingMarker, pingIndex) =>
                this.marker(pingMarker, pingIndex)
              )
            )}
        </MapView>
```

**Comment by rborn** [comment]
`this.getMarkers` is the network call ?

**Comment by mikeKane** [comment]
No by the time it hits the map view the JSON object is already populated. The network calls are all done via iOS/android specific. Each platform then sends the data down to React Native. 

Get Markers filters data 

```
 getMarkers(index, marker) {
    var isLessThan = this.state.filterOption == "is Less Than" ? true : false;
    var speed = parseInt(this.state.speedOption, 10);

    if (isNaN(speed)) {
      console.log("Marker speed is NaN");
      return markers;
    }

    var operators = {
      ">": function(a, b) {
        return a > b;
      },
      "<": function(a, b) {
        return a < b;
      }
    };
```

**Comment by rborn** [comment]
not sure why is doing this 😔

**Comment by mikeKane** [comment]
It's very strange. What happens when a map is re rendered? Does that memory get re allocated?

Also when does it add these observers? Is there a way to flush the memory is use or check if there's really 10 instances of the map still alive?

**Comment by rborn** [comment]
There shouldn't be 10 instances of the map, unless you generate the map somehow in a function on every ping.

My approach in your case would be the next (please bear in mind I don't know anything about your project or how you do things so I might be totally off  🤣 )

- build the map
- initialize an empty state for markers
- use this state to render the markers (`this.state.markers.map....)`
- every ping that receives new markers modifies the state pushing/updating the new markers

makes any sense?

**Comment by mikeKane** [comment]
Yes, that makes sense. I do render them from props. 

I will try assigning them to the state and see if there's a difference.

thank you for your suggestions

**Comment by Manhazito** [comment]
@mikeKane, I'm having a similar problem, did you manage to fix this? Can you show how you add the markers to the map?

**Comment by mikeKane** [comment]
I have managed to stop this behavior. I was passing screen props into the render function and assigning state through a filter function. 

After I filter the props when the component mounts and listening to component will update that got rid of those leaks and it is fast now. 

```
<MapView
          // provider={PROVIDER_GOOGLE}
          initialRegion={newRegion}
          style={styles.map}
          key="mapView"
          showsUserLocation={markers.length > 0 ? false : true}
          followsUserLocation={true}
          ref={ref => (this.map = ref)}
        >
          {markers.map((pingMarker, pingIndex) =>
            this.marker(pingMarker, pingIndex)
          )}
        </MapView>
```
