### ISSUE TITLE
show user location is not working

### ISSUE THREAD

**Issue by craigcosmo** [react-native-community/react-native-maps#2883]
```js
<MapView 
						provider={MapView.PROVIDER_GOOGLE}
						initialRegion={this.state.init} 
						showCompass={true} 
						rotateEnabled={false}
						showUserLocation={true}
						showsMyLocationButton={true}
						style={css.map}>
```

There is no blue dot on the map. am I missing something?

Also when I click the show location button, nothing seem to happen.

<img width="371" alt="Screen Shot 2019-05-25 at 12 03 27 AM" src="https://user-images.githubusercontent.com/538657/58344725-afb06f00-7e80-11e9-88d8-e38abe0f71a0.png">

**Comment by mikeKane** [comment]
Do you have location permission granted on the Device?

**Comment by craigcosmo** [comment]
it's xcode code iphone x simmulator. 

I think I did click allow the location prompt when first open the map.

How can I check that I actually did?

**Comment by craigcosmo** [comment]
does this mean location permission granted for expo apps?

<img width="167" alt="Screen Shot 2019-05-25 at 12 18 05 AM" src="https://user-images.githubusercontent.com/538657/58345492-b213c880-7e82-11e9-88af-55f17d9c328a.png">

**Comment by craigcosmo** [comment]
this is more like bug. reported

**Comment by gigeos** [comment]
You wrote `showUserLocation` insteadOf `showsUserLocation`
