### ISSUE TITLE
show user location is not working

### ISSUE THREAD

**Issue by craigcosmo** [react-native-community/react-native-maps#2884]
# Bug

userlocation is not showing

<img width="167" alt="Screen Shot 2019-05-25 at 8 42 56 AM" src="https://user-images.githubusercontent.com/538657/58363127-a8fa1a00-7ec9-11e9-8677-be422855aca9.png">

## Environment info

 React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
      Memory: 33.86 MB / 24.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
React native info output:

Library version: latest

## Steps To Reproduce

init a new project with expo
import the mapview component
set prop userlocation true

Describe what you expected to happen:

there should be a blue dot showing user current location

## Reproducible sample code

bug demo repo

https://github.com/craigcosmo/AwesomeProject.git

**Comment by rborn** [comment]
@craigcosmo 

Did you set the location of the simulator in your area? (in the Debug menu) 
Usually is set to Apple headquarters in US

You could zoom out the full map and see if you find it.

**Comment by craigcosmo** [comment]
yes I did set the location of the simulator in my area. Also zoomed out max, no blue spot

**Comment by craigcosmo** [comment]
I just tried set set location to none. now I got blue spot

<img width="167" alt="Screen Shot 2019-05-25 at 6 42 39 PM" src="https://user-images.githubusercontent.com/538657/58368866-f8b60100-7f1c-11e9-96b2-8c4219b9f55c.png">

**Comment by rborn** [comment]
So you set it to `none` then back to your location? or ?
Anyway, good to know it's solved 🎉

**Comment by craigcosmo** [comment]
It set it to `none` then the map shows the blue spot. Before that, the map doesnt show the blue spot
