### ISSUE TITLE
How to center two markers

### ISSUE THREAD

**Issue by craigcosmo** [react-native-community/react-native-maps#2885]
# Question 

I got two markers at two different coordinates.

How do people normally center two marker so that you can see two marker at the same time on map, regardless how far away they are.

**Comment by craigcosmo** [comment]
the question doesn't have template. it only said to check if there is the same question stackoverflow.

**Comment by rborn** [comment]
@craigcosmo I edited your issue and reopened it.
It seems you deleted the whole template so the title was gone.

We'll work in improving that and so to be harder to miss that header 🤗

**Comment by craigcosmo** [comment]
found the solution.

```js
this.map.fitToSuppliedMarkers(['mk1','mk2'],{ edgePadding: 
			{top: 50,
			  right: 50,
			  bottom: 50,
			  left: 50}

		})
```

`mk1` is the id of marker 1, `mk2` is the id of marker 2

To set id for marker just do like this
```js
<MapView.Marker 
								coordinate={{
									'latitude':this.state.marker1.lat,
									'longitude':this.state.marker1.lng}}
								title={'Pick up here'}
								identifier={'mk1'}
```
