### ISSUE TITLE
Can't build on iOS, if downgrade to 0.19.0 to work - android fails to build

### ISSUE THREAD

**Issue by dorin-popa** [react-native-community/react-native-maps#2890]
**My versions:** 

react-native: 0.59.5
react: 16.8.3
react-native-maps: 0.24.2

**What I've done**:
It worked perfect on android, then I start build iOS it didn't worked.
Started to figure out found that there is an issue with newest react-native version and react-native-maps 0.24.

I found that the only solution temporary is to downgrade to 0.19.0, but that doesn't work on android with the same react-native version!

Started to find out is there any way to have platform specific package version and didn't find any solutions :(

Please help to figure out what should I do and if there will be the next version which will fix the iOS build failure.

PS. I even tried to start projects from scratch with the specified version and the same issues arrived (even with react-native: 0.59.8)

Here is the issue with iOS with **react-native-maps**: 0.24.2
![Screen Shot 2019-05-28 at 11 58 35 AM](https://user-images.githubusercontent.com/51086211/58547311-cdc6f800-820f-11e9-8660-27801bd674c6.png)

Here is the issue with android with **react-native-maps**: 0.19.0
<img width="726" alt="Screen Shot 2019-05-29 at 12 42 57 PM" src="https://user-images.githubusercontent.com/51086211/58547250-b7b93780-820f-11e9-9ccd-99c38af08563.png">

**Comment by rborn** [comment]
@dorin-popa what's your cocoapods version `pod --version` ?

**Comment by jacquesdev** [comment]
Yup @dorin-popa - see this issue https://github.com/react-native-community/react-native-maps/issues/2876

**Comment by dorin-popa** [comment]
> @dorin-popa what's your cocoapods version `pod --version` ?

pod version is **1.7.0**

**Comment by dorin-popa** [comment]
> Yup @dorin-popa - see this issue #2876

Yes I investigated that issue but I didn't get what is the future plans regarding the library, is there any chance to use it with both platform with react-native: 0.59 ? )

**Comment by rborn** [comment]
@dorin-popa try 1.7.1 or downgrade to 1.5.3

**Comment by dorin-popa** [comment]
> @dorin-popa try 1.7.1 or downgrade to 1.5.3

Downgrade to 1.5.3 doesn't fix the issue, but 1.7.1 is not released yet, even in prerelease.

<img width="1170" alt="Screen Shot 2019-05-29 at 3 37 56 PM" src="https://user-images.githubusercontent.com/51086211/58557789-ed6a1a80-8227-11e9-80ea-5a17dbc15844.png">

I've fixed the iOS issue as I found thanks to @jacquesdev  by substituting the "-" with "_", but that means if I don't commit the Pods and try to do the build somehow remote on **Appcenter** it will not be able to do that.

**Comment by rborn** [comment]
@dorin-popa I have 1.5.3 and it works well, I think you might need clean your `Pods` folder, `podfile.lock` then run `pod repo update`, `pod install`

**Comment by dorin-popa** [comment]
> @dorin-popa I have 1.5.3 and it works well, I think you might need clean your `Pods` folder, `podfile.lock` then run `pod repo update`, `pod install`

Ok, thanks)
