### ISSUE TITLE
random position of text overlay-ed on react-native-maps

### ISSUE THREAD

**Issue by neodinger** [react-native-community/react-native-maps#2898]
# Question

I am new to react-native-maps.  I just created a very simple code which overlays a text wrapped in a view on react-native-maps. When reload the simulator, sometimes, the text position is correct, sometime the text shows at the top left of simulator screen.  Anyone encountered this issue?  Please help. Thanks. 

The code snippet:
`
  render() {

    return ( 
      <View style={{flex: 1,  justifyContent: 'center', alignItems: 'center', backgroundColor: '#F5FCFF'}}>     
       <MapView
            style={{...StyleSheet.absoluteFillObject}}
            initialRegion={{
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}
        >
            <View style={{position:'absolute', backgroundColor: 'red', top: 50, width: 200}}>
                <Text>This text to display</Text>
            </View>
          </MapView>
      </View>
    );
  }
`
correct text position:
![image](https://user-images.githubusercontent.com/26895939/58960607-1cf5c580-87da-11e9-8d29-31be7db660ed.png)

wrong text position: (happened sometimes when reload (press command+R)
![image](https://user-images.githubusercontent.com/26895939/58961076-04d27600-87db-11e9-9db7-06725e836287.png)

Please help. 

My react-native info:
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
      Memory: 17.85 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library:  react-native-maps@0.24.2

**Comment by rborn** [comment]
You cannot embed a `View` inside the `MapView`. 
If you want it to be on top of the map no matter how you interract with the map (zoom, pan, etc) you add it outside
~~~
<MapView.../>
<View.../>
~~~

If you want the view to be "locked" to a coordinate and move with the map then have a look in the examples at custom overlay
