### ISSUE TITLE
Map stopped working in Android

### ISSUE THREAD

**Issue by KirankumarDafda** [react-native-community/react-native-maps#2900]
I am working on this plugin from last one year and everything was just fine with android and iOS but suddenly map showing only grey blank screen with google logo only, yet it working fine in iOS

**package.json**

> "react": "16.0.0-alpha.12",
> "react-native": "^0.50.3",
> "react-native-fused-location": "^0.3.1",
> "react-native-geocoder": "^0.5.0",
> "react-native-google-places-autocomplete": "^1.3.6",
> "react-native-image-picker": "^0.26.10",
> "react-native-map-clustering": "^1.3.0",
> "react-native-maps": "^0.21.0",
> "react-native-maps-directions": "^1.6.0",

**androidmanifest.xml**

`<meta-data 
	android:name="com.google.android.geo.API_KEY" 
	android:value="Key-Goes-Here" />`

Even tried with new project and only react-native-maps but not working

**Comment by john20xdoe** [comment]
@KirankumarDafda were able to resolve this?
We're encountering the same issue for react-native-maps as we upgrade to Expo SDK v33.

**Comment by yagnesh-y** [comment]
Run your app and check for the logs. 
`adb logcat | grep 'Google Maps Android API'`.

For my case the logs stated:

> Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map. 
....Ensure that the following Android Key exists:

This means that i was using the wrong SHA1 to generate the api key, i've used SHA1 from `~/.android/debug.keystore` whereas gradle is reading it from `/root/.android/debug.keystore`.

So adding that SHA1 from `/root` instead solved my issue.

**Comment by israelouteiro** [comment]
@yagnesh-y thank you very much. I ran your command on my app downloaded from the Play Store and found that...

it's incredible. but when we send the app to Play Store the signature received by your certificate changes the fingerprint of the app, so we have 3 fingerprints for a single app, when in development, when in production but distributed outside the Play Store and a third when in Production and distributed in the Play Store.

so adding `My:App:Play:Store:Finger:Print` to Google Apis Console, All the maps are shown without any problems, now works!! Thanks alot
