### ISSUE TITLE
I upgraded react-native from 0.57.2 to 0.59.3 now its giving me error  Cannot find module 'metro-react-native-babel-preset'

### ISSUE THREAD

**Issue by mzeeshansikander** [react-native-community/react-native-maps#2907]
# Question

I just upgraded my react native from 0.57.2 to 0.59.3 using rn diff purge and updated all the required changes manually. Successfully built the project in android studio but when i run my project its giving me this error

![Capture](https://user-images.githubusercontent.com/16585991/59335725-93cd1a00-8d16-11e9-95fa-4298d6ec8c93.JPG)

Below is my devDependencies (package.json)

"devDependencies": {

    "babel-plugin-module-resolver": "3.1.1",
    "@babel/core": "^7.4.3",
    "@babel/runtime": "^7.4.3",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3",
    "schedule": "0.4.0"
  },

I have created babel.config.js as per rndiff purge documentation
module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
  };

**Comment by rborn** [comment]
did you run `npm install` ?

**Comment by mzeeshansikander** [comment]
no, npm install will update all my libraries which i dont want.

**Comment by rborn** [comment]
npm install will install the versions you have set in `package.json` as long as they are  "fixed" `"package":"1.0.1"` (no `^` or any other variation)

**Comment by christopherdro** [comment]
How is this issue specific to this library?

This issue seems related to react native and metro bundler. Please see existing issues below.
https://github.com/facebook/metro/issues/242
https://github.com/facebook/react-native/issues/21241

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-community/react-native-maps/issues/2907#issuecomment-501466942

**Comment by mzeeshansikander** [comment]
> npm install will install the versions you have set in `package.json` as long as they are "fixed" `"package":"1.0.1"` (no `^` or any other variation)

i have separately installed the updated packages. Issue is fixed now. Thankyou
