### ISSUE TITLE
Version bump for GoogleMaps dependency podspec

### ISSUE THREAD

**Issue by dblommesteijn** [react-native-community/react-native-maps#2909]
# Bug

I'm trying to install GoogleMaps via pod's for iOS, and I noticed your `v0.24.4` tagged release does not include the version bump for the dependency to `3.1.0`. As I am using yarn for dependency management, this will not work for me.

Can you please tag a new release version and release it to `npm` and `yarn`?

As a **workaround** I'm running the `react-native-maps` dependency straight of the `master` branch, which I do not like. 

I'm doing this in my `package.json`, which will use the master branch's HEAD.

```json
"react-native-maps": "https://github.com/react-native-community/react-native-maps.git"
```

I came across the fix here: https://github.com/react-native-community/react-native-maps/blame/99492e92abeb1e2e14450491396e37b07ef678ab/react-native-google-maps.podspec#L20 therefore I think the solution is quite simple.

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 98.80 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.3 => 0.59.3
```

Library version: `v0.24.4`.

## Steps To Reproduce

* Add dependency to yarn `yarn add react-native-maps`
* `cat ./node_modules/react-native-maps/cat react-native-google-maps.podspec`
  * it yields: `s.dependency 'GoogleMaps', '2.5.0'`

Related tickets: #2748

**Comment by rborn** [comment]
try to use the master version, I think this issue is fixed, is just pending to be released

**Comment by dblommesteijn** [comment]
> try to use the master version, I think this issue is fixed, is just pending to be released

Yes exactly, but i have to run master, which for a production app I do not want todo..

**Comment by rborn** [comment]
A quick-fix for you would be fork the released version and cherry pick the commit with your fix and use that till we publish.

I'll close the issue now as it's not a real bug, but not published.🤗

**Comment by dblommesteijn** [comment]
Fine, but know that you're forcing everyone to use your master branch instead of making a release.

**Comment by rborn** [comment]
@dblommesteijn how about "how can I help" instead of "demanding" to make a release?
We (the maintainers) give you our work and free time so you can use the module in your projects, however we don't owe you anything.

**Comment by dblommesteijn** [comment]
> @dblommesteijn how about "how can I help" instead of "demanding" to make a release?
> We (the maintainers) give you our work and free time so you can use the module in your projects, however we don't owe you anything.

Well sorry for that, I did no see there was a tag made, so I used that one instead.

PS. I am a maintainer myself, and personally I always tag/ release thinks when a breaking change happens. I know you are doing your best, so we'll just have to wait.
