### ISSUE TITLE
React Native version mismatch After upgrading to react native 0.59.3

### ISSUE THREAD

**Issue by mzeeshansikander** [react-native-community/react-native-maps#2912]
# Question

I just upgraded my react native from 0.57.2 to 0.59.3 using rn diff purge and updated all the required changes manually. Successfully built the project in android studio but when i run my project its giving me this error
![Screenshot_1560429050](https://user-images.githubusercontent.com/16585991/59432610-2d70f600-8e01-11e9-961c-f3a9f7fb5678.png)

**Comment by rborn** [comment]
This is not a react-native-maps issue. Closing.

You need to restart the metro-bundler and build the app again.

**Comment by mzeeshansikander** [comment]
> This is not a react-native-maps issue. Closing.
> 
> You need to restart the metro-bundler and build the app again.

my bad, I didn't see i am standing in react native maps.
let me repost this issue again.

**Comment by rborn** [comment]
@mzeeshansikander try first what I said before reposting, if it works you save some maintainer time ;)
