### ISSUE TITLE
react-native run-android error

### ISSUE THREAD

**Issue by p919533** [react-native-community/react-native-maps#2913]
# Question
![image](https://user-images.githubusercontent.com/26241954/59482276-cc95fc00-8e9a-11e9-960f-34284317087c.png)

**Comment by p919533** [comment]
![image](https://user-images.githubusercontent.com/26241954/59482343-0f57d400-8e9b-11e9-805f-678988e3753b.png)

**Comment by rborn** [comment]
This is not the repo for baidu-map, you might wanna open this issue there: https://github.com/lovebing/react-native-baidu-map

Closing
