### ISSUE TITLE
What is the example with the red background blocks in the README.md?

### ISSUE THREAD

**Issue by mfgabriel92** [react-native-community/react-native-maps#2916]
Where can I find examples of usage of the example shown in the README.md where it shows a few of red blocks being swiped and the map changing location?

https://camo.githubusercontent.com/9b5fcde0cb8146672f54d39fc3c34bd2e1f7891f/687474703a2f2f692e67697068792e636f6d2f336f365542644751644d31476d566f4964712e676966

**Comment by mfgabriel92** [comment]
There is no template specified for a simple question. Can I know more about that example?

**Comment by robertvorthman** [comment]
The example with the scrolling red views that animate the map is here:

https://github.com/react-native-community/react-native-maps/blob/master/example/examples/AnimatedViews.js
