### ISSUE TITLE
Zoom in and zoom out button not displayed ?

### ISSUE THREAD

**Issue by HusseinElGanzory** [react-native-community/react-native-maps#2917]
```
MapView
            provider={PROVIDER_GOOGLE} // remove if not using Google Maps
            style={styles.container}
            customMapStyle={RetroMapStyles}
            region={{
              latitude: LATITUDE,
              longitude: LONGITUDE,
              latitudeDelta: MAP_LATITUDE_DELTA,
              longitudeDelta: MAP_LONGITUDE_DELTA
            }}
            onPress={this.onMapPress}
            ref={c => this.mapView = c}
            minZoomLevel={2}  // default => 0
            maxZoomLevel={15} // default => 20
            zoom={1}
            showsUserLocation={true}
            followUserLocation={true}
            showsMyLocationButton={true}
            zoomEnabled={true}
            enableZoomControl={true}
            zoomTapEnabled={true}

          >
```

**Comment by hafeez-ullah-khan** [comment]
**<MapView
                    style={styles.map}
                    //provider={PROVIDER_GOOGLE}
                    mapType={isMaptype}
                    region={initialRegionValue}
                    showsUserLocation
                    zoomControlEnabled={true}
                    zoomEnabled={true}
                    enableZoomControl={true}
                    zoomTapEnabled={true}
                    rotateEnabled={true}
                    scrollEnabled={true}
                    pitchEnabled={true}
                // maxZoomLevel={7}

                >******


zooming in zooming out button is  not showing up

**Comment by Osamasomy** [comment]
same issue

**Comment by GolfredoPerezFernandez** [comment]
same here!! any fix?

**Comment by hafeez-ullah-khan** [comment]
onMapReady={() => { setMapWidth(mapWidth - 1) }}

**Comment by hafeez-ullah-khan** [comment]
https://stackoverflow.com/a/65848874/15060818 
here is the fixed

**Comment by hafeez-ullah-khan** [comment]
https://stackoverflow.com/a/65848874/15060818
here is fix for that, vote if it work for you

**Comment by hafeez-ullah-khan** [comment]
yes
https://stackoverflow.com/a/65848874/15060818

you can vote if it work for you
