### ISSUE TITLE
Running API requests through backend server

### ISSUE THREAD

**Issue by joshuakoh7** [react-native-community/react-native-maps#2920]
Hi guys,

I would like to run the API requests through my backend server that handles user authentication because I don't want to expose my API key to the public. Is there any way to change the API request URL without breaking the app?

Thanks!

**Comment by rborn** [comment]
What does this have to do with this module ?

**Comment by joshuakoh7** [comment]
I'm asking if there is a way to modify this module to make the calls through a custom URL instead of having to provide the API key in the app settings

**Comment by rborn** [comment]
The module uses the (google) sdk so it just follows their implementation.
