### ISSUE TITLE
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

### ISSUE THREAD

**Issue by vitorqshr** [react-native-community/react-native-maps#2924]
# Bug

App breaking when entering the screen

## Environment info

Samsuns Galaxy S8
react-native : 0.59.8
react-native-maps : 0.24.0 to 0.24.2 (tried both)

React native info output:

![image](https://user-images.githubusercontent.com/6797661/60057186-fc72aa00-96b9-11e9-89cb-585f7117dc88.png)

## Reproducible sample code

...

this.state = {
      region: {
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }
    }

.....

 <MapView
          ref={map => this.mapView = map}
          initialRegion={this.state.region}
          region={this.state.region}
          rotateEnabled={false}
          scrollEnabled={false}
          zoomEnabled={false}
          showsPointsOfInterest={false}
          showsBuildings={false}
          showsUserLocation={true}
          loadingEnabled={true}
        />

**Comment by rborn** [comment]
@vitorqshr can you please run a test with the master version? we just merged https://github.com/react-native-community/react-native-maps/issues/2924 (cc: @mikehardy )

**Comment by mikehardy** [comment]
If you are using react-native less than 0.60 my patch isn’t necessary I don’t think.

If (big IF! not sure this problem is AndroidX-related) this is an AndroidX problem with react-native 0.59.x or lower, you would see it if your app was androidX already, and you had not run `npm i jetifier` and `npm jetify` (along with hooking it in package.json postinstall)

If this wasn’t an AndroidX app then I’m not sure it would show up? 

I suppose issue templates in modules need to be updated to include a question if the app is AndroidX or not

**Comment by rborn** [comment]
@christopherdro  just  published 0.25.0 on npm, would be great to give it a shot and report back

**Comment by marchrenno** [comment]
I found a solution. Not sure if it's a long term one, but this will let you guys work until a permanent solution is found.
Just clear your cash:  npm start -- --reset-cache
And restart the project.
It worked for me.
FYI, I didn't eject my project yet.

**Comment by Jega1** [comment]
I have the same propblem.  i tried to all these methods not worked for me help!!!!!

**Comment by Mitra98t** [comment]
@Jega1 (sorry for my English) just try to type in the terminal react-native run-android instead of react-native start... that worked for me

**Comment by fatihmert** [comment]
I guess solved this error. So I'm using react-native version **0.61** 

_My impression are;_

I tested it on more than one real device. I loop without using components like flatlist or recyclerlist. (_I think react keeps these components in the cache and provides performance for the next refresh._) I get this error when I fetch and loop data multiple times. It doesn't happen the first time because RAM is fresh. When I started testing on different devices with high hardware capabilities, I realized that I had to fetch more data to get this error.

I have almost 4GB ram in the emulator (HAXM) I've fetched the data for 5 minutes yet I haven't encountered this error. The tests I made using flatlist without going to 3rd party were very successful.

You can try switching to any flatlist or 3rd party listing method. First, do not forget to convert your data to the component.

I must remind you; Even if a react-native bridge is performing, we should make sure that our code has permons.

Enjoy coding.

**Comment by Jega1** [comment]
@Mitra98t @fatihmert thanks a lot.

**Comment by anAnun** [comment]
I just had the same EXACT problem and errors. Clear the data and cache on your expo app on your phone, then it should work

**Comment by nolife08021** [comment]
clear app cache from the physical device works for me.

**Comment by Jeet78** [comment]
> I just had the same EXACT problem and errors. Clear the data and cache on your expo app on your phone, then it should work

It worked, much thanks.

**Comment by mayu-496** [comment]
I was getting the same problem with expo .. stopped  running the app ,  cleared expo recently open project and again started with ' expo start ' ... This worked for me..

**Comment by marlonparanhos** [comment]
Go to your project root folder/android > "...myAwesomeProject/android" and type "gradlew clean", then comeback and try to run it again

**Comment by gowthamrn4** [comment]
Just kill all node process and start npm server and run application
killall -9 node

**Comment by rosnaib11** [comment]
For expo, this happened to me when I clear data and cache of my Expo. Just restart your expo run 'epxo start -c'

**Comment by dancherb** [comment]
What about when your tracking detects this happening in production?

**Comment by Satyam-code143** [comment]
@nolife08021 
Same here .. 
I have just cleared the cache(app) from my device.
Thank You!1

**Comment by kalleriakronos24** [comment]
> What about when your tracking detects this happening in production?

i kinda still looking for this, just incase

**Comment by vicaster** [comment]
I had this error type when i used an old version of react-native.
Before version 0.59, the problem keeps coming back.
So i do in my terminal an upgrade of react-native pkg and the error is gone.
i think the best way to be sure is to do:
```npm i -g react-native-cli```
in your project folder.
Enjoy coding!! ;)

**Comment by PedroBern** [comment]
The same error here, fix after clear cache on the phone

**Comment by vicaster** [comment]
I have the same persistent problem.
When I have a lot of TextInput, the application generates this error..
So I isolated these TextInputs in a different screen. And this error comes back again but with a lower frequency.
Has anyone found a solution?
thx a lot for an futur answer.

**Comment by Shahzaib1999** [comment]
@vicaster have you found any solution?

**Comment by vicaster** [comment]
@Shahzaib1999 nop 😭

**Comment by alissonarom** [comment]
> I just had the same EXACT problem and errors. Clear the data and cache on your expo app on your phone, then it should work

Funcionou para mim. Obrigado

**Comment by eldano1995** [comment]
Same problem here. No solution yet??

**Comment by vicaster** [comment]
@eldano1995 nop. May be the 0.64 version will resolve it. i saw a commit which talk about resolve textInput bug.

**Comment by jafar-jabr** [comment]
why this bug is closed ?!!!

**Comment by nahidmbstu** [comment]
this is an active bug

**Comment by paulenokels** [comment]
> @nolife08021
> Same here ..
> I have just cleared the cache(app) from my device.
> Thank You!1

**Comment by HoppeDevz** [comment]
Clear the cache from expo project.
-> expo r -c 
and clear the cache from your celphone

**Comment by ketan1062** [comment]
https://github.com/facebook/react-native/issues/17530

**Comment by tiggem1993** [comment]
Hi I have recently face same crash with my production build. I have check my Firebase Crashlytics and found it occurred after user input some text and press the submit button.
 
**DEVICE INFO**
Android: 10
Device: samsung Galaxy Tab A (8.0", 2019)
RAM free: 368.54 MB
Disk free:  12.67 GB

**Dependencies**
"react": "16.13.1",    
"react-native": "0.63.4",
"@react-native-firebase/crashlytics": "^10.1.0",



```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures(DrawableContainer.java:880)
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.getOpacity(DrawableContainer.java:1163)
       at android.graphics.drawable.DrawableContainer.getOpacity(DrawableContainer.java:434)
       at android.graphics.drawable.InsetDrawable.getOpacity(InsetDrawable.java:259)
       at android.view.View.computeOpaqueFlags(View.java:19427)
       at android.view.View.setBackgroundDrawable(View.java:24704)
       at androidx.appcompat.widget.AppCompatEditText.setBackgroundDrawable(AppCompatEditText.java:112)
       at android.view.View.setBackground(View.java:24597)
       at android.view.View.<init>(View.java:6198)
       at android.widget.TextView.<init>(TextView.java:1215)
       at android.widget.EditText.<init>(EditText.java:106)
       at android.widget.EditText.<init>(EditText.java:102)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:74)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
       at com.facebook.react.views.textinput.ReactEditText.<init>(ReactEditText.java:111)
       at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:128)
       at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:84)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:261)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:728)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by snehalm-iprogrammer** [comment]
> Hi I have recently face same crash with my production build. I have check my Firebase Crashlytics and found it occurred after user input some text and press the submit button.
> 
> **DEVICE INFO**
> Android: 10
> Device: samsung Galaxy Tab A (8.0", 2019)
> RAM free: 368.54 MB
> Disk free: 12.67 GB
> 
> **Dependencies**
> "react": "16.13.1",
> "react-native": "0.63.4",
> "@react-native-firebase/crashlytics": "^10.1.0",
> 
> ```
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
>        at android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures(DrawableContainer.java:880)
>        at android.graphics.drawable.DrawableContainer$DrawableContainerState.getOpacity(DrawableContainer.java:1163)
>        at android.graphics.drawable.DrawableContainer.getOpacity(DrawableContainer.java:434)
>        at android.graphics.drawable.InsetDrawable.getOpacity(InsetDrawable.java:259)
>        at android.view.View.computeOpaqueFlags(View.java:19427)
>        at android.view.View.setBackgroundDrawable(View.java:24704)
>        at androidx.appcompat.widget.AppCompatEditText.setBackgroundDrawable(AppCompatEditText.java:112)
>        at android.view.View.setBackground(View.java:24597)
>        at android.view.View.<init>(View.java:6198)
>        at android.widget.TextView.<init>(TextView.java:1215)
>        at android.widget.EditText.<init>(EditText.java:106)
>        at android.widget.EditText.<init>(EditText.java:102)
>        at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:74)
>        at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
>        at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
>        at com.facebook.react.views.textinput.ReactEditText.<init>(ReactEditText.java:111)
>        at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:128)
>        at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:84)
>        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
>        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
>        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:261)
>        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
>        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
>        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
>        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
>        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
>        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
>        at android.view.Choreographer.doFrame(Choreographer.java:728)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
>        at android.os.Handler.handleCallback(Handler.java:883)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at android.os.Looper.loop(Looper.java:237)
>        at android.app.ActivityThread.main(ActivityThread.java:8107)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
> ```

facing the same issue .. can anyone help?

**Comment by DanielFredriksson** [comment]
Any fix?

**Comment by vicaster** [comment]
To resolve this problem i was created  my own <TextInput>, it's a custom keyboard.
So it's not THE solution but when my screen have a lot of <TextInputs> there is no crash.

Waiting for react native's staff resolve this problem.....
Have fun.

**Comment by vladi965** [comment]
> @vitorqshr , ¿puede ejecutar una prueba con la versión maestra? acabamos de fusionar [# 2924](https://github.com/react-native-maps/react-native-maps/issues/2924) (cc: @mikehardy )

Debes borrar el cache de tu celular a mi me funciono :)

**Comment by kkureli** [comment]
any solution ?

**Comment by mikehardy** [comment]
> That one is actually more of a workaround than a fix, you may apply it at any time, I see it in the upgrade-helper diffs for upgrades to react-native 0.67-rc series, and you can take it from there - it's only referencing things that you apply directly not any internal react-native code:
> 
> https://react-native-community.github.io/upgrade-helper/?from=0.66.1&to=0.67.0-rc.2

@kkureli

**Comment by ravikumar-yadav** [comment]
> @eldano1995 nop. May be the 0.64 version will resolve it. i saw a commit which talk about resolve textInput bug. this commit :
> 
> [facebook/react-native@6524e61](https://github.com/facebook/react-native/commit/6524e611d3cff11a9568a887b0208eeb1119358e)

same issue on oneplus with 0.64.1

**Comment by Nero2869** [comment]
Any updates? 
same issue on  "react-native": "0.64.2" which cooperate with   "react-native-paper": "^4.9.2",

**Comment by AllanBengco** [comment]
Adding my bug report to this thread.

Using React Native 0.64.2, with Expo, running the app in development is fine. The build for Google Play is another matter.

**Comment by Nero2869** [comment]
What's more this bug is so rare that I cant do more debug.. Its occurs also in production.

**Comment by davmaene** [comment]
I had the same problem; but i solved it by deleting data from my ```client expo``` app

**Comment by gurkanucar** [comment]
Same problem on expo. It doesn't matter for me while developing but if it will cause a problem in production this is a problem :/

**Comment by realTechmaniac** [comment]
wipe your virtual device data reset cache and restart simulator

**Comment by kristopalka** [comment]
The same issue, for me, occurs nearly every time I take a photo using expo camera

**Comment by avishain** [comment]
Issue still exists in RN 0.70.0. 
It worked fine with version 0.65.1.
Anyone to the rescue? I can share my dependencies list if it helps somehow.

**Comment by lieberscott** [comment]
Still getting this error. Any workaround yet?

**Comment by sourabhCCSD** [comment]
The REMEDY ..for android

Log out of the app.
From a Phone Home screen, navigate: Apps icon > Settings > Apps (Phone section)
Tap Application Manage.
From the Dropdown menu ensure All apps is selected, then locate and tap Expo Pass app.
Tap Storge.
Tap CLEAR CACHE.

**Comment by vishuk570** [comment]
Add the flowing line of code into [/android/app/src/main/res/values/styles.xml.](url)
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
       <item name="android:editTextBackground">@android:color/transparent</item> <-- Add this
       ...
</style>`
Hope this will work.

**Comment by HobaiGuigui** [comment]
Just Clean the cache witch this folownig command:

_yarn start -c_  OR _npx expo start_

**Comment by Onyelaudochukwuka** [comment]
> The REMEDY ..for android
> 
> Log out of the app. From a Phone Home screen, navigate: Apps icon > Settings > Apps (Phone section) Tap Application Manage. From the Dropdown menu ensure All apps is selected, then locate and tap Expo Pass app. Tap Storge. Tap CLEAR CACHE.

This worked for me Thanks!!

**Comment by vaish8529** [comment]
> Add the flowing line of code into [/android/app/src/main/res/values/styles.xml.](url) `<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar"> <item name="android:editTextBackground">@android:color/transparent</item> <-- Add this ... </style>` Hope this will work.
![TEXTINPUT](https://github.com/react-native-maps/react-native-maps/assets/105700183/4b3aeebc-bb45-4e24-9169-c37cbbb12628)

Thanks for solution but I am facing issue after applying above code, my textinputs ignoring css

**Comment by dgreasi** [comment]
Same issue with the following env:

```
"react-native": "0.72.5",
"react-native-maps": "^1.8.0",
```

**Comment by phaniankur** [comment]
When it works, it works. Resetting worked fine for me. 👍
` npm start -- --reset-cache`
