### ISSUE TITLE
Prevent Google Logo from Redirecting to Google Maps [iOS]

### ISSUE THREAD

**Issue by Eralyne** [react-native-community/react-native-maps#2936]
Is there any way to prevent the redirect to Google Maps when tapping on the Google Logo on iOS? Android has the tap go through the logo and press the map, which is what we want on both devices.

I'm perfectly fine with having the Google Logo visible (and I do want it visible, please don't recommend that I hide it) but redirecting users out of the app through possible miss-taps is very bad.

**Comment by rborn** [comment]
You don't want this, Google forbids any change of behaviour of their sdk and they can lock your access to the apis.

Also you didn't follow the template for this issue. Closing.
