### ISSUE TITLE
React Native 60 build gradle fix

### ISSUE THREAD

**Issue by owinter86** [react-native-community/react-native-maps#2940]
# Bug

React native 0.60 has arrived and with that androidX. The migratio guide recommends that a post install script is added to individual projects to run jetifier through node_modules bumping any legacy support integrations to androidX, https://github.com/mikehardy/jetifier#readme. However this will fail for projects that have projects, that has build gradle dependency with react native using compileOnly.

```
compileOnly('com.facebook.react:react-native:+') {
    exclude group: 'com.android.support'
  }
```
For jetifier to successfully run and complieOnly needs to change to implementation.
```
implementation('com.facebook.react:react-native:+') {
    exclude group: 'com.android.support'
  }
```
## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 128.93 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0 => 0.60.0
  npmGlobalPackages:
    create-react-native-web-app: 0.1.11
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Library version: 0.24.2

## Steps To Reproduce

1. init new react-native project
2. install react-native-maps
3. Add jettifier post install script.
4. build

Describe what you expected to happen:
Can use the post install jettifier solution to use react native maps on RN version 0.60

**Comment by rborn** [comment]
@owinter86 looks like you already know what has to be done, why not opening a PR? 🤗

**Comment by owinter86** [comment]
@rborn I thought I should do both so it can be tracked properly if there needs to be a discussion, you were just too quick for me.
