### ISSUE TITLE
JSON value of type NSMutableDictionary cannot be converted to CLLocationDegrees

### ISSUE THREAD

**Issue by AmeraAbdallah** [react-native-community/react-native-maps#2986]
# I store location object with latitude and longitude attributes in mongodb, and when I get the object and pass it to Marker coordinate prop .. I get this ERROR, please help me !

JSON value '{
    latitude = "32.885353";
    longitude = "13.180161";
}' of type NSMutableDictionary cannot be converted to CLLocationDegrees

+[RCTConvert(CoreLocation) CLLocationDegrees:]
    RCTConvert+CoreLocation.m:12
+[RCTConvert(CoreLocation) CLLocationCoordinate2D:]
__invoking___
-[NSInvocation invoke]
__createNSInvocationSetter_block_invoke
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.96
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2
RCTPerformBlockWithLogFunction
RCTPerformBlockWithLogPrefix
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke
__37-[RCTComponentData setProps:forView:]_block_invoke
-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
-[RCTComponentData setProps:forView:]
__50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke.405
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.461
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

**Comment by rborn** [comment]
Please update your issue following the question template and add more details (code, etc)

**Comment by davidbonan** [comment]
I have this error message and i solved it, for me it was a little misstake of wrong destructuring object. The result is coordinate={{latitude: {latitude, longitude}, longitude: null }}.
I think this error message is due to convert on Number in Latitude or Longitude and you don't pass a Number to it but an Object or whatever
