### ISSUE TITLE
Ref to map in Typescript

### ISSUE THREAD

**Issue by Anytram** [react-native-community/react-native-maps#2989]
Hello,
I have problem with assign ref to MapView to variable:

`
let map = React.createRef<MapView>();
<MapView
				provider={PROVIDER_GOOGLE}
				style={StyleSheet.absoluteFillObject}
				ref={ ref => map=ref}
			>
</MapView>
`

I keep getting this  error:

> let map: React.RefObject\<MapView\>
> Type 'MapView | null' is not assignable to type 'RefObject\<MapView\>'.
>   Type 'null' is not assignable to type 'RefObject\<MapView\>'.ts(2322)

I checked on StackOverflow - didn't find any solution. 

On the other hand when I tried:
`ref={map}`
it works but reference is null.
Please help :)

**Comment by madeinquant** [comment]
Hope this help. 
<MapView
            style={styles.map}
            provider={this.props.provider}
            **### ref={ref => { this.map = ref; }}**
            initialRegion={this.state.region}
            showsUserLocation={false}
            onRegionChange={region => this.onRegionChange(region)}>
            {this.createMarkers()}
          </MapView>

**Comment by madeinquant** [comment]
Hope this help
```
 <MapView
            style={styles.map}
            provider={this.props.provider}
            ref={ref => { this.map = ref; }}
            initialRegion={this.state.region}
            showsUserLocation={false}
            onRegionChange={region => this.onRegionChange(region)} >
            {this.createMarkers()}
 </MapView>
```

**Comment by rborn** [comment]
@Anytram did  it work for you? If yes please close the issue. 

Also next time please follow the template or we'll close the issue right away

**Comment by GolfredoPerezFernandez** [comment]
same here! solution?

**Comment by hmartiins** [comment]
so it seems no solution yet :(

**Comment by princefishthrower** [comment]
@mshavandi - wrong, with this method, you get:

```
TypeError: Object is not a function
```

The "types" on this library are something else...

**Comment by udabasili** [comment]
@mshavandi answer worked for me
`    const mapView = React.useRef<MapView | null>(null);`

Then 
`<MapView 
                                initialRegion={{
                                    ...location
                                }}
                                ref={ref => { mapView.current = ref  as MapView}}
      
                                style={styles.map} 
                            >`

**Comment by Kimbohlovette** [comment]
> `const mapRef = React.useRef<MapView | null>(null);`

It worked for me. Many thanks @mahdieh-dev
