### ISSUE TITLE
Android crash when MapView is rendered

### ISSUE THREAD

**Issue by Gabsys** [react-native-community/react-native-maps#2991]
React Native Version: 0.59.10

### What Happened
After entering the screen with MapView, the app crashes. 
There's no error from logcat.
MapView works fine in iOS but crashed in Android
Originally everything works fine in my older version of react native (Forgot which version lmao), but after I update my project to 0.59.10, this app crash happen.

My MapView code:
```
import MapView, {Marker,PROVIDER_GOOGLE} from 'react-native-maps';

<MapView
                    initialRegion={{
                    latitude: this.state.latitude,
                    longitude: this.state.longitude,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421,
                    }}
                    style={{height:'77.5%',width:'100%'}}
                    provider={PROVIDER_GOOGLE}
                    showsUserLocation={true}
                    followsUserLocation={true}
                    onUserLocationChange={location =>  this.setState({latitude:location.nativeEvent.coordinate.latitude, longitude:location.nativeEvent.coordinate.longitude})}
                >
                  <Marker
                    coordinate={{latitude: loclat, longitude: loclon}}
                    title={locname}
                />
   </MapView> 
```

**Comment by elkinjosetm** [comment]
Same here, it crashes on RN 0.60 because AIRMap isn't available on Android. I was able to get it working by excluding `play-services-base` and `play-services-maps` in `app/build.gradle`.

```
implementation(project(':react-native-maps')) {
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
}
```

Which means, I had to manually link the dependency on Android project.

**Comment by Gabsys** [comment]
> Same here, it crashes on RN 0.60 because AIRMap isn't available on Android. I was able to get it working by excluding `play-services-base` and `play-services-maps` in `app/build.gradle`.
> 
> ```
> implementation(project(':react-native-maps')) {
>     exclude group: 'com.google.android.gms', module: 'play-services-base'
>     exclude group: 'com.google.android.gms', module: 'play-services-maps'
> }
> ```
> 
> Which means, I had to manually link the dependency on Android project.

I also excluded play-services-base and play-services-maps. However, mine is still crashing :(

**Comment by agarwalnaveen22** [comment]
Add this line in your androidmanifest.xml file in the ```<application>``` tag:-

```
<uses-library android:name="org.apache.http.legacy" android:required="false"/>
```

**Comment by Gabsys** [comment]
> Add this line in your androidmanifest.xml file in the `<application>` tag:-
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```

Thanks man! Fixed the issue

**Comment by leoarmelin** [comment]
> Add this line in your androidmanifest.xml file in the `<application>` tag:-
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```

This worked for me!!!!!! Thxxx
I love u so much

**Comment by digicomsolutions11** [comment]
> > Add this line in your androidmanifest.xml file in the `<application>` tag:-
> > ```
> > <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> > ```
> 
> This worked for me!!!!!! Thxxx
> I love u so much

love you more. you saved my day :-*

**Comment by Archulan** [comment]
> Add this line in your androidmanifest.xml file in the `<application>` tag:-
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```

Thank you!

**Comment by dihan** [comment]
on Expo PROVIDER_GOOGLE crashes the App - Only on TestFlight. It works fine in Simulator 
    "react-native-maps": "~0.24.0" - SDK33

**Comment by zhitomir-oreshenski-mm** [comment]
Hi,

Above suggestion still fix the issue with real android devices:

`<uses-library android:name="org.apache.http.legacy" android:required="false"/>` in <application> tag.

BR,
Zhi

**Comment by Xerus2000** [comment]
Umm, I am using a managed Expo App, I can't modify my manifest - what now?

**Comment by dihan** [comment]
> Umm, I am using a managed Expo App, I can't modify my manifest - what now?

What happens if you leave the provider blank or as default?

**Comment by Xerus2000** [comment]
I have never set the provider.

**Comment by godswillokokon** [comment]
> Add this line in your androidmanifest.xml file in the `<application>` tag:-
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```

why did this work?

**Comment by Gabsys** [comment]
> > Add this line in your androidmanifest.xml file in the `<application>` tag:-
> > ```
> > <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> > ```
> 
> why did this work?

With Android 6.0, we removed support for the Apache HTTP client. Beginning with Android 9, that library is removed from the bootclasspath and is not available to apps by default.

To continue using the Apache HTTP client, apps that target Android 9 and above can add the following to their AndroidManifest.xml.

Source: https://developer.android.com/about/versions/pie/android-9.0-changes-28

**Comment by Dverybest** [comment]
mine still crashed even after adding
`<uses-library android:name="org.apache.http.legacy" android:required="false"/>`

**Comment by DevilPatels** [comment]
i having issue like this

this is my logcat

java.lang.NoSuchMethodError: No static method getFusedLocationProviderClient(Landroid/content/Context;)Lcom/google/android/gms/location/FusedLocationProviderClient; in class Lcom/google/android/gms/location/LocationServices; or its super classes (declaration of 'com.google.android.gms.location.LocationServices' appears in /data/app/com.drapp-C1klWmBxCroOYpKkCWvoAw==/base.apk!classes2.dex)
        at com.airbnb.android.react.maps.FusedLocationSource.<init>(FusedLocationSource.java:22)
        at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:165)
        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:85)
        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:987)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:958)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1083)
        at android.view.Choreographer.doCallbacks(Choreographer.java:908)
        at android.view.Choreographer.doFrame(Choreographer.java:831)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1070)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

could anyone find solution for this ?

**Comment by CrashingTheCode** [comment]
I have the same issue as @Gabsys and doing what @elkinjosetm and @agarwalnaveen22 said is not fixing the error, I have
reat-native: 0.70.0
react-native-maps: 1.3.2

When I render the MapView on Android there is a crash (a critical error without logs) only a stacktrace in which appears the AirMapView

T_T

**Comment by ckswopnera** [comment]
React native map crashes on android platform version 33. What to do?

**Comment by rojingharooni** [comment]
> Umm, I am using a managed Expo App, I can't modify my manifest - what now?

hi xeruf i'm also using expo . did u find any thing?
