### ISSUE TITLE
App crashes on MapView page in Production

### ISSUE THREAD

**Issue by abhinav-official** [react-native-community/react-native-maps#2997]
# Bug

When using MapView with react-native-maps in expo and building the app for production, the app restarts itself when navigated to the page calling MapView.

## Environment info

React native info output:

```bash
   "dependencies": {
    "axios": "^0.18.1",
    "expo": "^32.0.0",
    "moment": "^2.24.0",
    "qs": "^6.7.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-counters": "0.0.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^1.1.0",
    "react-native-image-slider-show": "^1.0.3",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-maps": "^0.24.2",
    "react-native-paper": "^2.15.2",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-super-grid": "^3.0.8",
    "react-navigation": "^3.11.0"
  },
```

Library version:"^0.24.2" + "^0.25.0"

## Steps To Reproduce

1. expo build:android

...

Describe what you expected to happen:

1.expected to work after building apk
2. works in development and on expo apps but not in production build

**Comment by lucas-wilmart** [comment]
I have the exact same issue. Any help would be highly appreciated

**Comment by Vitaly-V** [comment]
I have the exact same issue too.

**Comment by Vitaly-V** [comment]
> # Bug
> When using MapView with react-native-maps in expo and building the app for production, the app restarts itself when navigated to the page calling MapView.
> 
> ## Environment info
> React native info output:
> 
> ```shell
>    "dependencies": {
>     "axios": "^0.18.1",
>     "expo": "^32.0.0",
>     "moment": "^2.24.0",
>     "qs": "^6.7.0",
>     "react": "16.5.0",
>     "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
>     "react-native-counters": "0.0.1",
>     "react-native-datepicker": "^1.7.2",
>     "react-native-elements": "^1.1.0",
>     "react-native-image-slider-show": "^1.0.3",
>     "react-native-keyboard-aware-scroll-view": "^0.8.0",
>     "react-native-maps": "^0.24.2",
>     "react-native-paper": "^2.15.2",
>     "react-native-scrollable-tab-view": "^0.10.0",
>     "react-native-super-grid": "^3.0.8",
>     "react-navigation": "^3.11.0"
>   },
> ```
> 
> Library version:"^0.24.2" + "^0.25.0"
> 
> ## Steps To Reproduce
> 1. expo build:android
> 
> ...
> 
> Describe what you expected to happen:
> 
> 1.expected to work after building apk
> 2. works in development and on expo apps but not in production build

Did you manage to solve it?

**Comment by lucas-wilmart** [comment]
I sent an email to OP right after I wrote my comment and he send me this : https://docs.expo.io/versions/v34.0.0/sdk/map-view/#deploying-to-a-standalone-app-on-android. You have to register an Api key for Android SDK and follow each step carrefully. We both solved our issue that way

**Comment by Vitaly-V** [comment]
@lucas-wilmart thank you! It works now.

**Comment by abhinav-official** [comment]
@lucas-wilmart @Vitaly-V a pro tip before deploying apk just goto expo dev tools by pressing in "d" in command line where expo is running and switch your environment to production from development and test your app it will give your issues.

**Comment by minhvuongrbs** [comment]
You all should update about Google Map key in document!

**Comment by clarios6** [comment]
For anyone else browsing this in the future (Also a bit off-topic but this is the highest result on Google):

If you're on Expo and still having rendering problems even after adding an API key for Google Maps, double-check any Markers that you might be rendering with an `image` or `icon` prop. React Native Maps can only handle local images for custom Markers and Expo by default puts your images on EC2. There is a workaround to do something like:
```
<Marker>
  <Image />
</Marker>
```
but it makes it quite slow, it works without doing anything complex though.

You can try bundling the images with your build, I was having some issues with that but it's more of an Expo problem than a RNM one. This documentation link might be a bit helpful if you need to do it yourself: https://docs.expo.io/guides/preloading-and-caching-assets/
