### ISSUE TITLE
Custom Callout Positioning

### ISSUE THREAD

**Issue by TylerOlthuizen** [react-native-community/react-native-maps#2998]
Hello!

Thank you for this great component. I'm trying to I'm trying to get the arrow in the callout to be right over the marker. Is there a good way to position this perfectly everytime? Also when I clicked on the marker I am animated that point to be in the center of the map area.

![Screen Shot 2019-07-31 at 12 24 21 PM](https://user-images.githubusercontent.com/10456029/62237848-fcd42400-b38e-11e9-8be4-48d6605b0521.png)

**Comment by rborn** [comment]
no template closing

**Comment by bharatchavan-pro** [comment]
@rborn Have you got the solution?
