### ISSUE TITLE
Show user direction arrow 

### ISSUE THREAD

**Issue by luiz13lg** [react-native-community/react-native-maps#3017]
My map application doesn't show the user direction arrow, just the beam pointing to his location. Does anybody faced the same problem? 
I'm not sure if I have to add more code to the mapview, I'm using the 0.25.0v

the mapview code is this:
<MapView style={Estilos.map} showsMyLocationButton={true} showsUserLocation={true}
          followsUserLocation={true} initialRegion={this.state.region} loadingEnabled={true}
>
![image](https://user-images.githubusercontent.com/30446223/63027887-1e9bd380-be84-11e9-8ab0-01f9d8b083a7.png)

Thanks!!

**Comment by dodevski** [comment]
In my case, show arrow on emulator, but not on device

**Comment by CrisHemswerthThor** [comment]
I am also getting through it and it is really frustrating. In my case it is shown in IOS but not on android.
Is there any update on this issue?

**Comment by rborn** [comment]
@CrisHemswerthThor don't post the same question on multiple issues, it won't solve anything but you'll only manage to frustrate the maintainers 😕

**Comment by dodevski** [comment]
The arrow is here on my device. When I testing the App in motion the arrow is shown. Seems that is not arrow for showing a gyroscope sensor direction but direction of motion and show only if the device is in motion, if you stay the arrow is gone. :)

**Comment by CrisHemswerthThor** [comment]
**@rborn** ,I have no intension to frustrate you guys. But the problem is that i want solution for this.

**Comment by CrisHemswerthThor** [comment]
**@dodevski**, in case of IOS, the same thing is working properly then why not in android?

**Comment by Calyypso** [comment]
Even when I move with my phone, the arrow doesn't appear.
It's displayed in a very random way.

**Comment by luiz13lg** [comment]
![image](https://user-images.githubusercontent.com/30446223/65048239-2bf02600-d93a-11e9-87e9-3b359e30c283.png)

My app suddenly began to load the arrow without me doing anything. I don't know what happened but it's solved...

I'm closing this issue, thanks for all attention.

**Comment by arwantys** [comment]
Same problem, I can't find a solution

**Comment by luiz13lg** [comment]
@arwantys 
I don't know if this may help you, but I'm using:
"react-native": "0.59.8",
"react-native-maps": "0.27.1",
and just began to work, the Android version of this pic was 6, I also tested on 9 and worked very fine.

**Comment by Sanjay-C-H** [comment]
This is because your Device doesn't have gyroscope sensor
