### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by pawanvivekananda** [react-native-community/react-native-maps#3019]
<img width="285" alt="Screenshot 2019-08-15 at 5 25 29 PM" src="https://user-images.githubusercontent.com/2833596/63093310-42454380-bf82-11e9-8488-5522b722c014.png">

Not able to get map view in android
# Bug

## Environment info

React native info output:

```bash
 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 37.17 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.59.8
```

Library version: 
react-native": "0.59.9"
react-native-maps": "^0.25.0

**Comment by christopherdro** [comment]
Double check that your api key is correct and the initial region being passed in.

**Comment by rborn** [comment]
Closing, no reply

**Comment by zohraj** [comment]
I am having the same issue. API Key is correct and initial region is also provided.

**Comment by sujatha2016** [comment]
I too had the issue when I Enabled Google Maps SDk for iOS it started showing. Also ensure your project in console had billing enabled. Also the key is from correct project.
