### ISSUE TITLE
Where do you put the API key when using expo?

### ISSUE THREAD

**Issue by iqbal125** [react-native-community/react-native-maps#3030]
# Question
Im assumming its somewhere in app.json but I cant be sure.

**Comment by Eesssn** [comment]
same issue. please help

**Comment by christopherdro** [comment]
https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android
> In app.json, copy the API key from android.config.googleSignIn to android.config.googleMaps.apiKey.

Example diff:
https://github.com/brentvatne/growler-prowler/commit/3496e69b14adb21eb2025ef9e0719c2edbef2aa2

**Comment by Eesssn** [comment]
@christopherdro  thank you Bro

**Comment by WillSmithTE** [comment]
I know this is recommended by the expo docs, but doesn't it feel wrong to commit this?

**Comment by P-v-R** [comment]
@WillSmithTE - it does feel wrong! trying to make this decision now

**Comment by ser-emejia** [comment]
> I know this is recommended by the expo docs, but doesn't it feel wrong to commit this?

Hello, did you find another solution?

**Comment by CharlyPoppins** [comment]
With **app.config.js** or **app.config.ts** you can use something like :
```
android: {
      ....
      config: {
        googleMaps: {
          apiKey: process.env.GOOGLEMAPS_APIKEY,
        },
      },
    },
```
And define GOOGLEMAPS_APIKEY via command line on via `eas secret`
