### ISSUE TITLE
Heatmap: Did you forget to export the Heatmap module?

### ISSUE THREAD

**Issue by oliverdolgener** [react-native-community/react-native-maps#3033]
# Bug

Hey Guys, thanks for maintaining this library and adding more and more useful features. I was very hyped when Heatmap was finally supported. But did you forget to export the Heatmap module in `MapView.js`?

When I try to use it, there's an error saying that I exported undefined instead of a component. When I `import MapHeatmap from './MapHeatmap';` and `MapView.Heatmap = MapHeatmap;` in `MapView.js` everything works fine. Am I using it wrong or did you forget to export it? I am using it like: `import MapView from 'react-native-maps';` and then `return <MapView.Heatmap .../>`

## Environment info

React native info output:

```bash
 React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 2.32 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
```

Library version: master branch (25.0.0)

## Steps To Reproduce

`import MapView from 'react-native-maps';`

`return <MapView.Heatmap .../>`

Describe what you expected to happen:

Heatmap module should be working like all other modules.

## Reproducible sample code

```
import React from 'react';
import MapView from 'react-native-maps';

const HeatMap = ({ locations }) => {
  const points = locations.map(x => ({
    latitude: x.latitude,
    longitude: x.longitude, 
    weight: x.count
  }));

  return (
    <MapView.Heatmap
      points={points}
      radius={50}
      opacity={0.5}
    />
  );
};

export default connect(mapStateToProps)(HeatMap);
```

**Comment by rborn** [comment]
Please update the issue using the template

**Comment by oliverdolgener** [comment]
Updated issue using template

**Comment by Wangor** [comment]
Is the heatmap feature working at all? Is there any working example?
