### ISSUE TITLE
The following packages use deprecated "rnpm" config that will stop working from next release

### ISSUE THREAD

**Issue by TheMisir** [react-native-community/react-native-maps#3036]
# Bug

warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

## Environment info

React native info output:

```bash
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 925.44 MB / 7.89 GB
  Binaries:
    Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

Library version: 0.25.0

## Steps To Reproduce

1. Upgrade react-native to latest version
2. `react-native init MyProj` then `cd MyProj`
3. Install rnmaps package
4. Try `react-native run-android`

**Comment by kmvbatista** [comment]
I'm also with the same issue

**Comment by richardfelkl** [comment]
I'm also seeing the same error.

**Comment by TheMisir** [comment]
I think they have fixed it in MR #2975 which I think will be released (fixed) soon.

**Comment by hohien** [comment]
Any solutions?

**Comment by TheMisir** [comment]
@hohien just ignore the warning and keep your eye on new RNMaps updates. They already fixed this issue.

**Comment by hohien** [comment]
Oh, For now, I have updated this library to newish version, but I still don't see React-native config file in React-native-maps module,

**Comment by cristinaITdeveloper** [comment]
I'm working on a RN app these days and there's still this problem.

**Comment by TheMisir** [comment]
It looks like they haven't pushed fixed it :/

**Comment by NooruddinLakhani** [comment]
Still getting the same warning. What to do?

**Comment by TheMisir** [comment]
@NooruddinLakhani the maintainers haven't published the fixed version. Just need to wait for now 😕

**Comment by TheMisir** [comment]
I have good and bad news for you guys 🙂

1. 👍 This issue was fixed and published in the 0.26.0 version.
2. 👎 But don't upgrade to 0.26.0 and wait until 0.26.X, because they added new bugs to fix it later 🤣 - ["AIRMap" was not found bug](https://github.com/react-native-community/react-native-maps/commit/e8fb0c98c916eae4aa15bf79996d6ec10839540d) which is fixed but has not been published.

**Comment by rborn** [comment]
You can use the master for now :)

**Comment by TheMisir** [comment]
Thanks, @rborn.

**Comment by wwwbruno1981** [comment]
To help the next one that has this problem.

Run the command below to remove the package with "rnpm":

**yarn remove react-native-update-gradle**

after the command below to update the dependencies:

**yarn upgrade**

worked for min.
