### ISSUE TITLE
App getting crashed after react-native-maps installed 

### ISSUE THREAD

**Issue by thilinawarnakula** [react-native-community/react-native-maps#3043]
Im using react-native-maps(0.25.0) library in my react native project (0.60.5).
but after installing the library the app getting crashed without and error log
Please help on this :)

**Comment by thilinawarnakula** [comment]
@rborn issue is still there

**Comment by rborn** [comment]
@thilinawarnakula I closed the issue because you didn't follow the template and you didn't add any details

**Comment by keremcubuk** [comment]
Same issue, here is the fix: 
https://github.com/react-native-community/react-native-maps/issues/2991
