### ISSUE TITLE
React-Native 0.60 cannot assign a `ref` to `<MapView/>`

### ISSUE THREAD

**Issue by 20SangHun00** [react-native-community/react-native-maps#3062]
# Question
Several days ago, I've started upgrading a react-native project which I'm working on from v0.57.3 to v0.60.5, and now I started testing the app. Unfortunately, the old method of assigning refs is not working anymore, and the screen where MapView is placed is throwing me constantly errors. Here are some code snippets which I've tried to do for avoiding the problem:

```
import React from 'react';
...
constructor (props) {
    super(props);
    this.mapRef = React.createRef();
}
...
<MapView
...
          ref={this.mapRef}
...
       />
```

```
import React from 'react';
...
render() {
...
    this.mapRef = React.createRef();

...
return (
<MapView
...
          ref={this.mapRef}
...
       />)
```

And I've tried calling react-native-maps' methods by the old and new way (`this.mapRef.method` & `this.mapRef.current.method`), but the device still returns me the same error : `TypeError: undefined is not an object (evaluating '_this.mapRef.current')`.

Does anybody have any ideas?

**Comment by marcinj1** [comment]
You should use:
`ref={(ref) => this.mapRef = ref}`

**Comment by JonBerglund** [comment]
When I want to control the map from a parent component?
For example, I have created ref in the parent component and forwarded the ref to the map component.
Now in the parent component I want to be able to use moveCoordinate/Region but the app crashes because the parent doesn't have this function.l
