### ISSUE TITLE
iOS: How to get rid of GoogleMap when we require only Apple Map?

### ISSUE THREAD

**Issue by shebinkoshy123** [react-native-community/react-native-maps#3067]
react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.
![IMG_6694](https://user-images.githubusercontent.com/46756662/65136159-b745e600-da24-11e9-81b3-27345e37062d.PNG)

**Comment by shebinkoshy123** [comment]
Need to change provider to default

**Comment by isllyend** [comment]
how to change it？ @shebinkoshy123  🙏（：

**Comment by madeinquant** [comment]
I didn't specify to change the provider, Apple map is the default

 ```
 <MapView
        style={styles.map}
        // provider={provider}
        ref={MapView => { thismap = MapView }}
        initialRegion={region}
        showsUserLocation={true}
        onRegionChange={region => onRegionChange(region)}
      >
        {cluster.markers.map(renderMarker)}
      </MapView>
```
