### ISSUE TITLE
Crash on Android with RN 0.60.5 - Invariant Violation: requireNativeComponent: "AIRMap" was not found in the UI Manager

### ISSUE THREAD

**Issue by alubeck** [react-native-community/react-native-maps#3081]
# Bug

The library seems not to work with the latest stable React Native version 0.60.5. I just created a clean RN project via `react-native init` and added a simple map from the Getting Started guide. App in Dev Mode crashes with this error:

![Screenshot_20190923-140740](https://user-images.githubusercontent.com/6048707/65424386-bc7fa800-de0b-11e9-9ecd-af7040ae0b03.png)

All "magic" i've done after creating a new RN project can be seen here:
https://github.com/alubeck/react-native-maps-example/commit/2fe7319783323be6411f6dd2ad7a252feb648cdd

## Environment info

I'm using the latest commit from master of the library, since there was some time no release.

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 73.19 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/v12.10.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
```

Library version: 0.25.0 + X  (latest commit from master)

## Steps To Reproduce

1. Setup a clean project and add a simple map, like mentioned in the commit
2. Try to run the app on android with ```react-native run-android```

Describe what you expected to happen:

1. I should see a simple google map, centered to given coordinates.

## Reproducible sample code

https://github.com/alubeck/react-native-maps-example/commit/2fe7319783323be6411f6dd2ad7a252feb648cdd

**Comment by alubeck** [comment]
**WORKAROUND:**

Well, hours later (creation time of this issue will tell) there was this idea :smile: 

Just **do not**, what is written in the [installation instructions](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#build-configuration-on-android) and **link react-native-maps "manually"** as before. The map gets now properly for my setup.

I've updated my given example as well: https://github.com/alubeck/react-native-maps-example/commit/c63596cd3fd490aa17c4f5c0ac3e1fe96da406dc

At least we should find out here, why autolinking does not work or at least update the installation instructions.

**Comment by rogerkerse** [comment]
> **WORKAROUND:**
> 
> Well, hours later (creation time of this issue will tell) there was this idea 😄
> 
> Just **do not**, what is written in the [installation instructions](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#build-configuration-on-android) and **link react-native-maps "manually"** as before. The map gets now properly loaded for my setup.
> 
> I've updated my given example as well: [alubeck/react-native-maps-example@c63596c](https://github.com/alubeck/react-native-maps-example/commit/c63596cd3fd490aa17c4f5c0ac3e1fe96da406dc)
> 
> At least we should find out here, why autolinking does not work or at least update the installation instructions.

As a temporary solution it works :) (the manual linking)

**Comment by cormander** [comment]
I had this issue as well, and did @rogerkerse 's manual link work-around. I later figured out this issue was because I hadn't specified `androidMapsUtilsVersion` in my `build.gradle` file. Here's the diff to the fix to this on my project:

https://github.com/OurVoiceUSA/HelloVoter/commit/14857376632ab5dcb165e34e40f2b7ceb8906e3c

Hope this helps.

**Comment by kefyru** [comment]
> I had this issue as well, and did @rogerkerse 's manual link work-around. I later figured out this issue was because I hadn't specified `androidMapsUtilsVersion` in my `build.gradle` file. Here's the diff to the fix to this on my project:
> 
> [OurVoiceUSA/HelloVoter@1485737](https://github.com/OurVoiceUSA/HelloVoter/commit/14857376632ab5dcb165e34e40f2b7ceb8906e3c)
> 
> Hope this helps.

I've just install and run this example, and got error in android simulator: TypeError: Cannot read property 'Direction' of undefined

**Comment by gauravmc** [comment]
This got fixed in the new release: https://github.com/react-native-community/react-native-maps/releases/tag/v0.26.1

**Comment by eduardopelitti** [comment]
I'm getting the same error on Android, using v0.26.1 and RN 0.60.4.

I have specified an `androidMapsUtilsVersion` in `build.gradle` and followed the official steps for RN > 0.60

Tested on a physical device with Android 8.0.0 and on emulator.

**Comment by henoktsegaye** [comment]
you need to link then build the app "react-native start" , if you didnt did this before . this is not gonna work by just reloading the metro server

**Comment by anniewey** [comment]
It's working on v0.26.1 and RN0.61.2, thanks for the update.
