### ISSUE TITLE
ios google map without tiles on latest packages - rn 0.60.5 / react-native-maps 0.25.0

### ISSUE THREAD

**Issue by rares-lupascu** [react-native-community/react-native-maps#3083]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 450.21 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: x.x.x

## Steps To Reproduce

1. Install latest react native
2. Install latest react-native-maps on IOS + Google Maps (cocoapods)
3. Load the map
4. U will see an empty map where markers appear but tiles do not

Describe what you expected to happen:

1. See the map tiles

## Reproducible sample code

basic MapView implementation

[Screenshot](https://ibb.co/kJZjpCy)

**Comment by NguyenPhuong1907** [comment]
Be sure to add it   
[GMSServices provideAPIKey:@" API Key Google"];
or Check Console API Key Google

**Comment by rares-lupascu** [comment]
already did that ... works on android ... doesn't on ios

**Comment by rares-lupascu** [comment]
```javascript
"react": "16.9.0",
"react-native": "^0.61.1"
```
i removed ani restriction on the key from google developer console and still no tiles :(

**Comment by rares-lupascu** [comment]
for anyone watching this
in google developer console u have to activate 2 APIs
1) Maps for Android
2) Maps for IOS
I only activated the first one ... so ... my mistake
