### ISSUE TITLE
Use Deprecated 'rnpm' configuration on RN 0.61.1 & also on RN 0.60.5

### ISSUE THREAD

**Issue by arbabr96** [react-native-community/react-native-maps#3090]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by radeno** [comment]
Its fixed, not published yet
https://github.com/react-native-community/react-native-maps/pull/2975

**Comment by dyc5828** [comment]
@christopherdro Any ETA on when #2975 will make it into a release?

**Comment by harish92** [comment]
even I'm also getting the same issue with react-native-maps 0.25.0
 
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://github.com/react-native-community/react-native-maps#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by rborn** [comment]
@arbabr96 @harish92 can you please test with the master version? (we pushed 0.26 but there is an android bug that's fixed in master) Thanks

**Comment by rborn** [comment]
closing because https://github.com/react-native-community/react-native-maps/releases/tag/v0.26.1  🎉
