### ISSUE TITLE
🔥 Implementing react-native-google-places with react-native-maps

### ISSUE THREAD

**Issue by wmonecke** [react-native-community/react-native-maps#3101]
# Bug

I am using `react-native-google-places` for searching places and `react-native-maps` for displaying the actual map.

Both libraries use native code and rely on the `Google Maps` pod. However the `react-native-google-places` library is currently relying on version 3.1.1 while maps is on 3.2 so I am getting the following error when doing `pod install`:

````
[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
  In snapshot (Podfile.lock):
    GoogleMaps (= 3.1.0, ~> 3.1.0)

  In Podfile:
    GoogleMaps

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.26.0, which depends on
      GoogleMaps (= 3.2.0)

    react-native-google-places (from `../node_modules/react-native-google-places`) was resolved to 3.1.1, which depends on
      GoogleMaps (~> 3.1.0)

Specs satisfying the `GoogleMaps, GoogleMaps (= 3.1.0, ~> 3.1.0), GoogleMaps (~> 3.1.0), GoogleMaps (= 3.2.0)` dependency were found, but they required a higher minimum deployment target.
````

Any ideas on how to resolve this conflict? I am not this experienced with pods.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 47.43 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-P | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Library version: 0.26

**Comment by rborn** [comment]
in the podfile what's the `platform :ios, ` value ?

**Comment by cormander** [comment]
I have this same issue, I resolved it by using [patch-package](https://www.npmjs.com/package/patch-package) with the following patch: https://github.com/OurVoiceUSA/HelloVoter/blob/master/mobile/patches/react-native-google-places%2B3.1.2.patch

**Comment by wmonecke** [comment]
@rborn  
In my `podfile` I have:
`platform :ios, '9.0'`

**Comment by Gustash** [comment]
I had this issue as well just now. The problem was that yarn wasn't pulling through the right version of the package. Try to remove your node_modules folder and run yarn install again

**Comment by wmonecke** [comment]
@Gustash I am not using yarn and I also already reinstalled node_modules :/

**Comment by cormander** [comment]
Make sure you remove your `Podfile.lock` before you do the `pod install`.

**Comment by Gustash** [comment]
Then try doing `pod update GoogleMaps`. If that doesn't work try `pod deintegrate`, then delete the `Podfile.lock` and do `pod install`

**Comment by Gustash** [comment]
`pod update GooglePlaces`, sorry

**Comment by wmonecke** [comment]
I am now getting a new error when I try to compile the app.
I catched this in the logs:

````
/node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapCircle.h:10:9: fatal error: 'AIRMapCoordinate.h' file not found
#import "AIRMapCoordinate.h"
````

Is this a linking problem after all? God this is making me crazy.

**Comment by cormander** [comment]
Yes. What I ended up doing to go from RN 0.59 to 0.61 was starting fresh with ‘react-native init myproject’, installing dependencies (but not linking anything) and copying in my code / merging in some is the build tweaks I’ve made over the years. I have like 50 dependencies though, is which at least 15 are native code. If you don’t have much this process may be overkill.

**Comment by gdcorrea** [comment]
I resolved this issue by editing my node_modules/react-native-google-places/react-native-google-places.podspec and updated the dependency to this:
`s.dependency 'GooglePlaces', '3.2.0'
  s.dependency 'GoogleMaps', '3.2.0'`

**Comment by dev-newton** [comment]
> Then try doing `pod update GoogleMaps`. If that doesn't work try `pod deintegrate`, then delete the `Podfile.lock` and do `pod install`

Jeeeezzzz,  after three freaking weeks, i finally fixed the issue with this. You are a life saver!

**Comment by jyotiprakash111** [comment]
<img width="934" alt="Screenshot 2024-05-09 at 8 11 59 PM" src="https://github.com/react-native-maps/react-native-maps/assets/45302047/63aac516-9298-4dda-9a92-15eac14e78a4">
Anyone has any idea , i am still facing same thing, no luck.. tried above solutions.
