### ISSUE TITLE
iOS Google map marker load via custom XIB (XIB assign to IconView)(Swift 4.p)

### ISSUE THREAD

**Issue by pradipwalghude** [react-native-community/react-native-maps#3107]
Is there any way to deque custom marker xib in swift. 

My issue is Flipping marker when more than 10 marker.

PFB Code:-
for marker in array {
                let position = CLLocationCoordinate2D(latitude: (marker.customer?.latitude! as! NSString).doubleValue, longitude: (marker.customer?.longitude as! NSString).doubleValue)
                let locationmarker = GMSMarker(position: position)
                locationmarker.position = position
                bounds = bounds.includingCoordinate(locationmarker.position)
                
                markerAnnotationView  = (Bundle.main.loadNibNamed("MarkerXibView", owner: self, options: nil)![0] as! MarkerXibView)      //UIView
       
                markerAnnotationView?.titileLabel.text = marker.customer?.name
                markerAnnotationView?.annotationView.addViewShadow()
                locationmarker.iconView = markerAnnotationView      //UIView

## Environment info iOS Swift

Describe what you expected to happen:

1.
2.

**Comment by rborn** [comment]
that seems a feature request, please update the issue following the template or I'll close it

**Comment by pradipwalghude** [comment]
How it is Feature request? Could you please share solution? @rborn

**Comment by rborn** [comment]
I don't know the solution.
You should follow the template when you start an issue. This way there are more chances for people to look at it
