### ISSUE TITLE
Build error related to gradle property supportLibVersion

### ISSUE THREAD

**Issue by Nykollas** [react-native-community/react-native-maps#3108]
# Bug
The build fails, with a error saying that the  gradle property supportLibVersion not exists.

## Environment info
```bash
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 504.76 MB / 11.60 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 3.5.2 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

React native info output:

```bash
FAILURE: Build failed with an exception.

* Where:
Build file '/home/ascencion/IFCarona/node_modules/react-native-maps/lib/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':react-native-maps'.
> Could not get unknown property 'supportLibVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

 ```

Library version: 0.26.1

**Comment by Rendfold** [comment]
Did you find any solution?

**Comment by Nykollas** [comment]
Yes,  the solution was recently added, you can see it on the link below.

https://github.com/react-native-community/react-native-maps/pull/3106/files

**Comment by Rendfold** [comment]
Oh, okay. Thank you

**Comment by pietrovismara** [comment]
> Yes, the solution was recently added, you can see it on the link below.
> 
> https://github.com/react-native-community/react-native-maps/pull/3106/files

@Nykollas Excuse me for my ignorance, but should it be enough to install the latest `react-native-maps` in order to have this fix? I'm trying with `0.26.1` and I still get the error...

**Comment by Nykollas** [comment]
Try installing directly from github :

```bash
npm install --save git+https://git@github.com/react-native-community/react-native-maps.git
``bash

**Comment by Darkiring** [comment]
> Try installing directly from github :
> 
> ```shell
> npm install --save git+https://git@github.com/react-native-community/react-native-maps.git
> ```

This work for me! Thanks

**Comment by mortezacruise** [comment]
> Try installing directly from github :
> 
> ```shell
> npm install --save git+https://git@github.com/react-native-community/react-native-maps.git
> ```

nice it's working

**Comment by pietrovismara** [comment]
@Nykollas It would be much nicer to have a proper npm release though. If we use the git repository master branch, we will end up installing any unstable code change. Any plan on an npm release?

**Comment by diogoviannaaraujo** [comment]
This is in no way a solution, please make a release with the fix

**Comment by tuandm96** [comment]
> ```shell
> npm install --save git+https://git@github.com/react-native-community/react-native-maps.git
> ```

It good for me !

**Comment by Nykollas** [comment]
Yes @pietrovismara and @diogoviannaaraujo  the proper solution is to make a updated release. I i'll work on that in soon.

**Comment by RWOverdijk** [comment]
Thanks @Nykollas :D

**Comment by airTradies** [comment]
After we used the solution proposed by Nykollas, we instead receive the error...

_Could not find method safeExtGet() for arguments [supportLibVersion, 28.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler._

We removed the line, and instead updated the root build.gradle to include the supportLibVersion line below. Keen to hear others' thoughts.

```
buildscript {
    ext {
        supportLibVersion = "28.0.0"
        buildToolsVersion = "28.0.3"
```

**Comment by mebungler** [comment]
All these solutions did not helped me. I solved by adding 
`<uses-library android:name="org.apache.http.legacy" android:required="false"/>`
original answer [here](https://stackoverflow.com/questions/50782806/android-google-maps-java-lang-noclassdeffounderror-failed-resolution-of-lorg-a)

**Comment by hamzaehsan95** [comment]
Add this in your android/build.gradle

**Comment by bashirpour** [comment]
Add `supportLibVersion = "28.0.0"` to your `ext` in `android/build.gradle`


	buildscript {
	    ext {
	        buildToolsVersion = "28.0.3"
	        minSdkVersion = 16
	        compileSdkVersion = 28
	        targetSdkVersion = 28
	        supportLibVersion = "28.0.0"  // <=== add this line
	    }

	    ...
    }

**Comment by dragma** [comment]
Thanks a lot @bashirpour, but can you tell me why we need this to work ? I am a newbie in react native.

**Comment by maddes** [comment]
Is there a recommended way to get those values? I'm guessing those version numbers will be dated soon.

**Comment by maddes** [comment]
If not told otherwise I'll follow this rule:

> Match the compile sdk version.

So:

```gradle
  compileSdkVersion = 28 // ← Will use this one
  // ...
  supportLibVersion = "28" // Mind the quotes, this one needs to be a string
```

**Comment by arwysyah** [comment]
i am just add supportLibVersion = '28.0.0' to fix that

**Comment by sumitrajneesh** [comment]
Add supportLibVersion = "28.0.0" to buildscript in android/build.gradle

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"  // <=== add this line
    }

    ...
}

**Comment by hadpro24** [comment]
> Try installing directly from github :
> 
> ```shell
> npm install --save git+https://git@github.com/react-native-community/react-native-maps.git
> ```

Thanks.
