### ISSUE TITLE
Object(...) is not a function.

### ISSUE THREAD

**Issue by MOwais** [react-native-community/react-native-maps#3113]
I am getting the following error and warning after importing MapView from 'react-native-maps' in a expo managed app.

ERROR: Object(...) is not a function
Warning: Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.

USAGE:
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import MapView from 'react-native-maps';

export default function App() {
  return (
    <View style={styles.container}>
        <MapView
            initialRegion={{
                 latitude: 37.78825,
                 longitude: -122.4324,
                 latitudeDelta: 0.0922,
                 longitudeDelta: 0.0421
            }}
        />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

ENV INFO:
```
 System:
      OS: Windows 10
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 6.93 GB / 15.80 GB
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
```

package.json:
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-maps": "^0.26.1",
    "react-native-web": "^0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.0.0"
  },
  "private": true
}

```

**Comment by otispoly** [comment]
I am experiencing the same. Why did you close the issue? Did you solve?

**Comment by MOwais** [comment]
> I am experiencing the same. Why did you close the issue? Did you solve?

I was getting this error when running the app on the browser emulator.... The error went away when I switched to an actual device or AS emulator.

**Comment by James-revans** [comment]
Has anyone gotten around this error for web? Like @MOwais said it works fine on an actual device, but I would like to have it available for web if it's possible

**Comment by webface** [comment]
Im having the same issue for web

**Comment by harshmaisheri** [comment]
Did anyone found the solution? Facing the same issue

**Comment by harshmaisheri** [comment]
Facing the same issue. Guess native-maps does not support web.

**Comment by taj567** [comment]
./node_modules/react-native-fbsdk/lib/module/FBLoginButton.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.

am facing this issue after converting react-native to react-native-web.
