### ISSUE TITLE
blank map on Android

### ISSUE THREAD

**Issue by MOwais** [react-native-community/react-native-maps#3117]
I am getting a blank map with just the Google logo on Android emulator. I have enabled my API key and it is valid.

ENV INFO:
```
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 4.78 GB / 15.80 GB
  Binaries:
    Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

package.json:

```
{
  "name": "reactNativeMaps",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-maps": "^0.26.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Usage:

```
import React, { Component } from 'react';
import { Dimensions, StyleSheet, View } from 'react-native';

import MapView from 'react-native-maps';


export default class App extends Component {
    render(){
        return(
           <View style={styles.container}>
                <MapView 
                    style={styles.map}
                    initialRegion={{
                        latitude: 37.78825,
                        longitude: -122.4324,
                        latitudeDelta: 0.0922,
                        longitudeDelta: 0.0421
                    }}
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'flex-end',
      alignItems: 'center'
    },
    map: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0
    }
  });
```

Here are the relevant prints from logcat related to Google Maps Android API.... is it the mismatch in client vs package versions causing the issue? 

LOGCAT:

10-08 13:04:19.612  3756  3756 I Google Maps Android API: Google Play services client version: 11910000
10-08 13:04:19.628  3756  3756 I Google Maps Android API: Google Play services package version: 16089022

SHOT:

![googlemaps android emu](https://user-images.githubusercontent.com/7787941/66429085-47a09680-e9e5-11e9-8329-a61f2c86d321.png)

**Comment by Fghurayri** [comment]
I had a similar issue to yours. 

To ensure your API Key is valid, try to install & run the app on a physical Android device. If the issue disappears, then it is the emulator issue (even if it is was working before on the same emulator - like my case)

Potential solutions to the emulator:
* Ensure you enable Google Play services https://github.com/react-native-community/react-native-maps/issues/2778#issuecomment-486387049
* Cold boot
* Normal boot
* Wipe emulator's data
* Delete and re-create the emulator again

**Comment by MOwais** [comment]
Thanks but the potential emulator solutions did not work. My emulator was missing the Play Store so I created a new device with Play Store installed by default but still no luck.

Going to try installing on a physical device now.

**Comment by rborn** [comment]
This is an API key issues. The map itself works because the logo is there

**Comment by MOwais** [comment]
> This is an API key issues. The map itself works because the logo is there

So what is the issue?

I see traffic metrics for this API key in Google console... what other ways can I validate the key?

**Comment by rizwanatta** [comment]
@MOwais  

- I would say specifying the API key with google project
- attaching it with your **android app package name** along **adding SSH Key for it!** on the console of google

   In short making it bind with the single app of yours might help! try that!

**Comment by MOwais** [comment]
> @MOwais
> 
> * I would say specifying the API key with google project
> * attaching it with your **android app package name** along **adding SSH Key for it!** on the console of google
>   In short making it bind with the single app of yours might help! try that!

Didnt quite get you... how/where do I specify the API key with Google project and attach it with my Android package name? 

Can you please leave an example.

**Comment by LuizFBrisighello** [comment]
I'm facing the same issue here but with a physical device.
I generated my API key following [Google Documentation](https://developers.google.com/maps/documentation/android-sdk/get-api-key), this repo's doc recommendation.

> > @MOwais
> > 
> > * I would say specifying the API key with google project
> > * attaching it with your **android app package name** along **adding SSH Key for it!** on the console of google
> >   In short making it bind with the single app of yours might help! try that!
> 
> Didnt quite get you... how/where do I specify the API key with Google project and attach it with my Android package name?
> 
> Can you please leave an example.

I think he's refering to Google Cloud Platform key restriction, I did that but with no luck and the blank map persists, I encorage you to do the same hoping for a different outcome.

**Comment by LuizFBrisighello** [comment]
I just enabled [Google Maps SDK Android](https://console.developers.google.com/apis/library/maps-android-backend.googleapis.com?project=aqui-card-maps&folder&organizationId) for my project and for a couple minutes the map was still blank, but now its working..

@MOwais make sure to enable that!

**Comment by MOwais** [comment]
> I'm facing the same issue here but with a physical device.
> I generated my API key following [Google Documentation](https://developers.google.com/maps/documentation/android-sdk/get-api-key), this repo's doc recommendation.
> 
> > > @MOwais
> > > 
> > > * I would say specifying the API key with google project
> > > * attaching it with your **android app package name** along **adding SSH Key for it!** on the console of google
> > >   In short making it bind with the single app of yours might help! try that!
> > 
> > 
> > Didnt quite get you... how/where do I specify the API key with Google project and attach it with my Android package name?
> > Can you please leave an example.
> 
> I think he's refering to Google Cloud Platform key restriction (as shown [here](https://developers.google.com/maps/documentation/android-sdk/get-api-key#restrict_key)), I did that but with no luck and the blank map persists, I encorage you to do the same hoping for a different outcome.

no restrictions were ever applied. API key has been enabled for almost a week now.

Stumped.

**Comment by MOwais** [comment]
I generated an app using expo (instead of react-native cli) and used the same API key and the map now loads....

Issue is now resolved, although I'm still not sure what the cause was.

**Comment by jadonhansen** [comment]
Hi @MOwais ,
I had exactly the same issue as you, I was coming from Expo (where it worked) to the bare workflow where the maps suddenly didn't load.

I solved it by:
1.  Adding my `keystore.jks` file from Expo to the `android/app/` directory.
2.  Adding the following to my `gradle.properties` file in `android/`:
`MYAPP_UPLOAD_STORE_FILE=KEYSTORE_FILE
MYAPP_UPLOAD_KEY_ALIAS=KEY_ALIAS_FROM_EXPO
MYAPP_UPLOAD_STORE_PASSWORD=KEYSTORE_PASSWORD_FROM_EXPO
MYAPP_UPLOAD_KEY_PASSWORD=KEY_PASSWORD_FROM_EXPO`
3. And altering the following in my `build.gradle` file in `android/app/`:
`signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
}
buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
}`
4. Make sure your SHA-1 Certificate from Expo for your app has been added to your _Maps SDK for Android_ on GCP.

The reason it worked before is because Expo automatically used their generated keystore to sign you app, now you just need to manually put those credentials into the build time for the bare workflow.

After doing these steps your debug app build and your production app build will be signed with your the expo keystore. Therefore both build types are able to use the Maps SDK from Google.

**Comment by hanamurayuki** [comment]
I also face same problem. 
IOS is ok, but blank map on android with `eas build`.
Reason is google map api authorization. (logo exists, but map is brank)

Document was updated on Fri Nov 25 2022.
https://docs.expo.dev/versions/latest/sdk/map-view/

> # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> 
> 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> For development builds
> - If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> - After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> - `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`

Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, 
but we need to upload  `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials >  Application Identifiers > click your project's package name and under Android Keystore), 

After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.
