### ISSUE TITLE
How can we show route map between multiple points (3 or 4 points) in React-native maps.

### ISSUE THREAD

**Issue by ppv94** [react-native-community/react-native-maps#3127]
# Question
How can we show the route map between multiple points?
**I want to show route map between 3 or 4 points in react-native maps.**

I  referred google maps API and used 
`https://maps.googleapis.com/maps/api/directions/json?`
but I was able to show the route map between two points only. How can we show the route map by connecting three or four points in react-native maps?

**Comment by rborn** [comment]
Pretty old article but have a look here: https://pjanf.github.io/projects/2017/12/04/backend-01.html
Basically you need to decode the directions reply into coordinates pairs and use Mapview.Polyline to show the result on the map

**Comment by bargald** [comment]
You can use the polyline component

**Comment by ppv94** [comment]
@rborn if we use polyline we are getting straight lines, route map was not accurate or correct, what should we do to get accurate route between multiple points.

**Comment by rborn** [comment]
@ppv94 it means the route is not correct I guess ?

**Comment by ppv94** [comment]
@rborn yes it just draws the straight lines. How can we get accurate route?

**Comment by bramus** [comment]
This is handled by the https://github.com/bramus/react-native-maps-directions library. Set the option `precision=high`.

This issue can be closed, as it was duplicated by https://github.com/bramus/react-native-maps-directions/issues/108 which is already resolved.
