### ISSUE TITLE
Touchable markers not very responsive using google maps

### ISSUE THREAD

**Issue by pererasys** [react-native-community/react-native-maps#3133]
I'm using touchable map markers to render a popup that changes when a user touches a different marker, and I quickly realized that the response time was really slow when using the google maps provider. I'm not sure what's causing the issue but its really snappy when using built in apple maps so its not an issue with my code. My thought is that it has something to do with the way google handles gestures, but again, I can't be certain. I really like the custom styles I'm able to achieve with google, as well as the uniformity between ios and android, but if I can't find a fix I might look into implementing Mapbox. I'm just wondering if anyone has experienced something similar and has found a fix, thanks.

**Comment by michaelhayman** [comment]
I too noticed this when tapping a map marker... it's definitely slower than other actions in my app, e.g. doing the same action from a flat list.

Is it because of the built-in delay on mobile sites (which is overcome by fast click)?

**Comment by pererasys** [comment]
I think I hit it on the head with my assumption about how google's sdk handle's gestures, if you download the google maps mobile app it has the same issue. Don't think there's a workaround so im closing this
