### ISSUE TITLE
Invariant Violation: requireNativeComponent: "AIRMapHeatmap" was not found in the UIManager

### ISSUE THREAD

**Issue by mmacartney10** [react-native-community/react-native-maps#3139]
Hi

I have been having an issue with the Heatmaps on react-native-maps. I am getting the following error when I try and create a Heatmap:

<img width="319" alt="Screenshot 2019-10-17 at 17 02 37" src="https://user-images.githubusercontent.com/9461919/67027675-e160f580-f101-11e9-9079-34db2695b789.png">

My component code is below as well:

```import React, { useContext } from "react";
import { View } from 'react-native';
import Context from '../../../services/context-service';
import MapView from 'react-native-maps';
import styles from './Map.styles.js';

export default function Map(props) {

  const { region } = useContext(Context);

  const heatmapPoints = [
    {
      latitude: 53.3449,
      longitude: -6.1675,
      weight: 1
    },
    {
      latitude: 53.3749,
      longitude: -6.2675,
      weight: 1
    },
    {
      latitude: 53.3149,
      longitude: -6.2375,
      weight: 1
    },
    {
      latitude: 53.3449,
      longitude: -6.2775,
      weight: 1
    },
    {
      latitude: 53.3449,
      longitude: -6.2475,
      weight: 1
    }
  ];

  return (
    <View style={styles.container}>
      <MapView style={styles.map} region={region}>

        <MapView.Heatmap
          points={heatmapPoints}
          radius={20}
          opacity={0.7}
          gradient={{
            colors: ["#79BC6A", "#BBCF4C", "#EEC20B", "#F29305", "#E50000"],
            startPoints: [0, 0.25, 0.50, 0.75, 1]
          }}
        />

      </MapView>
    </View>
  );
}
```
I think it might have something to do with expo as the module it is trying to load is a native module that expo doesn't give access to. But I could be wrong.

`const AIRMapHeatmap = this.getAirComponent();`

Any ideas on what the issue could be?

#versions

expo: 35.0.0
react-native-maps 0.26.1

**Comment by christopherdro** [comment]
Expo uses this library as a dependency. v35.0 of Expo uses Maps 0.25.0 which doesn't include the HeatMap changes

**Comment by dennisbrandenburg** [comment]
I'm getting the same issue with Expo v36.0.0. and react-native-maps 0.26.1. My package.json looks like this:

  "dependencies": {
    "axios": "0.18.0",
    "expo": "^36.0.0",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-chart-kit": "^4.1.0",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-maps": "0.26.1",
    "react-native-paper": "^3.3.0",
    "react-native-svg": "^9.13.3",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-material-bottom-tabs": "^2.1.5"
  }

Am I missing anything?

**Comment by castalonirenz** [comment]
any fixes on this one?

**Comment by Nitingadhiya** [comment]
I've face same error when i use default map in iOS. it's working fine for google maps.

**Comment by castalonirenz** [comment]
fixed this for heatmap. the provider must be the same with MapView and HeatMap

**Comment by seyaobey** [comment]
@castalonirenz Please could you elaborate further on your solution? I'm facing the same problem. What do you mean "the provider must be the same with MapView and HeatMap?.
Here is a snippet of my code:

```
<MapView style={styles.mapStyle}>
     <Heatmap points={Points} />
</MapView>
```
Thanks

**Comment by SJImobility** [comment]
> fixed this for heatmap. the provider must be the same with MapView and HeatMap

can you explain more eon this

**Comment by SJImobility** [comment]
> 
> 
> fixed this for heatmap. the provider must be the same with MapView and HeatMap

`Invariant Violation: requireNativeComponent: "AIRMapHeatmap" was not found in the UIManager.This error is located at:
    in AIRMapHeatmap (at MapHeatmap.js:79)
    in MapHeatmap (at MapScreen.js:119)
    in AIRMap (at MapView.js:993)
    in MapView (at MapScreen.js:87)
    in RCTView (at MapScreen.js:86)
    in MapScreen (created by ConnectFunction)
    in ConnectFunction (created by SceneView)
    in SceneView (created by TabNavigationView)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at src/index.native.tsx:120)
    in Screen (created by ResourceSavingScene)
    in ResourceSavingScene (created by TabNavigationView)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (created by TabNavigationView)
    in RCTView (created by TabNavigationView)
    in TabNavigationView (created by NavigationView)
    in NavigationView (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by ForwardRef(CardSheet))
    in ForwardRef(CardSheet) (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by Card)
    in RCTView (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at src/index.native.tsx:120)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack (created by Context.Consumer)
    in KeyboardManager (created by Context.Consumer)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by StackView)
    in StackView (created by StackView)
    in StackView
    in Unknown (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by CardContainer)
    in RCTView (created by ForwardRef(CardSheet))
    in ForwardRef(CardSheet) (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by Card)
    in RCTView (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen (at createAnimatedComponent.js:151)
    in AnimatedComponent (at src/index.native.tsx:120)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack (created by Context.Consumer)
    in KeyboardManager (created by Context.Consumer)
    in RNCSafeAreaView (at src/index.tsx:28)
    in SafeAreaProvider (created by Context.Consumer)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by StackView)
    in StackView (created by StackView)
    in StackView
    in Unknown (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (at src/index.tsx:78)
    in RCTView (at Transitioning.js:138)
    in Wrapped (at src/index.tsx:73)
    in AnimatedSwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.js:19)
    in Provider (at App.js:18)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)getNativeComponentAttributes
    getNativeComponentAttributes.js:30:4
exports.get
    ReactNativeViewConfigRegistry.js:102:25
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0`

Any help would be appriciated
