### ISSUE TITLE
Marker title not visible iOS version >= 13

### ISSUE THREAD

**Issue by ChaeWonKong** [react-native-community/react-native-maps#3140]
# Bug
In iOS version above 13.x.x,
title prop in Marker is not visible.
description prop works fine, only title prop not visible.

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 70.70 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
```

Library version: 0.26.1

## Steps To Reproduce

1. provide title with any kind of string to Marker
2. Build iOS app using .xcworkspace 

Describe what you expected to happen:

1. Marker info window showing title in black text color.

## Reproducible sample code

```react
<MapView>
<Marker
          ref={ref => {
            this.marker = ref;
          }}
          coordinate={{
            latitude: targetY,
            longitude: targetX
          }}
          title={stationName}
          description={stationName}
        ></Marker>
</MapView>
```

**Comment by itsam** [comment]
Any workarounds on this?

**Comment by itsam** [comment]
Well, it seems that is happening ONLY when dark mode is enabled... Actually it makes the title white...

**Comment by ChaeWonKong** [comment]
I solved this problem by adding <Callout /> manually if `platform.os === 'ios`

`<Marker
                pinColor="red"
                ref={ref => {
                  this.marker = ref;
                }}
                coordinate={{
                  latitude: pointY,
                  longitude: pointX
                }}
                title={title}
                description={description}
              >
                {Platform.OS === "ios" ? (
                  <Callout
                    tooltip={true}
                    style={styles.callout}
                  >
                    <Text style={styles.title}>
											{title}
                    </Text>
                    <Text style={styles.description}>
                      {description}
                    </Text>
                  </Callout>
                ): null }
</Marker>`

**Comment by itsam** [comment]
@ChaeWonKong Thank you. Could you please share you "styles" as well?

**Comment by ChaeWonKong** [comment]
> @ChaeWonKong Thank you. Could you please share you "styles" as well?

Sure!

```jsx
import { fonts } from "../Styles/_mixin";


const styles = StyleSheet.create({
callout: {
                  backgroundColor: "white",
                  borderRadius: 4,
                  alignItems: "center",
                  justifyContent: "center",
                  padding: 4
                },
title: {
                    color: "black",
                    fontSize: 14,
                    lineHeight: 18,
                    flex: 1,
                    fontFamily: fonts.spoqaHanSansRegular
                  },
description: {
                    color: "#707070",
                    fontSize: 12,
                    lineHeight: 16,
                    flex: 1,
                    fontFamily: fonts.spoqaHanSansRegular
                  }
})

**Comment by itsam** [comment]
@ChaeWonKong Thank you :)

**Comment by PaitoAnderson** [comment]
Another workaround... you could use [patch-package](https://github.com/ds300/patch-package) to bump GoogleMaps to 3.5.0.

**`patches/react-native-maps+0.26.1.patch`**
```
diff --git a/node_modules/react-native-maps/react-native-google-maps.podspec b/node_modules/react-native-maps/react-native-google-maps.podspec
index 14417b4..e439e63 100644
--- a/node_modules/react-native-maps/react-native-google-maps.podspec
+++ b/node_modules/react-native-maps/react-native-google-maps.podspec
@@ -17,6 +17,6 @@ Pod::Spec.new do |s|
   s.compiler_flags = '-DHAVE_GOOGLE_MAPS=1', '-DHAVE_GOOGLE_MAPS_UTILS=1', '-fno-modules'
 
   s.dependency 'React'
-  s.dependency 'GoogleMaps', '3.2.0'
+  s.dependency 'GoogleMaps', '3.5.0'
   s.dependency 'Google-Maps-iOS-Utils', '2.1.0'
 end
```

Run `pod update` after as well
