### ISSUE TITLE
How to show accurate route map in react-native-maps with google apis

### ISSUE THREAD

**Issue by ppv94** [react-native-community/react-native-maps#3144]
# Question
I am using 
`https://maps.googleapis.com/maps/api/directions/json?
origin=Adelaide,SA&destination=Adelaide,SA
&waypoints=optimize:true|Barossa+Valley,SA|Clare,SA|Connawarra,SA|McLaren+Vale,SA
&key=YOUR_API_KEY`
to draw the route map between different points in react-native-maps.it works fine, **I used polyline to display route**, the route map is displayed but it gives straight lines instead of a detailed route map as shown in the image. 

how can draw the accurate route map using googleapis .
![Simulator Screen Shot - iPhone 6 - 2019-10-21 at 15 27 03](https://user-images.githubusercontent.com/28724702/67195812-4759bf80-f417-11e9-9217-50973fe02e40.png)

**Also tried**`react-native-maps-directions`**but if I want to get route map for more than 10 waypoints my app crashes**
you can refer this link https://github.com/bramus/react-native-maps-directions/issues/110

**Comment by christopherdro** [comment]
You can try and use googles snap to roads API https://developers.google.com/maps/documentation/roads/snap
