### ISSUE TITLE
Android Overlay must be a bitmap

### ISSUE THREAD

**Issue by hefejeff** [react-native-community/react-native-maps#3156]
I am building an ios/android app with Expo that includes a map with overlay images.  It runs perfectly on ios but I get an error on android devices that reads.

failed to decode image. the provided image must be a bitmap

`<MapView.Overlay
        bounds={this.state.overlay1.bounds}
	image={{uri: this.state.overlay1.image}}
	zindex={2} />`

Here is an example image.  Any help would be greatly appreciated.

![A20192912019295a_SST](https://user-images.githubusercontent.com/9152006/67622649-64a4da00-f7d9-11e9-951f-150be718e544.png)

**Comment by rborn** [comment]
@hefejeff please update your issue following the template or I'll close it

**Comment by hefejeff** [comment]
I figured it out.

**Comment by jimbevington** [comment]
@hefejeff how did you do it?
