### ISSUE TITLE
App crash on Android with custom image Marker

### ISSUE THREAD

**Issue by boreales** [react-native-community/react-native-maps#3158]
# Bug

Error while updating property 'image' of a view managed by: AIRMapMarker

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 130.54 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 26.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.11.0 => 16.11.0 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-vector-icons: 6.6.0
```

Library version: 0.26.1

## Steps To Reproduce

I have the following code to use a custom image on the Markers : 
`                  
                  <Marker
                    key={marker.id}
                    coordinate={{latitude: parseFloat(marker.lat), longitude: parseFloat(marker.lng)}}
                    title={marker.name}
                    description={marker.description}
                    image={require('../../assets/logo-marker.png')}
                    onCalloutPress={() => this.details(marker.id, marker.cover)}
                  />
`
It works fine on iOS but keeps crashing on Android.

**Comment by boreales** [comment]
Solved with this code : 

`<Marker 
  key={marker.id} 
  coordinate={{latitude: parseFloat(marker.lat), longitude: 
  parseFloat(marker.lng)}} 
  title={marker.name} 
  description={marker.description} 
  onCalloutPress={() => this.details(marker.id, marker.cover)} />

   <Image source={require('../../assets/logo-marker.png')} style={{height: 35, width:35 }} />

</Marker>`

**Comment by Kolyunya** [comment]
@boreales didn't dive in deep enough yet, but your solution makes the map 5x less responsive for me. Are there any tricks to fix this problem?

P.S. Created a separate [issue](https://github.com/react-native-maps/react-native-maps/issues/3664) for the original bug with a complete test application.
