### ISSUE TITLE
react-native run-android build error

### ISSUE THREAD

**Issue by Alicoo1907** [react-native-community/react-native-maps#3166]
C:\reactnative\CabApp>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1310 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...
<-------------> 0% WAITING                                                                                                                                              > IDLE                                                                                                                                                                  
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\reactnative\CabApp\node_modules\react-native-maps\lib\android\build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':react-native-maps'.
> No signature of method: java.lang.Integer.split() is applicable for argument types: (String) values: [\.]
  Possible solutions: split(groovy.lang.Closure), plus(java.lang.String), wait(), wait(long), print(java.lang.Object), plus(java.lang.Number)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\reactnative\CabApp\node_modules\react-native-maps\lib\android\build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':react-native-maps'.
> No signature of method: java.lang.Integer.split() is applicable for argument types: (String) values: [\.]
  Possible solutions: split(groovy.lang.Closure), plus(java.lang.String), wait(), wait(long), print(java.lang.Object), plus(java.lang.Number)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 5s

    at checkExecSyncError (child_process.js:622:11)
    at execFileSync (child_process.js:640:13)
    at runOnAllDevices (C:\reactnative\CabApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (C:\reactnative\CabApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at then.result (C:\reactnative\CabApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**I found the question here. but no one proposed a solution**
https://stackoverflow.com/questions/57906385/getting-error-no-signature-of-method-java-lang-integer-call-is-applicable-fo

**Comment by Guepardo** [comment]
This is because supportLibVersion, on build.gradle, needs to be a String. Change the value for something like this '20.0.0'

**Comment by eggsys** [comment]
Did you found how the solution yet ?
try follow @Guepardo #comment 

I've had this problem once and i try to random way the solve this problem ?

1. cd android
2. gradlew clean 

maybe this could help you

**Comment by Alicoo1907** [comment]
I deleted the project. I created a new project. I couldn't find another solution.

**Comment by eggsys** [comment]
> I deleted the project. I created a new project. I couldn't find another solution.
@Alicoo1907 

did you try remove node_module ? 
as i remember i got many Error after error so i try to follow  [this](https://stackoverflow.com/questions/58421179/react-native-build-failed-native-modules-gradle-line-182#new-answer)

**Comment by Alicoo1907** [comment]
I didn't try.I was able to add react native map in my new project.Should I close Issue?

**Comment by eggsys** [comment]
@Alicoo1907 I'm not sure this is first issue i do the reply. 
maybe someone who got the same problem to you will come here to find the solution and end up with delete the project that isn't best way we all know but anyway their is our answers  .

**Comment by XeeshanAnsari** [comment]
Please provide supportLibVersion value as string instead of the number.
        supportLibVersion= '28.0.0'
instead of
        supportLibVersion= 28

**Comment by rborn** [comment]
Closing, missing template and it also seems to be resolved.
