### ISSUE TITLE
Flatlist with maps

### ISSUE THREAD

**Issue by viniciusvelasco** [react-native-community/react-native-maps#3174]
# Question

Hello, I have a local database (RealmDB) that returns me 30 records and they all have value in the latitudeCenter and longitudeCenter properties. I try using a FlatList to render these 30 maps but I have an error that while updating initialRegion properties the longitude would be null. What am I doing wrong? Can you help me?
Below the error and [gist ](https://gist.github.com/viniciusvelasco/852bf765c50e4977eb8ee56585e5ce35.js")

![Screenshot_20191104-232529](https://user-images.githubusercontent.com/2370740/68176389-0a371680-ff5b-11e9-8d6f-04089b0eeef8.png)

**Comment by christopherdro** [comment]
Does the user need to interact with the map?

You’ll probably get better performance by using this https://developers.google.com/maps/documentation/maps-static/intro

**Comment by viniciusvelasco** [comment]
Hello @christopherdro , the app stays mostly offline. On other pages I will have interaction with the map. Thanks for answering

**Comment by viniciusvelasco** [comment]
Closing the issue. The one responsible for the error is the Realm. Unfortunately the Realm provides an object with proxies and have not yet been able to implement a solution to return a plain text object. I will look for another mobile database.

**Comment by fukemy** [comment]
static map required price, while mapView api is free
