### ISSUE TITLE
Can't get MapView to load - Invariant Violation: Element type is invalid: Expected a string but got undefined

### ISSUE THREAD

**Issue by Kathryn-Hackman** [react-native-community/react-native-maps#3193]
# Bug

<img width="296" alt="Screen Shot 2019-11-19 at 1 38 11 PM" src="https://user-images.githubusercontent.com/34175557/69175566-f995ad00-0ad1-11ea-82b9-d3f37bba1b7d.png">

Installed using cocoa pods, I also tried linking.

## Environment info

React native info output:

```bash

System:
    OS: macOS Mojave 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 82.32 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.26.1

## Reproducible sample code

<img width="800" alt="Screen Shot 2019-11-19 at 1 42 20 PM" src="https://user-images.githubusercontent.com/34175557/69175789-6f017d80-0ad2-11ea-9bb3-19fb243e237e.png">

I'm just trying to get the example code up and running. Any help is appreciated!

**Comment by mhendrick98** [comment]
Same issue!

**Comment by jonahoffline** [comment]
@Kathryn-Hackman @mhendrick98 Just remove the curly braces around `MapView` from the import statement.

```js
  import MapView from 'react-native-maps';
```

**Comment by Kathryn-Hackman** [comment]
Got it to work. Thank you!

**Comment by rellaElla** [comment]
I'm seeing this issue in version 1.2.0 along with react-native version 0.69.4
