### ISSUE TITLE
Android shows blank screen

### ISSUE THREAD

**Issue by ChakkiPower** [react-native-community/react-native-maps#3194]
I don't know what is wrong with maps on android. IOS works properly but on android maps show only blank screen with google logo. I configured my API key in google console, enabled Maps SDK for Android, added SHA 1 fingerprint with applicationId and i thought its might work, but it's not. I tested it on emulator and real device but on both blank screen. It's work fine when I'm using react-native 0.59 version but on 0.61 it's not. 
Can someone help me?
My code.

```
{
  "name": "mapsTestV2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-maps": "0.26.1"
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/runtime": "^7.7.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.6.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

App.js
```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import MapView from 'react-native-maps';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <MapView
          style={styles.map}
          initialRegion={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  map: {
    flex: 1
  }
});
```
build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "17.0.0"
        androidMapsUtilsVersion = "0.6.2"

    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

```

AndroidManifest

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.mapstestv2">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="AIzaSyBvr16cagMhwbyy2y7ovG**********"/>
    </application>

</manifest>

```

**Comment by Archulan** [comment]
> I don't know what is wrong with maps on android. IOS works properly but on android maps show only blank screen with google logo. I configured my API key in google console, enabled Maps SDK for Android, added SHA 1 fingerprint with applicationId and i thought its might work, but it's not. I tested it on emulator and real device but on both blank screen. It's work fine when I'm using react-native 0.59 version but on 0.61 it's not.
> Can someone help me?
> My code.
> 
> ```
> {
>   "name": "mapsTestV2",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "android": "react-native run-android",
>     "ios": "react-native run-ios",
>     "start": "react-native start",
>     "test": "jest",
>     "lint": "eslint ."
>   },
>   "dependencies": {
>     "react": "16.9.0",
>     "react-native": "0.61.2",
>     "react-native-maps": "0.26.1"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.7.2",
>     "@babel/runtime": "^7.7.2",
>     "@react-native-community/eslint-config": "^0.0.5",
>     "babel-jest": "^24.9.0",
>     "eslint": "^6.6.0",
>     "jest": "^24.9.0",
>     "metro-react-native-babel-preset": "^0.57.0",
>     "react-test-renderer": "16.9.0"
>   },
>   "jest": {
>     "preset": "react-native"
>   }
> }
> ```
> 
> App.js
> 
> ```
> import React, { Component } from 'react';
> import { StyleSheet, View } from 'react-native';
> import MapView from 'react-native-maps';
> 
> export default class App extends Component {
>   render() {
>     return (
>       <View style={styles.container}>
>         <MapView
>           style={styles.map}
>           initialRegion={{
>             latitude: 37.78825,
>             longitude: -122.4324,
>             latitudeDelta: 0.0922,
>             longitudeDelta: 0.0421,
>           }}
>         />
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1
>   },
>   map: {
>     flex: 1
>   }
> });
> ```
> 
> build.gradle
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
>         googlePlayServicesVersion = "17.0.0"
>         androidMapsUtilsVersion = "0.6.2"
> 
>     }
>     repositories {
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.4.2")
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
>         google()
>         jcenter()
>         maven { url 'https://jitpack.io' }
>     }
> }
> ```
> 
> AndroidManifest
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>   package="com.mapstestv2">
> 
>     <uses-permission android:name="android.permission.INTERNET" />
> 
>     <application
>       android:name=".MainApplication"
>       android:label="@string/app_name"
>       android:icon="@mipmap/ic_launcher"
>       android:roundIcon="@mipmap/ic_launcher_round"
>       android:allowBackup="false"
>       android:theme="@style/AppTheme">
>       <activity
>         android:name=".MainActivity"
>         android:label="@string/app_name"
>         android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
>         android:windowSoftInputMode="adjustResize">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>       </activity>
>       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
>       <meta-data
>         android:name="com.google.android.geo.API_KEY"
>         android:value="AIzaSyBvr16cagMhwbyy2y7ovG**********"/>
>     </application>
> 
> </manifest>
> ```

Installation steps differs for (React Native 0.59 and lower versions) and (React Native 0.60 and higher). Which steps you followed on the installation of react-native-maps?

**Comment by ChakkiPower** [comment]
@Archulan For 0.59 i followed steps for 0.59 version and same for 0.61 i followed 0.61 steps. I think if i did not install them correctly, they would not work totally. But they work and only shows blank screnn, IOS works fine.

**Comment by ChakkiPower** [comment]
Okay i fixed by enabling JS maps API and added token with android SDK able.

**Comment by qduld** [comment]
> Okay i fixed it by enabling JS maps API and added token with android SDK able.

I have the same issue.Can you tell me what your options ?Tanks

**Comment by conor909** [comment]
@ChakkiPower can you elaborate on the steps you took.  What do you mean by 

> token with android SDK able
