### ISSUE TITLE
How to change GoogleMap marker pin and dot color using react native

### ISSUE THREAD

**Issue by pramodjb** [react-native-community/react-native-maps#3197]
Hi, @rborn @bendman and others please help me,
Capture

hi all, How can change dot color using react native, dot color in the sense - inside marker pin one of the dot is there.i'm talking about that. please refer the screen shot,
![Capture]
(https://user-images.githubusercontent.com/13535859/69316588-2aefb380-0c5f-11ea-9ef9-b1708951ad45.PNG)

**Comment by rborn** [comment]
I think you need to use a custom marker the default markers don't have this feature

Closing the issue for not respecting the template

**Comment by pramodjb** [comment]
Hi rborn thank you so much for you reply. I done custom marker. :)
