### ISSUE TITLE
Map Marker snapping to road on Android

### ISSUE THREAD

**Issue by alexandrelt44** [react-native-community/react-native-maps#3199]
Hi, I have been trying to get the exact coordinates for my users on the beach.

Thing is, whenever I get away from the road, the map marker keeps snapped to it on Android only. In iOS I can get the marker and the device at the same location, but on Android the device starts getting further and further from the marker. 

Is there any special setting that I need to use on Android to "unsnap"  the marker from a known road or address?

**Comment by rborn** [comment]
No issue template, closing
