### ISSUE TITLE
followsUserLocation doesn't seem to be supported for Google Maps, but this is not mentioned in the docs

### ISSUE THREAD

**Issue by markymc** [react-native-community/react-native-maps#3206]
# Bug

I've been trying to get `followsUserLocation` working when using Google Maps with the following code:

```
  const [followUserLocation, setFollowUserLocation] = useState(true);

  return(
      <MapView
        ref={mapRef}
        style={styles.container}
        provider={PROVIDER_GOOGLE}
        initialRegion={currentRegion}
        onRegionChange={setCurrentRegion}
        showsUserLocation
        showsMyLocationButton
        followsUserLocation={followUserLocation}/>
  )
```

However it wasn't working. I looked into the source and it seems that AIRGoogleMap doesn't support this prop? If so, it's not mentioned in https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md. 

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 462.96 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v10.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 19, 20, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 22.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 0.26.1

## Steps To Reproduce

See code above.

Describe what you expected to happen:

1. The user's location will be followed.

## Reproducible sample code

See code above.

**Comment by RealDyllon** [comment]
followsUserLocation only works with Apple Maps on iOS. More info: https://github.com/react-native-community/react-native-maps/issues/1937

**Comment by markymc** [comment]
But unless I'm mistaken this isn't mentioned in the docs, right?

**Comment by RealDyllon** [comment]
The "only for iOS" part is in the docs: https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md

the excerpt in question: 

> followsUserLocation | _Boolean_ | _false_ | If true the map will focus on the user's location. This only works if showsUserLocation is true and the user has shared their location. Note: **iOS only.**
> -- | -- | -- | --

**Comment by RealDyllon** [comment]
I know this because I want to get the same behavior on android. Do let me know if you find a way to do so.

What I'm doing now is pooling the geolocation of the device and plugging it in to the region prop of the mapview, which makes for some pretty choppy animation.

**Comment by markymc** [comment]
> The "only for iOS" part is in the docs

Yes I saw that. The problem is that it's misleading (as far as I can see) as it doesn't mention that it's also not supported in Google maps.

Good luck with the Android part! I've not had to look at that yet as it turns out we won't be following the user location in our project. If you're able to get down to the native layer you may find a solution.

**Comment by richardbumm** [comment]
Your best best is to use the watchPosition function of the navigator and change the region of the map in the success callback function to where the user is

**Comment by markymc** [comment]
Just to be clear, I opened this issue as the docs need to be updated. I don't need help with overcoming an issue.

**Comment by rborn** [comment]
@markymc would you fancy a  PR  ? 😻

**Comment by markymc** [comment]
@rborn Thanks for the very quick merge!!!
