### ISSUE TITLE
How to detect if two circle radius overlapped?

### ISSUE THREAD

**Issue by rosnaib11** [react-native-community/react-native-maps#3208]
I have a Geofence setup and I have to handle how to detect if two radius are overlapped to each other.

**Comment by richardbumm** [comment]
Try this out:

1. Get the center of each circle
2. Find the distance between the two centers
3. Add up the radius of each circle
4. If the sum of the radius of both circles is >= the distance between the two centers, then they intersect.

**Comment by rosnaib11** [comment]
I saw this comment on stackoverflow question its like a basic math but it works as alternative. Can't find the link but I have the example below.

> distance between center 1 and center 2 < radius around center 1 + radius around center 2
