### ISSUE TITLE
Change custom marker position.

### ISSUE THREAD

**Issue by Anytram** [react-native-community/react-native-maps#3211]
Hello,
I'm trying to add my custom image as Marker on MapView. I want set this Marker coordinates to my localization.
My problem is that I can't center the marker on point, it is placed above actual localization. 
There is my code:
![Zrzut ekranu 2019-12-5 o 16 48 42](https://user-images.githubusercontent.com/37418524/70251012-193dfe00-177f-11ea-8b20-a9e3acb3f80d.png)

Here is the result:
![Zrzut ekranu 2019-12-5 o 16 55 32](https://user-images.githubusercontent.com/37418524/70251571-0ed03400-1780-11ea-935d-b3e8e681779c.png)

I tried to set centerOffset, but it didn't solve the problem.

**Comment by ezranbayantemur** [comment]
@Anytram did you find the solution?
