### ISSUE TITLE
UrlTile template

### ISSUE THREAD

**Issue by torchsmith** [react-native-community/react-native-maps#3213]
# Question

Hello, I have some custom tiles that I would like to overlay over a certain area on the map.

I am using UrlTile to serve the tiles from a server, and I can't figure out how to get the tiles to show up.

I have them set up in https://.../{z}/{x}/{y}.png I just don't know how to make X:0 Y:0 equal to the corner of my area.

Side note: Is there a way to prevent user from moving map (or preventing map from rendering completely) out of defined area?

If anyone could help that would be great. Have been looking for quite a few hours with no success.

**Comment by torchsmith** [comment]
Update, I figured out how tiles work.

Is there a way to offset x and y tile numbers? On file server all of my tiles are labeled from 0-xx instead of what the actual tile number is ex: 151231.

Still would like to know about limiting user's view or prevent rendering of map outside of box.

**Comment by atihungdx** [comment]
@torchsmith What are you do? I have same problem. I have tiles in local device and set UrlTile as "file://+ RNFS = require('react-native-fs') + 'titles/{z}/{x}/{y}.png but when load map it only show box.

**Comment by torchsmith** [comment]
@atihungdx if your tiles are local I'd recommend not using the UrlTile component. There is a component specifically for local tiles.

**Comment by atihungdx** [comment]
I alse use MapLocalTile with pathTemplate as "file://+ RNFS.DocumentDirectoryPath + 'titles/{z}/{x}/{y}.png but nothing show.
