### ISSUE TITLE
How to switch tile layer on map ?

### ISSUE THREAD

**Issue by hussainahmad** [react-native-community/react-native-maps#3220]
# Question

I am developing an application where I m using different map layers like open street , carto or yendex map tile layer. user can change the tile at any time like this. 

<img width="347" alt="Screen Shot 2019-12-12 at 12 07 21 PM" src="https://user-images.githubusercontent.com/5903522/70690832-594e3500-1cd9-11ea-93fe-fd89ea56b743.png">

I am unable to understand from docs how to achieve this feature in my application using this.

**Comment by stdavis** [comment]
@hussainahmad Did you resolve this issue? I'm attempting to switch `UrlTile` layers and it is not updating.
