### ISSUE TITLE
Map Navigation

### ISSUE THREAD

**Issue by teriologia** [react-native-community/react-native-maps#3229]
# Question

Hi guys, I need to build a navigation app and it will look like this

![gsmarena_002](https://user-images.githubusercontent.com/35257086/71355206-639ce880-258f-11ea-9b7f-f0baf86a3cf1.jpg)

but I don't know how to do this kind of thing 
I've markers and route like this when user press button I need to start navigation in my app

**Comment by TechGuyVN** [comment]
Hi anybody have solution, a need help this features too

**Comment by tiaanduplessis** [comment]
https://github.com/grantbriston/react-native-map-navigation should help

**Comment by TechGuyVN** [comment]
Thanks @tiaanduplessis i will try and let you know result

**Comment by ebnersilva** [comment]
@TechGuyVN did you test this library: react-native-map-navigation?

**Comment by MustaphaGhlissi** [comment]
@TechGuyVN @teriologia this pack react-native-map-navigation is useful ? does this do the job ? else any alternative solution ? 

I have same task to get done 

Thanks before

**Comment by TechGuyVN** [comment]
currently i still stuck with navigation on react-native,react-native-map-navigation no help, 
 i try to use another solution like Mapbox too, it's good but i can't add my marker on Map when Map move .
