### ISSUE TITLE
Failed resolution of: Lcom/google/android/gms/maps/model/RoundCap;

### ISSUE THREAD

**Issue by GibranPolonsky** [react-native-community/react-native-maps#3230]
# Bug

When I try to use any of the drawing tools such as Polygon  and Polyline the app closes.

## Environment info

"react-native": "0.61.5",
"react-native-maps": "0.26.1",

React native info output:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/model/RoundCap;
        at com.airbnb.android.react.maps.AirMapPolyline.<init>(AirMapPolyline.java:32)
        at com.airbnb.android.react.maps.AirMapPolylineManager.createViewInstance(AirMapPolylineManager.java:46)
        at com.airbnb.android.react.maps.AirMapPolylineManager.createViewInstance(AirMapPolylineManager.java:24)
```

## Steps To Reproduce

* Install and react-native-maps with autolink
* Use a Polyline inside of a MapView
```

<Polyline
		coordinates={[
			{ latitude: 37.8025259, longitude: -122.4351431 },
			{ latitude: 37.7896386, longitude: -122.421646 },
			{ latitude: 37.7665248, longitude: -122.4161628 },
			{ latitude: 37.7734153, longitude: -122.4577787 },
			{ latitude: 37.7948605, longitude: -122.4596065 },
			{ latitude: 37.8025259, longitude: -122.4351431 }
		]}
		strokeColor="#000" // fallback for when `strokeColors` is not supported by the map-provider
		strokeColors={[
			'#7F0000',
			'#00000000', // no color, creates a "long" gradient between the previous and next coordinate
			'#B24112',
			'#E5845C',
			'#238C23',
			'#7F0000'
		]}
		strokeWidth={6}
	/>
```

Describe what you expected to happen:

1. Show the polyline instead of crashing the app

**Comment by GibranPolonsky** [comment]
FIXED BY DELETING... 
`configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            details.useVersion('9.8.0')
        }
    }
}
`

**Comment by lopezjayhielvhon** [comment]
fixed by deleting `{
       exclude group: 'com.google.android.gms', module: 'play-services-base'
       exclude group: 'com.google.android.gms', module: 'play-services-maps'
   }` inside dependencies at android/app/build.gradle

**Comment by RafaelA977** [comment]
Not working for me.
