### ISSUE TITLE
Add `supportLibVersion = "28.0.0"` to `buildscript` in `android/build.gradle`

### ISSUE THREAD

**Issue by ashertoufeeq** [react-native-community/react-native-maps#3234]
Add `supportLibVersion = "28.0.0"` to `buildscript` in `android/build.gradle`

	buildscript {
	    ext {
	        buildToolsVersion = "28.0.3"
	        minSdkVersion = 16
	        compileSdkVersion = 28
	        targetSdkVersion = 28
	        supportLibVersion = "28.0.0"  // <=== add this line
	    }

	    ...
    }

_Originally posted by @bashirpour in https://github.com/react-native-community/react-native-maps/issues/3108#issuecomment-552795543_

**Comment by altany** [comment]
Seems to be fixed in 0.27.0
