### ISSUE TITLE
Map not appearing in RN 0.61.5 application

### ISSUE THREAD

**Issue by duarte-evocorp** [react-native-community/react-native-maps#3242]
# Bug

Map not appearing in RN 0.61.5 application

## Environment info

System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 1.07 GB / 7.60 GB
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 25, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

Library version: 0.26.1

"Expected map appears on screen"

**Comment by ezranbayantemur** [comment]
I worked on 0.61.5 too and not faced any problem. If you can see Google icon on bottom then it should be API key problem.

**Comment by duarte-evocorp** [comment]
The issue has been resolved, an API key was out of date. 
Thanks!
