### ISSUE TITLE
Fixed marker

### ISSUE THREAD

**Issue by somilmathur** [react-native-community/react-native-maps#3250]
Is there any way to make the marker fixed on one location?

I want the ability to be able to move the map but the location of marker stays fixed in the center of the screen even on dragging the map and the location of the marker gives the coordinates for region?

I have tried a lot to do it but coming up short. Any help would be greatly appreciated!

**Comment by rborn** [comment]
Would have been good if you could use the issue template we have in place.

To answer your question you can do this by adding a view on top of the map in the center of the screen that contains an image if the marker and on regionChange to find the center.
