### ISSUE TITLE
[iOS] Blank map

### ISSUE THREAD

**Issue by duarte-evocorp** [react-native-community/react-native-maps#3252]
# Bug

The map does not open in the application, with the following error: Error setting AIRGoogleMapMarker 'image' property with tag # 497: Calling bridge.imageLoader has been deprecated and will not work in newer versions of RN. Upgrade to themoduleForClass API or turboModuleLookupDelegate API.

## Environment info

System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz
    Memory: 83.67 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 24, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-25 | Google Play Intel x86 Atom
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7

React native info output:

"react-native-maps": "^0.26.1",

**Comment by VINMAIDA** [comment]
how did u solve it?
