### ISSUE TITLE
RCTConvert+GMSMapViewType.h: 'GoogleMaps/GoogleMaps.h' file not found

### ISSUE THREAD

**Issue by lchenfox** [react-native-community/react-native-maps#3253]
# Question

### package.json

```
{
  "name": "AndroidGoogleMaps",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "postinstall": "./node_modules/react-native-maps/enable-google-maps ./ios/**",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-maps": "^0.25.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.3",
    "@babel/runtime": "^7.8.3",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.4",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

When I tried to manually installed `react-native-maps` on iOS following the official installation docs, I got the build error in file `RCTConvert+CMSMapViewType.h`:  

```
'GoogleMaps/GoogleMaps.h' file not found
```

I'm sure I already integrated the map SDK for iOS. when I added the following content into `package.json`:

```
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "postinstall": "./node_modules/react-native-maps/enable-google-maps ./ios/**",
    "test": "jest"
  },
```

then run `npm install`, showing that installation was successful as follows:

```
➜  AndroidGoogleMaps npm install

> AndroidGoogleMaps@0.0.1 postinstall /Users/langke/TestReactNative/AndroidGoogleMaps
> ./node_modules/react-native-maps/enable-google-maps ./ios/GoogleMaps.framework

removed 1 package and audited 923118 packages in 4.351s
found 14 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

But why did I get that build error above? Can anyone please help me out? Thanks a lot in advance. It really took me a long time but not resolved.

screenshot as follows:

![shot](https://user-images.githubusercontent.com/22851821/72677793-3cc4ca00-3adb-11ea-912b-76fbe2fe21e3.png)

**Comment by lchenfox** [comment]
As supplementary: I also searched the issues on `StackOverFlow` and current `Issues` here. There may be the similar issues but not produced by installing manually. I just install this manually.

**Comment by rborn** [comment]
Please read how to install google map module here https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios-react-native-all-versions
Let me know if this works

**Comment by rborn** [comment]
closing , no reply
