### ISSUE TITLE
Open Info Window when load map

### ISSUE THREAD

**Issue by bilaluplogic** [react-native-community/react-native-maps#3267]
# Bug

I need open info window tool tip while opening map but currently my code shows tool tip only press on that icon.Kindly give me any code or idea for open info window with out onpress 

## My Code
```javascript
<Marker coordinate={{ latitude:Number(this.state.latitude), longitude:Number(this.state.longitude)}}  >
<Thumbnail square style={{ width: 40, height: 40 }} source={require('/marker.png')} ></Thumbnail>
 <Callout tooltip={true}>
   <View  style={styles.View2}>       
     <Text style={styles.popup}>Description</Text>
    </View>
  </Callout>
</Marker> 
```
## Environment info

react-native : 0.61
react-native-maps: 0.26.1

**Comment by kriscarle** [comment]
I think you are looking for `showCallout` https://github.com/react-native-community/react-native-maps/blob/master/docs/marker.md#methods

You can probably just save a ref to the marker and open it once the map is ready, something like this

```js
<Map
  onMapReady={() => { this.defaultMarker.showCallout() }
>
  <Marker ref={(ref) => this.defaultMarker = ref} />
</Map>
```

**Comment by bilaluplogic** [comment]
> I think you are looking for `showCallout` https://github.com/react-native-community/react-native-maps/blob/master/docs/marker.md#methods
> 
> You can probably just save a ref to the marker and open it once the map is ready, something like this
> 
> ```js
> <Map
>   onMapReady={() => { this.defaultMarker.showCallout() }
> >
>   <Marker ref={(ref) => this.defaultMarker = ref} />
> </Map>
> ```

Its working but **onMapReady** not work.So I have using **onRegionChange** instead of **onMapReady**.

Thanks @kriscarle
