### ISSUE TITLE
Change marker image without re-render MapView

### ISSUE THREAD

**Issue by igormoraesdev** [react-native-community/react-native-maps#3271]
Hi guys, i change image when i click on marker, but he re-render all time when i click, i want it he change the image without screen re-render, because he go back for initial position all time, anyone can help me?

``

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34649925/73680142-80523300-469a-11ea-87cb-12630727d6dc.gif)

**Comment by richardbumm** [comment]
The issue isn't the screen rendering.  It's rendering every time you move the screen anyway. The issue is how you are updating your map region. Make sure that when you are done moving the map, your current region is the maps current region, or it will jump around.  Check your state, etc.

**Comment by igormoraesdev** [comment]
Hey man, thanks for comment, i fixed here.

**Comment by preflower** [comment]
I met the same problem. Can you tell me how you solve it?
