### ISSUE TITLE
onUserLocationChange does not work for iOS

### ISSUE THREAD

**Issue by m-ruhl** [react-native-community/react-native-maps#3272]
Hey guys,

# Bug

The onUserLocationChange does not get triggered in iOS.

I think the wrong delegate method is used:
https://github.com/react-native-community/react-native-maps/blob/ef16f9c4d6f4cda3fb067c391f15239401969a69/lib/ios/AirMaps/AIRMapManager.m#L1304

It should be `didUpdateUserLocation`

```
- (void)mapView:(MKMapView *)mapView didUpdateUserLocation:(MKUserLocation *)userLocation NS_AVAILABLE(10_9, 4_0);
- (void)mapView:(MKMapView *)mapView didFailToLocateUserWithError:(NSError *)error NS_AVAILABLE(10_9, 4_0);
```

**Comment by mohameddroussi** [comment]
This is still not working, was there a fix for it?

**Comment by yairopro** [comment]
Any update  ?
@m-ruhl Why did you close the issue ?

**Comment by m-ruhl** [comment]
At the time this was only on the master, but not released

**Comment by yairopro** [comment]
I don't understand. What was only on master ?
The issue seems still to be here.

**Comment by m-ruhl** [comment]
At the time I created the issue (Feb) the reference method was only on the master branch, but was not included a release..

If you use 0.27.0 or later and still have a problem, what would be another issue.
