### ISSUE TITLE
[ANDROID] TouchableOpacity on top of map is not registering press events

### ISSUE THREAD

**Issue by wmonecke** [react-native-community/react-native-maps#3274]
Library version:  "react-native-maps": "^0.25.0",

When overlaying a component on top of `MapView` that has a TouchableOpacity (like a back button for example), the Touchable won't register `onPress` events.
This is only happening on Android. iOS working fine and as expected.

Any ideas why this could be happening?

**Comment by andyalcantara** [comment]
@wmonecke Did you find what was wrong? I am having the same issue

**Comment by resting** [comment]
Had the same problem. Just have to move the button to after `<MapView>`

Tap not registered:
```javascript
<MapContainer>
  <Button />
  <MapView />
</MapContainer>
```

Working:
```javascript
<MapContainer>
  <MapView />
  <Button />
</MapContainer>
```
