### ISSUE TITLE
Can't get custom map style to work in Expo app

### ISSUE THREAD

**Issue by DanLeCornu** [react-native-community/react-native-maps#3277]
Can't get custom map styling to work for my Expo iOS app. Example code below:

"expo": "36.0.2",
"react-native-maps": "0.26.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",

In the Map component:
```
import React from "react"  
import MapView, { PROVIDER_GOOGLE } from "react-native-maps"  

export const Map = () => {  
  return (  
    <MapView  
      customMapStyle={mapStyle}  
      provider={PROVIDER_GOOGLE}  
    />  
  )  
}

const mapStyle = [ ...generated JSON from https://mapstyle.withgoogle.com  ]  
```

and in my app.json:
```
{
  "expo": {
    ....
    "ios": {
      ....
     "config": {
       "googleMapsApiKey": MY_API_KEY,
      }
    },
  }
}
```

I've made sure i've enabled the Google Maps SDK for iOS service in the developer console, and have an unrestricted API key that allows both these services.

Result is the Google Maps map shows but without the custom styling (the json object i'm passing in is a dark mode theme, but the standard theme is still showing)

Anybody know anything about this? Haven't yet managed to test on Android so i'm not sure if it's something to do with iOS, or both, (or just something wrong in my code)

**Comment by JClackett** [comment]
Also cant find a way to get this to work

**Comment by Derewith** [comment]
Doesn't work in my Testflight app too..

**Comment by rborn** [comment]
Please move this to the expo repo, if it works in a pure project then it's an expo issue
