### ISSUE TITLE
Callout set opacity when i press

### ISSUE THREAD

**Issue by artmare** [react-native-community/react-native-maps#3279]
Hi everyone!

Callout set opacity when I press on it on Android. How I prevent it? Set _activeOpacity_ props don`t work.

**Comment by gotexis** [comment]
+1 i second this.

@rborn I think this shall be a valid issue even if no issue template?

**Comment by rborn** [comment]
@gotexis can we open a proper issue? (keep in mind that this doesn't mean it will be solved, is all if somebody from the community jumps in)
