### ISSUE TITLE
takeSnapshot of a map in hybrid mode for iOS creates a snapshot in default mode.

### ISSUE THREAD

**Issue by brandtnewww** [react-native-community/react-native-maps#3284]
# Bug

As described in https://github.com/react-native-community/react-native-maps/issues/2404, taking a snapshot in hybrid or satellite mode results in the snapshot taken in default mode.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 318.39 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
```

"react-native-maps": "0.26.1",

## Steps To Reproduce

1. On iOS: take a snapshot while in hybrid mode.
2. The snapshot does is not taken in the chosen hybrid mode. It's taken in the default mode instead.

Describe what you expected to happen:

If I set the Map to be in hybrid mode, I expect the snapshot to be in hybrid mode too.

**Comment by brunsy** [comment]
@brandtnewww I don't have time to submit a PR for this.
I got around it by patching takeSnapshot in AIRMapManager.m to match the implementation in AIRGoogleMapManager.m

**Comment by brandtnewww** [comment]
Thanks for the tip @brunsy 😊 Unfortunately, I'm currently running with an expo setup and therefore can't do that, I guess.

**Comment by christopherdro** [comment]
This should be resolved with the following PR that will be included in the next release. https://github.com/react-native-community/react-native-maps/pull/3120
