### ISSUE TITLE
【iOS】imprecise location for user location

### ISSUE THREAD

**Issue by lchenfox** [react-native-community/react-native-maps#3287]
# Bug

**Bug:** Imprecise location for user location.

**Installation Method:** Install manually.

**Screenshot 1 from react-native-maps:**

<img width="376" alt="Screenshot" src="https://user-images.githubusercontent.com/22851821/74398556-f735bb80-4e52-11ea-993e-04c388c0f6ef.png">

**Screenshot 2 from Google Maps installed from App Store:**

![Google Maps](https://user-images.githubusercontent.com/22851821/74398590-1cc2c500-4e53-11ea-972a-e28815e14be4.PNG)

As seen above, it's obvious that the current user location is extremely imprecise between `react-native-maps - picture 1` and `Google Maps installed from AppStore - picture 2`. **I'd like to know what's the reason?** If anyone knows that, please help me out. Thank you so much. I tried many times but failed. I think this may be a **bug**.

## Environment info

React native info output:

```
  React Native Environment Info:
    System:
      OS: macOS 10.15.3
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 4.15 GB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 24, 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: `"react-native-maps": "^0.25.0"`

## Steps To Reproduce

1. Install `react-native-maps` manually following the official installation correctly from this library.
2. Run it on real device - `iPhone XR` via Xcode
3. Go into map page and look the location of my current location
4. Alway keep imprecise

## Describe what you expected to happen:

The current user location  shown on the map is always precise.

## Reproducible sample code

**Codes as follows:**

```
<MapView
    style={styles.map}
    textStyle={{color: 'red'}}
    containerStyle={{backgroundColor: 'white', borderColor: 'green'}}
    provider={PROVIDER_GOOGLE}
    initialRegion={this.state.initialRegion}
    region={this.state.region} 
    showsUserLocation={true} 
    showsMyLocationButton={true} 
    followsUserLocation={true}
    showsCompass={true} 
    showsScale={true} // iOS. A Boolean indicating whether the map shows scale information. Default value is `false`
    showsIndoors={true} // android. A Boolean indicating whether indoor maps should be enabled. Default value is `false`
    showsIndoorLevelPicker={true} // android. A Boolean indicating whether indoor level picker should be enabled. Default value is `false`
   >
        <MapView.Marker
               coordinate={this.state.selectedCoordinate}
               ref={ref => this.marker = ref}
               draggable={false}
         />
</MapView>

const styles = StyleSheet.create({
    container: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    map: {
        ...StyleSheet.absoluteFillObject,
    },
});
```

**Comment by lchenfox** [comment]
It's because of coordinate conversion between earth(WGS-84) and mars in china(GCJ-02). Sorry for having this issue open. Closing.

**Comment by ggdegreat** [comment]
@lchenfox where do you got that info

> 
> 
> It's because of coordinate conversion between earth(WGS-84) and mars in china(GCJ-02). Sorry for having this issue open. Closing.

**Comment by lchenfox** [comment]
Yeah. This is a repo about coordinate conversion: [eviltransform: Transform coordinate between earth(WGS-84) and mars in china(GCJ-02)](https://github.com/googollee/eviltransform).

> @lchenfox where do you got that info
> 
> > It's because of coordinate conversion between earth(WGS-84) and mars in china(GCJ-02). Sorry for having this issue open. Closing.

Yeah. This is a repo about coordinate conversion: [eviltransform: Transform coordinate between earth(WGS-84) and mars in china(GCJ-02)](https://github.com/googollee/eviltransform).
