### ISSUE TITLE
Map not centered on ready

### ISSUE THREAD

**Issue by IgorDePaula** [react-native-community/react-native-maps#3293]
# Bug

On example more simple, the map not centered on screen the merker of initial region.

## Environment info

"react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-maps": "^0.26.1",

MacOS Catalina

React native info output:

None strange output;

Library version: x.x.x

## Steps To Reproduce

Any example more simples.

Describe what you expected to happen:

I expected centere any point that I selected

## Reproducible sample code

Any example more simples.

**Comment by IgorDePaula** [comment]
Resolved

**Comment by syedamirali14** [comment]
@IgorDePaula how did you do this?
