### ISSUE TITLE
How to show continuous moving car with MapView

### ISSUE THREAD

**Issue by BallySharma** [react-native-community/react-native-maps#3295]
Hi,

Please suggest we How can show continuous moving car with MapView using animations?...

Regards,
Bally Sharma

**Comment by BallySharma** [comment]
Trying using 

this.mapRef.animateToRegion(item, 10000);
this.marker._component.animateMarkerToCoordinate(item, 11000);

But motion is not smooth and moving icon looking flicker...

**Comment by aliwaqassi** [comment]
Yes @BallySharma  same issue with me marker is flickering, i am also looking for animation marker like uber

**Comment by rborn** [comment]
issue doesn't respect the template, closing
