### ISSUE TITLE
Redraw Marker on IOS

### ISSUE THREAD

**Issue by DominiciAntoine** [react-native-community/react-native-maps#3297]
# Bug

Hello, i am doing a smart parking app and the state of marker change really often so i had to use the function redraw on markers to optimise it. (problem was tracksViewChange : not made for how i am using markers ).

The problem is when i redraw the marker on IOS is not working and i get this error : TypeError: undefined is not an object (evaluating 'this.getMapManagerCommand(name).apply')

I think the error is from the function redraw it self, maybe he try to redraw with animation what is not working on IOS.

On android it works perfectly.

## Environment info

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 4.38 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-splash-screen: 3.2.0
    react-native-vector-icons: 6.4.2

React native info output:

TypeError: undefined is not an object (evaluating 'this.getMapManagerCommand(name).apply')

This error is located at:
    in CustomMarker (created by ConnectFunction)
    in ConnectFunction (at AllPlaces.js:122)
    in AllPlaces (created by ConnectFunction)
    in ConnectFunction (at HomeScreen.js:319)
    in AIRMap (at MapView.js:981)
    in MapView (at HomeScreen.js:318)
    in RCTView (at HomeScreen.js:316)
    in RCTView (at HomeScreen.js:311)
    in RCTScrollContentView (at ScrollView.js:1041)
    in RCTScrollView (at ScrollView.js:1181)
    in ScrollView (at KeyboardAwareHOC.js:517)
    in KeyboardAwareScrollView (at Content.js:47)
    in RCTSafeAreaView (at SafeAreaView.js:55)
    in SafeAreaView (at Content.js:46)
    in Content (at connectStyle.js:392)
    in Styled(Content) (at HomeScreen.js:310)
    in RCTView (at Container.js:12)
    in Container (at connectStyle.js:392)
    in Styled(Container) (at HomeScreen.js:295)
    in HomeScreen (created by ConnectFunction)
    in ConnectFunction (at SceneView.js:9)
    in SceneView (at createTabNavigator.tsx:67)
    in RCTView (at ResourceSavingScene.tsx:37)
    in RCTView (at ResourceSavingScene.tsx:26)
    in ResourceSavingScene (at createBottomTabNavigator.tsx:157)
    in RCTView (at screens.native.js:101)
    in ScreenContainer (at createBottomTabNavigator.tsx:147)
    in RCTView (at createBottomTabNavigator.tsx:146)
    in TabNavigationView (at createTabNavigator.tsx:228)
    in NavigationView (at createNavigator.js:80)
    in Navigator (at SceneView.js:9)
    in SceneView (at DrawerView.tsx:183)
    in RCTView (at ResourceSavingScene.tsx:37)
    in RCTView (at ResourceSavingScene.tsx:26)
    in ResourceSavingScene (at DrawerView.tsx:175)
    in RCTView (at screens.native.js:101)
    in ScreenContainer (at DrawerView.tsx:164)
    in RCTView (at createAnimatedComponent.js:218)
    in AnimatedComponent (at Drawer.tsx:530)
    in RCTView (at createAnimatedComponent.js:218)
    in AnimatedComponent (at Drawer.tsx:526)
    in PanGestureHandler (at Drawer.tsx:516)
    in DrawerView (at DrawerView.tsx:251)
    in DrawerView (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at App.js:124)
    in Provider (at App.js:123)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

_runCommand
    MapMarker.js:305:8
redraw
    MapMarker.js:287:21
componentDidUpdate
    CustomMarker.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:74:34
commitRootImpl
    [native code]:0
unstable_runWithPriority
    scheduler.development.js:643:23
commitRoot
    [native code]:0
runRootCallback
    [native code]:0
unstable_runWithPriority
    scheduler.development.js:643:23
notify
    Subscription.js:28:10
<anonymous>
    Subscription.js:70:2
handleChangeWrapper
    Subscription.js:75:13
handleChangeWrapper
    [native code]:0
dispatch
    redux.js:227:10
refreshHashMap
    AllPlaces.js:138:8
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:168386:34
tryCallOne
    core.js:37:14
setImmediate$argument_0
    core.js:123:25
_callTimer
    JSTimers.js:146:14
_callImmediatesPass
    JSTimers.js:194:17
callImmediates
    JSTimers.js:458:30
callImmediates
    [native code]:0
flushedQueue
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0

## My code 

import React, { PureComponent } from 'react';
import {View} from 'react-native'
import { Image } from 'react-native';
import { Marker, MarkerAnimated } from 'react-native-maps';
import { connect } from 'react-redux'

class CustomMarker extends PureComponent {
    constructor() {
        super();
        this.state={ref:null, firstLaunch: true};
    }

    shouldComponentUpdate(prevProps, prevState)
    {

        let previousMarker = prevProps.sensorsHashMapData;
        let currentMarker = this.props.sensorsHashMapData;

        if (this.state.firstLaunch)
        {
            this.setState({firstLaunch:false});
            return true;
        }
        if (currentMarker && previousMarker)
        {
            return ((currentMarker.state !== previousMarker.state ) ||   (prevProps.mapsDirectionData.directionState !== this.props.mapsDirectionData.directionState))
        }
        return false;
    }

    componentDidUpdate()
    {
            if (Platform.OS === 'android') {
                if (this.markerRef) {
                    this.markerRef.redraw();
                }
            }
            else
            {
                if (this.markerRef) {
                   this.markerRef.redraw()
                }
            }

    }

    render() {
        let currentMarker = this.props.sensorsHashMapData;
        if (currentMarker)
        {
            let currentImage = null;
            let imageSize = 16;
            let rendering = true;

            this.props.placeData.parkType === 1? (currentMarker.state === 1 ? currentImage = this.props.imagepo: currentImage = this.props.imagepl): (currentMarker.state === 1 ? currentImage = this.props.imageplto: currentImage = this.props.imagepltl);

            if (this.props.mapsDirectionData.directionState!==1) (this.props.mapsDirectionData.uidDirection === currentMarker.uid)? imageSize=40:rendering=false;

            if( rendering)

                return (

                    <Marker
                        key={this.props.key}
                        coordinate={this.props.coordinate}
                        tracksViewChanges={false}
                        ref={markerRef => this.markerRef = markerRef}
                        stopPropagation={true}
                    >
                        <Image
                            style={{height:imageSize, width:imageSize}}
                            source={currentImage}
                            fadeDuration={0}
                        />
                    </Marker>
                );
        }
        return(<View/>);

    }
}

const mapStateToProps = (state, ownProps) => {

    return {
        sensorsHashMapData:state.sensorsHashMapData[ownProps.placeData.uid],
        mapsDirectionData: state.mapsDirectionData

    }
};

export default connect(mapStateToProps)(CustomMarker);

## Last Word 

So thats all, if someone can give any solution, its will be wonderful, thank all in advance.

Ps : sorry for my bad english ^^

Dominici Antoine

**Comment by DominiciAntoine** [comment]
Hi, i might be found where the problem is but i don't know how to resolve it.

```  redraw() {
    this._runCommand('redraw', []);
  }

  _getHandle() {
    return findNodeHandle(this.marker);
  }

  _runCommand(name, args) {
    switch (Platform.OS) {
      case 'android':
        NativeModules.UIManager.dispatchViewManagerCommand(
          this._getHandle(),
          this.getUIManagerCommand(name),
          args
        );
        break;

      case 'ios':
        this.getMapManagerCommand(name)(this._getHandle(), ...args);
        break;

      default:
        break;
    }
  }
```
I think the problem is in the getMapManagerCommand function in IOS.

So if you guys have an idea how to solve it, it will be great ^^

**Comment by DominiciAntoine** [comment]
I found the solution, you don't need to use redraw on IOS, i don't why but the redrawing is done automatically. This is the solution ( i give you all my code for you to understand ) : 
```
import React, { PureComponent } from 'react';
import {View} from 'react-native'
import { Image } from 'react-native';
import { Marker, MarkerAnimated } from 'react-native-maps';
import { connect } from 'react-redux'

class CustomMarker extends PureComponent {
    constructor() {
        super();
        this.state={ref:null, firstLaunch: true};
    }

    shouldComponentUpdate(prevProps, prevState)
    {

        let previousMarker = prevProps.sensorsHashMapData;
        let currentMarker = this.props.sensorsHashMapData;

        if (this.state.firstLaunch)
        {
            this.setState({firstLaunch:false});
            return true;
        }
        if (currentMarker && previousMarker)
        {
            return ((currentMarker.state !== previousMarker.state ) ||   (prevProps.mapsDirectionData.directionState !== this.props.mapsDirectionData.directionState))
        }
        return false;
    }

    componentDidUpdate()
    {
            if (Platform.OS === 'android') {
                if (this.markerRef) {
                    this.markerRef.redraw();
                }
            }
    }



    render() {
        let currentMarker = this.props.sensorsHashMapData;
        if (currentMarker)
        {
            let currentImage = null;
            let imageSize = 16;
            let rendering = true;

            this.props.placeData.parkType === 1? (currentMarker.state === 1 ? currentImage = this.props.imagepo: currentImage = this.props.imagepl): (currentMarker.state === 1 ? currentImage = this.props.imageplto: currentImage = this.props.imagepltl);

            if (this.props.mapsDirectionData.directionState!==1) (this.props.mapsDirectionData.uidDirection === currentMarker.uid)? imageSize=40:rendering=false;




            if( rendering)

                return (

                    <Marker
                        key={this.props.key}
                        coordinate={this.props.coordinate}
                        tracksViewChanges={false}
                        ref={markerRef => this.markerRef = markerRef}

                    >
                        <Image
                            style={{height:imageSize, width:imageSize}}
                            source={currentImage}
                            fadeDuration={0}
                        />
                    </Marker>
                );
        }
        return(<View/>);


    }
}

const mapStateToProps = (state, ownProps) => {


    return {
        sensorsHashMapData:state.sensorsHashMapData[ownProps.placeData.uid],
        mapsDirectionData: state.mapsDirectionData

    }
};

export default connect(mapStateToProps)(CustomMarker);
```

**Comment by Yaolegol** [comment]
same problem, DominiciAntoine solution work
