### ISSUE TITLE
How to calculate polygon area like getPath()

### ISSUE THREAD

**Issue by sidpauhal** [react-native-community/react-native-maps#3300]
package.json file 
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-maps": "0.26.1",
  },

I have added polygon on map now I want to calculate total area of that polygon
Like in web version of google maps we can do something like
google.maps.geometry.spherical.computeArea(yourPolygon.getPath());

is there any functionality in this lib to calculate area?

Please help

**Comment by aliwaqassi** [comment]
These packages may help

https://www.npmjs.com/package/geolib
https://www.npmjs.com/package/spherical-geometry-js

**Comment by rborn** [comment]
No template and out of scope. Closing
