### ISSUE TITLE
null is not an object (evaluating 'o.markerDestination._component')

### ISSUE THREAD

**Issue by govind1530** [react-native-community/react-native-maps#3302]
React Native Environment Info:
    System:
      OS: Linux 5.3 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
      Memory: 345.47 MB / 11.54 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-exit-app: 1.1.0

                   <MapView style={styles.map} ref={c => this.mapView = c} region={data}>
                    <MapView.Marker coordinate={origin} /> 
![Skype_Picture_2020_02_24T09_10_10_575Z](https://user-images.githubusercontent.com/33393692/75139822-9be9b000-5713-11ea-9c38-3fbba653b6e3.jpeg)

              <MapView.Marker coordinate={destination} ></MapView.Marker>

**Comment by rborn** [comment]
Can you please update the issue with the template?

**Comment by rborn** [comment]
closing, no reply
