### ISSUE TITLE
steps to run an existing react-native app downloaded from Git

### ISSUE THREAD

**Issue by reejarejin** [react-native-community/react-native-maps#3306]
# Question
  
      Some one please advise the steps to run an existing react-native app from Gitlab both in iOS and android. tried so many times, its not working . 
installed watchman(4.9.0), node(12.16.0) ,x-code(10.1),cocoa pods( /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods.rb).

Thank You

**Comment by rborn** [comment]
This is not an issue related to this module. I'll close it for now
