### ISSUE TITLE
The strange maps appear in iOS

### ISSUE THREAD

**Issue by aromahyang** [react-native-community/react-native-maps#3311]
# Bug

Hi, I use react-native-maps and have noticed that there are strange maps on South Korea. Are those bugs? On Android, there's no problem, but on only iOS, those problems occur.
![IMG_0047](https://user-images.githubusercontent.com/20590502/75405527-4bf82c80-5951-11ea-9b7a-acc848bcc907.png)

## Environment info

react: 16.9.0
react-native: 0.61.5
react-native-maps: ^0.26.1

## Steps To Reproduce

 
When searching South Korea, the one of strange parts is showed on the right side of Busan and the other(the circle one) appears.

Describe what you expected to happen:

Please remove those maps.

**Comment by rborn** [comment]
The images fir the tiles are coming from Google or Apple, there is not much we can do about.
I'll close the issue for now as it's not under the module's power to do anything.
