### ISSUE TITLE
Draw shape on the map ?

### ISSUE THREAD

**Issue by AFMW** [react-native-community/react-native-maps#3328]
I wanna know if its possible to implement this kind of solution using react-native and react-native-maps.

Could you guys show me some tips for doing it?, how can I do it?

I'm using:
*"react-native": "0.59.10",*
*"react-native-map-clustering": "^3.1.2",*
*"react-native-maps": "^0.25.0".*

![image description](https://thumbs.gfycat.com/RemoteDisloyalCardinal-small.gif)

**Comment by linhlie** [comment]
can you give me soucre code
