### ISSUE TITLE
Publish 0.27.0 on NPM

### ISSUE THREAD

**Issue by jdegger** [react-native-community/react-native-maps#3329]
# Question
Hi, I was wondering why version 0.27.0 has not been published on NPM yet?

Many thanks!

**Comment by jdegger** [comment]
I see this is issue has been closed for "no issue template". Please note that this is the template provided when creating a question:

```
# Question

<!--
  Before submitting it, please ensure that this was not already asked in another issue, or on StackOverflow. Ideally, you should always refer to StackOverflow first.

  This issue should serve for you to ask a question about the library to the maintainers and other fellow developers - remember that even if the issue gets closed, the conversation can move forward 🤗
  Also, ideally this issue should culminate in a PR to the documentation for this library so that future developers will have that doubt cleared.
-->
```

I have added `# Question` on top of my issue.

**Comment by rborn** [comment]
Now it has the proper title 🤗

**Comment by jdegger** [comment]
Because `# Question` has been added? I mean I like templates but that is a little over the top bureaucratic.. might be me?

**Comment by rborn** [comment]
I understand it can be taken too far away for some people, but for the maintainers is easier to understand what's about. If I have 5' maybe I'll reply questions, if I have 15' maybe I'll look into an issue.

We still do this by hand but we hope that one day we'll be able to make a bot that does this. And then AI won't have any mercy of those who don't make the effort to actually write a proper issue 🤣

**Comment by jdegger** [comment]
Your effort in maintaining this repo is appreciated 👍 for bots it's totally understandable of course. I would recommend adding this explanation to the issue template as many developers would understand that.

**Comment by rborn** [comment]
Good idea, thank you :)

**Comment by christopherdro** [comment]
Testing builds on a few production apps. I will publish it soon.

**Comment by anhpham1509** [comment]
Hi, do you have any expected date to release this version?
