### ISSUE TITLE
Vector tiles

### ISSUE THREAD

**Issue by gokugen** [react-native-community/react-native-maps#3330]
First of all, sorry for my bad english...
Hello there,
I just wanted to ask you if it will be possible to use our own Vector tiles (with UrlTile) in a future version of the module. It will be such better in terms of user experience with smoother zoom (don't need to wait images to load) and 3D render for exemple.
Thank's a lot !

**Comment by rborn** [comment]
@gokugen please update your issue following the template, this is a question

**Comment by rborn** [comment]
Closing, no reply
