### ISSUE TITLE
 installation instructions for Android unclear

### ISSUE THREAD

**Issue by conor909** [react-native-community/react-native-maps#3332]
# Bug

The installation instructions for Android devices at:
`4. (React Native all versions) Specify your Google Maps API Key:`

The comments say:
`<!-- You will only need to add this meta-data tag, but make sure it's a child of application -->`
&
`<!-- You will also only need to add this uses-libray tag -->`

So do we "only" need to add the top line or the bottom line?  Sorry if it's just me thats confused about this, I have a bug thats API_KEY related and I cant work out what it is, so I need to narrow it down.

Thanks

**Comment by rborn** [comment]
@conor909  yeah, the `only` word there is confusing, it should be removed form both places, fancy a PR 🤓 ?

And to answer your question you need **both** changes.

**Comment by conor909** [comment]
Sure I'll make a PR.  Thanks for clearing that up!
