### ISSUE TITLE
Custom marker image size

### ISSUE THREAD

**Issue by franckmaurin** [react-native-community/react-native-maps#3335]
Hi. My question is about the custom marker image sizing.

I defined my markers like this 
```
<Marker
  key={marker.storeId}
  coordinate={{
    latitude: marker.gps.lat,
    longitude: marker.gps.lng
  }}
  image={markerIcon}
  onPress={() => this.setState({ marker })}
/>

```
FYI, `markerIcon` is an imported image of 68x82px.

When I test with the Simulator or with my Iphone 7 via Xcode, markers seems to be divided by two to be retina (first capture).

But, when the app is downloaded via appstore/testflight, markers seems to be display at the 68x82 (so non retina at all) and pixelated. (second capture)

How it's possible ? In the same device, the same marker image took 2 different sizes. Can we set the size when we define `<Marker />` ?

Thanks for your help 🙏

![Simulator Screen Shot - iPhone 7 - 2020-03-13 at 11 49 15](https://user-images.githubusercontent.com/217914/76615565-93baae80-6522-11ea-808b-26a3c3aae991.png)
![IMG_4825](https://user-images.githubusercontent.com/217914/76615580-9cab8000-6522-11ea-9aa1-475fd2f3e2f7.PNG)

**Comment by aliwaqassi** [comment]
Do like that

```
<Marker
  key={marker.storeId}
  coordinate={{
    latitude: marker.gps.lat,
    longitude: marker.gps.lng
  }}
  onPress={ () => this.setState({ marker }) }
>
  <Image source={require(markerIcon)} style={{width:50,height:50}} />
</Marker>
```

**Comment by franckmaurin** [comment]
Thanks @aliwaqassi it works like a charm now ! 🙏

**Comment by eyalyoli** [comment]
This should be opened as a bug! I encountered the same issue on Android & iOS.
