### ISSUE TITLE
Bug CalloutSubview on Android maps

### ISSUE THREAD

**Issue by KiziKr** [react-native-community/react-native-maps#3341]
Hello, i have message error when I use CalloutSubview component.

I receive this message: 'Invariant Violation: requireNativeComponent: "AIRMapCalloutSubview" was not found in the UIManager'.

Thanks

**Comment by RocKer004** [comment]
Any solutions to this ?

**Comment by khuntiharesh** [comment]
Hello, Is there any news on this issue?

**Comment by harashvaradhan** [comment]
Hi, I am getting this error for Android only, iOS build works fine.

Please find attached screenshot
![Screenshot_1617094748](https://user-images.githubusercontent.com/2690132/112962716-4f697300-9164-11eb-83d2-d3e267fa1074.png)
