### ISSUE TITLE
React/RCTImageLoaderProtocol.h' file not found

### ISSUE THREAD

**Issue by Nargle30** [react-native-community/react-native-maps#3343]
# Bug

Hello, react-native-maps contributors!

I have: RN v0.60.3, react-native-maps v0.27.0

I was using react-native-maps v0.26.1 and updated to v0.27.0 recently.
Unfortunately it doesn't work at my project any longer.
Every time I run the app I get error "**React/RCTImageLoaderProtocol.h' file not found**" at Pods/Development Pods/react-native-maps/AIRMapOverlay.m

I assume these changes cause the issue: https://github.com/react-native-community/react-native-maps/pull/3136.

What can I do with this? I would like to use the new version as you fixed custom polygon colors in it 🙏 
_I know I can fork the lib, but I am trying to avoid doing that_

## Steps To Reproduce
1. RN v0.60.3 (or RN <0.61.0 as the changes were made for RN >= v0.61.0)
2. react-native-maps v0.27.0
3. cd /ios && pod install
4. cd ..
5. run the project in XCode

**Comment by rborn** [comment]
@Nargle30 could you try to upgrade RN, I think 0.61 has some differences from 0.60 that might break this

**Comment by rborn** [comment]
@Nargle30 btw, you might want to edit the issue title :)

**Comment by Nargle30** [comment]
@rborn Unfortunately I cannot change react-native version right now. 
Is there any chance that the lib will work with RN <0.61 again?

**Comment by rborn** [comment]
@Nargle30  I don't think so. But you might try some fixes in your own fork. 
Here is one, https://github.com/itinance/react-native-fs/issues/791  but looking in google for the title you just set (thank you for this) will get more results.

**Comment by rborn** [comment]
Closing as not fixable

**Comment by NicoCevallos** [comment]
check proposed solution on https://github.com/react-native-community/react-native-maps/issues/3142#issuecomment-621966800

@rborn could you change the issue label?

**Comment by zhigang1992** [comment]
Also the example project is still on 0.59

**Comment by kigh143** [comment]
Has anyone got the answer to this issue?

**Comment by NicoCevallos** [comment]
@zhigang1992 @kigh143 
check proposed solution on https://github.com/react-native-community/react-native-maps/issues/3142#issuecomment-621966800

**Comment by chrisbobbe** [comment]
@rborn [said](https://github.com/react-native-community/react-native-maps/issues/3343#issuecomment-600191438):
> @Nargle30 could you try to upgrade RN, I think 0.61 has some differences from 0.60 that might break this

It appears that the `Libraries/Image/RCTImageLoaderProtocol.h` file, in the React Native repo, didn't exist until [facebook/react-native@bf78d79](https://github.com/facebook/react-native/commit/bf78d7969a48b63f7d57bf7cdb1b1d8af2f46e5c), which is tagged as released in RN v0.61.0.

**Comment by pankajnegi1893** [comment]
use 
`#import <React/RCTImageLoader.h>`
instead of
`#import <React/RCTImageLoaderProtocol.h>`

**Comment by stevieoj** [comment]
Thanks

**Comment by kukuandroid** [comment]
@pankajnegi1893  need pod install after that ?

**Comment by prakashw3expert** [comment]
Solution:-
Replace 
//#import <React/RCTImageView.h>
with
#import <React-RCTImage/React/RCTImageView.h>
and
//#import <React/RCTResizeMode.h>
#import <React-RCTImage/React/RCTResizeMode.h>
if you have error with RCTImageLoader
do same thing:
//#import <React/RCTImageLoader.h>
#import <React-RCTImage/React/RCTImageLoader.h>
