### ISSUE TITLE
flat and rotation not working on Marker on IOS

### ISSUE THREAD

**Issue by Stevemoretz** [react-native-community/react-native-maps#3348]
I want to have a car marker on the map.But in ios the flat and rotation don't work.Also There's no event to get the bearing angle so I can manually rotate the marker myself.Please fix this behavior.Why shouldn't that work if it exists?

**Comment by Stevemoretz** [comment]
Thanks you totally fixed my issue!
What's that supposed to mean?The problem is obvious.

**Comment by rborn** [comment]
Is supposed to follow the template you have once you open an issue. If you are not willing to do this how can you expect anyone to help with your issue?

Is a way to help maintainers filter the issues and later on we might implement a bot that will make this initial triage.

**Comment by Stevemoretz** [comment]
Sorry the problem was my html was not loaded completely.I guess that's why there was no template.So I create a new issue please remove this one thanks.
