### ISSUE TITLE
MapViewProps is missing onIndoorBuildingFocused in index.d.ts

### ISSUE THREAD

**Issue by TheGreatMarkus** [react-native-community/react-native-maps#3353]
# Bug

MapViewProps is missing onIndoorBuildingFocused in the index.d.ts type. An error shows up when using the library in a typescript project in vscode.

![image](https://user-images.githubusercontent.com/23544999/77236794-382e9780-6b98-11ea-8300-6631f9943fb0.png)

## Environment info

  Expo CLI 3.15.4 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.14.3 - /usr/local/bin/npm
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.15.4

Library version: 0.27.1

## Steps To Reproduce

1. Expo init a new project with typescript
2. Copy-paste the content of [the IndoorMap.js example code](https://github.com/react-native-community/react-native-maps/blob/master/example/examples/IndoorMap.js) into App.tsx.
3. Run `npm install react-native-maps`

Describe what you expected to happen:
1. No TypeScript errors show up for onIndoorBuildingFocused

## Reproducible sample code

See https://github.com/react-native-community/react-native-maps/blob/master/example/examples/IndoorMap.js

**Comment by rborn** [comment]
Lovely, fancy a PR  ? 😻

**Comment by TheGreatMarkus** [comment]
Sure, I'll make one real quick

**Comment by TheGreatMarkus** [comment]
I also noticed that type definitions were missing for setIndoorActiveLevelIndex. I will add them to my pr
