### ISSUE TITLE
Marker with 2 actions (buttons)

### ISSUE THREAD

**Issue by wilsolutions** [react-native-community/react-native-maps#3356]
# Question

How can I add 2 actions (buttons) inside a marker?

Currently I have only 1 action (button) but I would like to have 2:

```
      <Marker coordinate={data.latlng} key={data.id} tracksViewChanges={false}>
        <Callout style={styles.plainView} onPress={e => { showDetails(data.id); }}>
          <Text>{data.title}</Text>
        </Callout>
      </Marker>

```

**Comment by christopherdro** [comment]
How about a single callout with 2 buttons?

**Comment by wilsolutions** [comment]
> How about a single callout with 2 buttons?

Yep, I tried but the button events were not firing that's why I moved to the Callout onPress event.

For anyone running on the same issue it did turn up my new requirements just needed to have 1 event instead of two.

**Comment by PradumanS** [comment]
I'm quite late but for anyone facing the issue now can use "CalloutSubview" -> https://github.com/react-native-maps/react-native-maps/blob/master/docs/callout.md.
Here is an example: https://github.com/react-native-maps/react-native-maps/blob/master/example/examples/Callouts.js#L127

**Comment by FelipeGCastro** [comment]
> I'm quite late but for anyone facing the issue now can use "CalloutSubview" -> https://github.com/react-native-maps/react-native-maps/blob/master/docs/callout.md. Here is an example: https://github.com/react-native-maps/react-native-maps/blob/master/example/examples/Callouts.js#L127

Looks like CalloutSubview is only works on IOS

**Comment by josill** [comment]
https://github.com/react-native-maps/react-native-maps/issues/211
