### ISSUE TITLE
fake gps and mock locations

### ISSUE THREAD

**Issue by Daffodil12** [react-native-community/react-native-maps#3357]
### Is this a bug report?
no

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
yes

### Environment
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-maps": "^0.24.2",

##question
How can I make sure that user will not use the mock location and fake gps while using react native maps? When the developer mode is on users can still use the mock location do we have way to stop it?

**Comment by Daffodil12** [comment]
@TheGreatMarkus can you pls answer this?

**Comment by TheGreatMarkus** [comment]
I'm afraid I don't know. I am not an active developer for react-native-maps

**Comment by Daffodil12** [comment]
@rborn whats your opinion regarding minimising the location spoofing?

**Comment by rborn** [comment]
@Daffodil12 to be able to do this the native part should have a way first to detect it. If there is a way then it can be bridged to the RN module. But I don't know if it's possible

**Comment by rborn** [comment]
@Daffodil12 ok, it seems that `onUserLocationChange` provides `isFromMockProvider` however I'm not sure how it works, you might wan to dive into the source code

**Comment by Daffodil12** [comment]
@rborn to my knowledge in android we have a way to stop using mock locations https://developer.android.com/reference/android/location/Location.html#isFromMockProvider(). but i am not well aware what can be done for iPhones. I am struggling with this issue as I have a system in which the users should not be able to access the fake gps and the business requirement get effected badly if they use the fake locations. I was thinking of verifying location with wifi nearby or cell tower but honestly I am not expert at it. If you can think of any other possible ways let me know here. Thank You

**Comment by rborn** [comment]
@Daffodil12 in iOS on device you cannot fake the gps as far as I know. But I might be wrong?

**Comment by rborn** [comment]
@Daffodil12 here you go, not tested :) 

https://github.com/GantMan/jail-monkey

**Comment by Daffodil12** [comment]
@rborn  thank you for sharing this. Strangely, i did not came across this lib even after extensive gsearch :p I'll share my review here after using it. (y)

**Comment by rborn** [comment]
https://www.google.com/search?q=react+native+mocked+location  🤪

**Comment by rborn** [comment]
@Daffodil12 can we close this?

**Comment by rborn** [comment]
closing, no reply, assuming is solved based on comments
