### ISSUE TITLE
Return value from onUserLocationChange

### ISSUE THREAD

**Issue by daniel-addressya** [react-native-community/react-native-maps#3360]
# Question

According to the docs for MapView, the onUserLocationChange methods returns { coordinate: Location }, but when I use it it returns a SyntheticEvent. Is this an error in the doc?
https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#events

**Comment by christopherdro** [comment]
> To access event data, you will need to use e.nativeEvent. For example, onPress={e => console.log(e.nativeEvent)} will log the entire event object to your console.

Are you accessing the `nativeEvent` property?

**Comment by daniel-addressya** [comment]
No, I didn't know about that. So the documentation is incorrect?

**Comment by christopherdro** [comment]
That’s from the documentation.
