### ISSUE TITLE
How to change description text color of callout?

### ISSUE THREAD

**Issue by tae-at-speer** [react-native-community/react-native-maps#3365]
I've made to always show callout with calling showCallout method in the onRegionChangeComplete in the mapView.
And I've set description to show current location and it is working fine but I want to change the color of description to black.
Is this possible?

**Comment by tae-at-speer** [comment]
Why is this closed?

**Comment by rborn** [comment]
@tae-at-speer You didn't follow the issue template ( see the label?) .
