### ISSUE TITLE
How to change description text color of callout?

### ISSUE THREAD

**Issue by tae-at-speer** [react-native-community/react-native-maps#3369]
# Question

I've made to always show callout with calling showCallout method in the onRegionChangeComplete in the mapView.
And I've set description to show current location and it is working fine but I want to change the color of description to black.
Is this possible?

**Comment by rborn** [comment]
You can pass your own component in the callout. 

https://github.com/react-native-community/react-native-maps/blob/master/example/examples/Callouts.js#L93-L100

**Comment by rborn** [comment]
closing, no reply
