### ISSUE TITLE
Incredibly low resolution with OpenStreetMap, blurry tiles

### ISSUE THREAD

**Issue by Vahradrim** [react-native-community/react-native-maps#3388]
# Bug

Using OpenStreetMap gives low resolution tiles. Tiles and labels are blurry.

## Environment info

> System:
>     OS: Windows 10 10.0.18362
>     CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
>     Memory: 3.50 GB / 7.95 GB
>   Binaries:
>     Node: 12.16.1 - H:\Programs\NodeJS\node.EXE
>     npm: 6.13.4 - H:\Programs\NodeJS\npm.CMD
>   npmPackages:
>     react: ~16.9.0 => 16.9.0
>     react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
>     react-native-maps: 0.26.1

## Steps To Reproduce

Use a MapView component with google maps, and change the following to use OpenStreetMap (according to the documentation)

Describe what you expected to happen:
Get the OpenStreetMap tiles in the same resolution than Google Maps

## Reproducible sample code

This code is working perfectly with Google Maps : 

> import MapView, {
>   MAP_TYPES,
>   PROVIDER_DEFAULT,
>   PROVIDER_GOOGLE,
> } from "react-native-maps";
> ...
> <MapView
>           ref={(map) => (currentMap = map)}
>           initialRegion={location}
>           showsUserLocation
>           style={{
>             height: Globals.Layout.window.height,
>             width: Globals.Layout.window.width,
>           }}
>         >
>         </MapView>
You get the correct result :
![Screenshot_20200414_123617_host exp exponent](https://user-images.githubusercontent.com/32706466/79253892-ea811400-7e51-11ea-817c-d193becbb8c6.jpg)

 Change to this to use OpenStreetMap, and you get correct tiles, but everything is blurred and in low resolution :

>  import MapView, {
>   MAP_TYPES,
>   PROVIDER_DEFAULT,
>   PROVIDER_GOOGLE,
> } from "react-native-maps";
> ...
> <MapView
>           ref={(map) => (currentMap = map)}
>           initialRegion={location}
>           showsUserLocation
>           provider={PROVIDER_DEFAULT}
>           mapType={MAP_TYPES.NONE}
>           style={{
>             height: Globals.Layout.window.height,
>             width: Globals.Layout.window.width,
>           }}
>         ><MapView.UrlTile
>             urlTemplate={"http://a.tile.openstreetmap.org/{z}/{x}/{y}.png"}
>             shouldReplaceMapContent={true}
>           />
>         </MapView>
You get the result : 
![Screenshot_20200414_123447_host exp exponent](https://user-images.githubusercontent.com/32706466/79253945-fa98f380-7e51-11ea-81fa-152518dd6244.jpg)

**Comment by rborn** [comment]
@Vahradrim 
is possible that you need to serve tiles with @2x @3x size depending on device, check the openstreetmap docs if they say anything about retina displays

**Comment by Vahradrim** [comment]
> @Vahradrim
> is possible that you need to serve tiles with @2x @3x size depending on device, check the openstreetmap docs if they say anything about retina displays

Hi, first thank you to take the time to answer me, I'm struggling on this since 2 days now.
I read a lot of documentation and I don't see how I could adapt the size of the tile with a MapView component, would you have a quick code example to put me on the right track?

**Comment by rborn** [comment]
I'm sorry but I never worked with openstreetmaps and I didn't seem to find any good  answer with a quick google search :(

**Comment by Vahradrim** [comment]
Nah.. I've been searching the web for 2 days now.. 
I'm actively trying to find a solution on this one, gonna post the solution when I have it.
If anybody has a clue on this I would really appreciate and I think it would help a lot of people in the future.

**Comment by revo09** [comment]
@Vahradrim 
For you to use retina tiles, the tile service provider will need to provide them. From what I know, the official openstreetmap tile server provides the tiles only at 1x resolution (256x256 pixels). I don't think you will find a free service provider that will provide tiles at 2x or 3x the resolution (retina). You can also generate your own tiles and host them on your own server (generating tiles is quite a lengthy process if you want them pre-seeded so that they will load quickly on request, the alternative is that they will be generated on demand which will seem slow and dependent on the hardware). I have done this myself but only at country level. If you want to play with this and host your own tile server, you can check MapProxy.

Try to test using the RRZE test provider from the Examples (the second one). Go to the base site to see the links that you will need to add to your UrlTile config, and use the one with the "osmhd" which will provide 512x512 tiles.
 https://wiki.openstreetmap.org/wiki/High-resolution_tiles 
Also try to add this param tileSize={512} to your MapView.UrlTile config.

**Comment by Vahradrim** [comment]
Thank you for your response.
You're right, I noticed that the provider I was using was giving me low resolution tiles.
I tried to manipulate my own tiles (loading the next zoom 4 tiles in cache concatenated to increase the resolution) but unfortunately, using expo I cannot merge images together.
So I did change my provider and the tiles are now way better (https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y})
Here is a good link for people willing to find a suitable provider of their liking : 
https://leaflet-extras.github.io/leaflet-providers/preview/
Hope that helps

**Comment by Vahradrim** [comment]
For those having the same issue, I've solved the problem by simply applying this style : 
{
   height: SCREEN_HEIGHT * 2,
   width: SCREEN_WIDTH * 2,
   marginTop: -SCREEN_HEIGHT / 2,
   marginLeft: -SCREEN_WIDTH / 2,
   transform: [{ scale: 0.5 }],
}

**Comment by stdavis** [comment]
This hack worked slightly better for me:
```js
const SCREEN_HEIGHT = Dimensions.get('screen').height;
const SCREEN_WIDTH = Dimensions.get('screen').width;
const ZOOM_FACTOR = 1.75;

const styles = StyleSheet.create({
  map: {
    position: 'absolute',
    top: 0,
    ...Platform.select({
      ios: {
        height: SCREEN_HEIGHT,
        width: SCREEN_WIDTH,
      },
      android: {
        height: SCREEN_HEIGHT * ZOOM_FACTOR,
        width: SCREEN_WIDTH * ZOOM_FACTOR,
        marginTop: -(SCREEN_HEIGHT * ZOOM_FACTOR - SCREEN_HEIGHT) / 2,
        marginLeft: -(SCREEN_WIDTH * ZOOM_FACTOR - SCREEN_WIDTH) / 2,
        transform: [{ scale: 1 / ZOOM_FACTOR }],
      },
    }),
  },
});
```
