### ISSUE TITLE
'AIRMapCoordinate.h' file not found

### ISSUE THREAD

**Issue by HosseinRashno** [react-native-community/react-native-maps#3390]
I have a react-native project which was successfully integrated with "react-native-maps".
Two days ago, I upgraded one package (react-native-track-player@2.0.0-rc13) and after that when I tried to build the project, it does have problems with some headers in the "react-native-maps@0.26.1" package. It shows this error:

```
#import "RCTConvert+AirMap.h"        ->      'RCTConvert+AirMap.h' file not found
location: Pods>Development Pods>react-native-google-maps>AIRGoogleMapPolylineManager.m
```

After desperately trying to solve the problem without any success, I removed this line to see what happens without that and now I get this error:

`'AIRMapCoordinate.h' file not found`

I realized that this error happening because Xcode can't find those headers and those headers are in this directory: 

`$(SRCROOT)/../node_modules/react-native-maps/lib/ios/AirMaps
`

So I added this path to "Header search paths" but it still can't find those headers. I also delete pod files and re-install them and cleaned the project build folder but I still have the same problem. Do you have any ideas about what goes wrong here?

My environment:
React: 16.9.0
React native: 0.61.2
react-native-maps: 0.26.1
Xcode: Version 11.4 (11E146)
Pod: 1.8.3

**Comment by HosseinRashno** [comment]
Sorry, my bad.
Somehow during the process of upgrading "react-native-track-player", I accidentally removed "use_native_modules!" from my podfile!

**Comment by jose920405** [comment]
This is happening to me but I did not remove the `use_native_modules!` line. 😢
