### ISSUE TITLE
Custom map style with Apple Maps?

### ISSUE THREAD

**Issue by adlme** [react-native-community/react-native-maps#3392]
# Question
Hi! Is it possible to use custom map style with apple maps? Thanks

**Comment by aesthytik** [comment]
did you found the solution? @adlme

**Comment by rborn** [comment]
Only google maps

**Comment by alexandrzavalii** [comment]
it's not possible to customize apple maps?

**Comment by alichampion** [comment]
Hi, Isn't it possible to customize apple maps?

**Comment by bodrius** [comment]
++++

**Comment by chramos** [comment]
is it possible?

**Comment by bzozoo** [comment]
It seems It is not possible

**Comment by iSaBo96** [comment]
But why? If the provider is not set to GOOGLE, what will be used? Maps from the operating system? 
Is it also possible to use open street maps? If so, can I style this?
