### ISSUE TITLE
White screen for 0.1-3 sec between splash and first App render

### ISSUE THREAD

**Issue by ExpoNfinity** [react-native-community/react-native-maps#3398]
# Bug

After upgrading to SDK37 I've noticed app shows empty white screen after splashscreen and before first render of App. I've tried to simplify render as much as possible but screen still there, its duration differs on different devices, debug and apk mode, sometimes not noticed at all, but we'd liked to control all output of app, at least in APK if not possible to reach maximum equality between production and debug.

**I suspect this white screen is related somehow to new Hint screen that introduces new debug menu and does not appear anymore after hittign Got it. I suspect this compo appears but disappers once checked what "we've got"**

## Environment info

`react-native info` output:

I have not react-native cli installed. Just upgraded to SDK37, upgrade went smooth, only with need to manually replace ScreenOrientation component, app function properly where checked.

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. Create splash screen. 
2. Put this simple view in App.js render
render() {
        return <View style={{height: '100%', width: '100%', backgroundColor: '#ff0000'}}/>
}
3. Run, you'll probably notice white screen after splash but before render

Describe what you expected to happen:

After splash screen first render that we'd like to see is render() of App.js

## Reproducible sample code

render() {
        return <View style={{height: '100%', width: '100%', backgroundColor: '#ff0000'}}/>
}

What else to add, we've tried to pass to createStackNavigator as much as possible styles to be sure that white screen is something we cannot control:

headerBackground: '#01132c',
    backBehavior: 'history',
    navigationOptions: {
      headerStyle:{
        marginTop: 0,
        backgroundColor: '#00ffff'
      }
    },
    defaultNavigationOptions: { 
        headerTintColor: 'transparent',
        headerBackTitleVisible: false,
        backTitle: '',
        headerStyle: { 
            width: 0,
            color: '#fff',
            height: 0,
            opacity: 1,
            backgroundColor: '#01132c',
        },
        headerTitleStyle:{
            fontSize: 14,
            fontWeight: '800',
            textAlign: 'center',
            flex: 1, // to make a header centered to the screen
        }
    }, 
    cardStyle: {
        opacity: 1,
        backgroundColor: '#01132c',
    },

Please assist.

**Comment by richardbumm** [comment]
This is a RN issue, not a maps issue

**Comment by ExpoNfinity** [comment]
Thx for response
