### ISSUE TITLE
Heatmap not working

### ISSUE THREAD

**Issue by cisplRejjak** [react-native-community/react-native-maps#3399]
My normal map is displaying but Heatmap is not working.

I have added the following code

import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';
let points = [
    {latitude: 6.83646681, longitude: 79.77121907, weight: 1},
    {latitude: 6.82776681, longitude: 79.871319, weight: 1},
    {latitude: 6.82176681, longitude: 79.871319, weight: 1}
];
..........

    <MapView
    provider={PROVIDER_GOOGLE}
    style={Style.mapStyle}
    region={this.state.region}
    showsUserLocation={true}
    followUserLocation={true}
    >
        <MapView.Heatmap points={points} />
    </MapView>

React Native:0.61.1
react-native-maps:0.27.1

**Comment by rborn** [comment]
Please update the issue following the template or I'll delete it

**Comment by rborn** [comment]
Closing, no reply
