### ISSUE TITLE
Expo project crashes during MapView rendering

### ISSUE THREAD

**Issue by stexniolo** [react-native-community/react-native-maps#3405]
# Attempted import error : 'requireNativeComponent' is not exported from 'react-native-web/dist/index'

Hello everyone, i'm using the module 'react-native-maps' on my Expo project (React Native). Until a few days ago everything worked well, but not anymore. When i try to open a screen that use MapView component, my app crashes without leaving logs or error messages. Thus i tried to open the project in web browser and it showed me this error: 
![2020-04-24 (3)](https://user-images.githubusercontent.com/53082287/80228779-c393c080-864f-11ea-824e-300a10cbb17f.png)

It seems that MapView is missing something called _nativeComponent_. I am pretty confused because i was able to use this module perfectly and now this problem came out without reasons and without changing my code.

## Environment info

`react-native info` output:

```bash
 System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 3.10 GB / 7.92 GB
  Binaries:
    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

Library version: 0.26.1

## Steps To Reproduce

1. I have a simple button which, if pressed, it opens the map
2. after pressing the button the application crashes without logs

## Reproducible sample code

Here's my code:

     <MapView style={styles.map}
        showsUserLocation= {true}
        region={{
            latitude: this.state.latitude,
            longitude: this.state.longitude,
            latitudeDelta: 0.3,
            longitudeDelta: 0.3
       }}>
    {this.state.dataSource.map(event => 
        <MapView.Marker 
          key = {event.id}
          coordinate={{
          latitude: event.location.latitudine,
          longitude: event.location.longitudine,
          latitudeDelta: 0.4,
          longitudeDelta: 0.4
        }}
        title = {JSON.stringify(this.state.latitude)}
        description = {event.description}/>
    )}
    </MapView>

**Comment by rborn** [comment]
Did you update any module? Did you run pod install ?

**Comment by stexniolo** [comment]
No, should i? What does _pod_ do?
It's weird because i ran the project with an emulator and another smartphone and the problem doesn't appear.

**Comment by rborn** [comment]
Sorry, ignore me, I didn't see you are on Android. 
Try to delete the app form device and try again maybe ?

But I can't help much, this is Expo, and it's somehow outside the scope of this repo

**Comment by stexniolo** [comment]
Unforunately deleting app from devide didn't solve the problem. At this point I believe that I will continue to work on another device :joy::joy:

**Comment by ShahNafisRafique** [comment]
Hello I am using expo and I have the same issue where the rendering of the map causes the app to crash. I am not sure what I have to provide so for now I will just show my `package.json` and `app.js` file. Theres some extra stuff like react-navigation.

# Package.json

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.13",
    "expo": "~37.0.3",
    "expo-camera": "^8.2.0",
    "expo-image-picker": "^8.1.0",
    "expo-location": "^8.1.0",
    "expo-permissions": "^8.1.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-maps": "^0.27.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
  "private": true
}
```

# App.js

```js
import * as React from 'react';
import { Button, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import MapView from 'react-native-maps';

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <MapView />
      <Button
        title="Button"
        onPress={() =>console.log('hi')}
      />
    </View>
  );
}

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by ShahNafisRafique** [comment]
An update, since I am using this package for a class project I had one of my group members run the project on an iOs simulator with expo, we received an error about package `uuid-js` not being installed.  So we ran `npm i uuid-js`, deleted `package-lock.js` and `node_modules` folder, reinstalled with `npm install` and everything works now. 

It seems the key fix was the `uuid-js` package, although I am unsure what happened to cause it to not be there nor why running the app on an android app just crashes the expo without any errors or warnings.

**Comment by stexniolo** [comment]
The problem was solved simply by uninstalling and reinstalling Expo from my device.

**Comment by rborn** [comment]
closing as solved
