### ISSUE TITLE
ERROR OCCURED WHEN RUN "pod install"

### ISSUE THREAD

**Issue by bayorwor** [react-native-community/react-native-maps#3411]
**I get this error after installing react-native-google-places. It happens when I try running "pod install"**

# Question
[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
  In Podfile:
    GoogleMaps

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.27.1, which depends on
      GoogleMaps (= 3.5.0)

    react-native-google-places (from `../node_modules/react-native-google-places`) was resolved to 3.1.2, which depends on
      GoogleMaps (~> 3.1.0)

**Comment by rborn** [comment]
There are various issues related to react-native-google-places, try some solutions offered there. 
I'll close this as it's duplicate
