### ISSUE TITLE
zoom to street level

### ISSUE THREAD

**Issue by js08** [react-native-community/react-native-maps#3412]
hi,

- I  am implementing react native maps, in that I am able to shop maps and polyline between the coordinates.
- when the car reaches the destnation, I need to zoom ito street level.
- can you tell me how to achieve it.
- I googled but couldn't find any solutions.
- providing my code below in a gist.
- declared all my car coordinates inside my  let routes array.
- can you guys provide your inputs

https://gist.github.com/js08/da6378f91fe429eb627ded58b04903d6

**Comment by rborn** [comment]
Please update your issue with the template or I'll close it.

**Comment by js08** [comment]
Hi, thanks for your reply, I have posted the code in gist, can you let me know what you need

**Comment by sohustar** [comment]
Hi! I am freelancer!
I read your issues i want to discuss more with chat.
I am fullstack web developer and GIS expert.
So i am very interested in your project.
I am sure i can help you.
I will wait you!

This is my skype id live:.cid.de69aa52a59ffc4f.

**Comment by rborn** [comment]
@js08 when you start an issue there is a template in place, which you fully deleted and added just your text. This is used for easy triage if the issues.
