### ISSUE TITLE
Style/TextAppearence not found

### ISSUE THREAD

**Issue by marcilioware** [react-native-community/react-native-maps#3413]
# Bug

Try to build android APK with ./gradlew assembleRelease fails with following stack:

Execution failed for task ':react-native-maps:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     AAPT: /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_big_media_custom.xml:63: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_big_media_custom.xml:71: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_big_media_custom.xml:79: error: resource style/TextAppearance.Compat.Notification.Info.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Info.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_big_media_narrow_custom.xml:66: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_big_media_narrow_custom.xml:74: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_big_media_narrow_custom.xml:82: error: resource style/TextAppearance.Compat.Notification.Info.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Info.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_lines_media.xml:36: error: resource style/TextAppearance.Compat.Notification.Title.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Title.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_lines_media.xml:45: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_lines_media.xml:56: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_lines_media.xml:68: error: resource style/TextAppearance.Compat.Notification.Line2.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Line2.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_lines_media.xml:90: error: resource style/TextAppearance.Compat.Notification.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_lines_media.xml:100: error: resource style/TextAppearance.Compat.Notification.Info.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Info.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_media_custom.xml:55: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_media_custom.xml:63: error: resource style/TextAppearance.Compat.Notification.Time.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Time.Media) not found.
     /Users/christopherdro/Desktop/OSS/react-native-maps/lib/android/build/intermediates/res/merged/release/layout/notification_template_media_custom.xml:71: error: resource style/TextAppearance.Compat.Notification.Info.Media (aka com.airbnb.android.react.maps:style/TextAppearance.Compat.Notification.Info.Media) not found.
     error: failed linking file resources.

## Environment info

`react-native info` output:
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 2.64 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /var/folders/sm/x82xkbd13ld129p0bbv6rllh0000gn/T/yarn--1588350718872-0.5231404996180049/node
    Yarn: 1.21.1 - /var/folders/sm/x82xkbd13ld129p0bbv6rllh0000gn/T/yarn--1588350718872-0.5231404996180049/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

Library version: 0.27.1

## Steps To Reproduce

1. run yarn react-native run-android (everthing works ok)
2. run ./gradlew assembleRelease doesn't woks with above output
...

Describe what you expected to happen:

1. apk generated with success

## Workaround
Back to version 0.26.0 works fine.

**Comment by Brianop** [comment]
I fixed it by running ./gradlew clean

**Comment by joshuapinter** [comment]
I'm getting this as well and it would seem that there is something in the library itself that is hardcoded to the author, @christopherdro's, local file structure. I did a search and surprisingly, could not find anything showing the file path `/Users/christopherdro/Desktop/OSS/react-native-maps/` or anything like it. 

Maybe @christopherdro knows where this is being set.

**Comment by joshuapinter** [comment]
@marcilioware Because you said going back down to 0.26.0 didn't have this issue, I did a comparison between 0.26.0 and 0.27.1: 

https://github.com/react-native-maps/react-native-maps/compare/v0.26.0...v0.27.1

But I still couldn't find anything that would produce that hard-coded file path.
