### ISSUE TITLE
MapView customMapStyle is not working 

### ISSUE THREAD

**Issue by Shubham740** [react-native-community/react-native-maps#3421]
Custom Map style is not working in react native maps 

          <MapView
          customMapStyle={getCustomMapStyle()}
            style={styles.mapContainer}
            scrollEnabled={true}
            ref={this.mapRef}>
            {this.state.markerArr && this.state.markerArr.length >= 1 && (
              <View>
                <Marker
                  coordinate={this.state.markerArr[0].coordinate}
                  image={userLocation}
                  width={1000}
                  height={1000}>
                  </Marker>
              </View>
            )}
{this.state.waypoints != null &&
              this.state.waypoints.length > 0 &&
              this.state.waypoints.map((waypoint, index) => (
                <View key={index}>
                  <Marker
                    coordinate={waypoint}
                    image={markerImage}
                    width={1000}
                    height={1000}
                  />
                </View>
              ))}
            {this.state.currentLocation != null &&
              this.state.currentLocation.latitude != null && (
                <Marker
                  coordinate={this.state.currentLocation}
                  image={shuttleBlue}
                >
                    <Callout>
              <Text
              style={styles.myCurrentLocationTextStyle}
              >{LABLES.MY_CURRENT_LOCATION}</Text>
                  </Callout>
                  </Marker>
              )}

            {this.state.otherShuttleCoordinatesArray != null &&
              this.state.otherShuttleCoordinatesArray.length > 0 &&
              this.state.otherShuttleCoordinatesArray.map(
                (otherShuttleVendorItem, index) => (
                  <View key={index}>
                    <Marker
                      coordinate={otherShuttleVendorItem}
                      image={shuttleYellow}
                      width={1000}
                      height={1000}
                    >
                     

                      </Marker>
                  </View>
                ),
              )}
            {this.state.otherShuttleCoordinatesArray != null &&
            this.state.otherShuttleCoordinatesArray.length > 0 ? (
              <MapView.Polyline
                coordinates={this.state.otherShuttleCoordinatesArray}
                strokeWidth={5}
                strokeColor="rgb(55,151,239)"
              />
            ) : (
              <View />
            )}
            {this.state.destinationCoordinates &&
              this.state.destinationCoordinates.latitude != null && (
                <Marker
                  coordinate={this.state.destinationCoordinates}
                  image={userLocation}
                  width={1000}
                  height={1000}
                />
              )}

            {this.state.currentLocation != null &&
              this.state.destinationCoordinates != null && (
                <MapViewDirections
                  origin={this.state.currentLocation}
                  apikey={Config.GooglePlaceAPIKey}
                  destination={this.state.destinationCoordinates}
                  optimizeWaypoints={true}
                  mode="DRIVING"
                  strokeColor={Colors.THEME_COLOR}
                  strokeWidth={strokeWidth}
                  waypoints={this.state.waypoints}
                />
              )}
          </MapView>

customMap Style json :

[
    {
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#f5f5f5"
        }
      ]
    },
    {
      "elementType": "labels.icon",
      "stylers": [
        {
          "visibility": "off"
        }
      ]
    },
    {
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#616161"
        }
      ]
    },
    {
      "elementType": "labels.text.stroke",
      "stylers": [
        {
          "color": "#f5f5f5"
        }
      ]
    },
    {
      "featureType": "administrative.land_parcel",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#bdbdbd"
        }
      ]
    },
    {
      "featureType": "poi",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#eeeeee"
        }
      ]
    },
    {
      "featureType": "poi",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#757575"
        }
      ]
    },
    {
      "featureType": "poi.park",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#e5e5e5"
        }
      ]
    },
    {
      "featureType": "poi.park",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#9e9e9e"
        }
      ]
    },
    {
      "featureType": "road",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#ffffff"
        }
      ]
    },
    {
      "featureType": "road.arterial",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#757575"
        }
      ]
    },
    {
      "featureType": "road.highway",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#dadada"
        }
      ]
    },
    {
      "featureType": "road.highway",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#616161"
        }
      ]
    },
    {
      "featureType": "road.local",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#9e9e9e"
        }
      ]
    },
    {
      "featureType": "transit.line",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#e5e5e5"
        }
      ]
    },
    {
      "featureType": "transit.station",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#eeeeee"
        }
      ]
    },
    {
      "featureType": "water",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#c9c9c9"
        }
      ]
    },
    {
      "featureType": "water",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#9e9e9e"
        }
      ]
    }
  ]

**Comment by rborn** [comment]
This only works for google maps
