### ISSUE TITLE
the mapType="mutedStandard" prop crashes app.

### ISSUE THREAD

**Issue by reddo** [react-native-community/react-native-maps#3428]
# Bug

Adding `mapType="mutedStandard"` to <MapView /> causes the following error:

![image](https://user-images.githubusercontent.com/1180060/81484908-183f5a00-9252-11ea-8fc3-422535c45aec.png)

Library version: 0.27.1

**Comment by naveenprakash74** [comment]
The map type to be displayed.

- standard: standard road map (default)
- none: no map Note Not available on MapKit
- satellite: satellite view
- hybrid: satellite view with roads and points of interest overlayed
- terrain: (Android only) topographic view
**- mutedStandard: more subtle, makes markers/lines pop more (iOS 11.0+ only)**

**Comment by reddo** [comment]
I don't know how I could have overlooked that. 
In this case, shouldn't it be ignored on Android or fall back to standard?
