### ISSUE TITLE
i got error in android build

### ISSUE THREAD

**Issue by alib1989** [react-native-community/react-native-maps#3432]
hello 
i got this error when i build for android

/Users/user/Desktop/Works/App/App/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/FusedLocationSource.java:43: Error: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException [MissingPermission]
          fusedLocationClientProviderClient.getLastLocation().addOnSuccessListener(new OnSuccessListener<Location>() {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/user/Desktop/Works/App/App/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/FusedLocationSource.java:59: Error: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException [MissingPermission]
          fusedLocationClientProviderClient.requestLocationUpdates(locationRequest, locationCallback, Looper.myLooper());
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by peiqinli** [comment]
I got the exact same error, any update on this?

**Comment by kukuandroid** [comment]
How do you fix this ?

**Comment by 99uno** [comment]
Same issue!

**Comment by NazarNazaryshyn** [comment]
Did anyone fix this?
