### ISSUE TITLE
my device doesnt support google play service

### ISSUE THREAD

**Issue by js08** [react-native-community/react-native-maps#3433]
### Is this a bug report?

no

**If my device doesn't support google play service, can I still react-native-maps working**

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
Sadly no, this module is built on GoogleMaps (android) so it needs to have Google Play Services

**Comment by Udbhav12** [comment]
@rborn Can you please let me know the minimum Google Play Service Version required in Android phone for react-native-maps to work ?

 RN Version - 0.62.2
 react-native-maps: 0.26.1
