### ISSUE TITLE
Require cycle in react-native-maps

### ISSUE THREAD

**Issue by tranvanquang** [react-native-community/react-native-maps#3439]
Require cycle: node_modules/react-native-maps/lib/components/MapView.js -> node_modules/react-native-maps/lib/components/MapPolygon.js -> node_modules/react-native-maps/lib/components/MapView.js

Require cycle: node_modules/react-native-maps/lib/components/MapView.js -> node_modules/react-native-maps/lib/components/Geojson.js -> node_modules/react-native-maps/lib/components/MapView.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

Can u help me fix warning :( Thanks u so much

    "react-native-maps": "^0.27.1",
    "react-native": "^0.62.1",
    "react": "16.9.0",

**Comment by FanchenBao** [comment]
See the solution suggested here: https://github.com/react-native-community/react-native-maps/issues/3352#issuecomment-630168111

**Comment by tranvanquang** [comment]
Oke, I'm trying

**Comment by rborn** [comment]
Duplicate, and no template
