### ISSUE TITLE
Styling GeoJSON markers

### ISSUE THREAD

**Issue by systemallica** [react-native-community/react-native-maps#3450]
# Question

Hi, I am using the `Geojson` component to add several markers to the map. The problem is I cannot find documentation on how to style these markers.

- How can I change the Icon, Color, etc.?

- Can I pass some props to the component to do this? Or should I modify the GeoJSON file in some way?

**Comment by Covicake** [comment]
With the PR merged, this issue should be closed, right?

**Comment by systemallica** [comment]
Yes, indeed!
