### ISSUE TITLE
Use of undeclared identifier 'GMSServices'

### ISSUE THREAD

**Issue by wikramdas** [react-native-community/react-native-maps#3453]
# Bug report

## Summary

Use of undeclared identifier 'GMSServices'.
I am receiving this issue while my library is up to date

## Environment info

`react-native info` output:

```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 79.68 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 0.27.1

My AppDelegate.m file
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

#import <GoogleMaps/GoogleMaps.h>
#import <Firebase.h>
//@import GooglePlaces;
//@import GoogleMaps;
static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  #if DEBUG
    InitializeFlipper(application);
  #endif
  
  NSURL *jsCodeLocation;
  [GMSServices provideAPIKey:@"APIKey"];
  [FIRApp configure];
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"CustomerApp"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

**Comment by arinconc** [comment]
I have the same error.
When compiling for release I also have these errors: 

error: use of undeclared identifier 'FIRApp' if ([FIRApp defaultApp] == nil) {
error: use of undeclared identifier 'FIRApp' [FIRApp configure];
error: use of undeclared identifier 'GMSServices' [GMSServices provideAPIKey ...

But it doesn't happen to me in Debug!
Help please!

**Comment by wikramdas** [comment]
I solved this issue kindly import these files from above to #if DEBUG mode.
```
#import <GoogleMaps/GoogleMaps.h>
#import <Firebase.h>
```
Thanks

**Comment by Ajmal0197** [comment]
Put librarries above #if DEBUG

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"  // here
#import <GoogleMaps/GoogleMaps.h>
#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

**Comment by king-faraz** [comment]
#import <GoogleMaps/GoogleMaps.h>
add this line in Appdeligate.m 
google maps must be the first import after appdeligate.h 
this is how it works for me believe it or not

**Comment by ghostrydr** [comment]
I ran into the same issue, and after some trial and error I was able to determine that 

`#import <GoogleMaps/GoogleMaps.h>`

Needs to come before your `Flipper` imports.

**Comment by ProkhoDim** [comment]
> I solved this issue kindly import these files from above to #if DEBUG mode.
> 
> ```
> #import <GoogleMaps/GoogleMaps.h>
> #import <Firebase.h>
> ```
> 
> Thanks

This solution helped me!

**Comment by code2514** [comment]
> > I solved this issue kindly import these files from above to #if DEBUG mode.
> > ```
> > #import <GoogleMaps/GoogleMaps.h>
> > #import <Firebase.h>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks
> 
> This solution helped me!

This solution worked for me too

**Comment by rr180enovate** [comment]
This solution worked for me too

**Comment by pyagmyrov** [comment]
> I solved this issue kindly import these files from above to #if DEBUG mode.
> 
> ```
> #import <GoogleMaps/GoogleMaps.h>
> #import <Firebase.h>
> ```
> 
> Thanks

if you are using .swift. 
```
import GoogleMaps
```
is fixed my issue
