### ISSUE TITLE
How do you set the size for a Marker?

### ISSUE THREAD

**Issue by codingdudecom** [react-native-community/react-native-maps#3455]
# Question

I have a marker like this:
```JS
            <Marker
              title={marker.key}
              image={mapPinImg}
              key={marker.key}
              coordinate={marker.coordinate}
              style={styles.marker}
            ></Marker>

const styles = StyleSheet.create({
  marker: { width: 160 },
});
```

But the width property does not do anything. I tried also using a larger image for the marker, but that's not working either.

What's the correct way for setting the size for the markers?

thanks!
John

**Comment by pROFESOR11** [comment]
Hi @codingdudecom ,
try this:
```
<Marker ...>
 <Image style={{ width: 160, height: 160 }} />
</Marker>
```

**Comment by codingdudecom** [comment]
Thanks! it works

I used `resizeMode: "contain"` because the image was cropped. And also I had to set the same size on the `Marker` too because the placement of the marker was not correct


```
<Marker style={{width: 48, height: 48}}>
        <Image
                      source={require("../assets/map-pin.png")}
                      style={{ width: 48, height: 48, resizeMode: "contain" }}
                    />
</Marker>
```

**Comment by rajanAndroapps** [comment]
Just put the image or svg icon inside View
<Marker style={styles.marker} coordinate={{latitude: lat, longitude: long,}}>
      <View>
      <AutoRikshawIcon style={styles.autoRikshawIcon}/>
      </View>
    </Marker>

**Comment by rajanAndroapps** [comment]
Just put the svg or image icon inside <View> tag also give width and height to Svg
<Marker style={styles.marker} coordinate={{latitude: lat, longitude: long,}}>
      <View>
      <AutoRikshawIcon style={styles.autoRikshawIcon}/>
      </View>
    </Marker>

**Comment by rajanAndroapps** [comment]
Just put the svg or image icon inside tag also give width and height to Svg

**Comment by abhion** [comment]
> Thanks! it works
> 
> I used `resizeMode: "contain"` because the image was cropped. And also I had to set the same size on the `Marker` too because the placement of the marker was not correct
> 
> ```
> <Marker style={{width: 48, height: 48}}>
>         <Image
>                       source={require("../assets/map-pin.png")}
>                       style={{ width: 48, height: 48, resizeMode: "contain" }}
>                     />
> </Marker>
> ```

this does not work. Anyone else have any other solution?

**Comment by abhion** [comment]
> Hi [@codingdudecom](https://github.com/codingdudecom) , try this:
> 
> ```
> <Marker ...>
>  <Image style={{ width: 160, height: 160 }} />
> </Marker>
> ```

this didn't work

**Comment by NitayMG** [comment]
Does anybody have a solution?
