### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleMaps":

### ISSUE THREAD

**Issue by wmonecke** [react-native-community/react-native-maps#3459]
# Bug report

Hi!

I updated to RN 0.62.2 and also updated react-native-maps to the latest version (0.27.1) and got the following error:

````
[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
  In Podfile:
    GoogleMaps

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.27.1, which depends on
      GoogleMaps (= 3.5.0)

    react-native-google-places (from `../node_modules/react-native-google-places`) was resolved to 3.1.2, which depends on
      GoogleMaps (~> 3.1.0)
````

I tried running `pod update` with no success. Also deleted pods, cleared cache and ran `pod install` and still had this conflict. Any ideas? I am not really savvy about Pods.

## Podfile

````
 # react-native-maps dependencies
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
````

**Comment by christopherdro** [comment]
run `pod repo update` then run `pod install` again

**Comment by jimsheen** [comment]
Still having the same issue `pod repo update` and `pod install` didn't work for me

**Comment by irvinSing** [comment]
@jimsheen if you haven't tried this, you might need to remove podfile.lock before executing pod repo update.

**Comment by vhurryharry** [comment]
I am having the same issue and tried the following:
`pod deintegrate`
`rm podfile.lock`
`pod repo update`
`pod install`

But still having the issue. Is there any other way to fix this problem? Thanks!

**Comment by L0rdCr1s** [comment]
hey guys, did anyone find a solution for this, I'm stuck with the same problem

**Comment by nschild** [comment]
`pod update GoogleMaps` worked for me to upgrade to 3.5.0. Might need to run `pod repo update` first

**Comment by L0rdCr1s** [comment]
I deleted Pods folder, Podfile.lock and node_modules folder then did yarn install but when I do pod install I get this error

```
Auto-linking React Native modules for target `customerapp`: RNCAsyncStorage, RNCMaskedView, RNDateTimePicker, RNGestureHandler, RNPermissions, RNReanimated, RNSVG, RNScreens, RNVectorIcons, ReactNativeLocalization, lottie-react-native, react-native-geolocation, react-native-google-places, react-native-maps, react-native-netinfo, react-native-onesignal, react-native-safe-area-context, react-native-splash-screen, and react-native-webview
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
  In Podfile:
    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.27.1, which depends on
      GoogleMaps (= 3.5.0)

    react-native-google-places (from `../node_modules/react-native-google-places`) was resolved to 3.1.2, which depends on
      GoogleMaps (~> 3.1.0)

Specs satisfying the `GoogleMaps (= 3.5.0), GoogleMaps (~> 3.1.0)` dependency were found, but they required a higher minimum deployment target.
```

and `pod update` GoogleMaps doesn't work without Podfile.lock

**Comment by L0rdCr1s** [comment]
after a lot of trials i found a solution, somehow react-native-google-places GoogleMaps version was conflicting with react-native-maps so i had to apply a patch to update it to GoogleMaps version 3.5.0

here [https://gist.github.com/alekseyanikin/fb731613a0ff541d97b92da13aacbc05](url)

i used patch-package to apply it, if you don't know how to use it like i didn't, create a folder called `patches` on the root of your project directory and then paste the `.patch` file from the link.

after that install patch-package by running `yarn add --dev patch-package postinstall-prepare` after installing run `yarn patch-package`

if everything went well `pod install` should work fine now

**Comment by NachoJusticia** [comment]
I solved it like this:
- I checked my `node_modules/react-native-maps/react-native-google-maps.podspec` and I have the following versions:

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
...
  s.dependency 'GoogleMaps', '5.1.0'
  s.dependency 'Google-Maps-iOS-Utils', '3.10.3'
...
```

- then I updated my `Podfile` like this:
```
    rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path
    pod 'GoogleMaps', '5.1.0' # <<<<---- I added the '5.1.0' version here
    pod 'Google-Maps-iOS-Utils', '3.10.3' # <<<<---- I added the '3.10.3' version here
```

- I ran `pod install` and I got this error: `[!] The platform of the target `inguru` (iOS 10.0) may not be compatible with `GoogleMaps (5.1.0)` which has a minimum requirement of iOS 11.0.` 
- I updated the minimum required build version to `11.0` on top of my `Podfile`:
```
platform :ios, '10.0'
```

- I ran `pod install` again and everything worked.

**Comment by FanchenBao** [comment]
I followed the suggestion from @NachoJusticia , but I need to run `pod install --repo-update` to apply the version specifications.

**Comment by hlspablo** [comment]
![image](https://user-images.githubusercontent.com/16579563/179067793-2ffcf911-e42c-42b6-958b-fdda23a92c61.png)
Change this in the Xcode and in Podfile

**Comment by mucluck** [comment]
For `Expo` users:

https://docs.expo.dev/versions/latest/sdk/build-properties/

**Comment by AqeelAsghar** [comment]
go to you Podfile 
update platform :ios, '10.0'
to platform :ios, '13.0'
and then install pod

**Comment by Josiassejod1** [comment]
delete your Podfile.lock and reinstall

**Comment by Shailja-niranjan** [comment]
@AqeelAsghar when i tried your solution , app is getting crashed on map screen in app.

**Comment by VLadislav9607** [comment]
I deleted dependencies versions in node_modules/react-native-maps/react-native-google-maps.podspec  

 s.dependency 'React-Core'
 s.dependency 'GoogleMaps'
 s.dependency 'Google-Maps-iOS-Utils'
 
 It works for me

**Comment by LukaBabunadze** [comment]
> pod install --repo-update



> If someone got this type of issue in 2023, deleting package-lock.json followed by podfile.lock might help. If still issue is not resolved for you, look for ^(caret) sign before react-native-maps in package.json and remove it. And then try `npm install` & `pod install`

Works for me, thanks!!!

**Comment by Rustamyan94** [comment]
In the Podfile you can find the line "platform :ios, 13.4". change the iOS version as in the node_modules/react-native-maps/react-native-google-maps.podspec IOS version

**Comment by RaguRam1991** [comment]
pod 'Google-Maps-iOS-Utils', '4.2.2'

worked for me.

**Comment by umairbutt088** [comment]
> I am using:
> 
> ```
> React-Native: v0.73.2
> Node - 18.19.0
> Yarn: 1.22.21
> Cocoapods: 1.15.0
> Xcode 15.2
> ```
> 
> And I tried to use `"react-native-maps": "^1.7.1"`
> 
> This is my case:
> 
> ![Screenshot 2024-01-30 at 18 13 03](https://private-user-images.githubusercontent.com/57877361/300767164-9cd9b1f6-be2b-42ab-bea3-fa7368624424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTQ0NzUsIm5iZiI6MTcxNTI1NDE3NSwicGF0aCI6Ii81Nzg3NzM2MS8zMDA3NjcxNjQtOWNkOWIxZjYtYmUyYi00MmFiLWJlYTMtZmE3MzY4NjI0NDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDExMjkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYTY3YTIyNWZlMTRjZGQzOWJiOGVkOWQ4OGU1NGEyZmZkMmNiZGYyNjIyZjNhNzlhOGVmMGIyMGY5NWJhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sU3p5FGxk8Q1L8xT2eb4B7nrSM9uB47_N_tuUWA_nyM)
> 
> [!] CocoaPods could not find compatible versions for pod "react-native-google-maps": In Podfile: react-native-google-maps (from `../node_modules/react-native-maps`)
> 
> Specs satisfying the `react-native-google-maps (from `../node_modules/react-native-maps`)` dependency were found, but they required a higher minimum deployment target.
> 
> After changing the minimum deployment target version to 13.4, I can run it.

Thanks a lot! It saved my whole day.

**Comment by Tchaikovsky1114** [comment]
> I solved it like this:
> 
> * I checked my `node_modules/react-native-maps/react-native-google-maps.podspec` and I have the following versions:
> 
> ```
> require 'json'
> 
> package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
> 
> Pod::Spec.new do |s|
> ...
>   s.dependency 'GoogleMaps', '5.1.0'
>   s.dependency 'Google-Maps-iOS-Utils', '3.10.3'
> ...
> ```
> 
> * then I updated my `Podfile` like this:
> 
> ```
>     rn_maps_path = '../node_modules/react-native-maps'
>     pod 'react-native-google-maps', :path => rn_maps_path
>     pod 'GoogleMaps', '5.1.0' # <<<<---- I added the '5.1.0' version here
>     pod 'Google-Maps-iOS-Utils', '3.10.3' # <<<<---- I added the '3.10.3' version here
> ```
> 
> * I ran `pod install` and I got this error: `[!] The platform of the target `inguru`(iOS 10.0) may not be compatible with`GoogleMaps (5.1.0)` which has a minimum requirement of iOS 11.0.`
> * I updated the minimum required build version to `11.0` on top of my `Podfile`:
> 
> ```
> platform :ios, '10.0'
> ```
> 
> * I ran `pod install` again and everything worked.

thank you sir. i really appreciate your tip..!!

**Comment by lucasbachega** [comment]
My solution for React Native 0.76 was to set:

`pod 'Google-Maps-iOS-Utils', '6.1.0'`

using 'react-native-maps': '^1.23.7'
