### ISSUE TITLE
development and production keys

### ISSUE THREAD

**Issue by activebiz** [react-native-community/react-native-maps#3460]
# Question

I have already asked this question on stackoverflow and it has been voted down without any comments!!! 

https://stackoverflow.com/questions/62284228/react-native-maps-development-and-production-keys

I am gonna post the same question here I would be greatful if someone can help ?  Please let me know if you requires specific information. 

Is there a way to dynamically loading google provider keys (for ios and android) for development and production? Ideally would like to have one for local/dev/uat and one for production.

Is there a preferred way to do this in rn-maps/rn?

Thanks

**Comment by christopherdro** [comment]
There is no preferred way, it all depends on your setup or preference. Instead of hardcoding your api key you can use something like https://github.com/luggit/react-native-config then configure your `.env` based on what environment you're trying to deploy to.

**Comment by activebiz** [comment]
You cant be storing these keys in .env files. Its not secure.even the library users are not recommanding this.  https://github.com/luggit/react-native-config/issues/336

Anyway, I thought it was a genuine question to ask.
