### ISSUE TITLE
Custom Callout

### ISSUE THREAD

**Issue by DarshiniKenkere** [react-native-community/react-native-maps#3471]
# Feature request
Is it possible to show MapView callouts as a react native Modal at the bottom of the screen? with multiple clickable buttons?
Like this: 

![example](https://user-images.githubusercontent.com/67251560/85246082-f100bd00-b48c-11ea-9bfd-ac387cc00e2d.jpg)

I tried multiple ways to do so, creating a modal works on IOs( but slow) but doesn't show anything on android

**Comment by nvhungkt** [comment]
How about not using Callout, but use View instead, you can invoke a function to show the View when pressing on Marker, and dismiss it by pressing anywhere else on MapView

**Comment by DarshiniKenkere** [comment]
@nvhungkt It works like a charm. I removed callout and now using Modal for the custom view. Thank you so much

**Comment by PSainz** [comment]
Hi, @DarshiniKenkere  can you please share the code of how yo did it please¿? Thanks!
