### ISSUE TITLE
map marker not showing up

### ISSUE THREAD

**Issue by haziqfiqri** [react-native-community/react-native-maps#3474]
Given example of hardcoded coordinate below.
```
const items = [
    {id: 1, coordinate: { latitude: 37.78825, longitude: -122.4324 }},
    {id: 2, coordinate: { latitude: 37.78835, longitude: -122.4324 }},
    {id: 3, coordinate: { latitude: 37.78845, longitude: -122.4324 }},
    {id: 4, coordinate: { latitude: 37.78855, longitude: -122.4324 }},
]
```
I'm trying to show markers on the map by react-native-maps. However the marker does not show up, can anyone tell me where I did wrong? Any help is appreciated. Below is how I try to map all the coordinates. The map is being displayed but not the marker. Anyone can tell me what did I miss or did wrong? Any help is appreciated.
```
import React from 'react'
import MapView, { Marker } from 'react-native-maps'

const Test: React.FC = () => { 
    return ( 
        <MapView initialRegion={{latitude: 37.78825, longitude: -122.4324, latitudeDelta: 0.0922, longitudeDelta: 0.0421}}>
           {items.map((item) => {
              <Marker key={`test-${item.id}`} coordinate={item.coordinate}/>
           })}
        </MapView>
    )
}
export default Test
```
I'm using my android phone as the emulator. Using ```"react-native": "0.62.2"``` and ``` "react-native-maps": "^0.27.1"```

**Comment by haziqfiqri** [comment]
I forgot to put ```return``` after mapping all coordinates

**Comment by Imran109** [comment]
> I forgot to put `return` after mapping all coordinates

This saved my day!. I did the same mistake.

**Comment by oier27** [comment]
Thanks for remembering the `return`!

**Comment by AkbarEZMD** [comment]
when NewArchEnable = true than use latest version of maps and if you have old architecture like NewArchEnable= false than use react-native-maps@1.18.0 than it works in my case.
