### ISSUE TITLE
Bing Maps Support

### ISSUE THREAD

**Issue by treywhite21** [react-native-community/react-native-maps#3488]
# Question
Hi, I've looked around a little bit. I think I already know the answer but figured it couldn't hurt to ask: does this support Bing Maps? I know they have an Android and iOS SDK, but it appears that this library doesn't support Bing Maps.

Thanks!

**Comment by charleycesar** [comment]
Is there anyone who uses bing maps?

**Comment by rcstanciu** [comment]
We've been using Bing Maps for a web app that targets people from Eastern Europe, as we've found that Bing offers the best quality and the most recent tiles for that particular area.

Although Bing Maps can now be used by using an `UrlTile` (example here https://github.com/react-native-community/react-native-maps#using-a-custom-tile-overlay) (retrieving the tile URLs from https://docs.microsoft.com/en-us/bingmaps/rest-services/directly-accessing-the-bing-maps-tiles), this comes with a great cost on performance and network traffic.

**Comment by treywhite21** [comment]
@rcstanciu Thanks Rares. Not a terrible workaround. 👍
