### ISSUE TITLE
unresponsive map. UI thread is 100% busy when opening map in ios

### ISSUE THREAD

**Issue by EhsanSarshar** [react-native-community/react-native-maps#3502]
I just reopen this issue [Unresponsive map](https://github.com/react-native-community/react-native-maps/issues/3066#issue-494864587)

I just open the map there is not any marker or any thing but the UI thread is 100% busy.
I am using 
```
react native 0.62.2
react-native-maps 0.27.1
```

**Comment by rborn** [comment]
I reopened the original
