### ISSUE TITLE
ios can't display google map normally

### ISSUE THREAD

**Issue by AKclown** [react-native-community/react-native-maps#3520]
environment |  
-- | --
 "expo": "^38.0.0",
 "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",

Code：
![image](https://user-images.githubusercontent.com/33648653/89484533-4db3ff00-d7d1-11ea-9f63-af2f73317edd.png)

view：
![IMG_0825](https://user-images.githubusercontent.com/33648653/89484571-602e3880-d7d1-11ea-9d9c-e0e6bab4ebf4.PNG)

Android is normal， **do not add provider={PROVIDER_GOOGLE}**  ios is also normal

 Google Maps iOS base map not rendering  

How to solve it   thanks

**Comment by AKclown** [comment]
Found the reason because it was useless to overturn the wall

**Comment by pooja-wal** [comment]
@AKclown , I am facing the same issue. Could you please elaborate on what the reason is?

**Comment by pooja-wal** [comment]
Found the fix. In my case I had developed everything correctly but I just forgot to enable maps SDK for iOS from the google developer console for my app.

**Comment by mnjsnj** [comment]
Please check you package name in ios  you can verify or change your package name by opening the project in xcode
