### ISSUE TITLE
unable to show google maps in ios.

### ISSUE THREAD

**Issue by christopher-18** [react-native-community/react-native-maps#3536]
I want to show google maps in iOS. But getting errors.
I have added the following in my podfile.
```
rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
```
My podile contains the `use_framework! `
Therefore in order to remove the pod error for transitive dependency I have added the following

```
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```

I have followed the instructions from the :
https://github.com/googlemaps/google-maps-ios-utils/blob/b721e95a500d0c9a4fd93738e83fc86c2a57ac89/Swift.md
 
This is something which I did following the link:

<img width="263" alt="Screenshot 2020-08-22 at 11 52 33" src="https://user-images.githubusercontent.com/23613887/90950358-28302200-e46e-11ea-9d92-d7376c5b4f8d.png">
<img width="291" alt="Screenshot 2020-08-22 at 17 02 43" src="https://user-images.githubusercontent.com/23613887/90955232-71e23200-e499-11ea-83c3-deadc2070e5b.png">
<img width="412" alt="Screenshot 2020-08-22 at 17 02 52" src="https://user-images.githubusercontent.com/23613887/90955235-74dd2280-e499-11ea-8cdd-8b40626a9e17.png">
<img width="362" alt="Screenshot 2020-08-22 at 17 03 10" src="https://user-images.githubusercontent.com/23613887/90955236-77d81300-e499-11ea-8d5f-bd2a476e43c5.png">

Now on running it, gives the following error:
<img width="658" alt="Screenshot 2020-08-22 at 16 59 57" src="https://user-images.githubusercontent.com/23613887/90955174-eff20900-e498-11ea-9c58-a6d71f8b2b3a.png">
 
In header paths I have added the following:
<img width="541" alt="Screenshot 2020-08-22 at 17 01 15" src="https://user-images.githubusercontent.com/23613887/90955196-23cd2e80-e499-11ea-8b72-7987fb8b502c.png">

Is there any step which I missed?

**Comment by christopher-18** [comment]
This has been solved.
I had to put follow the manual instructions for swift project, drag the airgooglemaps folder in my project. Do the desired changes. Put the airmaps path in header search paths as mentioned in the above screenshot and in the preprocessor macros had to had 
```
HAVE_GOOGLE_MAPS=1
HAVE_GOOGLE_MAPS_UTILS=1
```.
Also I had to delete the HeatMapInterpolationPoint.swift file.

**Comment by fdobre** [comment]
@christopher-18 how did you succeed making the airgooglemaps access Google-Maps-iOS-Utils deps?

Just a drag of that folder doesn't seem to work.

<img width="998" alt="Screenshot 2021-04-07 at 19 00 40" src="https://user-images.githubusercontent.com/3833179/113900311-5af91180-97d6-11eb-8154-10b1edce418e.png">

For me when using `use_frameworks! :linkage => :static` not even a bridging header seems to work:

<img width="998" alt="Screenshot 2021-04-07 at 19 00 40" src="https://user-images.githubusercontent.com/3833179/113900427-78c67680-97d6-11eb-95c7-e09ef5711cae.png">
