### ISSUE TITLE
Android build is successful but app crashes right after splash screen (iOS works fine).

### ISSUE THREAD

**Issue by FeMaffezzolli** [react-native-community/react-native-maps#3548]
# Bug report

## Summary

Android build is successful but app crashes right after splash screen both on physical device or emulator.
(iOS works fine on both).

Since the app does not run I have no logs to figure out what's going on.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 50.52 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_241 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 0.27.1

## Steps to reproduce

1. Install react-native-maps and follow installation guide for 0.60 and above.
2. Use MapView component with style flex: 1
3. Build and run.

Describe what you expected to happen:

1. See the map.

**Comment by FeMaffezzolli** [comment]
Wow, cache was the problem.

Steps below made it.

```bash
watchman watch-del-all
npm cache clean
cd android
./gradlew clean
cd ..
```

**Comment by joaolfr** [comment]
> Wow, cache was the problem.
> 
> Steps below made it.
> 
> ```shell
> watchman watch-del-all
> npm cache clean
> cd android
> ./gradlew clean
> cd ..
> ```

You saved my day! Thanksssssssssssssss

**Comment by Archies13Singh** [comment]
Hey its not working for me 


I recently upgraded my android sdk from 33 to 34 because build is getting failed and its recommending to switch to android sdk 34.

I upgraded android sdk from 33 to 34 
 ext {
        kotlinVersion = "1.9.10"
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }

**Comment by Archies13Singh** [comment]
Please @FeMaffezzolli let me know if any details are required . Its working for IOS but not for android . Also in android.graddle i added below line 

`android.suppressUnsupportedCompileSdk=34`
