### ISSUE TITLE
MapView not moving on marker click for ios using GoogleMap provider

### ISSUE THREAD

**Issue by KaitlynCarlson** [react-native-community/react-native-maps#3549]
If I use apple maps on ios the mapview adjusts on marker click however when I set the provider to google maps the mapview does not adjust to the marker and the callout displays off screen. I've included my code below

```
import React from "react";
import {
  StyleSheet,
  View,
  Text,
  Dimensions,
  TouchableOpacity,
  Alert,
} from "react-native";
import {
  Marker,
  Callout,
  CalloutSubview,
  PROVIDER_GOOGLE,
} from "react-native-maps";
import MapView from "react-native-map-clustering";

const { width, height } = Dimensions.get("window");
const ASPECT_RATIO = width / height;
const LATITUDE = 47.6062;
const LONGITUDE = -122.3321;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
const SPACE = 0.01;

class Map extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
      events: [
        {
          description: "Sculpture Park",
          latitude: 47.616512,
          longitude: -122.355507,
        },
        {
          description: "Sculpture Park",
          latitude: 47.6205,
          longitude: -122.355507,
        },
        {
          description: "Space Needle",
          latitude: 47.6205,
          longitude: -122.3493,
        },
        {
          title: "Jam",
          description: "Century Link Field",
          latitude: 47.5952,
          longitude: -122.3316,
        },
        {
          description: "Coffee Shop",
          latitude: 47.613838,
          longitude: -122.319748,
        },
      ],
    };
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          moveOnMarkerPress={true}
          provider={PROVIDER_GOOGLE}
          style={styles.map}
          initialRegion={this.state.region}
          zoomTapEnabled={false}
          customMapStyle={customStyle}
        >
          {this.state.events.map((marker, index) => {
            return (
              <Marker
                image={require("./pins/blackPin.png")}
                coordinate={{
                  latitude: marker.latitude,
                  longitude: marker.longitude,
                }}
                title="You can also open this callout"
                description="by pressing on transparent area of custom callout"
              >
                <Callout style={styles.customView}>
                  <Text style={styles.markerTitle}>{marker.title}</Text>
                  <Text style={styles.markerDescription}>
                    {marker.description}
                  </Text>
                </Callout>
              </Marker>
            );
          })}
        </MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  customView: {
    width: 140,
  },
  markerTitle: {
    fontFamily: "Roboto",
    fontSize: 30,
  },
  markerDescription: {
    fontFamily: "Roboto",
    fontSize: 12,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});
const customStyle = [
  {
    elementType: "geometry",
    stylers: [
      {
        color: "#f5f5f5",
      },
    ],
  },
  {
    elementType: "labels.icon",
    stylers: [
      {
        visibility: "off",
      },
    ],
  },
  {
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#616161",
      },
    ],
  },
  {
    elementType: "labels.text.stroke",
    stylers: [
      {
        color: "#f5f5f5",
      },
    ],
  },
  {
    featureType: "administrative.land_parcel",
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#bdbdbd",
      },
    ],
  },
  {
    featureType: "poi",
    stylers: [
      {
        visibility: "off",
      },
    ],
  },
  {
    featureType: "poi",
    elementType: "geometry",
    stylers: [
      {
        color: "#eeeeee",
      },
    ],
  },
  {
    featureType: "poi",
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#757575",
      },
    ],
  },
  {
    featureType: "poi.park",
    stylers: [
      {
        visibility: "off",
      },
    ],
  },
  {
    featureType: "poi.park",
    elementType: "geometry",
    stylers: [
      {
        color: "#e5e5e5",
      },
    ],
  },
  {
    featureType: "poi.park",
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#9e9e9e",
      },
    ],
  },
  {
    featureType: "road",
    elementType: "geometry",
    stylers: [
      {
        color: "#ffffff",
      },
    ],
  },
  {
    featureType: "road.arterial",
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#757575",
      },
    ],
  },
  {
    featureType: "road.highway",
    elementType: "geometry",
    stylers: [
      {
        color: "#dadada",
      },
    ],
  },
  {
    featureType: "road.highway",
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#616161",
      },
    ],
  },
  {
    featureType: "road.local",
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#9e9e9e",
      },
    ],
  },
  {
    featureType: "transit.line",
    elementType: "geometry",
    stylers: [
      {
        color: "#e5e5e5",
      },
    ],
  },
  {
    featureType: "transit.station",
    elementType: "geometry",
    stylers: [
      {
        color: "#eeeeee",
      },
    ],
  },
  {
    featureType: "water",
    elementType: "geometry",
    stylers: [
      {
        color: "#c9c9c9",
      },
    ],
  },
  {
    featureType: "water",
    elementType: "labels.text.fill",
    stylers: [
      {
        color: "#9e9e9e",
      },
    ],
  },
];
export default Map;
```

**Comment by KaitlynCarlson** [comment]
![bug](https://user-images.githubusercontent.com/56324003/93406899-b5844d80-f845-11ea-9977-4d3dda8bc645.png)

**Comment by Ricardo-MT** [comment]
> If I use apple maps on ios the mapview adjusts on marker click however when I set the provider to google maps the mapview does not adjust to the marker and the callout displays off screen. I've included my code below
> 
> ```
> import React from "react";
> import {
>   StyleSheet,
>   View,
>   Text,
>   Dimensions,
>   TouchableOpacity,
>   Alert,
> } from "react-native";
> import {
>   Marker,
>   Callout,
>   CalloutSubview,
>   PROVIDER_GOOGLE,
> } from "react-native-maps";
> import MapView from "react-native-map-clustering";
> 
> const { width, height } = Dimensions.get("window");
> const ASPECT_RATIO = width / height;
> const LATITUDE = 47.6062;
> const LONGITUDE = -122.3321;
> const LATITUDE_DELTA = 0.0922;
> const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
> const SPACE = 0.01;
> 
> class Map extends React.Component {
>   constructor(props) {
>     super(props);
> 
>     this.state = {
>       region: {
>         latitude: LATITUDE,
>         longitude: LONGITUDE,
>         latitudeDelta: LATITUDE_DELTA,
>         longitudeDelta: LONGITUDE_DELTA,
>       },
>       events: [
>         {
>           description: "Sculpture Park",
>           latitude: 47.616512,
>           longitude: -122.355507,
>         },
>         {
>           description: "Sculpture Park",
>           latitude: 47.6205,
>           longitude: -122.355507,
>         },
>         {
>           description: "Space Needle",
>           latitude: 47.6205,
>           longitude: -122.3493,
>         },
>         {
>           title: "Jam",
>           description: "Century Link Field",
>           latitude: 47.5952,
>           longitude: -122.3316,
>         },
>         {
>           description: "Coffee Shop",
>           latitude: 47.613838,
>           longitude: -122.319748,
>         },
>       ],
>     };
>   }
> 
>   render() {
>     return (
>       <View style={styles.container}>
>         <MapView
>           moveOnMarkerPress={true}
>           provider={PROVIDER_GOOGLE}
>           style={styles.map}
>           initialRegion={this.state.region}
>           zoomTapEnabled={false}
>           customMapStyle={customStyle}
>         >
>           {this.state.events.map((marker, index) => {
>             return (
>               <Marker
>                 image={require("./pins/blackPin.png")}
>                 coordinate={{
>                   latitude: marker.latitude,
>                   longitude: marker.longitude,
>                 }}
>                 title="You can also open this callout"
>                 description="by pressing on transparent area of custom callout"
>               >
>                 <Callout style={styles.customView}>
>                   <Text style={styles.markerTitle}>{marker.title}</Text>
>                   <Text style={styles.markerDescription}>
>                     {marker.description}
>                   </Text>
>                 </Callout>
>               </Marker>
>             );
>           })}
>         </MapView>
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     ...StyleSheet.absoluteFillObject,
>     justifyContent: "flex-end",
>     alignItems: "center",
>   },
>   customView: {
>     width: 140,
>   },
>   markerTitle: {
>     fontFamily: "Roboto",
>     fontSize: 30,
>   },
>   markerDescription: {
>     fontFamily: "Roboto",
>     fontSize: 12,
>   },
>   map: {
>     ...StyleSheet.absoluteFillObject,
>   },
> });
> const customStyle = [
>   {
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#f5f5f5",
>       },
>     ],
>   },
>   {
>     elementType: "labels.icon",
>     stylers: [
>       {
>         visibility: "off",
>       },
>     ],
>   },
>   {
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#616161",
>       },
>     ],
>   },
>   {
>     elementType: "labels.text.stroke",
>     stylers: [
>       {
>         color: "#f5f5f5",
>       },
>     ],
>   },
>   {
>     featureType: "administrative.land_parcel",
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#bdbdbd",
>       },
>     ],
>   },
>   {
>     featureType: "poi",
>     stylers: [
>       {
>         visibility: "off",
>       },
>     ],
>   },
>   {
>     featureType: "poi",
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#eeeeee",
>       },
>     ],
>   },
>   {
>     featureType: "poi",
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#757575",
>       },
>     ],
>   },
>   {
>     featureType: "poi.park",
>     stylers: [
>       {
>         visibility: "off",
>       },
>     ],
>   },
>   {
>     featureType: "poi.park",
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#e5e5e5",
>       },
>     ],
>   },
>   {
>     featureType: "poi.park",
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#9e9e9e",
>       },
>     ],
>   },
>   {
>     featureType: "road",
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#ffffff",
>       },
>     ],
>   },
>   {
>     featureType: "road.arterial",
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#757575",
>       },
>     ],
>   },
>   {
>     featureType: "road.highway",
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#dadada",
>       },
>     ],
>   },
>   {
>     featureType: "road.highway",
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#616161",
>       },
>     ],
>   },
>   {
>     featureType: "road.local",
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#9e9e9e",
>       },
>     ],
>   },
>   {
>     featureType: "transit.line",
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#e5e5e5",
>       },
>     ],
>   },
>   {
>     featureType: "transit.station",
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#eeeeee",
>       },
>     ],
>   },
>   {
>     featureType: "water",
>     elementType: "geometry",
>     stylers: [
>       {
>         color: "#c9c9c9",
>       },
>     ],
>   },
>   {
>     featureType: "water",
>     elementType: "labels.text.fill",
>     stylers: [
>       {
>         color: "#9e9e9e",
>       },
>     ],
>   },
> ];
> export default Map;
> ```

Hello there, I´m facing the same issue, did you manage to solve it?
