### ISSUE TITLE
Get current bounding box (north-east/south-west coordinates)

### ISSUE THREAD

**Issue by aforty** [react-native-community/react-native-maps#356]
I can keep track of the maps position with `onRegionChange` but that only gives me the coordinates and delta. Is there anyway to retrieve (or calculate?) the north-east/south-west position displayed within the map?

**Comment by aforty** [comment]
I found a solution. For anyone coming across this later...

```
<MapView onRegionChangeComplete={(center) => {
  let northeast = {
      latitude: center.latitude + center.latitudeDelta / 2,
      longitude: center.longitude + center.longitudeDelta / 2,
    }
    , southwest = {
        lat: center.latitude - center.latitudeDelta / 2,
        lng: center.longitude - center.longitudeDelta / 2,
    };

    console.log(center, northeast, southwest);
}} />
```

**Comment by rgabrielsson** [comment]
This doesn't work, first it doesn't comply to the outline of the map coords system. More importantly , however, latitudeDelta does not represent the current view span.

**Comment by oliverbenns** [comment]
This only works if user isn't rotating map.

**Comment by aforty** [comment]
Agh. Well it has been good enough for me, however I would love some sort of official, documented, supported way of getting these values. Seems fairly important to a lot of different use cases.

I'm going to reopen this. Would love one of the developers to comment on this.

**Comment by jessym** [comment]
+1, need this as well.

The code sample above will be a decent approximation near the equator, but it will fail at the southern parts of the southern hemisphere and the northern parts of the northern hemisphere, because the (default) Mercator projection stretches out certain parts of the globe.

For example, you could have Antarctica in the south of your viewport (`latitude = -80`) and Japan in the north of your viewport (`latitude = 36`). The center of the screen (i.e. the projection of Earth we're looking at) would be somewhere south of Australia at `latitude = -49`.

The current maps API only gives us the values `region.latitude = -49` and `region.latitudeDelta = 116`, where `116` is calculated as the difference in latitude between Antarctica and Japan.

However, from these two numbers (`-49` and `116`), it's not possible to get the absolute latitudes of Antarctica and Japan without some clever mathematics by inverting the map projection. Also note that the code sample above fails for these numbers: `-49 - (116 / 2) = -107` (should be `-80`; a number lower than `-90` is not even allowed in fact) and `-49 + (116 / 2) = 9` (should be `36`).

**Comment by definitelycarter** [comment]
👍 - I would also like to know how to do this

**Comment by 1mjwebb** [comment]
would exporting these do it?

  GMSVisibleRegion visibleRegion = map.projection.visibleRegion;
  GMSCoordinateBounds *bounds = [[GMSCoordinateBounds alloc] initWithRegion: visibleRegion];

**Comment by martinezguillaume** [comment]
need this too !

**Comment by acomito** [comment]
@martinezguillaume  @definitelycarter  @jessym Has anyone reliably tackled this yet? 

I see react-google-maps on the web has a getBounds() function:

https://tomchentw.github.io/react-google-maps/

https://github.com/tomchentw/react-google-maps/search?p=2&q=getBounds&type=&utf8=%E2%9C%93

**Comment by mpontus** [comment]
I managed to get working solution by using known region to determine zoom level, and using reverse Mercator projection to get corner coordinates.

https://gist.github.com/mpontus/a6a3c69154715f2932349f0746ff81f2

It's not the most efficient solution, but its accurate.

**Comment by acomito** [comment]
Thanks @mpontus, by known region you mean the current lat/lng+deltas?

**Comment by alvelig** [comment]
Do you think implementing this answer as a method of MapView will solve the problem https://stackoverflow.com/questions/2081753/getting-the-bounds-of-an-mkmapview?

**Comment by alvelig** [comment]
Actually in my case 
```
const getBoundingBox = (region) => ([
  region.longitude - region.longitudeDelta/2, // westLng - min lng
  region.latitude - region.latitudeDelta/2, // southLat - min lat
  region.longitude + region.longitudeDelta/2, // eastLng - max lng
  region.latitude + region.latitudeDelta/2 // northLat - max lat
])
```
was accurate enough.

**Comment by PhmNgocNghia** [comment]
Can you please explain the algorithm why divide by two ? i don't understand it.

**Comment by alvelig** [comment]
latitudeDelta and longitudeDelta are the distances of edges. So, to have center coordinate you have to divide it by 2.

**Comment by PhmNgocNghia** [comment]
I have a map on web which created using googlemap v3 javascript and one on mobile created using react-native-maps. On server i have a bunch of marker (lat/lng) and i want to filter marker which contained by viewport of devices that can be either a web or mobile. Any tips ?

on web, i can use getbounds and get northeast and southweb (lat/lng) while on mobile i can use algorithm provided by alvelig  to get the bounding box which is array of four number.

**Comment by ShivamKJJW** [comment]
A [PR](https://github.com/react-community/react-native-maps/pull/2440) #2440 has been submitted to add this feature for the google maps. You can use this branch until the PR is closed.

**Comment by radeno** [comment]
I think there is a way how to get bounding box for both platforms. Working with `mapRef` when `onRegionChangeComplete` is called. And map method something like `getVisibleBoundaries()` could return:
```javascript
type Boundaries {
  northEast: {
    latitude: Number,
    longitude: Number
  }
  southWest: {
    latitude: Number,
    longitude: Number
  }
}
```
Google Maps:
https://stackoverflow.com/a/24210375/802949

Apple Maps:
http://www.softwarepassion.com/how-to-get-geographic-coordinates-of-the-visible-mkmapview-area-in-ios/

**Comment by radeno** [comment]
PR in progress: https://github.com/react-community/react-native-maps/pull/2571

**Comment by shrikantkunte** [comment]
@radeno I have tried the example given here https://github.com/react-community/react-native-maps/pull/2571/commits/c3545b29c0efb0c40e4daa253f06092333f53075#diff-42e926053813235167fcbea608214fdd
but it gives error 'Possible unhandled promise rejection'.

**Comment by radeno** [comment]
@shrikantkunte you are using one just commit from whole PR. Use full PR as I linked before.

**Comment by sebackend** [comment]
Hi, i was playing with this

> const getBoundingBox = (region) => ([ region.longitude - region.longitudeDelta/2, // westLng - min lng region.latitude - region.latitudeDelta/2, // southLat - min lat region.longitude + region.longitudeDelta/2, // eastLng - max lng region.latitude + region.latitudeDelta/2 // northLat - max lat ])

Everything was working fine (i put some markers to test both coordinates, northEast & southWest), but when i rotated the map, the markers are showed in another position...How can this be fixed?

**Comment by radeno** [comment]
@sebackend could you please open new issue about that ? We will try to figure it out

**Comment by MatsMaker** [comment]
`export const getBoundByRegion = (region, scale = 1) => {
  /*
  * Latitude : max/min +90 to -90
  * Longitude : max/min +180 to -180
  */
  // Of course we can do it mo compact but it wait is more obvious
  const calcMinLatByOffset = (lng, offset) => {
    const factValue = lng - offset;
    if (factValue < -90) {
      return (90 + offset) * -1;
    }
    return factValue;
  };

  const calcMaxLatByOffset = (lng, offset) => {
    const factValue = lng + offset;
    if (90 < factValue) {
      return (90 - offset) * -1;
    }
    return factValue;
  };

  const calcMinLngByOffset = (lng, offset) => {
    const factValue = lng - offset;
    if (factValue < -180) {
      return (180 + offset) * -1;
    }
    return factValue;
  };

  const calcMaxLngByOffset = (lng, offset) => {
    const factValue = lng + offset;
    if (180 < factValue) {
      return (180 - offset) * -1;
    }
    return factValue;
  };

  const latOffset = region.latitudeDelta / 2 * scale;
  const lngD = (region.longitudeDelta < -180) ? 360 + region.longitudeDelta : region.longitudeDelta;
  const lngOffset = lngD / 2 * scale;

  return {
    minLng: calcMinLngByOffset(region.longitude, lngOffset), // westLng - min lng
    minLat: calcMinLatByOffset(region.latitude, latOffset), // southLat - min lat
    maxLng: calcMaxLngByOffset(region.longitude, lngOffset), // eastLng - max lng
    maxLat: calcMaxLatByOffset(region.latitude, latOffset),// northLat - max lat
  }
}`

**Comment by pawelotto** [comment]
@MatsMaker Your solution works like a charm. I owe you probably more than one beer bro. THANKS!

**Comment by oliverfunk** [comment]
I found very little online for this so I thought I would post my solution:

```js
import React, { useCallback, useRef } from "react";
import MapView, { PROVIDER_GOOGLE, type Region } from "react-native-maps";

const Map = () => {
  const mvRef = useRef<MapView>(null);

  const onMapRegionChange = useCallback(
    (region: Region) =>
      console.log(mvRef.current?.boundingBoxForRegion(region)),
    [],
  );

  return (
    <MapView
      className="h-full w-full"
      provider={PROVIDER_GOOGLE}
      showsUserLocation={true}
      onRegionChangeComplete={onMapRegionChange}
      ref={mvRef}
    />
  );
};
export default Map;
```

Which prints
```bash
{"northEast": {"latitude": 70.80113503086783, "longitude": 17.070082426071167}, "southWest": {"latitude": 22.30878469808772, "longitude": -20.722878947854042}}
```

I'm using Tailwind with RN so that's why there's `className`.

Works on both iOS and And, I haven't tested the accuracy but anecdotally it looks like it works well.

**Comment by Pabblittto** [comment]
> Hi, i was playing with this
> 
> > 
> 
> ```
> const getBoundingBox = (region) => ([ 
>     region.longitude - region.longitudeDelta/2, // westLng - min lng 
>     region.latitude - region.latitudeDelta/2, // southLat - min lat 
>     region.longitude + region.longitudeDelta/2, // eastLng - max lng 
>     region.latitude + region.latitudeDelta/2 // northLat - max lat 
> ])
> ```
> 
> Everything was working fine (i put some markers to test both coordinates, northEast & southWest), but when i rotated the map, the markers are showed in another position...How can this be fixed?

Hi @sebackend, it is a really oooooold answer, but did you find any solution for it?
