### ISSUE TITLE
Manually dismissing callout on iOS call breaks subsequent callouts

### ISSUE THREAD

**Issue by richeterre** [react-native-community/react-native-maps#361]
In my project, I'm showing a callout by tapping its marker, with no extra code needed. Then I want to dismiss the callout via a contained `TouchableHighlight` element. However, calling `hideCallout()` breaks things for me, unless I also use `showCallout()` to summon the callout in the first place.

I'm able to reproduce the issue with a very simple map view hierarchy:

``` jsx
<View style={{flex: 1}}>
  <MapView style={{flex: 1}}>
    <MapView.Marker ref={'marker'} coordinate={{latitude: 52.516667, longitude: 13.383333}} >
      <MapView.Callout>
        <TouchableHighlight onPress={() => { hideCallout(this.refs['marker']) }}>
          <Text>Tap here to dismiss the callout.</Text>
        </TouchableHighlight>
      </MapView.Callout>
    </MapView.Marker>
  </MapView>
</View>
```
1. Tap the marker to show callout
2. Tap inside callout to dismiss it
3. Tap the marker once more

Expected result: The callout is shown again.
Actual result: The callout is not shown.

**Comment by kardolus** [comment]
Did you ever solve this?

**Comment by richeterre** [comment]
Wow, I'm surprised to see this issue still exists 😮 I "solved" it back then by explicitly calling `showCallout() whenever a marker is pressed. This could sometimes lead to the callout popping up twice in rapid succession, but at least prevents the case of callouts not showing correctly.

```
return (
  <MapView.Marker
    onPress={() => {
      this.refs[name].showCallout()
    }}
    ...
  />
)
```

@kardolus

**Comment by kardolus** [comment]
Hey thanks dude- that fixed it for me as well.

**Comment by jeffreymendez1993** [comment]
needs to be fixed not. Currently callout opens twice and isnt that smooth.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by yogendra-leocan** [comment]
is any body find proper solution for this issue?
