### ISSUE TITLE
Add `id` prop for markers to be passed back in all events

### ISSUE THREAD

**Issue by lelandrichardson** [react-native-community/react-native-maps#37]
This would make the event handlers on the mapview much more useful since you could know which marker was causing the event.  This would also help performance when you need to have a ton of markers, but don't want to have a ton of bound event handler functions.

**Comment by christopherdro** [comment]
@lelandrichardson Is there anyway we can set the `key`or `ref` prop and have either those be available in the event callback?

**Comment by lelandrichardson** [comment]
@christopherdro i don't think `key` is available in the context of the child... and I'm not sure `ref` is the best way to do it as refs come with a bit of overhead, and also wont be available in functional stateless components.

**Comment by ghamaide** [comment]
So at the moment, it's not possible to know which marker triggered an `onMarkerSelect` method for example ?

**Comment by lelandrichardson** [comment]
@ghamaide You can use the `onSelect` event on the marker directly, and you can also get the marker node by using the `event.target` property.

**Comment by ghamaide** [comment]
I'm a bit new to RN. How do I get info on the marker that triggered an onMarkerSelect method knowing the event.nativeEvent.target (which returns an integer, for example 514). I don't know what that integer represents in fact. This is what onMarkerSelect returns : 

```
{ dispatchConfig: { registrationName: 'onSelect' },
  dispatchMarker: '.r[1]{TOP_LEVEL}[0].0.0.3.$navigator.0.$nav0.0.$mapcontainer.$map.$465',
  nativeEvent: 
   { id: 'unknown',
     coordinate: { longitude: 2.3575678, latitude: 48.8798646 },
     target: 514,
     action: 'marker-select' },
  type: undefined,
  target: undefined,
  currentTarget: 514,
  eventPhase: undefined,
  bubbles: undefined,
  cancelable: undefined,
  timeStamp: 1455286645886,
  defaultPrevented: undefined,
  isTrusted: undefined,
  isDefaultPrevented: [Function],
  isPropagationStopped: [Function],
  _dispatchListeners: [Function],
  _dispatchIDs: '.r[1]{TOP_LEVEL}[0].0.0.3.$navigator.0.$nav0.0.$mapcontainer.$map.$465' }
```

**Comment by frankbolviken** [comment]
+1 for this. Im having a hard time tying this together. 

My marker definition:
`<MapView.Marker
            key={station.csmd.id}
            title= {'' + station.csmd.id}
            coordinate={ station.coords }
            onSelect= {this.onStationTap}
            image={require('../../assets/station.png')}
          />`

As you can see from the image below, the only slight reference to the marker I have tapped is the last part of the dispatchMarker string in the event in the callback. currentTarget etc is some random number as far as I can see, not attached to the marker itself. Is this expected? Or am i doing something wrong here?

![screen shot 2016-03-29 at 15 28 38](https://cloud.githubusercontent.com/assets/688190/14109586/ff7d0448-f5c2-11e5-880b-83727db07974.png)

**Comment by frankbolviken** [comment]
You would actually think that a basic thing like being able to quickly see which marked was tapped on would be perhaps the most needed functionality of a map component. So I'm a bit surprise that this doesn't get more attention.

**Comment by frankbolviken** [comment]
The way I solved this for anyone interested was that I did a substring of the dispatchId prop to get the id (last digits behind $). Then using this id with "this.refs[id]". When initialising the markers i added the station as a parameter on the Marker.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
