### ISSUE TITLE
Create a `FeatureCollection` component that encourages composition

### ISSUE THREAD

**Issue by lelandrichardson** [react-native-community/react-native-maps#40]
The API of this library, which works by having the children of the `<MapView />` component does a great job making maps and map features more "React-like", but it could go a bit further.

Right now, it is possible to make composable react components that end up rendering a single feature (like marker), and passing them as children to the map view

``` jsx
const FooMarker = ({ foo }) => (
  <MapView.Marker coordinate={foo.coordinate}>
    <View styles={styles.fooContainer}>
      {...}
    </View>
  </MapView.Marker>
);

const MapScene = ({ foo }) => (
  <MapView {...}>
    <FooMarker foo={foo} />
  </MapView>
);
```

However, as soon as we want to render more than one feature and compose, it wont work...  because react requires every component to return a single node, and thus you would need to "wrap" the features in something, but still end up adding them to the mapview as direct children.

The API I'm envisioning could go something like this:

``` jsx
const Foo = ({ foo }) => (
  <MapView.FeatureCollection>
    {/* render a custom marker for the `foo` */}
    <MapView.Marker coordinate={foo.coordinate}>
      <View styles={styles.fooContainer}>
        {...}
      </View>
    </MapView.Marker>
    {/* also render a circle under the marker based on foo's properties */}
    <MapView.Circle 
      center={foo.coordinate}
      radius={foo.reach}
      fillColor={fooColorFromType(foo.type)}
    />
  </MapView.FeatureCollection>
);

const MapScene = ({ foo }) => (
  <MapView {...}>
    <Foo foo={foo} />
  </MapView>
);
```

This could allow for limitless composition of map features, and much better separation of concerns

This might require some acrobatics on the native side, but I think it would be worth it.

**Comment by aaronofleonard** [comment]
I wholeheartedly agree. It is a little frustrating when you have dozens or hundreds of objects that need to be rendered, but they all need to be direct children. This means expensive re-rendering of the entire parent component. If we were able to group features together as you proposed, we could implement change detection and re-render as little as possible.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
