### ISSUE TITLE
Custom Callouts are cut off after updating module and react-native

### ISSUE THREAD

**Issue by BigPun86** [react-native-community/react-native-maps#427]
Hey there, i have updated React-Native to 29.2 and this module to latest.

Now my CustomCallouts, are cut off at some point. I can not display the whole callut view any more....

```
class CustomCallout extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        const {spot} = this.props;
        return (
            <View style={{flexDirection: 'row', elevation: 5}}>
                <View
                    style={{
                        backgroundColor       : Theme.Colors.MAIN,
                        padding               : 10,
                        borderTopLeftRadius   : 10,
                        borderBottomLeftRadius: 10,
                        height                : 80,
                        justifyContent        : 'center',
                        flexDirection         : 'row'
                    }}>
                    <Text style={{color: 'white'}}>INFO</Text>
                </View>
                <View
                    style={{
                        backgroundColor        : 'white',
                        padding                : 10,
                        borderTopRightRadius   : 10,
                        borderBottomRightRadius: 10,
                        height                 : 80,
                        justifyContent         : 'center'
                    }}>
                    <Text style={{marginBottom: 5, color: Theme.Colors.MAIN}}>
                        {spot.name}
                    </Text>
                    <Text style={{marginBottom: 5}}>
                        {spot.address.address} {spot.address.city}
                    </Text>
                </View>
            </View>
        )
    }
}

......

class Map extends Component {
.....


    _renderMarker(spots) {
        return spots.map((spot, i) => {
            const marker = {
                coordinate : {
                    latitude : parseFloat(spot.center.latitude),
                    longitude: parseFloat(spot.center.longitude)
                },
                title      : spot.name,
                description: spot.address.address,
                key        : i
            };

            return (
                <MapView.Marker
                    {...marker}
                    key={i}
                    centerOffset={{y: -24}}
                >
                    {this._pinRender(spot.localUsers.length, Math.round(spot.averageRating) || 0, spot['@type'], spot['premiumPartner'], spot['processed'])}
                    <MapView.Callout onPress={()=>this._onPressInfo(spot)} tooltip={true}>
                        <CustomCallout spot={spot}/>
                    </MapView.Callout>
                </MapView.Marker>);
        });
    }

.....
}

```

Any ideas?

**Comment by Randyanto** [comment]
Same with me, the normal callout also can't render the children inside it.

**Comment by BigPun86** [comment]
I fixed this by adding styles to my MapView.Callout component (I think u have to give him width and height and that should be enough):

	<MapView.Callout 
                         onPress={()=>this._onPressInfo(spot)} 
                         **style={{width: 300, height: 100}}**
			 tooltip={true}>
		 <CustomCallout spot={spot}/>
	</MapView.Callout>

**Comment by Randyanto** [comment]
@BigPun86 Thx, I also have solved this by adding width before you reply my answer hehe.

**Comment by GantMan** [comment]
not a fan of this regression :(

**Comment by GantMan** [comment]
Do you think we should PR a default style that can be overriden?

**Comment by esutton** [comment]
@gblejman  suggested this improvement in issue https://github.com/lelandrichardson/react-native-maps/issues/314

Using RN 0.32 and latest 0.8.0 maps

@gblejman Thank you! position: '**relative**' fixes the restricted width on Android and iOS.

position: '**relative**' fixes the restricted width:

`<MapView.Callout style={{ flex: 1, position: 'relative' }}>`

<img width="314" alt="screen shot 2016-08-31 at 11 23 38 am" src="https://cloud.githubusercontent.com/assets/6115047/18137435/ec4b49e6-6f6d-11e6-8dcb-07f6b74d1e89.png">

position: '**absolute**' restricts maximum width:

`<MapView.Callout style={{ flex: 1, position: 'absolute`

<img width="310" alt="screen shot 2016-08-31 at 11 29 04 am" src="https://cloud.githubusercontent.com/assets/6115047/18137597/92769730-6f6e-11e6-94c2-7878eb52db20.png">
' }}>

I just need to figure out if can get the pointer back to center of marker. Or maybe just turn off the pointer for now.

Is there a work-around that can fix the offset callout pointer when using position: '**relative**'  work-around for restricted width?

**Comment by cyphire** [comment]
Hey - I'm not sure that this is an issue with your module... I'm having the same problem with Modal views in react-native v33.  It doens't happen on all the emulators I use, but seems to be on the larger ones (latest ver 6 android?).  Anyway, it just cuts off the bottom of a modal.  I mostly use exact height and width on the modal which has the problem .  Is your issue with the Modal in your code?

**Comment by satori-ytolstoguzov** [comment]
The behavior I see with Google Maps on iOS:
* Custom callouts do not grow horizontally properly, if it's possible the grow vertically. For example with a text they wrap the text and make it vertical.
* `flexDirection: 'row'` breaks auto sizing: Callout only takes size of the first children and second children become partially or completely invisible.
* Specifying width and height let you go around some issues, but without good way to calculate your content width/height (for instance, for text) it becomes real problem.

Here is example project that I made: https://github.com/satori-ytolstoguzov/rn-maps-callout-offset/tree/flex-direction-row 

![callout-layout](https://user-images.githubusercontent.com/31261230/33957805-8979e970-dff7-11e7-97a8-949427e49411.png)

Code:
```js
...
<MapView.Callout tooltip>
  <View style={{flexDirection: 'row'}}>
    <Text style={{backgroundColor: 'blue'}}>1st Callout</Text>
    <Text style={{backgroundColor: 'green'}}>2nd Callout</Text>
  </View>
</MapView.Callout>
```

**Comment by Jun711** [comment]
if I am not using custom callout, how can I set the width of the callout and make the text wrap?

**Comment by satori-ytolstoguzov** [comment]
@Jun711 I don't think you can with current version. 
These 2 docs define all props that apply to callouts:

* https://github.com/react-community/react-native-maps/blob/master/docs/marker.md
* https://github.com/react-community/react-native-maps/blob/master/docs/callout.md

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
