### ISSUE TITLE
Callout does not update after props change on Android

### ISSUE THREAD

**Issue by wkrause13** [react-native-community/react-native-maps#486]
I'm having an issue on Android where the content of the tooltip does not update after its props have changed. 

I am fetching data from an API as a result of the onPress event for a custom marker. After the data is returned, I am updating the state of the component, and the relevant attributes are passed down as props to the content component for the custom callout. On iOS the custom content re-renders after the state is updated. However, on android, the content does not re-render. 

```
            <MapView.Marker
              onPress={() => this.fetchData(item.id)}
              key={key}
              coordinate={{latitude, longitude}}
            >
              <MapView.Callout
                    style={{width: 200}}>
                    <CustomTooltipContent text={this.state.text} isLoading={this.state.isLoading} />
            </MapView.Callout>
            </MapView.Marker>
```

**Comment by wkrause13** [comment]
Here is a simple working example. The increment button increments the count variable. However, on android you need to dismiss the tooltip and reopen it to see the changed. On iOS you see the counter increment like a normal react component.

```jsx

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight
} from 'react-native';

import MapView from 'react-native-maps';


class mapTest extends Component {
  constructor () {
    super()
    this.state= {
      coordinate: {
        latitude:37.78825,
        longitude: -122.4324
      },
      count: 0
    }
    this.increment = this.increment.bind(this)
  }
  increment () {
    this.setState({count: this.state.count + 1})
  }
  render() {
    const {coordinate} = this.state
    return (
      <View style={{flex: 1}}>
        <View style={styles.container}>
          <MapView
          style={styles.map}
            initialRegion={{
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}
          >
            <MapView.Marker coordinate={coordinate}>
              <MapView.Callout style={{width:250}}>
                <View><Text>{this.state.count}</Text></View>
              </MapView.Callout>
            </MapView.Marker>
          </MapView>
      </View>
        <View style={{flex: 1, justifyContent:'center', alignItems:'center'}}>
          <TouchableHighlight onPress={this.increment} underlayColor={'#e69500'} style={styles.button}>
            <Text style={{color: '#FFFFFF', fontWeight:'bold'}}>Increment</Text>
          </TouchableHighlight>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 3 
  },
 map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  button: {
    height: 40,
    width: 100,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor: 'orange',
    borderRadius: 5,
    bottom:0
  }
});

AppRegistry.registerComponent('mapTest', () => mapTest);

``` 

![maptooltipissue](https://cloud.githubusercontent.com/assets/4914208/17915589/a5c5f452-6979-11e6-967c-265777c58a8e.png)

**Comment by CacaoRick** [comment]
I have same problem, and I do these to solve:
- Save Marker's ref.
- Save isCalloutShow in state.
- Update isCalloutShow state when Marker.onPress(callout will show) and Maps.onPress(callout will hide).
- When data update, if (isCalloutShow) call MarkerRef.showCallout() again.
- Callout will update.

**Comment by viet97** [comment]
i have the same problem ,any solution ?

**Comment by jorgenavarrochavez** [comment]
I have the same problem!!! I am test it on android!!!

**Comment by satori-ytolstoguzov** [comment]
It's strange, I don't have this problem. I am using the latest release (19.0). The only difference in my app markers updated as well (coordinates of markers), may be it helps.

**Comment by satori-ytolstoguzov** [comment]
Seems related #324

**Comment by Rewieer** [comment]
How comes no one implemented a simple state switch in MapMarker to know wether or not the callout is visible ? Are there anything planned about this or do you need some help ?

**Comment by ShaikhKabeer** [comment]
Hi Guys. I'm also facing the issue related to Callout. I have created Custom Callout and on Markerpress I'm showing it. But when I press on another marker the callout is not updating. Need help !!

**Comment by glrd78** [comment]
Someone have a issue ?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by oliverdolgener** [comment]
I have the same problem. I'm showing a callout with the distance between the user and the marker but the callout is not updating when the user's position changes. The callout always shows the same value unless it is closed and reopened.

**Comment by bartello1982** [comment]
same issue here. Marker Callout does not update unless you close and open it again. Any solutions ?

**Comment by nguyenanhthai** [comment]
I got same issue in iOS with Google Map.
After looking at API of Marker, I found the reason: Callouts only renders 1 time at first because of this prop tracksInfoWindowChanges (default is false)

So there we have 2 solutions for it:
1. Set tracksInfoWindowChanges is true (decrease the performance)
2. We need "redrawCallout" after the data is changed.

More information:
https://github.com/react-native-community/react-native-maps/blob/master/docs/marker.md

Hope can help someone.

**Comment by hungthuanmk** [comment]
> I got same issue in iOS with Google Map.
> After looking at API of Marker, I found the reason: Callouts only renders 1 time at first because of this prop tracksInfoWindowChanges (default is false)
> 
> So there we have 2 solutions for it:
> 
> 1. Set tracksInfoWindowChanges is true (decrease the performance)
> 2. We need "redrawCallout" after the data is changed.
> 
> More information:
> https://github.com/react-native-community/react-native-maps/blob/master/docs/marker.md
> 
> Hope can help someone.

Unfortunately, your solution supports only for iOS, is there any way to solve this problem on Android :(

**Comment by LuongTruong** [comment]
Hello guys, I have a work around for this case:

    this._resetMarkersTimeoutId = setTimeout(() => {
        this._androidMarkers[<marker-id>].showCallout()
    });

The show can update the Callout view.

**Comment by FanchenBao** [comment]
A more comprehensive work-around in Android using `showCallout()`: https://stackoverflow.com/a/64015623/9723036

**Comment by MedNabilEssefaihi** [comment]
Hello everyone!
I had the same problem and I fixed, see this source:
https://stackoverflow.com/questions/63364796/react-native-maps-callout-content-not-updated-on-change/64015623#64015623

**Comment by yogieeka** [comment]
Try using setTimeOut like this:

`setTimeout(() => {
    markersRef.current[index].showCallout();
      }, 1);`

**Comment by lortschi** [comment]
On iOS the `redrawCallout()` was helpful for rerendering the callout.  If there are multiple markers and callouts on map then should be set a useRef() on the marker to have all markers and callouts. This is how I done:

`
const markerRef = useRef([])

const [pressedMarkerCoordinates, setPressedMarkerCoordinates] = useState({})

const handleMarkerPress = (e) => {
		setPressedMarkerCoordinates(e.nativeEvent.coordinate)
.....

}

useEffect(() => {
		if (routeDistance > 0) {
			markerRef.current?.forEach((marker) => {
				if (
					marker.props.coordinate.latitude ===
						pressedMarkerCoordinates.latitude &&
					marker.props.coordinate.longitude ===
						pressedMarkerCoordinates.longitude
				) {
					marker.redrawCallout()
				}
			})
		}
	}, [routeDistance])

return (
    <MapView ....
       {lotMarkersObjArr.map((coords, index) => (
	    <Marker
		    ref={(el) => (markerRef.current[index] = el)}
		    key={index}
		    coordinate={{
			    latitude: parseFloat(coords.lat),
			    longitude: parseFloat(coords.lng),
		    }}
		    // title="Vending Location"
		    onPress={handleMarkerPress}` 

......
`

**Comment by QuocHuy-hash** [comment]
> I have the same problem. I'm showing a callout with the distance between the user and the marker but the callout is not updating when the user's position changes. The callout always shows the same value unless it is closed and reopened.

how to fix it bro?
