### ISSUE TITLE
[IOS] Some markers appear on top left of mapview when moving the map

### ISSUE THREAD

**Issue by keung725** [react-native-community/react-native-maps#678]
Some markers appear on top left of mapview when moving the map but these markers have already rendered in specific coordinate correctly

```
var makers = annotations.map((annotation, i) => {
      return(
        <MapView.Marker
          key={i}
          coordinate={{
            longitude: annotation.longitude,
            latitude: annotation.latitude,
          }}
          image={annotation.image}
        />
      )
    });

<MapView
              ref={ref => { this.map = ref; }}
              initialRegion={this.state.region}
              followUserLocation={false}
              showsMyLocationButton={false}
              style={{
                width: screenWidth * 0.8,
                height: screenHeight / 9 * 7,
              }}
              maxDelta={0.01}
              showsUserLocation={true}
            >
              {makers}
            </MapView>
```

IOS
react-native-maps 0.10.1
RN 0.33

**Comment by keung725** [comment]
top left markers:
<img width="245" alt="screen shot 2016-10-12 at 10 35 07 am" src="https://cloud.githubusercontent.com/assets/15522239/19295527/a937fd78-9067-11e6-9333-52799b4d9332.png">
<img width="241" alt="screen shot 2016-10-12 at 10 34 46 am" src="https://cloud.githubusercontent.com/assets/15522239/19295528/aa649670-9067-11e6-92a4-43ce26f2fc06.png">

**Comment by veliaho** [comment]
I can see the same. Did you find the reason?

**Comment by ovekyc** [comment]
Me too. Please let me know if there are any reason or solution.

**Comment by leoi11** [comment]
is happening to me without the need to move the map.
RN: 0.37
react-native-maps: 0.11.0

**Comment by mmchougule** [comment]
This is happening to me as well in iOS.
react-native-maps: 0.8.2
react native: 0.32.0
Please let me know if anyone found any solution for this.

**Comment by veliaho** [comment]
I gave up waiting a solution for this. So I'm just using Image tag which works fine but not as good in performance wise in case lot of markers.
`            <MapView.Marker
                  key={marker.key}
                  identifier={marker.key}
                  coordinate={marker.coordinate}
            >
                <Image
                    source={marker.image}
                    style={[marker.style]}
                 />
            </MapView.Marker>`

**Comment by jenshandersson** [comment]
I'm seeing this issue too. I'm adding Markers with an image attribute and somehow there is always one marker stuck in the top left corner.

![simulator screen shot 30 jan 2017 16 26 23](https://cloud.githubusercontent.com/assets/1150467/22431316/03e744e8-e709-11e6-8e2b-08a8458799f1.png)

It can easily be reproduced. If I render a few Markers and then I remove them, the little guy in the top left corner stays... And the marker data is good.

```
renderUsers() {
    return this.state.users.map(marker => (
      <MapView.Marker
        key={marker.id}
        coordinate={marker.latlng}
        title={marker.title}
        description={marker.description}
        image={require('../assets/map-man.png')}
      />
    ));
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          style={{ flex: 1 }}
          showsUserLocation
          region={this.state.region}
          onRegionChangeComplete={(region) => this.setState({ region })}
        >
          { this.renderPins() }
          { this.renderNewPin() }
          { this.renderUsers() }
        </MapView>
      </View>
    );
  }
}
```

**Comment by ciAnd7** [comment]
I have same problems when markers with custom image is added after map is rendered first time. If such marker has out of screen coordinates it renders at top left corner. IMHO, it is happened because Marker implements MKAnnotation and MKAnnotationView with image property. RN add view to MKMap hierarchy, but MKMap don't track position of it because annotation has out of screen coordinates. 

So, the simplest way to fix it is patch of AIRMapMarker.m reactSetFrame:

```
diff -u ios/AirMaps/AIRMapMarker.m /Users/ZZZ/XXX/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m
--- ios/AirMaps/AIRMapMarker.m	2017-03-07 10:48:42.000000000 +0300
+++ /Users/ZZZ/XXX/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m	2017-03-07 10:41:27.000000000 +0300
@@ -34,7 +34,7 @@
     // height though, we need to compensate in such a way that the bottom of the marker stays at the same spot on the
     // map.
     CGFloat dy = (bounds.size.height - self.bounds.size.height) / 2;
-    CGPoint center = (CGPoint){ self.center.x, self.center.y - dy };
+    CGPoint center = (CGPoint){ self.center.x -100, self.center.y - dy };
 
     // Avoid crashes due to nan coords
     if (isnan(center.x) || isnan(center.y) ||

```

It is not good enough solution and looks like 'dirty hack', but it just hide the glitch.

**Comment by EricPKerr** [comment]
Is there any followup to this? Experiencing same issue with custom marker images being placed in the top left corner of the map if the coordinates are outside the viewport.

react: 0.43.4
react-native-maps: 0.14.0

**Comment by freshnewegg** [comment]
I managed to fix this issue by making sure all my images/icons for the markers were loading in "componentDidMount" and setting my markers based on when the map was done its onLayout(). Previously, i loaded them in the constructor.

It seems to happen if the markers are rendered too soon before the map is ready
<img width="350" alt="screen shot 2017-06-12 at 4 47 27 pm" src="https://user-images.githubusercontent.com/5714313/27054455-ed07d4f6-4f8e-11e7-80d9-a0d5eaf20fc9.png">
<img width="362" alt="screen shot 2017-06-12 at 4 47 39 pm" src="https://user-images.githubusercontent.com/5714313/27054457-ef097eee-4f8e-11e7-94f3-60f385239525.png">
<img width="581" alt="screen shot 2017-06-12 at 4 47 47 pm" src="https://user-images.githubusercontent.com/5714313/27054459-f0a39604-4f8e-11e7-9656-f8766f749933.png">

**Comment by freshnewegg** [comment]
I managed to fix it by adjusting when the MKAnnotation images were supplied. This bug appears I think when you try to change the image of an MKAnnotationView.

https://github.com/freshnewegg/react-native-maps/commit/81afd1b072b99ac4927e2cd679dddfb8fcb6407e

it works for me, cheers

**Comment by zhantx** [comment]
+1

**Comment by alexgvozden** [comment]
this is still an issue, will it get officially fixed, for me the hack did not work

**Comment by AlexandreRoba** [comment]
I also have the problem... Any idea when this will be resolved? Thanks for the good work.

**Comment by AlexandreRoba** [comment]
I can provide more information on the issue:

The Mock api I use to retreive the marker is:
```javascript
class BikeApi {
  static getAllBikes() {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(Object.assign([], bikes));
      }, delay);
    });
  }
}
```

Then I have created two actions. One loading the items and one handling the success using redux.thunk.
```javascript
export function loadBikesSuccess(bikes) {
  return {
    type: types.LOAD_BIKES_SUCCESS,
    bikes,
  };
}

export function loadBikes() {
  return function(dispatch) {
    return VehicleApi.getAllBikes().then((bikes) => {
      dispatch(loadBikesSuccess(bikes));
    }).catch((error) => {
      throw error;
    });
  };
}
```

Then i combine this reducers to set the state of my store

```javascript
export default function bikeReducer(state = [], action) {
  switch (action.type) {
    case types.LOAD_BIKES_SUCCESS:
      return action.bikes;
    default:
      return state;
  }
}
```

When My app start I call the action to load up the bike in the store
```javascript
const store = configureStore();
// Dispatch a first action that loads the vehicles
store.dispatch(loadBikes());
```

The map get rendered with the marker and once the api call complete the bikes are displayed...
The issue come from the SetTimeout on the mock api call.... If I set the delay to 0, the marker show properly... If I set the delay to 1ms then the marker display on the top left... Weird... :(

**Comment by athomaj** [comment]
@AlexandreRoba This problem happened to me when I wrapped the content of my MapView inside an other View(<MapView><View><MapView.Marker /></View></MapView>). If my markers are displayed directly inside the mapview, the problem goes away.
I hope it can help you or anyone else.

**Comment by AlexandreRoba** [comment]
thanks for the reply. I did remove the view encapsulating the list of marker and it did resolve it... Unfortunattely I had to remove also the Image... This means I cannot use custom marker... this really annoying :(

**Comment by athomaj** [comment]
@AlexandreRoba You should be able to keep your custom image

**Comment by AlexandreRoba** [comment]
@athomaj When I define a custom image using the image attribute of the marker,  It appears on the top left corner. Then if I pan around the map and zoom in and zoom they end up showing at the right place. I gave up on this and tried the google provider on IOS. With it it works as expected. Thanks for the help.

**Comment by cihadturhan** [comment]
At least there is [a workaround](https://github.com/react-community/react-native-maps/issues/499#issuecomment-262440218)

**Comment by andrioid** [comment]
@cihadturhan: That work-around doesn't work on Android 7.1 where we can't show use `<Image />` children anymore (see #1870).

**Comment by redisean** [comment]
Thank you for your help with this issue, I had a similar problem resulting in the same thing.

My structure was <MapView>functionReturning{<View><MapView.Markers></></>}</> and this was causing an issue, once I removed the <View> and put the <MapView> inside the function instead it made it all work seemlessly.

Came to this result from reading the above and just wanted to thank you guys for your efforts in workarounds and fixes.

**Comment by teepeevee** [comment]
iOS with Google Maps (react-native-maps 0.22 and react-native 0.57.1) shows always invisible marker on top left corner of the map and the marker stays there when map is panned. Android with Google Maps and iOS with Apple Maps don't have this invisible marker.

We've used <MapView><MapView.Marker><View><Image source={ImageSource}> structure for building our custom marker, but the same invisible marker also appears if we use <MapView><MapView.Marker image={ImageSource}> structure or if we use non-custom markers.

Also if you set backgroundColor for the marker, it is only shown for this invisible marker and all other markers are missing the background color (red background color in this example screenshot):
<img width="378" alt="screenshot 2018-10-17 at 9 44 17" src="https://user-images.githubusercontent.com/42848481/47067414-002c6380-d1f2-11e8-90fd-abd8fd4fb582.png">

**Comment by rborn** [comment]
Old issue, closing, pleas open a new one if you still have it
