### ISSUE TITLE
Is it possible to replace Google Maps with another Map Engine?

### ISSUE THREAD

**Issue by leeight** [react-native-community/react-native-maps#712]
Due to [GFW](https://en.wikipedia.org/wiki/Great_Firewall) it's hard to access google services in the  mainland of china, so if provide an extra options to replace Google Map with other Engine? For example: 

```
  <MapView
    provider="Google"   // Some others map engine ....
    initialRegion={{
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    }}
  />
```

**Comment by tlvenn** [comment]
While technically feasible it would be a substantial effort to provide alternate provider such as mapbox for example.

**Comment by jeveloper** [comment]
I would suggest you look into mapbox as a complete alternative

**Comment by felipecsl** [comment]
One possible solution would be have this library use [AirMapView](https://github.com/airbnb/AirMapView) under the hood, since it provides options for google web maps and mapbox and the external api is similar to the google one

**Comment by vijayst** [comment]
It will be nice to have MapBox as a provider.

**Comment by alvelig** [comment]
Similar to #773

**Comment by wregis** [comment]
Any provider would be great as long as it works. Maybe if there was a way to switch the base map provider would satisfy the ones who wish to keep Google and the ones who prefer other solutions.

**Comment by enieber** [comment]
I get started the project to use OpenStreetMaps or GoogleMaps to Android.  https://github.com/enieber/react-native-open-street-map

**Comment by alvelig** [comment]
See #2348

**Comment by amaurymartiny** [comment]
@rborn The reason why #2348 has been closed are clear.

But why is this issue closed?

**Comment by rborn** [comment]
I just cleanup the repo for very old issues and yours was a victim of this.
If you think is important please open a new one following the new template.
Thanks and sorry for any annoyance 😻
