### ISSUE TITLE
outputRange must have 2 elements

### ISSUE THREAD

**Issue by jomaint** [react-native-community/react-native-maps#746]
While following the AnimatedView.js example, i have the error:
`outputRange must have 2 elements` in the componentDidMount()

```
region.timing({
      latitude: scrollX.interpolate({
        inputRange: markers.map((m, i) => i * SNAP_WIDTH),
        outputRange: markers.map(m => m.coordinate.latitude),
      }),
```

Did anyone else manage to solve this error? I suspect the Animated.interpolation function requires 2 input

**Comment by jomaint** [comment]
Still stuck on this issue. Anyone managed to get the AnimatedView to work?

**Comment by traendy** [comment]
If there is a solution, I'll be greatful to read about it.

**Comment by sja1n** [comment]
is there a fix for this issue yet ?

**Comment by rborn** [comment]
The latest versions  have camera* methods implemented. Closing.

**Comment by anthlasserre** [comment]
Still have the same error...

**Comment by zerosrat** [comment]
Make sure `markers.length >= 2`, unless the error is throwed by RN
