### ISSUE TITLE
Draggable circle/polygon

### ISSUE THREAD

**Issue by niftylettuce** [react-native-community/react-native-maps#81]
I'd like to know how we can get the `draggable` prop currently on Markers to also be for circle/polygon/rectangle (so we can drag these shapes around the map by touching them).  I noticed we can embed custom views inside Markers, but if we want to have respect to the map (e.g. use `meters`), then how do we calculate the `width` and `height` of the custom views inside a Marker?  For example, I want to create a custom draggable marker with an embedded square inside that has a radius of 1000 meters from center.  What would the math look like to get this?

**Comment by lelandrichardson** [comment]
@niftylettuce This is something that I don't think is possible out of the box with the native APIs. If someone can hack together a solution, that'd be really cool... but is currently not something that's very easy to implement.

**Comment by niftylettuce** [comment]
@lelandrichardson I figured out how to do this, I also fixed/figured out the following:

* Convert points from React Native views to coordinates on map
* Add gestures with circles/polygons etc to map
* Calculate meters from points
* Added `onMapReady` to iOS (alleviating the weird `setState({ isReady: true })` fix you had done I think because iOS didn't have `onMapReady` yet?)
* Switched from `...props` from being first in object to last in object (so we can override them)

Maybe I should submit a PR?  I've spent a ton of time on this, not only with this component, but your iOS/Android code too.. collaborator status would be dope :smile:   We should put together an organization on GitHub for this and its surrounding documentation.  Like a "react-native-maps" team :+1:

**Comment by lelandrichardson** [comment]
@niftylettuce i apologize for not responding to this sooner. I've been busy with react conf and I'm just now getting caught up with my github issues :)

It sounds like you've done quite a bit of work. I'd love to take a look at it! Please do submit a PR, and we can talk over the code.

Thanks

**Comment by niftylettuce** [comment]
@lelandrichardson I'll get my PR in tonight I think :+1:

**Comment by mohammadrafigh** [comment]
what's the progress guys? I really need it now!

**Comment by niftylettuce** [comment]
you could look at the commit in my fork here https://github.com/niftylettuce/react-native-maps

I think I need to finish Android integration with all these helper methods I added, can't remember if I did.

**Comment by lee-dabiker** [comment]
Hi, were these changes implemented in the trunk? Where do I begin to look for examples of how to work with shapes (I want the user to be able to draw a circle somehow and position it, then check if lat, lng from a server request is withing this circle.... eventually.)

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by adityaproctur97** [comment]
@niftylettuce The PR you shared is not accessible. Could you please share it ?
