### ISSUE TITLE
How do you detect a pinch and zoom?

### ISSUE THREAD

**Issue by the-simian** [react-native-community/react-native-maps#837]
I don't mean any region change, but specifically if a user uses pinch and zoom.

the only handler I can see that fires on pinch and zoom is `onRegionChangeComplete`. There seem to be user-driven handlers for `onPanDrag`, and `onPress`, and `onLongPress`. Is there a most appropriate handler for pinch/zoom? Can you perhaps do something with one of these other handlers to know that was a user initiated Pinch and Zoom?

**Comment by gilbox** [comment]
try checking for change in delta in `onRegionChangeComplete` ?

**Comment by henrikra** [comment]
@gilbox This would not work for people who are using methods like `animateToCoordinate` since methods like that invoke `onRegionChangeComplete ` too. 

I would also like to have event that invokes only when human has actually zoom or pinched the map :)

**Comment by seppemarotta** [comment]
+1
This feature'd be great. I'm using custom image markers, and i'd like to resize them according to user zoom in /out.

**Comment by fmelp** [comment]
@seppemarotta did you figure out how to make the markers zoom with the map by any chance

**Comment by the-simian** [comment]
much like this:  https://github.com/airbnb/react-native-maps/issues/487 to my understanding this is simply not supported at the moment

**Comment by seppemarotta** [comment]
@fmelp 
I'm using this 
`this.map.fitToSuppliedMarkers([id], animated);`

Where id is the id of the Marker and animated is a boolean.

**Comment by rexlow** [comment]
+1

**Comment by the-simian** [comment]
@fmelp , hey can you express in a bit more detail what you're doing? I am looking for something like a handler that fires when the user attempts to pinch and zoom. Is there a way to use this in that way?

**Comment by the-simian** [comment]
Has this been solved? can we detect when a user explicitly pinches and zooms?

**Comment by wkoutre** [comment]
@the-simian I use the `onPanDrag` prop — works great. Pretty sure it also covers explicit pinch & zoom, as well as — obviously — panning.

**Comment by tonygriv** [comment]
+1

**Comment by hegelstad** [comment]
+1

**Comment by lyseiha** [comment]
Any Update? Need Help.

**Comment by lyseiha** [comment]
+1

**Comment by ppatel890** [comment]
Any updates on this one? Want to be able to differentiate between a user moving on the map and using the `animateToCoordinate` method. Using `onPanDrag` required `scrollEnabled` to be disabled on iOS, so we weren't able to use that.

**Comment by christopherdro** [comment]
You can try using https://github.com/kmagiera/react-native-gesture-handler

**Comment by windhelm** [comment]
> You can try using https://github.com/kmagiera/react-native-gesture-handler

this work with IOS, but android not fired this events(

**Comment by gurkanguran** [comment]
Anyone has a solution already for this ? I tried to detect double tap by assuming that when you press on map, onPress will be triggered but it also does not work.

**Comment by KyleAsaff** [comment]
also looking for a solution to this. I need to know when a user pinch zooms to render specific markers.

> @the-simian I use the `onPanDrag` prop — works great. Pretty sure it also covers explicit pinch & zoom, as well as — obviously — panning.

where is the zoom attribute in the onPanDrag callback? I tried calling getCamera inside but it was way too slow to call it for every single onPanDrag event.
