### ISSUE TITLE
Inconsistent Default Marker Anchor

### ISSUE THREAD

**Issue by gilbox** [react-native-community/react-native-maps#867]
I noticed that on iOS, using `provider={MapView.PROVIDER_GOOGLE}`, the dafault `anchor` value is `{ x: 0.5, y: 1 }`, ie anchored at the bottom-middle of the marker.

However, on iOS using `provider={MapView.PROVIDER_DEFAULT}` (MapKit) it seems to default to the equivalent of `anchor={{ x: 0.5, y: 0.5 }}`, ie anchored in the center of the marker.

In conversation with @lelandrichardson recently he told me he had intended the default to be consistently anchored at the bottom-middle of the marker. 

If we decide to fix this, we should consider implementing `anchor` for MapKit.

**Comment by alvelig** [comment]
#1771
