### ISSUE TITLE
Max & Min zoom level

### ISSUE THREAD

**Issue by zvoncha** [react-native-community/react-native-maps#878]
Is it possible to set properties for maximum & minimum zoom level? Google maps have that property  https://developers.google.com/maps/documentation/javascript/reference#MapOptions, however I can't find on this particular component.

Thanks.

**Comment by gilbox** [comment]
we'd welcome a PR for this. should be pretty trivial for google. for mapkit less so:

http://stackoverflow.com/questions/1636868/is-there-way-to-limit-mkmapview-maximum-zoom-level

**Comment by zvoncha** [comment]
Thanks @gilbox

**Comment by ABleas** [comment]
Using Google and would really love a zoom and pan limit.

**Comment by childv** [comment]
Hi, has there been any update regarding how to limit user zoom/panning to a certain area in MapView? I'm currently controlling panning by preventing a region update (see below), but it looks very glitchy.

`  
onRegionChange(region) {
    // Check to make sure region is within arbitrary bounds
    if (((region.latitude <= 44.46316089) && (region.latitude >= 44.45690153)) && ((region.longitude <= -93.14903207) && (region.longitude >= -93.15727215))) {
      this.setState({ region });
      this.prev_region = region;
    // Limits to previous state
    } else {
      this.setState({ this.prev_region});
    }
  }
`

Any help would be appreciated. Thanks!

**Comment by ABleas** [comment]
@childv are you using 'mapView.animateToRegion()' when reverting regions?

Also for the zoom level, I found this useful for conversion from raw coords:
http://stackoverflow.com/a/6055653

**Comment by childv** [comment]
Hey @ABleas thanks for the zoom level resource, that helps a lot!

Regarding panning, I've been using setState(). I just replaced it with animateToRegion() though and, while it's definitely less jerky, I don't want the user to be able to pan past certain coords using map view. With animateToRegion(), the view nicely transitions back to the accepted bounds I've hard coded above instead, but I'd like to stop the user from moving the view past the bounds all together.

Any more suggestions? I'm new to react, and after poking around the react-native-maps example lib I found a [PanController](https://github.com/airbnb/react-native-maps/blob/master/example/examples/PanController.js) module that looks promising but not sure if it's what I want yet. Thanks!

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
