### ISSUE TITLE
Custom MapStyle not working

### ISSUE THREAD

**Issue by raysmithdev** [react-native-community/react-native-maps#881]
Hey,

I followed the setup for a custom mapStyle in the docs but my map is not showing the custom style. I know I am a bit vague on the info but has any1 else had the same issue? My Map component file can be viewed at https://gist.github.com/raysmithdev/d7391ff2378a16cd28812399c9787faa

Ray

**Comment by gilbox** [comment]
atm, it's only supported when you use `provider={MapView.PROVIDER_GOOGLE}`

**Comment by raysmithdev** [comment]
@gilbox thanks for the reply. Where do you put `provider={MapView.PROVIDER_GOOGLE}` ?

**Comment by Kilbukas** [comment]
having the same issue, tried with `provider={MapView.PROVIDER_GOOGLE}` without success.

**Comment by raysmithdev** [comment]
Kilbukas did you manage to resolve it?

**Comment by peterpme** [comment]
Hey @Kilbukas and @raysmithdev 

In order to solve this issue, please set `provider={PROVIDER_GOOGLE}` within the `<MapView` component:

```
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'

<MapView
  provider={PROVIDER_GOOGLE}
  customMapStyle={MapStyle}
>

```

Then add the `AirGoogleMaps` directory:

https://github.com/airbnb/react-native-maps/blob/1e71a21f39e7b88554852951f773c731c94680c9/docs/installation.md#ios

**Comment by heron2014** [comment]
Hi @peterpme I am fairly new to RN, could you please clarify for me steps to add AirGoogleMaps dir.

Previously I linked library via ```react-native link```
I dragged the directory AirGoogleMaps from node_modules to xCode project. 
I am confused in regards to setup ```Podfile```. Where is this file located? Do I need some extra steps before that? 

Thanks.

**Comment by bsiddiqui** [comment]
@gilbox can we note that it only works for google maps in the docs? Happy to make a PR

**Comment by duhaime** [comment]
@peterpme do you know of any reproducible implementations of this feature? Like  @heron2014 I had run a `react-native link` command, dragged AirGoogleMaps (and AirMaps) into Xcode, and ran a pod install (after copying the default [pod file](https://github.com/airbnb/react-native-maps/blob/1e71a21f39e7b88554852951f773c731c94680c9/example/ios/Podfile)) but the custom styles didn't appear...

**Comment by heron2014** [comment]
@duhaime I managed to enable GoogleMaps on IOS and add custom styling. I created visual step by step tutorial https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0. Have a look and hopefully that will solve your issue.

**Comment by duhaime** [comment]
@heron2014 Thanks so much for this fantastic write-up--it works perfectly!

**Comment by rborn** [comment]
Old issue, closing, please open a new one if you still have it

**Comment by TopDragon523** [comment]
Hello How are you doing? I would like to change the style of building but its style is not working How can I do this? ![image](https://github.com/react-native-maps/react-native-maps/assets/97777348/cebc8e62-5c7a-41f1-aed0-183f5fdca62c)
![image](https://github.com/react-native-maps/react-native-maps/assets/97777348/9a700630-98d1-4555-945b-9471c4626f16)

Please help me
