### ISSUE TITLE
Change pinColor of MapView.Marker to Black

### ISSUE THREAD

**Issue by nyxynyx** [react-native-community/react-native-maps#887]
The color of `MapView.Marker` does not seem to change from the default red color even after assigning a color to `pinColor`.

Is something wrong?

	{ this.state.markers.map(marker => {
		return (
			<MapView.Marker 
				coordinate={{latitude: marker.latitude, longitude: marker.longitude}}
				key={marker.key}
				pinColor='#000000'
			/>
		)
	})}

**Screen cap from Android Emulator**

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/R0CAD.png

**Comment by krsjoseph** [comment]
Hey @nyxynyx try adding the pinColor value in curly braces like this.

`
{ this.state.markers.map(marker => {
	return (
		<MapView.Marker 
			coordinate={{latitude: marker.latitude, longitude: marker.longitude}}
			key={marker.key}
			pinColor={'#000000'}
		/>
	)
})}
`

![screen shot 2016-12-14 at 5 24 38 pm](https://cloud.githubusercontent.com/assets/1019869/21201714/68cb253e-c222-11e6-8f20-7b59b8ae38c3.png)

**Comment by daose** [comment]
Observing the same problem, iOS works but android still renders the default red pin (also tried @krsjoseph solution, same result)

**Comment by alexprice91** [comment]
bump

**Comment by bufke** [comment]
Google maps markers only show in certain colors. You can't just use any color. I wish a had a canonical source to back this up, but try experimenting with shades of a color. You can't change the shade but at a certain hex value it will just appear as a different color.

**Comment by duvnjak99** [comment]
I had the issues (only on Android) that the pin color change did not work. I assume the map is reusing the pin based on the key.

Changing the marker key property to something different worked for me

key={this.updatePinKeyForMarker(marker)}

**Comment by douglasjunior** [comment]
Same problema here. I'm trying to set the color `#474744`. But the pin turns yellow.

Correct color:
![image](https://user-images.githubusercontent.com/1512341/28831208-5be6cf20-76af-11e7-8df9-f241ce2c834b.png)

Google Pin Color:
![image](https://user-images.githubusercontent.com/1512341/28831267-843a3304-76af-11e7-8ab7-250f2b366a77.png)

**Comment by jorgutdev** [comment]
Same issue here, @bufke is right.
Anyone have a list of available colors?

**Comment by pcooney10** [comment]
Going to bump this as well. Almost every hex color I've tried is defaulting to the red marker, and the `customMapStyle` prop doesn't seem to be working either.

Versions:
````json
"expo": "^19.0.0",
"react-native": "^0.46.1"`
"react-native-maps": "^0.15.3"
````

@jorgutdev I was unable to find a list of available colors, but here are some I found from testing (per @bufke's suggestion):

- `red` (default)
- `tomato`
- `orange`
- `yellow`
- `gold`
- `wheat`
- `tan`
- `linen`
- `green`
- `blue` / `navy`
- `aqua` / `teal` / `turquoise`
- `violet` / `purple` / `plum`
- `indigo`

Not the best set of colors IMO, and it doesn't seem to offer anything on a grayscale (which is what I need for my app).

@duvnjak99, would you mind elaborating on your `updatePinKeyForMarker` function? Does it allow you to pass custom styles to your pins? Or is it just used to update the pin color?

**Comment by raduflp** [comment]
@pcooney10 thanks for the research, not a great set of colors indeed.
I think a simple mention of this limitation in the docs would help a great deal

**Comment by pcooney10** [comment]
Yes, agreed @raduflp. Best bet IMO is just to use custom images.

**Comment by octopuss** [comment]
From my research, I've find out that only colors that are created from combination HUE + 100% saturation and 100 % value/lightness can be used see docs page ( 
https://developers.google.com/android/reference/com/google/android/gms/maps/model/BitmapDescriptorFactory)
for example HUE_GREEN is 120 (100, 100 - see convertor https://www.rapidtables.com/convert/color/hsv-to-rgb.html) , which converts to #00FF00 and can be used as marker color.

**Comment by bendman** [comment]
@fduvnjak I am having the same issues you mention about the key playing a role in allowing/preventing rendering with a new color.

I'm simply switching between `red` and `yellow` values (both accepted on Android) for the `pinColor` when a user presses on the marker, but the color wasn't changing unless I generated a new `key` prop.

I ended up using something like
```jsx
<Marker
  pinColor={isActive ? 'yellow' : 'red'}
  key={`${markerId}-${isActive ? 'active' : 'inactive'}`}
  // ... other props ...
/>
```

**Comment by rborn** [comment]
Closing as per https://github.com/react-native-community/react-native-maps/pull/2429

**Comment by pramodjb** [comment]
![Capture](https://user-images.githubusercontent.com/13535859/69306092-63d25d00-0c4c-11ea-8f26-d8ccb6d3e12e.PNG)

hi all, How can change dot color, dot color in the sense - inside marker pin one of the dot is there.i'm talking about that. please refer the screen shot

**Comment by rraina91** [comment]
> I had the issues (only on Android) that the pin color change did not work. I assume the map is reusing the pin based on the key.
> 
> Changing the marker key property to something different worked for me
> 
> key={this.updatePinKeyForMarker(marker)}

Thank you @fduvnjak !

This was precisely my problem, too.

I "foolishly" tried to use a stable, natural key (i.e. strictly domain-object derived) and every time my redux store was modified with prop values changing the pinColor, the color wouldn't actually update. By adding something that's different every time (i.e. getMilliseconds()) to the key, I was able to get the reacted updates as I expected from marker changes.

That will teach me to build keys with meaning.. right?? Hah.

**Comment by SonuGitCfcs** [comment]
> @fduvnjak I am having the same issues you mention about the key playing a role in allowing/preventing rendering with a new color.
> 
> I'm simply switching between `red` and `yellow` values (both accepted on Android) for the `pinColor` when a user presses on the marker, but the color wasn't changing unless I generated a new `key` prop.
> 
> I ended up using something like
> 
> ```js
> <Marker
>   pinColor={isActive ? 'yellow' : 'red'}
>   key={`${markerId}-${isActive ? 'active' : 'inactive'}`}
>   // ... other props ...
> />
> ```
> 
> It seems that there are two issues at hand here: Android only allows very specific colors for markers, and marker colors don't update on Android unless the `key` prop changes.

Thank you ! Its work for me

**Comment by AnnaKohlbecker** [comment]
If custom colors are important, I recommend using PNG marker pin images (128 x 128 pixels) for each color variation.

Example:
```
import GreenMarker from 'assets/marker-green.png';

...

<Marker
    coordinate={marker}
    image={GreenMarker}
    onPress={onPress}
/>
```

**Comment by dastin23** [comment]
can i disable pinColor?
