### ISSUE TITLE
Changing image marker set breaks marker selection

### ISSUE THREAD

**Issue by stinju** [react-native-community/react-native-maps#892]
After a map is rendered with a set of image markers, if the map is re-rendered with a new set of markers, the markers are then very difficult to select (trigger callout).  In the example below, one marker is simply removed from the existing set.  The markers seem to shift in the order that they are presented.  

Before:

![image](https://cloud.githubusercontent.com/assets/75614/21165119/2650cdec-c152-11e6-86ee-1a61af8a175b.png)

After:

![image](https://cloud.githubusercontent.com/assets/75614/21165121/2e22527a-c152-11e6-9556-0ac864f5f9cd.png)

```
'use strict';

var React = require('react');

import { Component } from 'react';
import { Text, View, Platform, Image, TouchableOpacity } from 'react-native';

import MapView from 'react-native-maps';

class MapPlay extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selectedId: null,
      locs: [],
      selectedBusinessName: null
    };

    // setting on first render seems to do something weird to tapping icons
    setTimeout(() => {
      this.setState({locs: data})
    }, 0);
  }

  render() {
    var { locs } = this.state;

    // image markers
    var markers = locs.map(bl => (
      <MapView.Marker
        key={bl.business_name}
        coordinate={{latitude: +bl.latitude, longitude: +bl.longitude}}
        title={bl.business_name}
        image={{uri: 'https://facebook.github.io/react-native/img/favicon.png'}}
      />
    ));

    return (
      <View>
        <MapView
           initialRegion={{
             latitude: +data[0].latitude,
             longitude: +data[0].longitude,
             latitudeDelta: 0.0922,
             longitudeDelta: 0.0421,
           }}
           style={{width: 300, height: 300}}
         >
          {markers}
        </MapView>

        <TouchableOpacity onPress={() => this.setState({locs: data.slice(1)})}>
          <Text>Change Markers</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

var data = [
  {
    "latitude": "37.563979",
    "longitude": "-122.322948",
    "business_name": "A",
  }, {
    "latitude": "37.56461",
    "longitude": "-122.32123",
    "business_name": "B",
  }, {
    "latitude": "37.56392",
    "longitude": "-122.324647",
    "business_name": "C",
  }, {
    "latitude": "37.566714",
    "longitude": "-122.320529",
    "business_name": "D",
  }, {
    "latitude": "37.5786",
    "longitude": "-122.349049",
    "business_name": 'E',
  }
];

export default MapPlay;
``` 
		"react": "15.4.1",
		"react-native": "0.39.2",
		"react-native-maps": "0.12.2"

Please let me know if you need more information.  Thanks in advance!

**Comment by stinju** [comment]
Actually, I think this is a duplicate of https://github.com/airbnb/react-native-maps/issues/397.  The workaround seems to resolve the above example scenario.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
