### ISSUE TITLE
Android google maps doesn't apply borderRadius, iOS apple maps do

### ISSUE THREAD

**Issue by florianbepunkt** [react-native-community/react-native-maps#893]
Hi, working on react native 0.37 with latest react-native-maps.

Title basically says it: Applying a borderRadius style on iOS works, but on android it gets ignored.

**Comment by florianbepunkt** [comment]
@gilbox here we go… nothing crazy, just the component with borderRadius

```
render() {
  return (
    <MapView
      style={[styles.mapView, this.props.mapViewStyle]}
      initialRegion={{
          latitude: this.props.currentMessage.location.latitude,
          longitude: this.props.currentMessage.location.longitude,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
      }}
      scrollEnabled={false}
      zoomEnabled={false}
    >
    </MapView>
  )
}

const styles = StyleSheet.create({
  mapView: {
    width: 150,
    height: 100,
    borderRadius: 13,
    margin: 3,
  },
});
```

this is on iOS, looking as exspected… the second screen is on android (a bit hard to see, but borderRadius is ignored)

![simulator screen shot 14 12 2016 21 36 12](https://cloud.githubusercontent.com/assets/8314202/21199826/64ee91bc-c245-11e6-982c-9f93b7a91ab0.png)

![screenshot_1481747865](https://cloud.githubusercontent.com/assets/8314202/21199886/a50f2630-c245-11e6-9377-bd149132afc5.png)

**Comment by gilbox** [comment]
interesting, did you try adding `overflow: 'hidden'`? or workaround by wrapping in a `<View />` ?

**Comment by florianbepunkt** [comment]
@gilbox Yeah, tried both… no effect.

**Comment by LeonChabbey** [comment]
Have you found a solution? 

I know that overflow: hidden/visible isn't quite good on Android, they are testing a new UI system for Android in 0.41 (called Nodes) but this one doesn't even support zIndex atm.

**Comment by saberking** [comment]
Yes, this is an age-old issue https://github.com/facebook/react-native/issues/3198

**Comment by Mjuk-Biltvatt** [comment]
@florianbepunkt Have you found a solution for this yet?

**Comment by florianbepunkt** [comment]
@Mjuk-Biltvatt No, the project I was working on was cancelled shortly after the issue occured. But if you find something it would be great if you could post it here.

**Comment by Mjuk-Biltvatt** [comment]
@florianbepunkt Alright, I will look into it further but I'm not sure I will find anything useful after what I've found so far. Will update you if I find anything interesting.

**Comment by kevinmcampos** [comment]
To solve this layout problem I used this workaround: 

https://github.com/facebook/react-native/issues/3198#issuecomment-214414423

**Comment by bss-trongluong** [comment]
<View style={ {
            width: circleSize,
            height: circleSize2,
            borderRadius: 20.8/2,
            overflow: 'hidden',
            backgroundColor:'#0094FF'
          }}>
            <MapView
              style={[{...StyleSheet.absoluteFillObject},{borderRadius: 10.4}]}
              region={{
                latitude: 37.78825,
                longitude: -122.4324,
                latitudeDelta: 0.015,
                longitudeDelta: 0.0121
              }}
            >

            </MapView>
            <View style={{
              position: 'absolute',
              top: -circleFixBorder,
              bottom: -circleFixBorder,
              right: -circleFixBorder,
              left: -circleFixBorder,
              borderRadius: 20.8 / 2 + circleFixBorder / 2,
              borderWidth: circleFixBorder,
              borderColor: '#ff0000'}} pointerEvents='none'/>

          </View>
With
const  circleSize=312.7;
const  circleSize2=150;
const circleFixBorder=50;

It run good for android

**Comment by bss-trongluong** [comment]
![capture](https://user-images.githubusercontent.com/34734374/34714731-efb7ab08-f55c-11e7-93bf-45eb86934bd3.PNG)

**Comment by feargswalsh92** [comment]
Refactored [this](https://github.com/facebook/react-native/issues/3198#issuecomment-210119432) to this styling which is a the MapView contained within a view, works for my very specific use case but I don't see why it wouldn't work for others.

**Comment by eblaauw** [comment]
Overflow hidden on the parent element works for me now.

**Comment by JatinBhuva** [comment]
Any latest solution?  (overflow: "hidden") not working

**Comment by jocoders** [comment]
None of the above solutions does not work for me. Any solutions?
