### ISSUE TITLE
Android Map Style inconsistency

### ISSUE THREAD

**Issue by carleryd** [react-native-community/react-native-maps#909]
I have created a style on SnazzyMaps and loaded the JSON code as the 'customMapStyle' prop on MapView. At first this seemed to work perfectly but I have now noticed that city textx don't load correctly. Countries load at the correct zoom levels but city texts load extremely late(very zoomed in) which makes navigating very hard. This works fine with the default map however.

Here are screenshots demonstrating the problem from zoomed out to very zoomed in.
As you can see the city texts load very late, I have made sure they load earlier(more zoomed out) without styling :)
http://imgur.com/a/So7SZ

**Comment by Clcll** [comment]
@matthewwardrop
