### ISSUE TITLE
Editable Polygons

### ISSUE THREAD

**Issue by nitaliano** [react-native-community/react-native-maps#916]
@spikebrehm @lelandrichardson @gilbox 

I've been using react-native-maps extensively for one of my work projects and I've needed the ability to be able to edit polygons by dragging vertices and midpoint vertices for google maps on iOS similar to leaflet-draw.

Here is the very rough [code](https://github.com/airbnb/react-native-maps/compare/master...unboundfire:polygon-editing) that I've been using so far if interested.

My question is this something that you guys would want react-native-maps to support or should there be another library that can handle drawing/editing similar to the split between leaflet and leaflet-draw?

**Comment by Stonelinks** [comment]
Howdy, coworker of @unboundfire here. FWIW I'm also in favor of the split. As Nick mentioned we've done a bunch of work with [Leaflet](https://github.com/Leaflet/Leaflet) / [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) that follows this pattern with success.

Seems like react-native-maps should stay a relatively clean and simple passthrough to underlying native map libraries. react-native-maps-draw would build on top of it and add shape drawing / editing capabilities (probably circle, polyline and polygon to start).

**Comment by pawan8525** [comment]
Mr. Lucas Doyle , is  Leaflet.draw  working with react-native-map  for drawing / editing polygon if not then what is alternate?

**Comment by nitaliano** [comment]
@pawan8525 we created this library a long time ago https://github.com/airware/react-native-maps-draw it added support for editing polygons/polylines with react-native-maps. It hasn't been maintained but could be a good base if you wanted to fork it and update the code to fit your needs

**Comment by pawan8525** [comment]
Hey @nitaliano thanks for reply   i downloaded the code that you  suggest  run the respective folder"react-native-maps-draw-master\react-native-maps-draw-master\example" to install all dependencies   but after run it give a message "Please wait....Fetching JS Bundle"
full day i did many change but not get success  please suggest i also did what below reference do but not success.  
i follow https://stackoverflow.com/questions/37958376/fetching-js-bundle-monstrously-slow 
 Please suggest

**Comment by leolusoli** [comment]
+1

We are interested in updates/helps/contributs/discuss the **airware@react-native-maps-draw** with the purpose of implementing a polygon draw functionality into an our production app. @nitaliano thanks for posting the component.

**Comment by naderz** [comment]
Is there any other library that is out there that does the above which is fairly up to date ?

**Comment by nes123** [comment]
+1

**Comment by Anuj-logiciel** [comment]
Anybody here - Can help me marking same polygon as [here](http://jsfiddle.net/itsanujraghuvanshi/0trq9b4x/1/)? Will be thankful if I can get some links. Thanks in advance!!

**Comment by dev-event** [comment]
@Anuj-logiciel , @naderz,  @le6o 
For React Native, you can use
using PanResponder to track x y and convert to latitude and longitude. You can view it here: https://github.com/dev-event/react-native-maps-draw
