### ISSUE TITLE
Add edgePadding to fitToElements also?

### ISSUE THREAD

**Issue by henrikra** [react-native-community/react-native-maps#922]
When using fitToElements function it would be good to have edgePadding like fitToCoordinates function has. This is because we have markers that are wider than default markers. So they dont fit perfectly :P

**Comment by DevManny** [comment]
great feature +1

**Comment by lsps9150414** [comment]
Agree. IMHO all `fitToCoordinates`, `fitToSuppliedMarkers`, `fitToElements` should take the same `options: { edgePadding: EdgePadding, animated: Boolean }` Arguments.

**Comment by j-nolan** [comment]
Here's how I solved it:

```jsx
import React, { Component } from 'react'
import MapView from 'react-native-maps'

const EDGE_PADDING = {
  top: 100,
  right: 100,
  bottom: 100,
  left: 100
}

class PaddedMapView extends Component {
  fitToMarkers = () => {
    const markers = React.Children.map(
      this.props.children,
      child => child.props.coordinate
    )
    const options = {
      edgePadding: EDGE_PADDING,
      animated: false // optional
    }
    this.ref.fitToCoordinates(markers, options)
  }

  render() {
    return (
      <MapView
        ref={(map) => {
          this.ref = map
        }}
        onLayout={this.fitToMarkers}
        {...this.props}
      />
    )
  }
}

export default PaddedMapView
```
The component fits to element as soon as it renders.
Use `<PaddedMapView />` component as you would use `<MapView />`.

**Comment by hegelstad** [comment]
Works great, thanks @j-nolan!

**Comment by Billy-** [comment]
> Agree. IMHO all `fitToCoordinates`, `fitToSuppliedMarkers`, `fitToElements` should take the same `options: { edgePadding: EdgePadding, animated: Boolean }` argument.

Agreed. I was also add all of the `animate*` methods too.
