### ISSUE TITLE
Loading indicator not visible on Android

### ISSUE THREAD

**Issue by f0rr0** [react-native-community/react-native-maps#925]
`loadingEnabled` is set to true, however, loading indicator is not visible on Android. Works fine on iOS

**Comment by rexlow** [comment]
+1

**Comment by LucasMonteiro1** [comment]
+1

**Comment by PurvaPawar28** [comment]
+1

**Comment by rborn** [comment]
Old issue, closing. Please open a  new one if you still encounter this.

**Comment by mMarcos208** [comment]
+1
