### ISSUE TITLE
<MapView.UrlTile /> Does not fire onRegionChangeComplete

### ISSUE THREAD

**Issue by jpgarcia** [react-native-community/react-native-maps#930]
It just happens on physical **iOS** devices. 

Here is a minimal sample code to reproduce the issue. The `alert('handleRegionChangeComplete')` is only shown on emulators.

```JSX
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';

import MapView from 'react-native-maps'

class MapSample extends Component {
  
  handleRegionChangeComplete = () => {
    alert('handleRegionChangeComplete')
  }

  render() {
    const style = { flex: 1 }

    const region = {
      latitude: 32,
      longitude: -117,
      latitudeDelta: 1,
      longitudeDelta: 1,
    }

    return (
      <MapView
        style={style}
        initialRegion={region}
        onRegionChangeComplete={this.handleRegionChangeComplete}
      >
        <MapView.UrlTile urlTemplate="https://c.tile.openstreetmap.org/{z}/{x}/{y}.png" />
      </MapView>
    )
  }
}

AppRegistry.registerComponent('MapSample', () => MapSample)

```

**Comment by jpgarcia** [comment]
Anyone facing this issue? it is very easy to reproduce

**Comment by mmoravec** [comment]
I'm having this issue as well. Any way to resolve?

**Comment by eduatletico** [comment]
Hello support! Are you alive?

**Comment by markmssd** [comment]
Having a similar issue. Trying to have a dynamic `urlTemplate` which would change depending on props. But the tiles are never re-updated with the new `urlTemplate`... any suggestions are welcome!

**Comment by willfulbard** [comment]
I'm having this issue as well, and only on physical devices.

        "react-native": "0.47.1",
        "react-native-maps": "0.16.2",

I confirmed that when I remove the custom URL tiles it starts working again, and fires off `onRegionChangeComplete` as expected.

**Comment by parkerziegler** [comment]
+1 for this bug. I can confirm that this only appears to happen on **physical iOS devices**. Check out [this snack](https://snack.expo.io/@pziegler/react-native-onregionchangecomplete-with-mapview.urltile) to see it in action. Works great running on the Android device, but breaks down entirely when running on the iOS device. Any iOS devs out there who might be able to track down what is happening?

**Comment by EOdOW** [comment]
I had the mapType prop set to 'none' for the layers that have UrlTile and onRegionChangeComplete was not being called. By setting mapType to one of ("standard", "satellite", "hybrid") first and then to 'none' I was able to go around this issue.

**Comment by raphaelrk** [comment]
@EOdOW any chance you could share the code you used to fix this?

**Comment by mikkokut** [comment]
+1
