### ISSUE TITLE
Is it possible to render KML/KMZ using this library (for Google Maps)?

### ISSUE THREAD

**Issue by jenshandersson** [react-native-community/react-native-maps#967]
Has anyone tried/failed/managed to load Google Maps data using KML or KMZ?
Or is there any way to load My Maps data?

Any feedback on this matter would be of interest.

**Comment by kengiro** [comment]
A need it too, i choose for make it with json but it is slow when show the polygons

**Comment by esutton** [comment]
[ Off-topic but related ] 

It would be cool to also have built-in KML support for iOS maps via react-native-maps.

For a basic KML file containing place marks markers it would not be too difficult to convert the KML lat / lon to react-native-maps markers.   Implementing more complete KML support such as paths and stuff would be quite challenging ( but an interesting project ).

**Comment by ABleas** [comment]
It seems like [this utility](https://developers.google.com/maps/documentation/android-api/utility/kml), though in beta, would make it easy to add a kml layer to maps and expose the import call to RN?

I haven't looked at the react-native-maps internals much but presumably there is a place for `KmlLayer layer = new KmlLayer(getMap(), R.raw.kmlFile, getApplicationContext());` to go without too much refactor? :)

**Comment by datalin** [comment]
I also need this, any plan for it? Did somebody figure out the required changes?

**Comment by zzimbler** [comment]
For anyone curious, I figured out how to do this. The general strategy I used as follows
- Download and parse KML file using toGeoJSON https://github.com/mapbox/togeojson to JSON
- Created my own translation of my KML to arrays & objects that I could render on the screen
- Used polylines, circles, etc from the map library per whatever type of data I had extracted to render on the screen

This was a pretty painful process, but worked.

**Comment by eelia001** [comment]
@zzimbler Did you run togeojson within your react native app or had to use node to convert a kml file and then read that file?

**Comment by zzimbler** [comment]
@eelia001 I did it all within my React Native app. Happy to help you troubleshoot your issue if you have one or if you want feedback on something you're working on. Shoot me an email zachzimbler@gmail.com

**Comment by Jun711** [comment]
@zzimbler what did you mean by "Created my own translation of my KML to arrays & objects"?
Is it a geojson format?

**Comment by zzimbler** [comment]
@Jun711 well the togeojson gives you a nice blob of JSON, but at least as far as I know there is no way to automatically pipe that information into the react native map. So you have to manually come up with how you want to display that data on the map with pins, lines, points, etc. By my own translation I mean I used .map and then spit out the elements on the map that I wanted. Does that help? Email me if you have something specific

**Comment by stereu** [comment]
Not working, won't show the markers in your example. Any Ideas? Using react-native 0.54.4

**Comment by zzimbler** [comment]
@stereu My example or @rafaellincoln PR? You should add context to your comments and be slightly more thorough. Saying it won't/doesn't work isn't exactly useful. Perhaps logs, code snippets, etc included would be wise next time around

**Comment by stereu** [comment]
@zzimbler Sry I forgot to add that i was trying to get @rafaellincoln PR running. I'm using the example provided in version 0.21.0 with his PR built in. I'm getting only one marker called "TEST" which is hardcoded, but the markers defined in the KML from pastebin won't show. Tested this on two machines from ground up. Any Ideas?

**Comment by stereu** [comment]
Fixed it. PR linked above.

**Comment by smoczynskicitiz** [comment]
Hi @zzimbler , I shot you an email :)

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by wtfkeklol** [comment]
Any chance someone could point me in the right direction in how to use the toGeoJSON library inside react-native? I can't find anything about this.

Also, @zzimbler , I shot you an email, hope you don't mind!

**Comment by smoczynskicitiz** [comment]
Hi @wtfkeklol ,

I'm using the library [react-native-geojson](https://github.com/frankrowe/react-native-geojson).
There is an example on the github page, it should be simple.

**Comment by rossparachute** [comment]
Hey folks,

For what it's worth, in case anyone comes up against this problem again, here's how we handled it.

Cheers,
Ross

----

Say you've got a functional React Native component:

`
import MapView, { Polyline } from "react-native-maps"; // for rendering
import Geojson from "react-native-geojson"; // optional: for rendering
import { DOMParser } from "xmldom"; // for parsing your KLM string, converting it to an XML doc
import { kml } from "@tmcw/togeojson"; // for converting KLM docs to JSON

export const Foo = () => {
    const kmlStr = "bar"; // some example KML from a file or endpoint, nab it as a string
    const parser = new DOMParser();
    const routeKml = parser.parseFromString(kmlStr);
    const routeJson = kml(routeKml);
    const routeCoords = routeJson.features[0]; // where we had a walking route line feature at this index

    return (
       <MapView>
           <Polyline
               coordinates={routeCoords}
               strokeColor={"orange"}
               strokeWidth={6}
               lineCap="round"
               lineDashPattern={[0]}
            />
       </MapView>
    )
}
`

You'll end up with something like this:
![image](https://user-images.githubusercontent.com/67894901/145459415-02729af3-e2ac-4bbd-8bbc-34a25d603bc9.png)

If you don't want fine control over what components render your features then "react-native-geojson" is an option available.

Just drop the Geojson component inside your <MapView>:
`
<MapView>
   <Geojson geojson={routeJson} />
</MapView>
`
