### ISSUE TITLE
Disable drag on markers

### ISSUE THREAD

**Issue by DVassilev** [react-native-community/react-native-maps#976]
When I've got many custom markers on the screen and I try to zoom in and out or drag around the map, unless I'm touching the map and not the marker it fails to do anything. I presume this is because the markers can be draggable as when I set pointerEvents to none it works. Any solutions?

**Comment by saberking** [comment]
Same issue here

**Comment by DVassilev** [comment]
@saberking only happens on iOS for me too. No idea how to fix, tried various things but can't find anything.

**Comment by DVassilev** [comment]
@lelandrichardson could you please check this out and let us know if you have any suggestions on what we can try? I've been unable to fix it and everyone I've spoken to doesn't know either.

**Comment by DavidLore** [comment]
same problem on iOS happens to me...

**Comment by jdross** [comment]
This remains a problem for our team on iOS as well. Any advice appreciated

**Comment by bsiddiqui** [comment]
@jdross not really a solution but this issue and https://github.com/airbnb/react-native-maps/issues/865 were deal-breakers for me so I switched to https://github.com/mapbox/react-native-mapbox-gl. Better performance and more customizable.
